### ISSUE TITLE
Error: spawn ENOENT on Windows

### ISSUE THREAD

**Issue by insin** [feross/standard#1]
joyent/node#2318 strikes again.

This workaround fixes it for me:

```javascript
if (/^win/.test(process.platform)) {
  JSHINT += '.cmd'
  JSCS += '.cmd'
}

```

**Comment by feross** [comment]
Can you send a PR? I'd do it but I don't have a windows machine to test on.

**Comment by feross** [comment]
@insin Did you just add your snippet after [this line](https://github.com/feross/standard/blob/master/index.js#L11)?

**Comment by insin** [comment]
Putting a PR together now - found another couple of issues on Windows

**Comment by feross** [comment]
Fixed by https://github.com/feross/standard/pull/4
