### ISSUE TITLE
global whitelist?

### ISSUE THREAD

**Issue by zeke** [feross/standard#101]
I have some mocha test files I want to `standard`ize, but I'm getting errors about `describe`, `it`, etc being undefined.

```
normalize-license* master » standard --format
Error: Use JavaScript Standard Style (https://github.com/feross/standard)
  test/index.js:7:0: 'describe' is not defined.
  test/index.js:8:2: 'describe' is not defined.
  test/index.js:11:4: 'it' is not defined.
```

I know this is one of the things some people don't like about mocha, but I'm a fan of this design choice, as it reduces boilerplate code in tests. Is there a way to whitelist globals in package.json or something?

**Comment by jprichardson** [comment]
Add this to the top of your file:

/* global describe, it */

On Wednesday, April 1, 2015, Zeke Sikelianos <notifications@github.com>
wrote:

> I have some mocha test files I want to standardize, but I'm getting
> errors about describe, it, etc being undefined.
>
> normalize-license* master » standard --format
> Error: Use JavaScript Standard Style (https://github.com/feross/standard)
>   test/index.js:7:0: 'describe' is not defined.
>   test/index.js:8:2: 'describe' is not defined.
>   test/index.js:11:4: 'it' is not defined.
>
> I know this is one of the things some people don't like about mocha, but
> I'm a fan of this design choice, as it reduces boilerplate code in tests.
> Is there a way to whitelist globals in package.json or something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feross/standard/issues/101>.
>


-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson

**Comment by zeke** [comment]
:metal:

**Comment by zeke** [comment]
For those who stumble upon this issue, @jprichardson's suggestion is a `jshint` thing: http://jshint.com/docs/

**Comment by gabeio** [comment]
👍  thanks

**Comment by ifraixedes** [comment]
For mocha globals specifics , I use `/* eslint-env mocha */`
