### ISSUE TITLE
Defining globals

### ISSUE THREAD

**Issue by kmamykin** [feross/standard#103]
I am working on a Appcelerator Titanium project, where the framework defines several globals that I would like to ignore. 
Is there a suggested way to override them (through package.json for example) and keep using standard (instead of switching to eslint)?

**Comment by yoshuawuyts** [comment]
From the [README](https://github.com/feross/standard#how-do-i-ignore-files):


### How do I ignore files?

The paths `node_modules/`, `.git/`, `*.min.js`, `bundle.js`, and `coverage/` are automatically excluded
when looking for `.js` files to style check.

Sometimes you need to ignore additional folders or specific minfied files. To do that, add
a `standard.ignore` property to `package.json`:

```json
"standard": {
  "ignore": [
    "**/out/**",
    "**/lib/select2/**",
    "**/lib/ckeditor/**"
  ]
}
```

**Comment by kmamykin** [comment]
@yoshuawuyts you probably misunderstood my question. I am trying to ignore certain globals from generating standard's errors through some config setting. But I finally settled on explicitly specifying 
``` javascript
/* global Titanium, Allow, arguments */
```
in each file.

**Comment by yoshuawuyts** [comment]
whoops, my bad.

**Comment by mattdesl** [comment]
Is there a resolution for this issue? I tend to work with APIs like ThreeJS, CocoonJS, PIXI, etc. which are often in global scope.

**Comment by maxogden** [comment]
@mattdesl I put `/* global foo */` at the top of all my files, it's the simplest thing I can think of. Other than to not use globals :)
