### ISSUE TITLE
Any way to use babel-eslint here?

### ISSUE THREAD

**Issue by ColCh** [feross/standard#106]
Nice project! How we can use [babel-eslint](https://github.com/babel/babel-eslint)?

**Comment by feross** [comment]
There's no way to use a custom parser with `standard`, sorry. I might reconsider if there's significant demand, but it's not likely.

**Comment by bendrucker** [comment]
I'm interested in this as well

**Comment by julien-f** [comment]
I am currently using some ES7 features (such as `await`/`async`) which are not currently supported by ESPree.

It is annoying because these parse failures (`unexpected token`) break ESLint and prevent the detection of potential errors.

I am not sure what would be the best way to tackle this issue without breaking the various editor plugins that integrate standard.

**Comment by yoshuawuyts** [comment]
@julien-f If Espree can't parse a token it will break, there's little that can be done about that. 

I think the solution is to make sure Espree can parse all tokens; you could either make it parse the build output (yuck) or help Espree forward by [creating an issue](https://github.com/eslint/espree/issues) and / or a PR to add `async / await` support.

**Comment by julien-f** [comment]
Extracting the core (#87) and the EsLint config (#132) would also helps in creating a fork using babel-eslint.

**Comment by feross** [comment]
Re-opening for discussion.

**Comment by julien-f** [comment]
I created [babel-standard](https://github.com/julien-f/babel-standard) based on [eslint-standard-config](https://github.com/feross/eslint-config-standard) and [babel-eslint](https://github.com/babel/babel-eslint).

@feross I added you as a collaborator (and @sebmck, Babel creator), feel free to play with it.

**Comment by feross** [comment]
Is [this line](https://github.com/julien-f/babel-standard/blob/master/rc/.eslintrc#L4) the only thing you changed?

**Comment by sebmck** [comment]
@julien-f Why didn't you just fork this repo so history was retained? Unsure how (or if) you're planning on keeping it in sync.

**Comment by bendrucker** [comment]
I use a fork (https://github.com/bendrucker/standard/tree/babel) and it's indeed a one liner just to set the `parser` in `./rc/.eslintrc`: https://github.com/feross/standard/compare/master...bendrucker:babel

**Comment by julien-f** [comment]
@feross Yep.

@sebmck I just put things together for testing, but you're right I should have done so and will fix it.

**Comment by ColCh** [comment]
@bendrucker may be you want to test [npm scopes](http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages) with your fork?

**Comment by bendrucker** [comment]
@ColCh Yeah I should have, but at this point you can just use Julien's. 

I think it's reasonable to treat parsers as the one case where eslint config can be provided without defeating the purpose of standard. There's really only two (esprima-fb and babel-eslint). Babel's targeting future ES features so this is an ongoing concern.

This is also blocked by eslint as far as I can tell. Parsers are read from the config file and there's no way to provide them via `CLIEngine`.

**Comment by RnbWd** [comment]
I got it working today with 'eslint-config-standard' - thank you for that!!

**Comment by jladuval** [comment]
What's the story around this. I too would love to be able to use async-await. Should I use babel-standard?

**Comment by julien-f** [comment]
@jladuval You can use babel-standard, if you find some bugs please report them [there](https://github.com/julien-f/babel-standard/issues).

**Comment by feross** [comment]
The latest version of standard (3.12.0) now supports custom JS parsers!

To use a custom parser, install it from npm (example: `npm install babel-eslint`) and add this to your package.json:

```json
{
  "standard": {
    "parser": "babel-eslint"
  }
}
```

That's it. Enjoy!

**Comment by chris9753** [comment]
Using the latest version here with config and I still get unexpected token on '=>'

**Comment by vtambourine** [comment]
I am also experiencing troubles using custom linters in Atom's lint engine. Not sure if it is standard's problem or linter-js-standard's.
