### ISSUE TITLE
Invalid autoformatting when function name contains word "function"

### ISSUE THREAD

**Issue by leomelin** [feross/standard#109]
I ran a cross this problem when I tried to autoformat a file that runs a function called "viewFunctions()"
````
var viewFunctions = function () {
}

viewFunctions()
````

The formatter formats it as:
````
var viewFunctions = function () {}

viewfunction s ()
````

... aand that breaks the code. The problem propably bubbles from https://github.com/maxogden/standard-format -library, and from there it propably bubbles from https://github.com/millermedeiros/esformatter ?

**Comment by feross** [comment]
Yep, this is a know issue with `standard-format`. It will be fixed once https://github.com/maxogden/standard-format/pull/47 is merged and released (soon!).

**Comment by leomelin** [comment]
ok, great! btw. Awesome job with this library!

**Comment by feross** [comment]
Thanks! :-)
