### ISSUE TITLE
web workers

### ISSUE THREAD

**Issue by calvinmetcalf** [feross/standard#11]
the global variable in a web worker is named self, so renaming this to self in a worker can be tricky if you then need to grab a reference to the global, does this assume it's always in a browserify context?

**Comment by feross** [comment]
For web workers, I would just add this to the top of the file:

```
/* global self */
```

I'm hesitant to do this by default because then we lose the protection of checking for accidental use of `window.self` when people accidentally forget `var self = this` in a method.

**Comment by feross** [comment]
Closing this now, since adding a comment is a pretty nice solution :)
