### ISSUE TITLE
stdout instead of stderr

### ISSUE THREAD

**Issue by malandrew** [feross/standard#112]
Currently standard uses stderr for all output. This means that if you want to pipe standard, you need to redirect stderr to stdout with `2>&1 >/dev/null`.

All lint errors should instead be printed to stdout so unix pipes work.

The general semantics of stdout is "content I'm interested in if I'm running this program" and stderr is "any content that is not related to the functionality of this program".  i.e. these lines are appropriate for stderr: 
https://github.com/feross/standard/blob/master/bin/cmd.js#L89
https://github.com/feross/standard/blob/master/bin/cmd.js#L108

**Comment by Flet** [comment]
Some previous discussion on this is in https://github.com/feross/standard/issues/21.
@mafintosh's comment is relevant:
>i think it should keep printing to stderr since its normal to do stuff like standard && tape test.js. otherwise it would mess up a tap parser (like npm test | tap-spec)
>
>you can always just run
>
>`standard 2>&1 | grep variable`

And FAQ on this:
https://github.com/feross/standard/blob/master/README.md#why-cant-i-pipe-standard-to-other-tools

**Comment by Flet** [comment]
The previous thread on this sort of died off as no one was complaining about it. Perhaps this needs to be revisited?

**Comment by malandrew** [comment]
The tap-parser issue is easy to solve, just print every line prefixed by `# `.

Alternatively, would you accept pull-requests for different formatters:
 - stylish
 - json
 - checkstyle

**Comment by feross** [comment]
@malandrew Thanks for the link about how stdout and stderr are supposed to work in unix programs. Very handy - I learned a few things.

I don't want to solve this by introducing multiple formatters - that's a slippery slope...

Let's just print the lint errors to stdout. I just tested `tap-spec` and it seems to ignore non-TAP output, so I don't think this will cause any problems for @mafintosh's use case.

There's one case where we'll continue printing the lint errors to stderr, and that's for `standard --stdin --format`. This command formats code on stdin and prints it to stdout, so any remaining lint errors need to go to stderr.

**Comment by mafintosh** [comment]
@feross i don't feel strongly about printing to stderr/stdout and since tap-spec still works :+1: from me

**Comment by feross** [comment]
Made a PR for this: https://github.com/feross/standard/pull/113 Please share feedback.

**Comment by Flet** [comment]
Does not change format behavior. Cool. :+1:

**Comment by feross** [comment]
Released as 3.6.0.
