### ISSUE TITLE
Negative patterns in .gitignore make all files ignored

### ISSUE THREAD

**Issue by julien-f** [feross/standard#115]
It works with any negative patterns, the one who matches nothing `!*` and the one who matches anything `!inexisting`.

**Comment by feross** [comment]
Can you give an example of a .gitignore you're trying to use?

**Comment by matthewmueller** [comment]
Just ran into this. Probably a better way to write this but here's what I had.

```
!*/db
db
```

Ignore `/db`, but don't ignore say, `/lib/db`.

**Comment by julien-f** [comment]
@matthewmueller you can simply write `/db` which ignore the `db` entry in the directory where the `.gitignore` is.

@feross I can show you a trivial example but any valid gitignore should be correctly interpreted.

```
dist/*
!dist/.keepme
```

**Comment by feross** [comment]
standard@3.7.0 removed support for .gitignore until we can make it work more reliably.
