### ISSUE TITLE
Support for patterns starting with / in .gitignore.

### ISSUE THREAD

**Issue by julien-f** [feross/standard#116]
If there is a `dist/` directory which is ignored from the `.gitignore` file with the `/dist/` pattern, it will nevertheless be explored by standard.

**Comment by Flet** [comment]
It seems that gitignore patterns do not directly translate to globs.

May want to defer to another module to do this, such as:
https://www.npmjs.com/package/gitignore-globs
(Really great Resources section in the readme)

**Comment by feross** [comment]
All this glob and pattern matching stuff has bugs in it.

I was trying to put something together to fix this, but had to send out PRs first:

- https://github.com/sevenweb/gitignore-globs/pull/1
- https://github.com/isaacs/node-glob/issues/189

Once these are resolved, I'll try again.

**Comment by feross** [comment]
standard@3.7.0 removed support for .gitignore until we can make it work more reliably.
