### ISSUE TITLE
revert .gitignore?

### ISSUE THREAD

**Issue by jprichardson** [feross/standard#117]
Can we consider reverting the .gitignore patch? It doesn't work like people expect, see: https://github.com/feross/standard/issues/116 & https://github.com/feross/standard/issues/115.

I'm working on migrating a large project over and my .gitignore is huge. Standard (with .gitignore patch) reports no issues,  which is incorrect, because versions before report thousands of lines. What I liked about standard before was that it was super simple to ignore files, just place the patterns in `package.json`. Now I don't know if it's looking in `package.json` first and then `.gitignore` or vice versa. Regardless, it's complicated the whole thing.

I can understand why one would choose `.gitignore` patterns, but I think we need to either get it near perfect or not at all IMHO.

@feross what are your thoughts?

**Comment by feross** [comment]
I think it won't be too hard to just fix up the `.gitignore` pattern matching to work correctly. Wouldn't that be the best solution?

We can always apply the `package.json` ignores after the `.gitignore` so you have an out if you need to un-ignore something.

**Comment by feross** [comment]
standard@3.7.0 removed support for .gitignore until we can make it work more reliably.
