### ISSUE TITLE
No errors or output when linting certain files/projects

### ISSUE THREAD

**Issue by pdehaan** [feross/standard#120]
## Prerequisites:
Install `standard` globally:
```sh
$ npm i standard -g
```

### Steps to reproduce:
1. `git clone git@github.com:mozilla/fxa-content-server.git .`
2. `standard`
3. `standard --verbose`
4. `echo $?`

### Actual results:
```sh
$ standard
$ standard --verbose
$ echo $? # 0
$ standard --version # 3.6.1
```

Not sure why I'm not seeing any output or errors (with or without the `--verbose` flag).

**Comment by Flet** [comment]
This looks to be relatd to the .gitignore problems with negative patterns... #115 #116 #117
If I remove all the negative patternds from the `.gitignore` file, then I get results.

**Comment by Flet** [comment]
@feross maybe its time to revert the gitignore stuff and work it in a branch :(

**Comment by feross** [comment]
@Flet Agreed.

@pdehaan Please try again with standard 3.7.0, which disables `.gitignore` support. It should work now.

**Comment by pdehaan** [comment]
@feross Looks great, thanks!
