### ISSUE TITLE
Specify eslint-env globally?

### ISSUE THREAD

**Issue by pdehaan** [feross/standard#122]
Is there a way to set ESLint environments globally (via config or setting) without having to specify ESLint `eslint-env` flags in each file? (ie: `/*eslint-env and, mocha */`)

When I run `$ standard` in one of our project's directories, I get a bunch of these warnings in dozens of files:

```
/tests/spec/views/ready.js:109:8: 'it' is not defined.
/tests/spec/views/reset_password.js:7:0: 'define' is not defined.
/tests/spec/views/reset_password.js:28:4: 'describe' is not defined.
/tests/spec/views/reset_password.js:50:6: 'beforeEach' is not defined.
/tests/spec/views/reset_password.js:63:12: '$' is not defined.
/tests/spec/views/reset_password.js:67:6: 'afterEach' is not defined.
/tests/spec/views/reset_password.js:72:8: '$' is not defined.
/tests/spec/views/reset_password.js:77:6: 'describe' is not defined.
/tests/spec/views/reset_password.js:78:8: 'it' is not defined.
/tests/spec/views/reset_password.js:79:20: '$' is not defined.
/tests/spec/views/reset_password.js:82:8: 'it' is not defined.
/tests/spec/views/reset_password.js:113:6: 'describe' is not defined.
/tests/spec/views/reset_password.js:114:8: 'it' is not defined.
/tests/spec/views/tooltip.js:58:8: 'it' is not defined.
/tests/spec/views/tos.js:7:0: 'define' is not defined.
/tests/spec/views/tos.js:17:4: 'describe' is not defined.
/tests/spec/views/tos.js:22:6: 'beforeEach' is not defined.
/tests/spec/views/tos.js:38:6: 'afterEach' is not defined.
/tests/spec/views/tos.js:43:6: 'it' is not defined.
/tests/spec/views/unexpected_error.js:7:0: 'define' is not defined.
/tests/spec/views/unexpected_error.js:16:4: 'describe' is not defined.
/tests/spec/views/unexpected_error.js:19:6: 'beforeEach' is not defined.
/tests/spec/views/unexpected_error.js:28:6: 'afterEach' is not defined.
/tests/spec/views/unexpected_error.js:34:6: 'it' is not defined.
/tests/test_start.js:130:6: 'beforeEach' is not defined.
/tests/test_start.js:134:6: 'afterEach' is not defined.
...
```

**Comment by rlidwka** [comment]
Put it into `.eslintrc` file in your `/tests` folder like [this](https://github.com/rlidwka/sinopia/blob/master/test/.eslintrc).

**Comment by pdehaan** [comment]
@rlidwka, odd, that didn't seem to work:

```sh
$ standard --version # 3.7.0

$ cat tests/.eslintrc
env:
  mocha: true
  amd: true

$ standard tests
$ standard tests --verbose

$ cd tests
$ standard
standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  ./app/tests/lib/blanket_lcov.js:9:0: Unexpected space between function name and paren.
  ./app/tests/lib/helpers.js:7:0: 'define' is not defined.
  ./app/tests/mocks/canvas.js:7:0: 'define' is not defined.
  ./app/tests/mocks/crosstab.js:7:0: 'define' is not defined.
  ./app/tests/mocks/crosstab.js:13:37: Extra semicolon.
  ./app/tests/mocks/dom-event.js:7:0: 'define' is not defined.
  ./app/tests/mocks/file-reader.js:7:0: 'define' is not defined.
  ./app/tests/mocks/fxa-client.js:7:0: 'define' is not defined.
  ./app/tests/mocks/history.js:6:0: 'define' is not defined.
  ./app/tests/mocks/oauth_servers.js:5:0: 'define' is not defined.
  ./app/tests/mocks/profile.js:7:0: 'define' is not defined.
  ./app/tests/mocks/router.js:7:0: 'define' is not defined.
  ./app/tests/mocks/window.js:7:0: 'define' is not defined.
  ./app/tests/mocks/window.js:59:34: There should be no spaces inside this paren.
  ...

$ standard | wc -l
standard: Use JavaScript Standard Style (https://github.com/feross/standard)
    1554
```

**Comment by feross** [comment]
Just add a `/* global define, it, describe */` comment at the top of each file.

**Comment by pdehaan** [comment]
FWIW, we have about 108 *.js files in our /app/tests/** directory.
Currently we're using JSHint and can just specify the globals in the .jshintrc file in one place instead of copy/pasting into over a hundred files separately.

**Comment by jprichardson** [comment]
What I like about embedding the globals in the comments is that a JavaScript file then becomes standard "certified" in a sense. External configs remove this. 

@pdehaan I know it's painful as I've done it with a couple of projects now. To ease the pain, what if you whipped up a quick script (using recast or just prepend text) to insert the global comments in every file?

**Comment by pdehaan** [comment]
@jprichardson Yeah, it's not difficult/impossible to do, but gets exponentially worse if we change our tests to some other library that uses different globals or syntax. I'd either have to go through and search/replace all these crazy `/*global define, it, describe, afterEach, beforeEach, ... */` strings in every file or else manually go through them and tweak them so we don't end up with 2-3 different `/*global ... */` blocks or a mix of `/*global ... */` and `/*eslint-env ... */` blocks.

But I totally agree with the [I disagree with rule X, can you change it](https://github.com/feross/standard#i-disagree-with-rule-x-can-you-change-it) docs in the README. Plus the [Can you make rule X configurable?](https://github.com/feross/standard#can-you-make-rule-x-configurable) docs clearly say:

> _**Can you make rule X configurable?**
> No. Use `eslint` directly if you want to configure hundreds of options individually._

**Comment by jprichardson** [comment]
@pdehaan Totally understand. If you do change to another testing library, you could use [recast](https://www.npmjs.com/package/recast) to rewrite each file with the new globals. If you haven't used `recast` yet, it's one of the easiest ways to use `esprima` and parse/emit JavaScript. It's worth checking out at some point :)

**Comment by matthewadams** [comment]
So I'm a little confused here.  I'm see the same behavior as @pdehaan.  However, http://eslint.org/docs/user-guide/configuring#specifying-environments says that the environment `mocha` is explicitly supported.  So, is this a problem only when linting with `standard`?  It seems to work correctly if I `npm install -g eslint eslint-config-standard` then `eslint . | grep describe` in my project directory (there's no output because nothing got `grep`ed).

In my project, I've simply done `npm install --save-dev standard`, then invoked it via `$(npm bin)/standard`.  When I lint this way, I get `'describe' is not defined` messages.

Is this expected behavior from `standard`?  I don't really like the suggestion by @feross (https://github.com/feross/standard/issues/122#issuecomment-95347801) to litter all files with eslint directives; it seems like creating a `.eslintrc` in my `test/` directory with content
```
{
  "env": {
    "node": true,
    "mocha": true
  }
}
```
should do the trick.  I'd appreciate clarification by a knowledgeable somebody.  :)

**Comment by feross** [comment]
`.eslintrc` and `.eslintignore` files are not supported by `standard`. Your options are:

1. Add `/*eslint-env mocha */` to the top of the file with mocha globals.

2. Add `"env": [ "mocha" ]` to the `package.json` under the `"standard"` property.

**Comment by ImanMh** [comment]
I have `myFile.js` and `myFile.test.js` side by side in a directory. How can I make it work? It also says that expect is available in `myFile.js` which is false.
