### ISSUE TITLE
standard style with jshint?

### ISSUE THREAD

**Issue by zeke** [feross/standard#123]
I'm using standard for some personal projects and loving it, but I have other projects with `.jshintrc` files that are not ready to be switched over to standard.

Is there a jshint equivalent of standard style that I can use in my `~/.jshintrc`? This would allow me to keep using @sindresorhus' `jshint` Atom.io linter on all projects, and remove the project-specific `.jshintrc`files gradually.

**Comment by feross** [comment]
In the early versions of `standard`, we used `jshint`. You can try using that original `.jshintrc`, here: https://github.com/feross/standard/blob/3afa5e5dfe8578f161092291a1f4e42a56ef164c/rc/.jshintrc

However, it's pretty limited in what it will check. Have you considered disabling the atom plugin for `jshint` and using the `standard` one instead? Then you can just fix things up as you notice them in your editor.

**Comment by zeke** [comment]
Thanks, @feross. I will give that old `.jshintrc` a try.

I am using the standard atom plugin, but [not liking it](https://github.com/AtomLinter/Linter/issues/514).

**Comment by Flet** [comment]
@zeke have you tried [standard-format](https://github.com/maxogden/standard-format) (or just `standard --format`) to convert old projects yet? :)

**Comment by zeke** [comment]
@Flet yes I have used `standard --format` and I love it. The main reason I can't fully switch is https://github.com/npm/newww, a project which has more stakeholders and would be a much bigger task to convert. But maybe one day..
