### ISSUE TITLE
Array destructuring

### ISSUE THREAD

**Issue by cbas** [feross/standard#129]
Seems like this syntax triggers a false positive, or maybe my ES6 understanding is lacking.

Input
```js
let [a, b = {}] = [1, 2]
a
b
```
Output
```
3:0: 'b' is not defined. (no-undef)
```

**Comment by Flet** [comment]
I dont think `b = {}` is valid.
Putting it into Firefox console yields:
```
let [a, b = {}] = [1, 2]
SyntaxError: missing variable name
```

But this works
```
let [a, b] = [1, 2]
```

**Comment by cbas** [comment]
> In Firefox, default values for destructuring assignments are not yet implemented: var { x = 3 } = {} and var [foo = "bar"] = []. See bug 932080 and also bug 1018628 for destructured default values in functions.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by feross** [comment]
Cool, thanks for debugging this.

**Comment by dcousens** [comment]
@feross so wait, is the conclusion that it is an `eslint` issue?

**Comment by cbas** [comment]
@feross Why was this closed? :confused: 

Could be related to https://github.com/eslint/eslint/issues/2405

**Comment by Flet** [comment]
Reopening :) 
I think @cbas was just showing me that default assignment for destructing arguments is not in Firefox yet. :) Thanks for the info btw!

That eslint issue links to the real issue which is in escope https://github.com/estools/escope/issues/33

**Comment by feross** [comment]
Ah, sorry I misunderstood what this issue was about. ;) Thanks for re-opening @Flet.

**Comment by feross** [comment]
This issue is fixed. Not sure which version it was fixed in, but there's no longer an error when linting:

```js
let [a, b = {}] = [1, 2]
a
b
```

Nice!
