### ISSUE TITLE
Should function declaration in catch be allowed?

### ISSUE THREAD

**Issue by davidpfahler** [feross/standard#131]
I got `Move function declaration to function body root.` error for the following code:

```javascript
initialise()
function initialise () {
  try {
    return nativeImplementation()
  } catch (e) {
    function fakeImplementation () {
      // ...
    }

    return fakeImplementation()
  }
}
```

I was intentionally declaring the `fakeImplementation` function in the catch block, because I though it to be a waste to declare the function if it is most likely never being used. Isn't this an anti-pattern?

**Comment by julien-f** [comment]
Function declarations are hoisted (automatically moved to the top of the scope) so your `fakeImplementation()` function is always created.

What you want is to use a function expression assigned to a variable:

```javascript
initialise()
function initialise () {
  try {
    return nativeImplementation()
  } catch (e) {
    var fakeImplementation = function () {
      // ...
    }

    return fakeImplementation()
  }
}
```

**Comment by feross** [comment]
What @julien-f said is correct. The error message could be more helpful, but I think we can keep this rule in place. I'm going to close this issue, but feel free to continue discussing if you want.
