### ISSUE TITLE
extract standard config as a an eslint shareable config module

### ISSUE THREAD

**Issue by Flet** [feross/standard#132]
http://eslint.org/docs/developer-guide/shareable-configs

This would also allow a level of versioning specific to the rules themselves

**Comment by julien-f** [comment]
It seems like a good idea.

**Comment by AlexKVal** [comment]
:+1:

**Comment by feross** [comment]
Okay, this is published here: https://github.com/feross/eslint-config-standard

**Comment by feross** [comment]
And `eslint-config-standard` on npm.

**Comment by feross** [comment]
This package should depend on [eslint-config-standard](https://github.com/feross/eslint-config-standard) so we can keep the rules in just one place. That's done on the [shareable-config](https://github.com/feross/standard/tree/shareable-config) branch, but it doesn't work because of this eslint bug (https://github.com/eslint/eslint/issues/2487). Once that's fixed, we can release that branch.

**Comment by feross** [comment]
Also, I just added all current collaborators to the eslint-config-standard repo.

**Comment by feross** [comment]
I just merged the `shareable-config` branch into `master` and published standard 3.9.0.

`standard` now depends on [`eslint-config-standard`](https://github.com/feross/eslint-config-standard). If you want to fork `standard`, you should extend it instead using eslint's [shareable configs](http://eslint.org/docs/developer-guide/shareable-configs).

@Flet care to try that with `semistandard`? Let's see if it works as expected.

**Comment by Flet** [comment]
FYI, `semistandard` now uses `eslint-config-semistandard` which extends `eslint-config-standard`, 

This is incredibly awesome now:
- `semistandard` should automagically get all non-breaking `standard` changes on every install.
- `eslint-config-semistandard` clearly shows only the rules that are mutated from standard (The One Rule).
- if others are considering forking `standard`, I highly recommend looking at `semistandard` as an example! :)

**Comment by dcousens** [comment]
Cheers @Flet, this is very cool indeed.

**Comment by feross** [comment]
Nice @Flet!
