### ISSUE TITLE
Working with Babel's experimental transformers?

### ISSUE THREAD

**Issue by gsklee** [feross/standard#133]
Is this compatible, or able to work with Babel's [experimental transformers](http://babeljs.io/docs/usage/experimental/) like decorators, object spread, etc.?

**Comment by julien-f** [comment]
AFAIU, no.

standard is based on EsLint which does not support some features (e.g. ES7).

Using the [babel-eslint](https://github.com/babel/babel-eslint) parser would probably help but it is not clear atm how to integrate it properly (#106).

**Comment by feross** [comment]
Duplicate of https://github.com/feross/standard/issues/106
