### ISSUE TITLE
Upgrade eslint to "^0.21.0"

### ISSUE THREAD

**Issue by aputinski** [feross/standard#134]

**Comment by Flet** [comment]
I believe there is a blocker in here #98 that is preventing us from moving to the latest version.

**Comment by aputinski** [comment]
@Flet Ahh.. should I close this issue?

**Comment by feross** [comment]
Okay, this is done on the `eslint-0.21` branch: https://github.com/feross/standard/tree/eslint-0.21

**Comment by feross** [comment]
Okay, this is released as standard 3.8.0!
