### ISSUE TITLE
Scan only a subdirectory in CLI

### ISSUE THREAD

**Issue by gsklee** [feross/standard#135]
Is there something like `$ standard ./src/util` that I can do to only scan a subdir through the cli?

**Comment by Flet** [comment]
`standard src/util/**/*.js`  (the /**/ means it will be recursive and check subdirectories)
or
`cd src/util && standard`

**Comment by gsklee** [comment]
Thanks! I've sent a PR to update the readme with #136 accordingly.

**Comment by mnquintana** [comment]
Any chance of reopening this? It wasn't obvious even from the Readme that passing in directory names *wasn't* supported, and [that makes Standard oddly inconsistent with other linters](https://github.com/atom/ci/pull/20/files) (including eslint, which Standard uses in the background).

**Comment by feross** [comment]
Sure, let's reopen. I would accept a PR that added support for passing a directory name to the standard CLI. I think the necessary changes would go into [deglob](https://github.com/flet/deglob).
