### ISSUE TITLE
Linebreaks on Windows (CRLF vs. LF)

### ISSUE THREAD

**Issue by timdp** [feross/standard#140]
Let me start by saying I'm all for avoiding bikeshedding and finally agreeing on a clean style for JS. As soon as I discovered the standard, I started pushing it here at work.

That being said, we're primarily a Windows company and I was kind of disappointed when Atom's Standard linter started complaining about the fact that I use CRLF rather than LF. I'd happily switch to LF if it wouldn't cause issues with some apps (which I didn't write, so this is just a statement of fact).

Since I basically push all my stuff to a Git repository and Git silently handles line endings, personally, I don't worry about mixing CRLF and LF. I just use CRLF all over, since the platform actually expects me to.

I'd obviously like to avoid starting all my scripts with a preamble that makes the linter ignore CRLFs, especially since it won't affect people that pull in my code via Git. What are my options here?

I'm assuming that this issue pertains to JS Standard Style itself and not to the linter per se. Do correct me if I'm wrong. Thanks!

**Comment by feross** [comment]
@timdp Fair enough. I agree that most people are using Git and that automatically handles this. Released as 3.11.0.

**Comment by timdp** [comment]
Cool, thanks!
