### ISSUE TITLE
try/catch one liners

### ISSUE THREAD

**Issue by LinusU** [feross/standard#143]
Isn't the following allowed? I'm getting a rather cryptic error message and since we do allow e.g. `if` one liners I figured it would be okay.

```javascript
var result
try { result = parse(raw) }
catch (err) { return cb(err) }

cb(null, result)
```

```text
Closing curly brace does not appear on the same line as the subsequent block.
```

**Comment by julien-f** [comment]
I think it's because, `catch` should follow the closing braces of the `try`:

```javascript
try { result = parse(raw) } catch (err) { return cb(err) }

// or

try {
  result = parse(raw)
} catch (err) {
  return cb(err)
}
```

**Comment by LinusU** [comment]
Wow, fast reply!

Having them on one line actually works, but it makes for very long lines so I'm not sure if I want to use that.

Hmm, well we do allow the following

```javascript
if (false) return 123
else return 456
```

But not with curly brackets:

```javascript
if (true) { return 123 }
else { return 456 }
```

But with `try` and `catch` the brackets are mandatory :(

**Comment by julien-f** [comment]
You can use the following, it's ugly but it should work:

```javascript
try { result = parse(raw)
} catch (err) { return cb(err) }
```

**Comment by LinusU** [comment]
Ugh, that is ugly :) I think I'll stick with the 4-line version for now.

But I do propose that we have the rules be something that disallows anything after the `{`, unless the `}` is on the same line. And maybe even disallow having try and catch on the same line?

That way the thing I originally wanted would work and that ugly hack wouldn't...

I don't think there is any use case where you want to allow text after the curly bracket, unless when it's a one liner that closes on that line.

**Comment by julien-f** [comment]
standard is based on ESLint, therefore you will to find this rule in the [set of existing ones](http://eslint.org/docs/rules/) or propose a new one [there](https://github.com/eslint/eslint/issues).

**Comment by feross** [comment]
Like @julien-f says, you should use:

```javascript
try { result = parse(raw) } catch (err) { return cb(err) }

// or

try {
  result = parse(raw)
} catch (err) {
  return cb(err)
}
```

This is a result of our requiring "one true brace style", i.e. opening brace of a block must be on the same line. You can read more here: http://eslint.org/docs/rules/brace-style I agree that this try-catch case seems like it should be an exception. If you can get eslint to change it or add an option for this, I would merge it.

But this isn't a bug in standard, so I'm going to close this issue for now.
