### ISSUE TITLE
Tips for Vim users who also use jshint

### ISSUE THREAD

**Issue by olalonde** [feross/standard#146]
1) make sure your Syntastic is up to date (:PluginUpdate). standard support was only added a few months ago

2) If you use other syntax checkers, add this to your `.bashrc` or `.zshrc` and launch vim with `vims` to enable standard.

```
alias vims="vim -c \"let g:syntastic_javascript_checkers = ['standard']\""
```

**Comment by yoshuawuyts** [comment]
Or alternatively let vim auto detect your config in root, defaulting to `standard` if none is found:
```viml
autocmd FileType javascript let b:syntastic_checkers = findfile('.jshintrc', '.;') != '' ? ['jshint'] : ['standard']
```
[source](http://stackoverflow.com/questions/28573553/how-can-i-make-syntastic-load-a-different-checker-based-on-existance-of-files-in)

**Comment by dcousens** [comment]
Anyone have a snippet to instead use `./node_modules/bin/standard`?

**Comment by olalonde** [comment]
@yoshuawuyts nice. Do you have any idea on how I could have jshint as default and use standard only in projects which list it in package.json?

**Comment by yoshuawuyts** [comment]
@olalonde no idea, I'm not much of a viml expert. You could shell out to node or `jq`, read the json and check for the values you're expecting.

**Comment by olalonde** [comment]
@yoshuawuyts thanks, I'll see if I can come up with something.

**Comment by olalonde** [comment]
```viml
autocmd FileType javascript let b:syntastic_checkers = findfile('node_modules/.bin/standard', '.;') != '' ? [ 'standard' ] : [ 'eslint' ]
```

seems to work as expected.

**Comment by rstacruz** [comment]
as a neovim user i prefer https://github.com/benekastah/neomake. has built-in standard support and runs tools asynchronously (ie, no pause when you save files).
