### ISSUE TITLE
Support passing file names in as arguments

### ISSUE THREAD

**Issue by feross** [feross/standard#15]
Run `standard` to recursively check a whole project.
Run `standard < index.js` to check an individual file.

Need to support: `standard index.js` or `standard index.js test.js lib/a.js` to check a list of files. Shouldn't be hard to add.

**Comment by jonathanong** [comment]
looking for `standard lib`, where `lib` is a folder as well. might be useful to use https://www.npmjs.com/package/fs-readdir-recursive for that

**Comment by feross** [comment]
This is implemented now! Released as 2.4.0.

**Comment by feross** [comment]
@jonathanong It expects glob patterns, so `standard lib/*.js`. That work for you?

**Comment by feross** [comment]
Also, listing out files one at a time works too.

`standard index.js test.js bin/cmd.js`
