### ISSUE TITLE
Policy for adding browser globals?

### ISSUE THREAD

**Issue by cesarandreu** [feross/standard#151]
What are your plans for handling new browser globals? Or rather, how far along does adoption have to be for a browser global to get added?

For example, [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) adds `window.fetch`, `window.Request`, `window.Response`, and `window.Headers`.

**Comment by yoshuawuyts** [comment]
The browser globals are defined [here](https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json#L13-L19). I'm not sure if there's a policy, but only a minimum amount of globals are exposed. I wouldn't expect `window.fetch` to be called as `fetch`.

**Comment by cesarandreu** [comment]
Gotcha. I hadn't noticed, but yeah, none of the other browser globals are set.

**Comment by dcousens** [comment]
@cesarandreu IMHO the policy is you should be using `window.fetch`,  not just `fetch`.
If you feel strongly against this,  you could always add `/* global fetch */` at the top of your file.

**Comment by feross** [comment]
Yep, especially for lowercase global variables like `fetch`, it's really not clear where they come from (local or global variable?) unless you prefix with `window`. `window.fetch` is clearest.

I've considered adding all the browser globals that begin with capital letters, but it hasn't been annoying enough for me yet (or seemingly anyone else). I just do `/* global Blob */` if I'm going to be using lots of `Blob`s in a certain file.

**Comment by cesarandreu** [comment]
I gave it some thought, I agree it's probably better since it's more explicit.

**Comment by feross** [comment]
Cool, I'm going to close this.
