### ISSUE TITLE
EditorConfig file

### ISSUE THREAD

**Issue by emgeee** [feross/standard#153]
Has there been any discussion around including a default `.editorconfig` file configured with the defaults of standard?

**Comment by feross** [comment]
What would `.editorconfig` cover that our eslint rules doesn't already cover?

**Comment by emgeee** [comment]
As far as I'm aware, eslint merely yells at you if you break convention, it doesn't do anything to enforce convention. EditorConfig would allow you a simple mechanism for ensuring your editor is configured to use 2 spaces (instead of tabs, 4 spaces, etc), as well as automatically strip line endings.

**Comment by feross** [comment]
We use [`standard-format`](https://npmjs.com/package/standard-format) to automatically format code, including fixing things like space vs. tabs and stripping line endings.

You can use it with `standard --format` :-)

**Comment by winniehell** [comment]
With `.editorconfig` in place, you can use the short cut for formatting in your favorite IDE / editor. When using the same editor for languages other than JavaScript¹ mapping the shortcut to `standard --format` is not an option (... unless there is a `standard` for every common language out there).

¹ yes, I can't believe they stopped existing, either :grinning:

**Comment by feross** [comment]
I don't think `standard` should automatically add .editorconfig to people's
repos, but if you want to share an example of an .editorconfig that's set
up nicely for use with `standard`, we can link to it from the website or
readme.

On Sunday, August 2, 2015, Winnie <notifications@github.com> wrote:

> With .editorconfig in place, you can use the short cut for formatting in
> your favorite IDE / editor. When using the same editor for languages other
> than JavaScript¹ mapping the shortcut to standard --format is not an
> option (... unless there is a standard for every common language out
> there).
>
> ¹ yes, I can't believe they stopped existing, either [image: :grinning:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feross/standard/issues/153#issuecomment-127071728>.
>


-- 
Feross | blog <http://feross.org/> | webtorrent <http://webtorrent.io/> |
studynotes <http://www.apstudynotes.org/>

**Comment by winniehell** [comment]
Nevermind, I tried - but several (formatting) rules are not representable in `.editorconfig` settings. For example `spaces_around_brackets` does not distinguish between function definition and function call.
