### ISSUE TITLE
--formatter breaks on common ES6 code, fixed with esformatter ^0.7.0 dep

### ISSUE THREAD

**Issue by seeekr** [feross/standard#156]
Cross-posting here as well, not sure if that's necessary or not, but would really appreciate if this got fixed soon. It's a useful tool you created here and I'd like to be able to use from time to time the automatic formatter for converting projects with a different style.

If there's another way to help, I'd be happy to do so.

cc https://github.com/millermedeiros/esformatter/issues/324 https://github.com/maxogden/standard-format/issues/74

**Comment by feross** [comment]
Published standard-format 1.3.7 that uses esformatter 0.7.0.
