### ISSUE TITLE
Shorthand if/else statement

### ISSUE THREAD

**Issue by ricardofbarros** [feross/standard#158]
Shouldn't this be allowed? 
```js
var state = plug.currentState.toLowerCase() === 'off' ? false : true
```

In the newest version `4.x.x` standard is outputting this:

- Unnecessary use of boolean literals in conditional expression

**Comment by sindresorhus** [comment]
Should be: `var state = plug.currentState.toLowerCase() !== 'off'`

**Comment by julien-f** [comment]
Your code can be simply written like:

```javascript
var state = !(plug.currentState.toLowerCase() === 'off')
```

**Comment by ricardofbarros** [comment]
Thank you both, I completely forgot I could do that.
