### ISSUE TITLE
if statements: force brace or one-liner

### ISSUE THREAD

**Issue by dcousens** [feross/standard#16]
I find I have to double take when I look at [this](https://github.com/feross/bittorrent-dht/blob/a12735875febc72069256e47c14c7b89495656a2/client.js#L439-L441), to make sure I'm not mis-understanding what is actually part of the expressions that get executed.

The example is the following:
```javascript
if (condition)
  expression
else
  more expressions
otherstuff
```

I think that is confusing and unnecessary, and IMHO it should only either be:
```javascript
if (condition) expression
else more expressions
```

or

```javascript
if (condition) {
  expression
} else {
  more expressions
}
```

**edit:** Infact, I only ever use the shorthand one-liner for early-exit `return` statements, but YMMV.

@feross thoughts?

**Comment by mafintosh** [comment]
:+1:

**Comment by feross** [comment]
I'm also :+1: but theres no ESLint or JSCS rule that captures this. The closest I could find is: http://eslint.org/docs/rules/curly.html but it's not quite what we want. Take a look for yourself.

**Comment by kytwb** [comment]
+1 for braces everywhere:

```javascript
if (condition) {
  expression
} else {
  more expressions
}
```

**Comment by feross** [comment]
There is now an `eslint` rule that would enforce @dcousens's original request. `curly: [2, "multi-line"]`, see: http://eslint.org/docs/rules/curly.html

If we add this rule to `standard`, the following patterns will be considered errors:

```js
if (foo)
  doSomething()
else
  doSomethingElse()

while (foo
  && bar) baz()

if (foo) foo(
  bar,
  baz)
```

It will not error for these patterns:

```js
if (foo) return; else doSomething()

if (foo) return
else if (bar) baz()
else doSomething()

do something()
while (foo)

if (foo) {
  return
}

if (foo) { return }

while (true) {
  doSomething()
  doSomethingElse()
}
```

This is definitely a breaking change (it causes many of the modules in `test.js` to fail), so we'd need to bump the major version and release this as `3.0.0`.

**Comment by feross** [comment]
Is this worth doing? cc @mafintosh @othiym23

**Comment by dcousens** [comment]
I'm happy with the result of that rule.  ACK from me.

**Comment by othiym23** [comment]
@feross I'm in favor, but (to set error bars) I feel like I'm unusually particular about this rule.

**Comment by yoshuawuyts** [comment]
fwiw, I'm also in favor of this.

**Comment by mafintosh** [comment]
:+1: from me

**Comment by kytwb** [comment]
Isn't it too permissive?

**Comment by dcousens** [comment]
@kytwb what would you see changed?

**Comment by kytwb** [comment]
I'd reject those as well

``` javascript
if (foo) return; else doSomething()

if (foo) return
else if (bar) baz()
else doSomething()

do something()
while (foo)

if (foo) { return }
```
And force explicit blocks and braces while accepting same line chaining of else/else if/while with previous closing brace:

``` javascript
if (foo) {
  return; 
} else {
  doSomething()
}

if (foo) {
  return
} else if (bar) {
  baz()
} else {
  doSomething()
}

do {
something()
} while (foo)

if (foo) { 
  return 
}
```

**Comment by dcousens** [comment]
@kytwb I personally use `if (condition) return` as an early exit *everywhere* in my code, so that removing that would be a huge deal breaker for me.

**Comment by feross** [comment]
@kytwb Most users of `standard` use `if (condition) return` liberally. It's not practical to forbid it – we have to be pragmatic. I think the succinctness is worth the small risk of errors in this case, since handling an `err` argument is so common in JavaScript/node.js code: `if (err) return cb(err)`.

**Comment by kytwb** [comment]
Fair enough.

**Comment by feross** [comment]
This rule is added in `3.0.0-alpha`. Works great! Please give it a try and update your modules to always use statement braces, except for single-liners.

`npm install standard@3.0.0-alpha -g`
