### ISSUE TITLE
Bind operator breaks standard

### ISSUE THREAD

**Issue by LinusU** [feross/standard#160]
Using the bind operator completely breaks standard since it sees it as an illegal token.

```text
/tmp/bind-operator/example.js:5:20: Unexpected token :
```

Source:

```javascript
function ucFirst () {
  return this[0].toUpperCase() + this.substring(1)
}

console.log("linus"::ucFirst())
```

The bind operator is a strawman proposal for ES7, read more here: [ForbesLindesay/bind-operator][1], [Strawman spec][2].

[1]: https://github.com/ForbesLindesay/bind-operator
[2]: http://wiki.ecmascript.org/doku.php?id=strawman:bind_operator

**Comment by julien-f** [comment]
standard support custom parsers such as babel-eslint, see [this comment](https://github.com/feross/standard/issues/106#issuecomment-106883572)!

**Comment by LinusU** [comment]
This is awesome! There is no mentioning of it in the readme thought, and as far as I can tell you can't use it from the command line.
