### ISSUE TITLE
Mention custom parsers in the readme

### ISSUE THREAD

**Issue by LinusU** [feross/standard#161]
From #106 

> The latest version of standard (3.12.0) now supports custom JS parsers!

> To use a custom parser, install it from npm (example: npm install babel-eslint) and add this to your package.json:

```javascript
{
  "standard": {
    "parser": "babel-eslint"
  }
}
```

It would be good if this could be documented in the `README.md`

**Comment by yoshuawuyts** [comment]
PRs are welcome!

**Comment by feross** [comment]
Done.

**Comment by LinusU** [comment]
:+1:
