### ISSUE TITLE
Re-enable no-lone-block

### ISSUE THREAD

**Issue by julien-f** [feross/standard#163]
This rule has been disabled in #121 because it did not take into account ES6 block bindings.

As it has been fixed in [eslint 0.23](https://github.com/eslint/eslint/blob/master/CHANGELOG.md), I think it should be enabled again.

**Comment by Flet** [comment]
We may want to wait until 0.24.0 as there is a bug in 0.23.0 that is causing some of the tests to fail (eslint/eslint#2764).

**Comment by Flet** [comment]
...or at least 0.23.1 :)

**Comment by julien-f** [comment]
Indeed :)

**Comment by feross** [comment]
Agreed. I'll just re-enable the rule right away. We're [already depending](https://github.com/feross/standard/blob/2693b1d73d9af6da5fff9964fa1f88e89d8da5a0/package.json#L18) on a git commit hash for the eslint dependency, so I can just update the hash. As soon as 0.23.1 or 0.24.0 is released, we can switch back to the npm dep.

Released as 4.3.1.
