### ISSUE TITLE
Problem when using the full path when ignoring files

### ISSUE THREAD

**Issue by watson** [feross/standard#166]
I have a folder named `~/code/node_modules` in which I put the source code of all the modules I'm developing. But as of v4.0.0 it seems that standard will now use the full path of a file when choosing to ignore it or not (I think it was introduced by 647672192bb7188b8255be7302211acbb7e9f582). And since my `.gitignore` is set up to ignore the folder `node_modules`, standard will now ignore all my files since the parent two levels up is also called `node_modules`.

I think it would be an easy fix to just use the relative path, but I'm not sure so I would like to hear your comments :)

**Comment by feross** [comment]
Thanks to @mafintosh, this is fixed! Released as 4.3.2.
