### ISSUE TITLE
create website

### ISSUE THREAD

**Issue by jden** [feross/standard#169]
Whether or not we like it, a lot of javascript adoption happens in cargo-cult fashion based on how popular a thing is perceived to be and how much it looks like a "real thing." We use `standard` because we want our code to be consistent and have good defaults, and so we don't have to waste time with these little decisions. The less time we have to spend convincing other people we work with to do this, the better. Having a nice, memorable URL to send people to will help with `standard` adoption and help us put all this other stuff behind us.

**Comment by feross** [comment]
Yes! Let's do it.

**Comment by reg4in** [comment]
What about *standard.js.org*?
We could register that here: http://js.org/
Also, do we want a second repo or just a gh-pages branch?

I'd contribute :+1:

**Comment by louh** [comment]
:+1:

**Comment by feross** [comment]
@maxogden do you have any thoughts about how to get a site up and running? I know you've done this a bunch before for other projects :+1:

**Comment by maxogden** [comment]
@feross sorry missed your comment. I usually just fork a static site of another project that I like and modify it. In this case I think the site should have a 'paste your code here to check it with standard' thing, installation instructions and philosophy

could fork this http://moose-team.github.io/friends/

**Comment by bcoe** [comment]
I love the idea of having a website. Perhaps it could have a section that features projects that adhere to the standard format? Good way to show off the adoption happening.

**Comment by Flet** [comment]
Had some fun today
http://flet.github.io/standard-www

This is just a site generated from the README.md (and RULES.md) using a theme I like :)

Agree with @bcoe that it would be cool to have a "Who's using it?" page. If the list of sites in `clone.js` were its own json file, it could be done with this generated site.

**Comment by feross** [comment]
@Flet Nice!

**Comment by feross** [comment]
@Flet 

I just registered standardjs.com. Waiting for Linode support (apparently someone else has set up DNS for standardjs.com before - just need them to delete that old entry) and then I can point it at your repo.

Then we just need to add a `CNAME` file that contains `standardjs.com` to the repo and we're good :)

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by Flet** [comment]
Cool! Happy to transfer it to you as well for consistency and add contributors.

**Comment by feross** [comment]
Okay, that's a good idea. Can you transfer it? Thanks!

**Comment by Flet** [comment]
Done and done.
http://github.com/feross/standard-www

**Comment by feross** [comment]
And now DNS is set up! http://standardjs.com should work!

If it doesn't work, give it a few hours... DNS is slow.

**Comment by feross** [comment]
Now that we have a site, post site related issues here: https://github.com/feross/standard-www/issues

I'll close this now. Thanks so much @Flet!! :cat2: :+1: :cat2:
