### ISSUE TITLE
Redefinition of 'Map'

### ISSUE THREAD

**Issue by LinusU** [feross/standard#171]
Node.js dosen't ship with `Map` from ES6 so I'm using a standalone library to provide it. It seems like `standard` thinks that `Map` already exists in the global scope since it gives me back the following error.

```text
/path/to/filename.js:1:4: Redefinition of 'Map'.
```

This is my code:

```javascript
let Map = require('es6-map')
```

**Comment by feross** [comment]
In general, this rule is a good thing. It prevents you from redefining `Array` and other built-ins. You can selectively disable this rule for your situation. Run `standard --verbose` to find out the rule name (`no-native-reassign`).

You can disable the specific rule like this:

```js
let Map = require('es6-map') // eslint-disable-line no-native-reassign
```

Or more succinctly disable all checking on this line, like this:

```js
let Map = require('es6-map') // eslint-disable-line
```

**Comment by dcousens** [comment]
@LinusU that is because,  conceptually,  you are overriding the `Map` built in,  its just that you don't have that built in... yet.

**Comment by LinusU** [comment]
Sounds fair enough
