### ISSUE TITLE
The "no semicolons" - let's start a philosophical discussion ;)

### ISSUE THREAD

**Issue by redaktor** [feross/standard#176]
First of all:
Basically I agree with each and every point of this "standard" - 
This is "best options" and I want to thank you.
But there is one thing I totally disagree with: *no semicolons*.

Does it really mean it is forbidden to use semicolons ? <br>
I know that they are basically not needed. For me it is more a philosophical and logical question.<br>
Can we start a discussion ?

In most written languages sentences are terminated by a dot.
This is because the writer wants to tell the reader to think for a millisecond. 
And to indicate that the next sentence might have a different logic.
The same applies to programming languages.
Additionally I feel better if humans see the invisible signs that machines are processing.
Veto. I would not prohibit semicolons.

I know that there is a [dup with 43 entries](https://github.com/feross/standard/issues/78) which was so active and became closed and locked. 
So many people saying it is impractical.
And I am just another person who would not use such a "standard" just due to this one point.

**Comment by dcposch** [comment]
> Can we start a discussion?

Nope, sorry.

Dupes #5, #78, and #79. Check out the explanation on #78 in particular.

**Comment by dcposch** [comment]
Also, you might find semistandard useful: https://github.com/Flet/semistandard

**Comment by dcousens** [comment]
And if you like semicolons *and* tabs,  you might like [happiness](https://github.com/JedWatson/happiness). 

I personally prefer `standard`,  but the advantages are far to great to let bike shed discussions stop you from reaping the benefits that this approach provides.
