### ISSUE TITLE
standard organization

### ISSUE THREAD

**Issue by Flet** [feross/standard#178]
Does putting `standard` in an organization seem like a good idea? 

There are several little supporting repositories owned by various folks that could make sense grouped together (standard-format, sublime/atom plugins, eslint configs, etc). This org could also host a repository for a github pages website for #169.

I guess its really up to @feross, but I would be happy to transfer my related repositories.

**Comment by jprichardson** [comment]
In most cases I'd support this sort of move. In this case, I'm not so sure. I think @feross has done an excellent job maintaining `standard` and pushing updates in a timely fashion. Maybe we (really he) should wait until it becomes a big problem? As you said, ultimately it's up to @feross; I'll support his decision either way.

**Comment by yoshuawuyts** [comment]
I agree with @jprichardson, apart from discovery there doesn't appear to be much incentive at this time to move to an org. Maybe it'd be worthwhile thinking about how discovery of `standard` related modules could be improved?

**Comment by feross** [comment]
I'm not sure what the benefit of an org is. I'd rather keep things the way they are for now. If there's a compelling reason in the future, I'm happy to move this to an org :)

Re: the discoverability point, I just added a section to the readme with a list of packages related to `standard`: https://github.com/feross/standard/commit/8ff248c7773e87110c80bf852c7aaa11e406d58d Feel free to add more to the list!

**Comment by Flet** [comment]
Indeed, @feross you're doing great :)

Thanks all for sharing!
