### ISSUE TITLE
Question: how do you handle file-wide IIFEs?

### ISSUE THREAD

**Issue by rstacruz** [feross/standard#179]
You'll commonly see this pattern in frontend scripts, especially ones using the umd loader:

```js
;(function () {
  // code here
}());
```

the semicolons are there to prevent oddities in concatenation with other scripts. you can keep the beginning `;`, but not the ending `;`.

is there a better workaround other than to resort to `// eslint-disable-line`?

**Comment by yoshuawuyts** [comment]
Maybe it's a silly suggestion, but couldn't the concat script be configured to inject a `;` between each file?

**Comment by feross** [comment]
I usually write commonJS and use browserify to make a standalone UMD build when I need it, so this hasn't come up for me.

If you're concerned about your users using a naive concatenation script, I would leave the `;` at the end of the file and use `// eslint-disable-line` like you suggested:

```js
;(function () {
  // code here
}()); // eslint-disable-line
```

I'll leave this issue open for a while in case others have ideas.

**Comment by rstacruz** [comment]
> Maybe it's a silly suggestion, but couldn't the concat script be configured to inject a ; between each file?

Most smart concatenators would do something like this, but not all concatenators are smart.
