### ISSUE TITLE
var arr = [ 1, 2 ] and arr = [1,2] allowed

### ISSUE THREAD

**Issue by vvo** [feross/standard#180]
Reading https://github.com/feross/eslint-config-standard/blob/114e768090adff82ed8f8641e60ae5568b3dcdbd/eslintrc.json#L175 means that you can write your code:

```js
var arr = [ 1, 2 ]
// or
var arr = [1,2]
```

1. is that true?
2. I thought the goal of standard was to avoid such situations but I may be wrong and http://jscs.info/overview.html may be a better solution
3. if the goal of standard is to avoid such issues then forgive me and close it :)

**Comment by dcousens** [comment]
> var arr = [1,2]

That is not allowed,  and will give you a warning regards the trailing space.

**Comment by feross** [comment]
@dcousens You're right, but there's still a bit of ambiguity here. Both of these are allowed:

```js
var arr = [ 1, 2 ]
var arr = [1, 2]
```

Similarly to my comment [here](https://github.com/feross/standard/issues/182#issuecomment-118176321), I would like to enforce `[ 1, 2 ]` but I think it may be too late to make a change like that without upsetting tons of users.

**Comment by dcousens** [comment]
@feross heh, true, I don't think I've ever written an array like `[ 1, 2 ]`,  but in terms of consistency, you're entirely correct that it is the right choice.
