### ISSUE TITLE
ESLint: `no-useless-call`

### ISSUE THREAD

**Issue by mightyiam** [feross/standard#184]
https://github.com/eslint/eslint/commit/2f2924f5fb8cefe403279ea4e0bdf5a6d6b4ed55

**Comment by dcousens** [comment]
This is great,  for ES6.

In ES5 it would limit the user from using `apply`.

**Comment by mightyiam** [comment]
@dcousens it doens't prevent use of `appply` altogether. Only when it is better to use the `()` call syntax.

Do you see something that I do not?

**Comment by feross** [comment]
@mightyiam Nice - this rule looks good to me, unless I'm missing something that @dcousens has caught. The new rule is in the `master` branch, so we have to wait for a release before we can add this rule.

**Comment by dcousens** [comment]
Nevermind,  I was mistaking the changes for `prefer-spread` to be relevant to this rule also.

:+1: lets put it in.

**Comment by feross** [comment]
This will be fixed in eslint 1.0.0 and standard 5.0.0. https://github.com/feross/standard/issues/192
