### ISSUE TITLE
Link to @shama's excellent semicolons video

### ISSUE THREAD

**Issue by Flet** [feross/standard#191]
Can we add a link @shama's video on semicolons to the README and/or the wiki? 

https://www.youtube.com/watch?v=gsfbh17Ax9I

It very clearly spells out the corner cases :)

**Comment by feross** [comment]
Nice video! I like it

**Comment by shama** [comment]
Thanks! I'm glad you like it! :D

**Comment by feross** [comment]
I just added a link!
