### ISSUE TITLE
standard v5.0.0

### ISSUE THREAD

**Issue by feross** [feross/standard#192]
eslint v1.0.0 will be released soon! eslint added some new rules that are nice, and lots of existing rules have subtle behavior changes designed to catch more errors.

Let's talk about the next version of standard! We'll bump the major version to standard v5.0.0 to pull in these improvements.

#### New rules:

- space before/after arrow functions (https://github.com/feross/eslint-config-standard/commit/cf31561306f102b0772de55cd410b20912e733ee)
- indent switch "case" sections (https://github.com/feross/eslint-config-standard/commit/c6b10f68aa31e323933b14e04b50d8c1075ef28c)
- don't reassign class variable names (https://github.com/feross/eslint-config-standard/commit/96c727fdf917f213e23320cc9971a0e2e5bf2b7b)
- don't reassign const variables (https://github.com/feross/eslint-config-standard/commit/2dd1a09edcff6656731a394231e93850e55cc39d)
- don't use .call() or .apply() to invoke a function unless it's necessary (https://github.com/feross/eslint-config-standard/commit/6fba6e34d9281a716bf7ffc9fc5d804f6403f505)
- generator functions should always have a `yield` keyword (https://github.com/feross/eslint-config-standard/commit/63ab1c60c186411cc694c2fab76984d35f01cae9)

There were other new rules that I didn't add because they have too many false positives, require ES6-only codebases, or would be divisive: https://github.com/feross/eslint-config-standard/commit/a211a1c9ca9f5ae64899746b8578b3978d9270dc

#### Changed rules:
- use `no-extra-parens` instead of the deprecated `no-wrap-func` rule (https://github.com/feross/eslint-config-standard/commit/fc8a076c156d949b0b6046281f2e5f5c91e7da62)
- `indent` got stricter and catches errors in object literal indentation. 12/131 repos in the test suite started failing after this rule was improved.

I'm posting this to get feedback. Please share your thoughts! I published a prerelease version (v5.0.0-1). Please give it a try on your code!

```
npm install -g standard@next
```

**Comment by feross** [comment]
Just fixed something up. Use `standard@5.0.1-0`

**Comment by feross** [comment]
This might also be a good opportunity to make other breaking changes we want to make. In particular, the work in this PR: https://github.com/feross/standard/pull/189 Anything else we should think about?

**Comment by jprichardson** [comment]
Unnecessary `apply` (`no-useless-call`) rule fails on common case of using `concat` to flatten an array one level deep. Consider:

```js
var arr = [].concat.apply([], [[1], [2], [3]])
console.dir(arr)
```

**Comment by Flet** [comment]
standard@5.0.1-0 === standard@latest?

**Comment by feross** [comment]
@Flet I believe that's expected behavior. The `latest` tag is what you use if you want prerelease versions. Running `npm install -g standard` still gives you the stable `4.5.4` version.

**Comment by feross** [comment]
@jprichardson Good catch re: `no-useless-call`. This looks like an eslint bug to me. I just opened an issue: https://github.com/eslint/eslint/issues/3054

I also just learned that`5.0.1-0` should have been `5.0.0-1`. Future v5 prereleases will be `5.0.0-1`, `5.0.0-2`, `5.0.0-3`, etc.

**Comment by Flet** [comment]
@feross thanks, I did not realize this!

Doing this: `npm install -g standard`= 4.5.4
Doing this: `npm install -g standard@latest` = 5.0.1-0

Looking for some npm docs on this behavior, but not finding any :( 

Anyways, carry on. :)

**Comment by feross** [comment]
hm, actually, i think what's happening is that when you do a publish, npm updates the `latest` tag to point to it. and `npm install` just picks the most recent, non-prerelease version to install.

**Comment by Flet** [comment]
Yeah, I found where [npm iterates over the versions](https://github.com/npm/npm/blob/c9fbbb540083396ea58fd179d81131d959d8e049/lib/fetch-package-metadata.js#L116) and picks the one to install... It looks like `semver` is checking the version against an empty string since none was specified.
Also https://github.com/npm/node-semver#prerelease-tags

Fun stuff!
```
❯ npm install semver && node 
> var semver = require('semver')
undefined
> semver.satisfies('5.0.0-0', '')
false
> semver.satisfies('5.0.0', '')
true
```

And of course there is code above this part that will use the tagged version if a tag is passed.

Cool, I assumed that `lastest` was always used, but that is not the case!

**Comment by LinusU** [comment]
I get this version when I run the following, is that suppose to happen?

```text
➜  npm install --save-dev standard
standard@5.0.0-2 node_modules/standard
```

**Comment by dcousens** [comment]
@jprichardson because it should?

`[].concat([1], [2], [3])` will be exactly the same.

**Comment by jprichardson** [comment]
> [].concat([1], [2], [3]) will be exactly the same.

No it's not. That outputs:

```js
[ 1, 2 ]
```

What I was trying to demonstrate:

```js
var b = [[1], [2], [3]]
var arr = [].concat.apply([], b)
console.dir(arr)
```

Which standard accepts. So maybe there isn't much of an issue here.

**Comment by dcousens** [comment]
``` javascript
> [].concat([1], [2], [3])
[ 1, 2, 3 ]
```

@jprichardson,  what?

**Comment by jprichardson** [comment]
> @jprichardson, huh?

Had a screw loose, you are correct.

> I use this pattern all the time to flatten arrays, using [].concat(... arrays).

As do I, that's why I brought up the issue as noted in my first comment.

> Just re-read your example, you meant in the case that b wasn't a constant expression... I'm pretty sure it will be allowed in that case.

Hence, why I said:

> Which standard accepts. So maybe there isn't much of an issue here.

i.e. it looks like `standard`/`eslint` is working correctly :)

**Comment by feross** [comment]
@LinusU When I run `npm install --save-dev standard` I get:

```
standard@4.5.4 node_modules/standard
```

Can you check your `package.json` and make sure that `"standard": "*"` isn't present? `npm install` should not install prerelease versions like `5.0.0-2` unless the `package.json` explicitly allows it. I think that is what's going on for you.

**Comment by LinusU** [comment]
![screen shot 2015-07-21 at 00 30 51](https://cloud.githubusercontent.com/assets/189580/8789090/c6389d40-2f3f-11e5-9202-11dece28534d.png)

```text
➜  test  npm --version 
2.10.1
➜  test  node --version 
v0.12.4
```

**Comment by DadaMonad** [comment]
> generator functions should always have a yield keyword (feross/eslint-config-standard@63ab1c6)

I agree that this is a neat rule in most cases. But what if a third party library expects a generator function as an argument, and my generator implementation doesn't actually need to `yield`? Since I can't configure standard it is impossible for me to lint successfully.

**Comment by dcousens** [comment]
@DadaMonad then use an inline comment to disable that rule in place?

**Comment by DadaMonad** [comment]
@dcousens  I don't think that this is a good solution. I have plenty of generator definitions that do not yield. In my humble opinion, the linter should not get too much in my way.

Furthermore, I don't really see a scenario where a rule like this could prevent me from doing something stupid. When you declare a generator function you probably have good reasons for it..

**Comment by dcousens** [comment]
@DadaMonad well, beyond that,  I haven't used `yield` enough to give a meaningful opinion :),  so I'll trust your judgement.

**Comment by feross** [comment]
@LinusU 

Okay, I cleared up the version confusion by using tags.

```
$ npm dist-tag ls standard
latest: 4.5.4
next: 5.0.0-3
```

To get the 5.0.0 beta versions, use `npm install standard@next`.

**Comment by feross** [comment]
@DadaMonad Can you link to some examples of generator functions you've written that do not yield? You may have a point.

**Comment by DadaMonad** [comment]
@feross I want my framework to support different databases to store its  state persistently. I use indexedDB in the browser, and redis in nodejs. When I yield, I request data from the database. You can also store non-persistently in the Memory. An in-memory database implementation naturally has no asynchronous behaviour - therefore, I do not need to yield.

You can compare the following files: [Memory](https://github.com/y-js/yjs/blob/dd5e2adc87fc7adcdca80a54c22a9214bcdba5e7/src/OperationStores/Memory.js) vs. [indexedDB](https://github.com/y-js/yjs/blob/dd5e2adc87fc7adcdca80a54c22a9214bcdba5e7/src/OperationStores/IndexedDB.js)

**Comment by mightyiam** [comment]
Thank you for 5.0!

**Comment by feross** [comment]
@DadaMonad Thanks for the feedback. I just removed the `require-yield` rule.

**Comment by DadaMonad** [comment]
Thanks a lot @feross ! :+1:

**Comment by cesarandreu** [comment]
Another case where you want a generator function that doesn't yield anything is with koa. I have a reasonable amount of those. Each middleware is a generator functions, and depending on how you setup your middleware, your final "controller action" middleware can end up looking like this:

```js
UsersController.current = function * current () {
  this.body = this.state.user
}
```

Along the same line, when using async functions you don't wanna force it to have an await. One example of this: you have an async function that'll return a cached value immediately if it's available, otherwise it will do a network request. Since an async function will always return a promise, it's always async (no zalgo, kthx) but you might not have anything that you need to actually await. 

```js
async function getOrFetch (id) {
  return id in cache
    ? cache[id]
    : (await fetchThing(id))
}
```

**Comment by feross** [comment]
@cesarandreu Good to know!

**Comment by feross** [comment]
ESLint has one more breaking change we haven't discussed yet:

> Switch to 1-based columns (fixes https://github.com/eslint/eslint/issues/2284) (Nicholas C. Zakas)

Before, ESLint would report errors with 0-based columns.

The current 5.x pre-releases are just passing this change through, meaning that editor integrations are  currently off-by-one with standard 5.x. It's not hugely disruptive, but plugin maintainers should update their packages.

That's you @Flet, @ricardofbarros, @ishamf, @scrooloose. :cat2: 

I'll release the stable 5.0.0 today.

**Comment by LinusU** [comment]
@feross If plugin maintainers need to make an update, what do you think of adding `--json` to get the output in a format even easier to parse than what is current. That way we have a path forward for starting to change the output to be even prettier and more human readable.

ping #218

**Comment by feross** [comment]
@LinusU The current format is super easy to parse with a one-line regex https://github.com/Flet/SublimeLinter-contrib-standard/blob/master/linter.py#L25 But let's keep that discussion in https://github.com/feross/standard/pull/218.

**Comment by feross** [comment]
standard 5.0.0 is released! :tada: :balloon:

**Comment by ricardofbarros** [comment]
Thank you @feross Will update as soon as possible :smile:

**Comment by feross** [comment]
@ricardofbarros nice!

**Comment by cesarandreu** [comment]
\o/

**Comment by mightyiam** [comment]
Hurrah!

**Comment by boennemann** [comment]
@feross Thanks so much for this new version!

I just wanted to suggest adding these release notes (or at least a link) to the Releases page on GitHub or to a CHANGELOG.md file.

For me I only notice that there is a new version of standard, because some dependency badges turn yellow or red. I then come to your repo page to check whether the changes actually affect me and how to update, but I just can't find any indication of what's breaking. Only because I know you and the project well enough I then turn over to Twitter where I find a link to this issue. I think using common places like GitHub Releases or CHANGELOG.md makes the update process way easier for everyone.

Thank you :+1:

**Comment by LinusU** [comment]
+1 for [keeping a changelog](http://keepachangelog.com), it's a great way to keep up to date with the rule changes.

**Comment by feross** [comment]
@boennemann @LinusU Thanks for the changelog suggestion. I just added the release notes from this issue to the Releases page. :+1:
