### ISSUE TITLE
Why not use the babel-eslint parser?

### ISSUE THREAD

**Issue by 0x80** [feross/standard#193]
I am using es7 decorators and noticed that standard linter doesn't allow them, and then found out that standard is not using babel-eslint as it's parser. Please start using that.

**Comment by Flet** [comment]
Hello!

Its possible to provide a custom parser to meet these needs:
https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support

**Comment by 0x80** [comment]
Aha! Thanks. Sorry I missed that.
