### ISSUE TITLE
Phantomjs environment broken

### ISSUE THREAD

**Issue by LinusU** [feross/standard#194]
For some reason a file like the following fails with `"phantom" is not defined.`.

```javascript
/* eslint-env phantomjs */

phantom.exit(0)
```

**Comment by LinusU** [comment]
The problem was in eslint, I proposed a fix over there...

**Comment by LinusU** [comment]
Patch merged into master in eslint

**Comment by LinusU** [comment]
@feross Could you add the `blocked-on-eslint` label on this bug please :)

**Comment by feross** [comment]
@LinusU Done! Thanks :)

**Comment by feross** [comment]
Fixed in eslint master :) standard will get the fix the next time we update eslint.
