### ISSUE TITLE
Vim: How to run `standard --format` on `save`

### ISSUE THREAD

**Issue by diasdavid** [feross/standard#195]
Following this [thread](https://twitter.com/daviddias/status/622077275022831616), one of the features I've enjoyed a lot using [vim-go](https://github.com/fatih/vim-go) was its ability to run `gofmt` on each save, saving me a ton of work. Would love to have this functionality for JavaScript with Standard codestyle, but I'm not sure how to do it or if there is an option available out there already. Thoughts?

Thank you.

**Comment by feross** [comment]
As far as I know, Syntastic doesn't support formatters, so someone needs to write a vim plugin to do this.

**Comment by feross** [comment]
@diasdavid There is a suggestion here for how to make a plugin. https://twitter.com/feross/status/624033217016930304

Looks like it might be a one-liner!

**Comment by caspervonb** [comment]
Minor variation, primarily calling it after the file has finished writing and making it a silent operation.

```vim
autocmd bufwritepost *.js silent !standard % --format
```

**Comment by diasdavid** [comment]
![](https://www.dropbox.com/s/2xpbhy38yzv9zqo/Screenshot%202015-07-22%2023.07.57.png?dl=0)

This is very good stuff! Thank you! 

We are almost there. Comparing to vim-go, the only thing missing is to do formatting without that confirmation. Would that be possible?

**Comment by dcousens** [comment]
@diasdavid you'd probably need to modify the buffer directly,  overwriting its contents rather than overwriting the underlying file.

**Comment by yoshuawuyts** [comment]
Haven't verified if it works yet, but [`vim-autoformat`](https://github.com/Chiel92/vim-autoformat) was updated recently to support this exact use case.

**Comment by caspervonb** [comment]
That's with the post write event? was getting it with `bufwrite` but not with `bufwritepost`

**Comment by caspervonb** [comment]
If thats still the case, setting `:set autoread` should do the trick and disable the W11 warning, always re-reeading the file.

**Comment by diasdavid** [comment]
rad! it works :D 

```
autocmd bufwritepost *.js silent !standard % --format
:set autoread
```

**Comment by caspervonb** [comment]
@diasdavid  was `autoread` required?

**Comment by feross** [comment]
Sweet! Glad you guys got it figured out. Thanks for the help @caspervonb!

I'll add this snippet to the readme. Should someone publish this as a standalone vim plugin? I'm not sure if the community does small modules like npm does ;)

**Comment by feross** [comment]
There was a suggestion on Twitter to persist cursor position as well: https://twitter.com/oObsi/status/624533766434910208

I haven't tested the snippet out yet. Is this actually necessary?

**Comment by cryptix** [comment]
IIRC from some buffer replacement hacking, your cursor gets reset to line 0 but i might be or did things  wrong.

**Comment by diasdavid** [comment]
If there are 'errors' that --format can't fix, like non used vars, the autoformat gets weird:

![image](https://cloud.githubusercontent.com/assets/1211152/8886463/7079a7c2-321f-11e5-8738-65a43d2b9a7b.png)

**Comment by caspervonb** [comment]
That's "expected", but i did not expect `standard` to lint and format at the same time.
@feross anyway to suppress errors and just format?

**Comment by feross** [comment]
@caspervonb Can't you just ignore stdout and stderr? The formatting happens in place to the file on disk, so it's safe to just throw away that output if you don't want to show it in the UI.

**Comment by feross** [comment]
@caspervonb Also, if it's helpful, you can format a file by piping it to stdin using `standard --format --stdin`. The transformed code is written to stdout. Lint errors are written to stderr which can be safely ignored.

**Comment by caspervonb** [comment]
Could try muffle the output from standard with redirection

```vim
autocmd bufwritepost *.js silent !standard % --format > /dev/null>2&1
```

**Comment by locksmithdon** [comment]
Now that the formatting feature of standard has been moved into standard-format, has anyone worked out how to apply this in vim?

**Comment by caspervonb** [comment]
@locksmithdon What is the difference? just invoke it as you would from a shell basically.

**Comment by locksmithdon** [comment]
@caspervonb I was missing `-w` and it wasn't working. I know, RTFM :wink: This works:
```vim
autocmd bufwritepost *.js silent !standard-format -w %
set autoread
```

**Comment by babenzele** [comment]
Just to close the loop since I got here from google, this is explained in the docs:

https://standardjs.com/#vim
