### ISSUE TITLE
Trigger Travis rebuild

### ISSUE THREAD

**Issue by LinusU** [feross/standard#197]
@feross, could you please trigger a rebuild [on Travis CI](https://travis-ci.org/feross/standard). The current master failed because of mafintosh/chromecasts#9 which now has been merged.

**Comment by Flet** [comment]
I pushed some buttons.
The master build Looks good now? https://travis-ci.org/feross/standard/branches

**Comment by feross** [comment]
Travis seems to base the badge state on the most recent build, regardless of whether it's the latest commit or not. Not ideal...

**Comment by Flet** [comment]
Maybe update readme to point to master for the badge?

https://travis-ci.org/feross/standard.svg?branch=master&style=flat
