### ISSUE TITLE
`no-throw-literal` warning not shown on concatenated exception messages

### ISSUE THREAD

**Issue by taromero** [feross/standard#198]
`throw 'a' + 'b'` doesn't show the `no-throw-literal` warning, as I would expect.

`throw 'a'` (no string concatenation) does show the warning.

This is probably an issue of the underlying linters that `standard` uses (in which case please close this ticket), but I'm rising the flag just in case.

**Comment by feross** [comment]
Reported to eslint: https://github.com/eslint/eslint/issues/3099

**Comment by feross** [comment]
Fixed in eslint master :) standard will get the fix the next time we update eslint.
