### ISSUE TITLE
My opinion: Use of self is a bad idea

### ISSUE THREAD

**Issue by DamonOehlman** [feross/standard#2]
For a couple of reasons:

1. `self` resolves to the global window context in the same way that this does, well at least that's been my experience and have been confused by it in the past.  Open the dev console in chrome and eval `self` for an example.

2. It assumes that there is only one item that will have it's context dissociated on callback firing.  While this is generally true when you are writing nice clean code, there are occasionally instances where this will not be true.

Like I said though, this is just my opinion...

**Comment by DamonOehlman** [comment]
Just checked Firefox and self -> Window also...

**Comment by joshgillies** [comment]
So advocating the use of `Function.prototype.bind()` as opposed to `var that = this` or `var self = this` as a convention?

**Comment by DamonOehlman** [comment]
I think `var foo = this` is a reasonable approach, and I definitely do it frequently.  Usually though I replace `self` with something that is more meaningful with regards to object instance.  While I'm not a fan of using `that` it doesn't fall victim to problem 1 so might be ok.

**Comment by feross** [comment]
You are correct that `self` resolves to `window` in the browser. Here's an MDN page on the behavior: https://developer.mozilla.org/en-US/docs/Web/API/Window.self

I know no one who would ever intentionally use `self` instead of `window`, and this module considers using `window.self` a failure. It fails with the error:

```bash
Error: Code style check failed:
  /Users/feross/code/standard/index.js:47:3: 'self' is not defined.
```

I think `self` is a lot clearer than `that` or `_this`. Given that this module catches the case where the user forgets to declare `var self = this` I think it's a safe recommendation.

**Comment by feross** [comment]
Fun fact: Did you know that `self.window.self.window.self.self.self === window`?

**Comment by feross** [comment]
@DamonOehlman Given that there's a check for accidental `window.self` usage, would you say point 1 is sufficiently addressed?

**Comment by DamonOehlman** [comment]
Yeah absolutely mate - and thanks for the fun fact :)

**Comment by tbranyen** [comment]
Can you use standard when writing WebWorker code where you cannot avoid the self global?

> Workers run within a global context different from the current window. Thus, using the window shortcut to get the current global scope (instead of self) within a Worker will return an error.

**Comment by feross** [comment]
Yep.
