### ISSUE TITLE
Array destructuring

### ISSUE THREAD

**Issue by despairblue** [feross/standard#203]
Neither
```javascript
let [route,] = 'post?id=1234'.split('?') // Unexpected trailing comma.
```
nor 
```javascript
let [route, ] = 'post?id=1234'.split('?') // Unexpected trailing comma. + A space is required after ','.
```
is allowed.

Whereas this
```javascript
let [, parameters] = 'post?id=1243'.split('?')
```
is allowed.

Whether doing this is a good idea is probably disputable, but it is legal syntax.

**Comment by feross** [comment]
`standard` is a code linter – the whole purpose is to prevent legal syntax that's confusing and/or likely to be a bug. :)

The first two examples `let [route,] = ...` and `let [route, ] = ...` are better written as `let [route] = ...`. The comma does nothing, and `standard` disallows trailing commas in other situations, so this is consistent.

The last example `let [, parameters] = ...`, actually does something useful. It selects the second item in the array. Unless I'm missing something, I can't see a reason to disallow this usage

**Comment by despairblue** [comment]
@feross duh, yeah, I missed the forest for the trees while refactoring, my bad :sweat_smile:

**Comment by feross** [comment]
No worries!
