### ISSUE TITLE
Standard on the ternary operator

### ISSUE THREAD

**Issue by naknode** [feross/standard#206]
Take this code for example.

    var test = {
      getTest: function (foo) {
        var foo
        var bar = 0
        if (foor == null ? bar = 12 : bar = 5)
      }
    }
    
    test.getTest(false)

Using Standard formatting and Standard styling, it will always compile an error whenever there is a [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) present.

The error will occur on `line 6` at the `}` character. How would you propose going around this?

Using this for reference:

    λ standard --verbose src/js/monsters.js | snazzy
    standard: Use JavaScript Standard Style (https://github.com/feross/standard)
    
    \wamp\www\navarra\src\js\monsters.js
      6:4  error  Unexpected token }   undefined

I am a Windows 7 (64-bit) build.

**Comment by dcousens** [comment]
@naknode this isn't just a ternary expression,  you are actually missing the followup `if` block entirely.
Hence, the parsing error `error  Unexpected token }   undefined`

**Comment by naknode** [comment]
Well, now... don't I feel foolish. I must have mis-read the [document](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) wrong on Mozilla. Thank you.

**Comment by dcousens** [comment]
No worries @naknode :)
