### ISSUE TITLE
Function argument alignment causes false positive about indentation

### ISSUE THREAD

**Issue by idan** [feross/standard#208]
So, I have an unfortunate function with a slew of default parameters like so:

```javascript
export function create (id, xfilter, rawType,
                        width=defaultWidth, height=defaultHeight,
                        footerHeight=defaultFooterHeight,
                        padding=defaultPadding) {
  // ... function body, indented two spaces
}
```

However this gets me complaints about the function body not being indented 26 spaces. :frowning: 

I tried putting the opening brace on the following line in column zero, and it netted me a separate warning about the brace not being on the same line as the controlling statement.

One way I've found to keep standard happy is by doing this:

```javascript
export function create (
id, xfilter, rawType,
width=defaultWidth, height=defaultHeight, footerHeight=defaultFooterHeight,
padding=defaultPadding) {
  // ... function body, indented two spaces
}
```

.. which doesn't read well for me.

Another is this, which is more legible to my eye:

```javascript
export function create (id, xfilter, rawType,
                        width=defaultWidth, height=defaultHeight,
                        footerHeight=defaultFooterHeight,
                        padding=defaultPadding
) {
  // ... function body, indented two spaces
}
```

I feel like I'm missing something. What's the proper way to author standardjs-compliant functions with multiline arguments?

**Comment by julien-f** [comment]
What about this?

```js
export function create (
  id, xfilter, rawType,
  width=defaultWidth, height=defaultHeight,
  footerHeight=defaultFooterHeight,
  padding=defaultPadding
) {
  // ... function body, indented two spaces
}
```

Anyway, IMHO with so many arguments you should use named parameters with an object and destructuring.

**Comment by feross** [comment]
@idan What version of standard? Run `standard --version`.

**Comment by idan** [comment]
@julien-f that does look nice. In this case I wanted the laziness of default params and with destructuring, I think I'd have to add some extra logic to set the defaults? I need to read up on how that would work.

@feross 4.5.4

**Comment by julien-f** [comment]
@idan Nope, not so much:

```js
export function create ({
  id, xfilter, rawType,
  width=defaultWidth, height=defaultHeight,
  footerHeight=defaultFooterHeight,
  padding=defaultPadding
} = {}) {
  // ... function body, indented two spaces
}
```

**Comment by idan** [comment]
@julien-f nifty! Thanks for the educational moment. :smile:

**Comment by feross** [comment]
@julien-f that's sexy!

This looks like an indentation bug in eslint. Bug filed here: https://github.com/eslint/eslint/issues/3173

**Comment by feross** [comment]
Fixed in eslint master, so this will be fixed in a future `standard` release when we upgrade the eslint dependency.
