### ISSUE TITLE
space-in-parens in template string

### ISSUE THREAD

**Issue by despairblue** [feross/standard#209]
```javascript
var test = `(hi )`
console.log(test)
```

yields `/home/despairblue/vcs/git/prototype2/test.js:1:15: There should be no spaces inside this paren. (space-in-parens)`

I suppose that's an eslint bug? I'm not sure, I think in the past the the `verbose` flag also said what linter that error was coming from.

**Comment by feross** [comment]
@despairblue We only use eslint now - they added enough new rules that the other linters were redundant.

**Comment by feross** [comment]
Confirmed this an eslint bug. Opened an issue here: https://github.com/eslint/eslint/issues/3182

**Comment by feross** [comment]
This is now fixed in eslint master, and it'll make it into the next release of `standard`.
