### ISSUE TITLE
output is not shown when using through `watch`

### ISSUE THREAD

**Issue by mightyiam** [feross/standard#21]
Thanks for this.

I'm using it as such:

``` json
{
  "name": "foo",
  "devDependencies": {
    "watch": "^0.13.0",
    "standard": "*",
    "jasmine": "^2.2.0"
  },
  "scripts": {
    "watch": "watch 'npm test'",
    "test": "standard && jasmine"
}
```

When I run `$ npm test` all is well and as expected.

The issue comes when I use `watch`, such as `$ ./node_modules/.bin/watch 'npm test'` or `$ npm run watch`.

The output from `standard` is not printed. I know that `standard` runs because `jasmine`'s output is printed.

Do you think that `watch` is doing something wrong?

**Comment by mightyiam** [comment]
I've just tried with `$ dirwatch -vc standard` and `$ onchange 'somefile' -- standard`. No output. Perhaps `standard` is throwing to wrong output?

**Comment by yoshuawuyts** [comment]
possibly related: piping through `grep` doesn't filter.
```sh
standard | grep variable
```

**Comment by feross** [comment]
`standard` prints to stderr. I'm not sure what the convention is for these things. Should it print to stdout instead?

**Comment by mafintosh** [comment]
i think it should keep printing to stderr since its normal to stuff like `standard && tape test.js`. otherwise it would mess up a tap parser (like `npm test | tap-spec`)

you can always just run

```
standard 2>&1 | grep variable
```

**Comment by yoshuawuyts** [comment]
@mafintosh ah, that makes sense. Didn't know `grep` was so picky with its input, hah. Thanks for explaining!

**Comment by yoshuawuyts** [comment]
Added a PR that adds the explanation to the FAQ. Pretty sure this is also the reason `watchify` is failing for @mightyiam. Hope it'll resolve this issue.

**Comment by mafintosh** [comment]
@yoshuawuyts typing random chars in bash fixes most problems :+1:

**Comment by yoshuawuyts** [comment]
@mafintosh you might've just fixed life itself :clap::clap::clap:

**Comment by mightyiam** [comment]
I'm observing that the standard behavior is to output to `stdout` and not to `stderr`.

Try it like this:

Clone standard.
```
git clone feross/standard
cd standard
npm i
```

Make a non–standard JS file.
```
echo ';\n ;' > nonstandard.js
```

Run ESLint and JSCS on the non–standard JS file, redirecting `stdout`s to files.
```
./node_modules/eslint/bin/eslint.js -c rc/.eslintrc nonstandard.js 1> eslint-stdout
./node_modules/jscs/bin/jscs -c rc/.jscsrc nonstandard.js 1> jscs-stdout
```
Observe that no output was printed. This means `stderr` wasn't used.
See that `stdout` was used.
```
cat jscs-stdout
cat eslint-stdout
```

Try the same with our beloved standard.
```
./bin/cmd.js 1> standard-stdout
cat standard-stdout
```

So it seems that the standard is to print to `stdout`.

**Comment by mightyiam** [comment]
Unless, of course, standard experiences an actual error—like bad arguments or not finding its dependencies or something.

**Comment by feross** [comment]
@mightyiam You make a good point.

@maxogden Do you have any thoughts?

**Comment by mightyiam** [comment]
BTW, I've switched to `npm-watch`, because of the integration with `package.json`. It is just "how it is done".

**Comment by feross** [comment]
Going to close this issue as it doesn't seem to be causing trouble for anyone anymore. Feel free to make a new issue or leave a comment if that's not true.

**Comment by mightyiam** [comment]
Since https://github.com/scrooloose/syntastic/commit/c1a2098954201fafac7f9ecb550d0c84f4f4fff6 I have it in my editor so I'm not using `watch` or `npm-watch` so I'm not affected by this anymore.

If you're not in a hurry to fix it, that's ok but it seems to me that this issue should at least be kept open.
