### ISSUE TITLE
The Function constructor is eval

### ISSUE THREAD

**Issue by thr0w** [feross/standard#211]
I'm using Function constructor because need pass parameters to code. But standard not accept it.

What you suggest to do?

```javascript
var code = 'param.sum = param.a + param.b'
var fn = new Function('param', code)
var res = fn({a: 1, b: 2})
assert(res.sum, 3)
```

**Comment by julien-f** [comment]
I don't understand your need, why not simply create a regular function?

```js
function fn (param) {
  param.sum = param.a + param.b
  return param
}
var res = fn({a: 1, b: 2})
assert(res.sum, 3)
```

**Comment by thr0w** [comment]
Because code is generated. I need eval or new Function. I'm choosing for new Function because eval expose all my context.

**Comment by julien-f** [comment]
Standard is based on ESLint and there is a way to ignore some warnings, check [in the README](/feross/standard#how-do-i-hide-a-certain-warning).

**Comment by thr0w** [comment]
Ok @julien-f , thanks. I will disable in my code. 

But what you think? If it's necessary parse a generated code why use eval? Eval expose all scope to the evaluated code, it's not safe.

**Comment by julien-f** [comment]
I am not sure I understand your question :p

It is probably indeed better to use `new Function()` than `eval()` but it's still risky and that is why you have to manually disable the warning.

**Comment by thr0w** [comment]
ok. Sorry. It's explained here.
https://jslinterrors.com/the-function-constructor-is-eval

Thank you

**Comment by yoshuawuyts** [comment]
@thr0w you might be interested in https://github.com/mafintosh/generate-function
