### ISSUE TITLE
Self referential anonymous function

### ISSUE THREAD

**Issue by anacrolix** [feross/standard#215]
This kind of code seems quite common:
```
console.log('meh');
(function a() {
	console.log('hiya');
}());
```
But standard formats it like so:
```
console.log('meh');(function a () {
  console.log('hiya')
}())
```

**Comment by reg4in** [comment]
It's rather:

```js
console.log('meh')
;(function a () {
  console.log('hiya')
}())```

Also, you'll find a couple of reasons not to use this sorrily common pattern.

**Comment by anacrolix** [comment]
Feel free to enlighten me.

**Comment by yoshuawuyts** [comment]
Self-calling functions need to be prepended with a `;` to prevent it from being interpreted as a call to the returned value from the previous line (e.g. `console.log()()`).

**Comment by reg4in** [comment]
What I meant was that you should avoid using IIFEs if you can :)

**Comment by feross** [comment]
Pretty sure that @anacrolix is referring to `standard-format`. When I run his code through it, it joins the two lines into one: `console.log('meh');(function a () {`. Moved this issue to: https://github.com/maxogden/standard-format/issues/92
