### ISSUE TITLE
Stroustrup style braces

### ISSUE THREAD

**Issue by wavded** [feross/standard#219]
a.k.a.

```js
if (true) {
}
else {
}
```

instead of

```js
if (true) {
} else {
}
```

My intention isn't to bikeshed here.  More curious for an explanation as it doesn't seem like any strong opinion was expressed.  My current style matches almost all of Standard except this one.  I like this option because I can put comments above and it keeps the keyword on the left side (easier to see).

```js
if (true) {
}
// Otherwise we will do yada yada
else {
}
```

Thanks for the excellent lib btw!

**Comment by jprichardson** [comment]
I actually agree with this, but I'm thinking it may be too late to change. 

Making the change now would dramatically affect all of `standard` users. I also would wonder if it would hurt the tool's perception of stability (assuming it has this perception). Any kind of style change like this would have to be for a very good reason.

**Comment by feross** [comment]
This is one of the decisions in standard where we 'just picked something'. Here's what the readme says about this:

>  At the end of the day you have to 'just pick something', and that's the whole philosophy of standard -- its a bunch of sensible 'just pick something' opinions.

You make a good point about comments being a little more readable in Stroustrup style, though. :) 

This is one of those decisions that we can't revisit. Nearly every repo that uses `standard` would break, and that's not acceptable -- even with major version bump. 

(If it really matters to you, consider using [eslint-shareable-config](https://github.com/feross/eslint-config-standard) and overriding this one rule.)

**Comment by wavded** [comment]
Fair point and thanks for the response.  For now I'm just overriding that rule and perhaps I'll adapt later.

**Comment by timwis** [comment]
Hey guys, thanks again for the background on this. Forgive me for resurrecting an old question but I can't help but notice one thing you said:
> Nearly every repo that uses standard would break

Just to clarify, what _I_ was talking about, at least, would be a rule such as:
> `else {` must be on the same line as closing curly `}` or be preceded by a comment line

This way existing repos would not break, as `} else {` would be valid. But repos could also use:
```
// Test x condition
if (foo) {
}
// Otherwise, y
else {
}
```
To be clear, I'm not trying to make a case -- just trying to clarify that I didn't mean "instead of" the current rule but an additional allowance. If this still doesn't make sense in standard, no worries. In that case, one thing that would be helpful, though, would be guidance on where to put those comments in a consistent way.
```
// Test x condition
if (foo) {
} else { // Otherwise, y
}
```
```
if (foo) {
  // Test x condition
} else {
  // Otherwise, y
  // Though this doesn't stand out nearly as much when there's code in this block
}
```
Thanks for taking the time to reply

**Comment by dcousens** [comment]
``` javascript
// the true case
if (true) {

// the false case
} else {

}
```

Is the convention for comments I follow.
I don't think the
``` javascript
if (...) {
}
else {

}
```

syntax is in the spirit of standard.

**Comment by yoshuawuyts** [comment]
I concur with @dcousens

**Comment by timwis** [comment]
Nice! Hadn't thought of that, thanks

**Comment by eddiemonge** [comment]
That looks so ugly and to me the comment looks related to the `if` statement, not the else.
