### ISSUE TITLE
Exclude `coverage` directory

### ISSUE THREAD

**Issue by brandonhorst** [feross/standard#22]
When I use `istanbul` in a project, it generates some js files in the `coverage` directory. This directory is in the Github-default .gitignore, and standard should probably ignore it by default too.

**Comment by yoshuawuyts** [comment]
The PR for this looks fairly simple: 
- add `'coverage/**'` to https://github.com/feross/standard/blob/master/index.js#L25
- update `README.md` to also mention `coverage`
Was contemplating to PR this later today, but would you like to give it a shot?

**Comment by brandonhorst** [comment]
I'd be happy to - just wanted a :thumbsup:
