### ISSUE TITLE
New rule: linebreak-style

### ISSUE THREAD

**Issue by LinusU** [feross/standard#220]
How about including this rule for forcing unix line breaks? I found the rule while comparing which rules `xo` has versus `standard` here: https://github.com/feross/standard/issues/216#issuecomment-127569835

```json
"linebreak-style": [2,"unix"]
```

**Comment by feross** [comment]
This isn't a friendly rule for Windows users. See https://github.com/feross/standard/issues/140. I think it's best we leave it disabled, unless there's a good reason.

**Comment by LinusU** [comment]
Ah, I understand. I've had some problems with the git auto-converter when I've copied files from some source. When I check in a windows-line-endings-file on linux I think it will get marked as 'always windows style' which can cause problems later...

But I think the benefit doesn't outweigh the problem it causes for windows users, closing this.
