### ISSUE TITLE
New rule: consistent-return

### ISSUE THREAD

**Issue by LinusU** [feross/standard#221]
Suggesting that we include the rule [consistent-return](http://eslint.org/docs/rules/consistent-return.html)

-----

This rule is aimed at ensuring all return statements either specify a value or don't specify a value.

The following patterns are considered warnings:

```javascript
function doSomething(condition) {

    if (condition) {
        return true;
    } else {
        return;
    }
}

function doSomething(condition) {

    if (condition) {
        return;
    } else {
        return true;
    }
}
```

The following patterns are considered okay and do not cause warnings:

```javascript
function doSomething(condition) {

    if (condition) {
        return true;
    } else {
        return false;
    }
}
```

-----

*I found the rule while comparing which rules `xo` has versus `standard` here: https://github.com/feross/standard/issues/216#issuecomment-127569835*

**Comment by feross** [comment]
On the surface, this seems like a good rule. But it's actually not that well implemented, and it gives a ton of false positives. 23 repos in the test suite will fail if you enable this rule.

`standard` has to be pragmatic -- we can't enable flaky rules!

Of particular note, this kind of code won't work with the rule enabled:

```js
      rs.pipe(through.obj(function (data, enc, cb) {
        if (data.value.toString()[0] === '{') return cb()
        if (verify) {
          verify(u, val.message, val.signature, function (_, valid) {
            m.valid = !!valid
            processor(m, cb)
          })
          return
        }
     })
```

You can play around with potential rule changes by modifying `eslint-config-standard` and running the `standard` tests with `npm test`.

**Comment by LinusU** [comment]
Ahh, that makes very much sense.

I'll try to play around with the rules and see if there is anything that we can learn from xo and others :)

**Comment by feross** [comment]
Great idea, thanks!
