### ISSUE TITLE
Expose eslint's output formatting flag

### ISSUE THREAD

**Issue by abacon** [feross/standard#222]
I'd love to be able to use [sindresorhus/eslint-tap](https://github.com/sindresorhus/eslint-tap) with standard, but standard doesn't expose eslint's `-f` flag for formatting the _output of the linter itself_.

In fact, standard already overloads the term 'format' by providing a (lovely) way to automatically format source code.

What do y'all think about exposing an `--output-format` flag, or something similar, to support this use case?

**Comment by Flet** [comment]
How about [standard-tap](https://github.com/Flet/standard-tap) :)
```bash
npm install -g standard-tap
standard | standard-tap
```

Or [standard-json](https://github.com/Flet/standard-json)
```bash
npm install -g standard-json
standard | standard-json
```

**Comment by abacon** [comment]
Nice! That's certainly enough for my purposes. Did you just whip those up? Thanks!

It's a bit odd to see you basically reverse-engineer the `-f` interface in your standard-json implementation, though. Isn't it better to work with the json in the first place, instead of going eslint json -> standard output plaintext -> json? And if standard ever changes its output format -- e.g. adding another line of preamble, or allowing multiline error messages -- then someone will have to dig through `var re = /\s*([^:]+):([^:]+):([^:]+): ([^(]*) ?(\((.*)\))?/.exec(line)`. :\ Of course, I'm not super familiar with how tough it'd be to pipe `-f` through, so I understand if it's not worth the effort there.

Thanks again so much for your help!

**Comment by feross** [comment]
Nice, there's plenty of choice now. The built-in reporter, [snazzy](https://www.npmjs.com/package/snazzy), [standard-json](https://www.npmjs.com/package/standard-json), and [standard-tap](https://www.npmjs.com/package/standard-tap).

I'd rather stick with this approach than add formatters to `standard`. This is better than `standard` being a gatekeeper of which formatters get in.
