### ISSUE TITLE
Structuring name duplicate

### ISSUE THREAD

**Issue by dcousens** [feross/standard#223]
I'm not sure of exact name for this syntax,  but [assuming ES6 is detected], should we allow both of these syntaxes: 

`{ x: x }` and `{ x }`?
Or should we force `{ x }` if both the lhs and rhs match?

**Comment by feross** [comment]
Right now, we're not actively pushing people toward ES6 features, so I'm -1.

If we end up detecting ES6 (discussion here: https://github.com/feross/standard/issues/159) then we should recommend `{ x }` over `{ x: x }` - agreed.

**Comment by jokeyrhyme** [comment]
@dcousens ESLint calls this "object shorthand properties" and "object shorthand methods", and has an [object-shorthand rule](http://eslint.org/docs/rules/object-shorthand).
