### ISSUE TITLE
Feature Request: allowing eval "eval can be harmful"

### ISSUE THREAD

**Issue by reggi** [feross/standard#225]
I found a work-around to allow `eval` by using `global['eval']`. Is there a better way to allow eval? Perhaps a comment? 

```
/* permit eval */
```

**Comment by reggi** [comment]
Also, no mention of `eval` in the docs. :(

**Comment by dcousens** [comment]
`new Function`?

**Comment by feross** [comment]
There are instructions in the readme that explain how to disable individual rules. You can figure out what the rule is called by running with --verbose. This rule is "no-eval".
