### ISSUE TITLE
"Infix operators must be spaced" not resolved correctly by `standard --format`

### ISSUE THREAD

**Issue by nknapp** [feross/standard#227]
I have a file `test-infix.js` containing the file

```js
console.log(1===2?3:4)
```
When I run `standard --format test-infix.js`, the error `test-infix.js:1:20: Infix operators must be spaced` is displayed and the file is modified as follows

```js
console.log(1 === 2? 3: 4)
```
The same error still occurs because of the missing space between `2` and `?` and between `3` and `:`.
The correct formatting would be (I guess)

```js
console.log(1 === 2 ? 3 : 4)
```

but `standard` does not change the file that way

**Comment by nknapp** [comment]
Tested with `standard@5.0.2`

**Comment by Flet** [comment]
This is actually a `standard-format` issue, but no worries! 

I just fixed it here: https://github.com/maxogden/standard-format/commit/f52b384eaf5a5d5218de0866c1f7f5c627438741 and published standard-format 1.6.3. I also added your tests above and they are passing.

If you reinstall `standard` it should pull in the fixed version... can you give it a try?

**Comment by nknapp** [comment]
I've done another test and found out that 

```js
var gt = 'a'
var x = []
gt === '>' ? x[1]  : 2
```
is always changed to 
```js
var gt = 'a'
var x = []
gt === '>' ? x[1] : 2
```

Wow, that was fast. I'll try!

**Comment by nknapp** [comment]
Verified, many thanks
