### ISSUE TITLE
Documentation or formatter for consistent spacing rules

### ISSUE THREAD

**Issue by nknapp** [feross/standard#228]
I'm would like to have documentation on rules about consistent spacing. I had a file containing a line similar to 

```js
console.log({ arr: [{ a: 'aa'}, { a: 'bb'}]})
```
which is not consistently spaced, appearently. I changed it to 
```js
console.log({ arr: [{ a: 'aa' }, { a: 'bb' }]})
```
which still didn't work. Then wondered, if "consistent" meant "consistent across the project/file/statement". 
Finally I found out that  the following examples work
```js
console.log({ arr: [{ a: 'aa' }, { a: 'bb' }] })
console.log({ arr: [{a: 'aa'}, { a: 'bb' }] })
```

The best thing would be to have the formatter correct those errors automatically based on the initial spacing. Second best would be documentation with a few example about what is allowed and what isn't.

**Comment by feross** [comment]
Thanks for pointing out that this is confusing. I opened an issue on `standard-format` for this: https://github.com/maxogden/standard-format/issues/95
