### ISSUE TITLE
Early exit vs if else

### ISSUE THREAD

**Issue by dcousens** [feross/standard#231]
Case 1

``` javascript
if (condition) {
  return true
} else {
  // ... code
}
```

Case 2

``` javascript
if (condition) return true

// ... code
```

IMHO,  I find case 2 to be the clearest and cleanest,  @feross did you have any thoughts on this?  Should we align to either convention?  Even if we do,  can we do anything about it?

**Comment by feross** [comment]
I prefer case 2, but there's no way to enforce this with eslint, nor do I think we should do that. :)

**Comment by dcousens** [comment]
No worries,  just though I'd bring it up as I had a case of nit picking about it in a recent repository,  and it just stirred up a unnecessary discussion.
