### ISSUE TITLE
Badge not visible on dark backgrounds

### ISSUE THREAD

**Issue by Shoozza** [feross/standard#234]
The badge is not visible on dark backgrounds.
This is an issue for people using the Stylish Addon and the Github Dark style.

Suggestion: Add a shadow
![Badge with shadow](http://i.imgur.com/O3Rq7WW.png "Possible solution")

**Comment by nickcolley** [comment]
Could make the background white?

**Comment by feross** [comment]
A white background would work nicely.

**Comment by nickcolley** [comment]
https://github.com/feross/standard/pull/239

**Comment by feross** [comment]
Thanks, nice work!
