### ISSUE TITLE
CodeClimate

### ISSUE THREAD

**Issue by knownasilya** [feross/standard#238]
How do we get CodeClimate to honor standard and not trigger issues that really don't exist?

Seems like there is a codeclimate config, but it's not exactly clear how to make it work. Do I really have to use eslint-standard?

Related issue on my project: https://github.com/Strider-CD/core/issues/14 You can see my setup there.

**Comment by knownasilya** [comment]
Looks like exlint modules aren't supported by codeclimate.. https://github.com/codeclimate/codeclimate/issues/79

**Comment by feross** [comment]
Looks like this issue might be caused by CodeClimate not supporting a custom JS parser, like babel instead of the default that's built into ESLint. `standard` just uses the default one, unless you specify otherwise.

This isn't an issue with `standard`.

**Comment by knownasilya** [comment]
I don't think it's the parser so much, as it is the ` "extends": "standard"` syntax, which loads an eslint module, e.g. https://github.com/feross/eslint-config-standard

**Comment by feross** [comment]
Does it work if you `npm install eslint-config-standard`?

**Comment by mikz** [comment]
CodeClimate just added standard to their engine: https://github.com/codeclimate/codeclimate-eslint/issues/75#issuecomment-223652528

**Comment by knownasilya** [comment]
Yay!
