### ISSUE TITLE
hangs indefinitely on directories without any files to lint

### ISSUE THREAD

**Issue by brandonhorst** [feross/standard#24]
```bash
mkdir /tmp/new
cd /tmp/new
standard
```
if you don't have any js files, in /tmp, it should just hang forever.

**Comment by brandonhorst** [comment]
Hmmm, the problem seems to be that if you don't pass any files to JSCS, it waits for input from stdin. I'll submit a PR.

**Comment by feross** [comment]
Fixed in https://github.com/feross/standard/commit/87b750b515a56dccac67fd810893f3a55ee5c268

**Comment by feross** [comment]
Released as 2.4.2.
