### ISSUE TITLE
Require trailing commas in multiline object and array literals?

### ISSUE THREAD

**Issue by lydell** [feross/standard#240]
This is a very sensible styleguide. I don’t agree with all of it personally on a purely aesthetical level, but don’t care since I think it’s worth it because of the simplicity.

Here’s another sensible rule, that I think is a tiny bit ugly myself, but is very useful: Require trailing commas in multiline object and array literals. Why? Because it reduces diffs. When adding or removing a new item at the end of the literal you only need to modify _one_ line instead of _two._

```js
var obj = {a: 1,} // Error: trailing comma in singleline object literal.
var obj = {a: 1} // OK
var obj = {
  a: 1 // Error: Missing trailing comma in multiline object literal.
}
var obj = {
  a: 1, // OK
}
```

The above examples can be extended with multiple items per literal, of course, and the same apply to array literals.

This can be implemented by setting the [comma-dangle](http://eslint.org/docs/rules/comma-dangle) rule to `[2, "always-multiline"]`. As described in the [comma-dangle](http://eslint.org/docs/rules/comma-dangle) docs, the only caveat is IE8 in certain circumstances. In my opinion you should have your build tool take care of that. Most likely you’ll minify the code, and then trailing commas will be removed anyway to reduce size.

**Comment by dcousens** [comment]
Although personally I agree with fundamental reasons you argue for this.  As it stands,  this would be *so* much of a breaking change,  it will never be accepted.

**Comment by feross** [comment]
Thanks for the thoughtful issue! Unfortunately, it would be a lot of work for all the existing users of standard (almost 100K downloads per month) to change their code. We can't really make breaking changes at this point without a *really* good reason.

Fortunately, this style choice isn't the most important since it doesn't affect code correctness or make programmers more likely to write bugs. At the end of the day you have to 'just pick something', and that's the whole philosophy of standard -- its a bunch of sensible 'just pick something' opinions.

**Comment by lydell** [comment]
Right, thanks for taking your time to read and answer!

**Comment by yanivtal** [comment]
I agree with the philosophy of this approach... and yet this choice will be responsible for millions of lines of diffs based on the number of downloads per month...

**Comment by dcousens** [comment]
@yanivtal is the upgrade diff cost greater than than the diff cost of leaving it the same for say, 5 years?
Probably not,  but if you want to run the numbers,  I'm sure it'd be an interesting read.

**Comment by dcousens** [comment]
s/greater/less

**Comment by gimenete** [comment]
Instead of making it mandatory at least it could stop marking it as an error. Now it says `Unexpected trailing comma. (comma-dangle)`.

So, no error if you use it and no error if you don't.

What do you think guys?

**Comment by yanivtal** [comment]
i like that suggestion. but regardless, @dcousens good answer ;)

**Comment by gimenete** [comment]
As you can see https://github.com/eslint/eslint/issues/4966 I've made a PR to `eslint` to add a new option on `comma-dangle`: `allow-multiline`. This will warn only when using a dangle comma on single line node, but makes it optional on multiline ones.

**Comment by mattdesl** [comment]
> So my suggestion is: no error if you use it and no error if you don't.

:+1: 

Some posts on the subject.

https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8#.yndunrwhf
http://dontkry.com/posts/code/trailing-commas.html

**Comment by feross** [comment]
The issue with relaxing the rule is that some places in the codebase will have it, some won't. That will lead to discussion about the issue in PRs, edit wars, etc. `standard` should enforce one style.

**Comment by feross** [comment]
If you feel *that* strongly about a single style rule like trailing commas, then `standard` is probably not for you. Consider using eslint directly with [`eslint-config-standard`](https://github.com/feross/eslint-config-standard) and tweak away to your hearts content, if that's what you wish.

**Comment by jokeyrhyme** [comment]
Note that ESLint's `--fix` option will automatically migrate code in either direction regarding the [comma-dangle](http://eslint.org/docs/rules/comma-dangle) rule. Does having a computer-assisted code migration like this change the perception of compatibility breakage?

**Comment by jokeyrhyme** [comment]
There's a thorough discussion about this subject here: https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

**Comment by dcousens** [comment]
@jokeyrhyme 

> almost 100K downloads per month

> We can't really make breaking changes at this point without a really good reason.

Are simply not compatible,  `--fix` or not.  It's just not worth it by comparison to the trivial difference in diffs it provides.
It really doesn't make *that* great a difference.

**Comment by lucascosta** [comment]
2 cents here: the diff things is not as important for me as the _Easier Code-Manipulations_ argument, which seems to be apart from this discussion. How many objects and arrays are multilined in everyone's code? Have you never had to change the order or sort some properties and spend time fixing the comma? I sure did.
So for me that's the math in discussion: developer hours! How many added hours will it take to automatically change all the missing commas from all the existing projects in a release? How many added hours will we will be thrashing in next years of use of the `standard` fixing dangled commas?
For me, that's a _really_ good reason.

**Comment by jokeyrhyme** [comment]
FYI: Upstream ESLint have moved "comma-dangle" from Possible Errors to Stylistic Issues, and also removed it from the `"eslint:recommended"` configuration:
- https://github.com/eslint/eslint/issues/6403#issuecomment-226806815

This helps enforce the notion that this is a style thing, and Standard is a standard for code style.

**Comment by dcousens** [comment]
> How many objects and arrays are multilined in everyone's code? Have you never had to change the order or sort some properties and spend time fixing the comma? I sure did.

I concur,  I have spent some unprecedented amount of time on this,  it is especially bad when dealing with huge JSON files that might lag out your editor.

**Comment by jokeyrhyme** [comment]
@dcousens the JSON specification does not allow trailing commas: http://www.json.org/
See the rail-road diagram for Array and Object.

JSON !== JavaScript, and I'm not sure JavaScript Standard Code Style covers JSON.

But for Objects and Arrays in JavaScript, I do not disagree with you.

**Comment by dcousens** [comment]
@jokeyrhyme true indeed!  Welp.
