### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by kube** [feross/standard#241]
It would be a good thing to provide support for Typescript files.

**Comment by feross** [comment]
Sorry, this would complicate what is currently a simple tool. We only support JavaScript.

**Comment by krzkaczor** [comment]
I have been working recently on standardTS. https://github.com/krzkaczor/standardts 

`tslint` rules are not so advanced as `eslint` ones so there's still a lot of work to do but I guess it already provides some value.

**Comment by kirillgroshkov** [comment]
Too bad, I would definitely use it for typescript if possible. Maybe it could be done in some simpler way like stripping down all typescript-specific stuff (like type annotations), other typescript things are based on ES6/7 syntax. Just saying. Using TSLINT now, but 2 problems: not enough rules, a lot of work to write and maintain your own config instead of just using "the only one".

**Comment by feross** [comment]
@kirillgroshkov Maybe `standardts` or another project can take the approach you describe? I just don't think that typescript support belongs in this repo.

**Comment by mightyiam** [comment]
Perhaps this will be revisited when ESLint supports different parsers. I've found a love for TypeScript and I'm heart broken about not being able to use standard.
https://github.com/eslint/eslint/issues/6364

**Comment by feross** [comment]
Why don't you just use https://github.com/nzakas/eslint-plugin-typescript ?

```json
{
  "standard": {
     "plugins": [
        "typescript"
    ]
  }
}
```

That ought to strip type annotations so you can still use `standard`. Though I haven't tried it myself, since I don't use Typescript.

More complete instructions, but for Flow, are here: https://github.com/feross/standard#can-i-use-a-javascript-language-variant-like-flow

**Comment by mightyiam** [comment]
Not actually really working. I'll report bugs to eslint-plugin-typescript.
See travis of https://github.com/mightyiam/cyclejs-web-components/pull/13

**Comment by feross** [comment]
@mightyiam If you figure out that the README instructions are not enough for Typescript, can you please PR to add instructions?

**Comment by mightyiam** [comment]
If I figure out what to do, I'll surely do so.

**Comment by mightyiam** [comment]
This is what I currently do:
https://www.npmjs.com/package/tslint-config-standard

**Comment by KC-SI** [comment]
With this as the test.ts file
```typescript
let obj: string;
obj = "yo";
// Error: Type 'number' is not assignable to type 'string'.
obj = 10;

function sayIt(what: string) {
    return `Saying: ${what}`;
}
const said: string = sayIt(obj);

class Sayer {
    // mandatory
    what: string;

    constructor(what: string) {
        this.what = what;
    }

    // return type if you want to
    sayIt(): string {
        return `Saying: ${this.what}`;
    }
}
```
I got the following output
```
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  $HOME/Downloads/test/test.ts:1:16: Extra semicolon.
  $HOME/Downloads/test/test.ts:2:7: Strings must use singlequote.
  $HOME/Downloads/test/test.ts:2:11: Extra semicolon.
  $HOME/Downloads/test/test.ts:4:9: Extra semicolon.
  $HOME/Downloads/test/test.ts:6:15: Missing space before function parentheses.
  $HOME/Downloads/test/test.ts:7:5: Expected indentation of 2 spaces but found 4.
  $HOME/Downloads/test/test.ts:7:29: Extra semicolon.
  $HOME/Downloads/test/test.ts:9:7: 'said' is assigned a value but never used.
  $HOME/Downloads/test/test.ts:9:32: Extra semicolon.
  $HOME/Downloads/test/test.ts:11:7: 'Sayer' is defined but never used.
  $HOME/Downloads/test/test.ts:13:5: Expected indentation of 2 spaces but found 4.
  $HOME/Downloads/test/test.ts:15:5: Expected indentation of 2 spaces but found 4.
  $HOME/Downloads/test/test.ts:15:16: Missing space before function parentheses.
  $HOME/Downloads/test/test.ts:16:9: Expected indentation of 6 spaces but found 8.
  $HOME/Downloads/test/test.ts:16:25: Extra semicolon.
  $HOME/Downloads/test/test.ts:20:5: Expected indentation of 2 spaces but found 4.
  $HOME/Downloads/test/test.ts:20:10: Missing space before function parentheses.
  $HOME/Downloads/test/test.ts:21:9: Expected indentation of 6 spaces but found 8.
  $HOME/Downloads/test/test.ts:21:38: Extra semicolon.
```
using the following as my package.json
```json
{
  "devDependencies": {
    "babel-eslint": "^7.2.1",
    "eslint-plugin-flowtype": "^2.30.4",
    "eslint-plugin-typescript": "^0.1.0",
    "standard": "^10.0.1"
  },
  "standard": {
    "parser": "babel-eslint",
    "plugins": [
      "flowtype",
      "typescript"
    ]
  }
}
```
and running
```shell
node_modules/standard/bin/cmd.js test.ts
```
How would I add the files to package.json so that it would lint .ts files too?

**Comment by feross** [comment]
@KC-SI Please open a new issue instead of posting into an already-closed issue. Thanks.

**Comment by mightyiam** [comment]
I have released [eslint-config-standard-with-typescript](https://www.npmjs.com/package/eslint-config-standard-with-typescript). Please report issues and send in PRs. Should be a step forward.

**Comment by GantMan** [comment]
`standardts --fix` isn't working with missing whitespace.

I'm a fan of standard, and I'm a fan of typescript.  Anyone got a fix for this?
