### ISSUE TITLE
Getter not present

### ISSUE THREAD

**Issue by dcousens** [feross/standard#245]
``` javascript
var x = {
  set: 1
}
```

> Error: Getter is not present (accessor-pairs)

**Comment by feross** [comment]
I can't reproduce this. What version of `standard`?

**Comment by dcousens** [comment]
Fixed in latest `standard`.  Was `5.0.0`.

**Comment by feross** [comment]
Ah, great. I tested the last 3-4 versions and couldn't repro. Thanks for closing this.
