### ISSUE TITLE
Webstorm Support

### ISSUE THREAD

**Issue by tusharmath** [feross/standard#247]
A lot of good work has been done on other IDEs and editors, it would be great to have something for webstorm.

**Comment by cesarandreu** [comment]
You can setup eslint with standard as the config, fyi.

**Comment by tusharmath** [comment]
thats's what I am using right now. Is that the right approach?

**Comment by feross** [comment]
@tusharmath PR welcome!

**Comment by rom1504** [comment]
I tried setting standard up with webstorm, but it doesn't seem to work, I'm still getting warning about missing semicolons and I'm not sure the eslint thing does anything at all.
So if someone managed to make it work, it would really be useful to add info about it in the README.

**Comment by cesarandreu** [comment]
@rom1504 https://github.com/feross/eslint-config-standard

**.eslintrc**

```
{
  "extends": [
    "standard"
  ]
}
```

And in your **package.json**, you'll wanna install the following:

* `eslint`
* `eslint-config-standard`
* `eslint-plugin-standard`

**Comment by tusharmath** [comment]
@rom1504 Also make sure you deselect `unterminated statement` setting in **settings > editor > inspections > Javascript > code style issues**

**Comment by rom1504** [comment]
Okay I'll do that, thanks

**Comment by gunta** [comment]
+1

**Comment by feross** [comment]
@cesarandreu Nice - can you send a PR to add this to the readme?
