### ISSUE TITLE
Suggestion: make it work without package.json

### ISSUE THREAD

**Issue by Deadarius** [feross/standard#249]
Currently if I need to specify globals/ignores etc I have to write it down in package.json, which is perfectly fine, but this is a linter for javascript and javascript doesn't necessarily mean node.js - In my concrete case I work on meteor project. Meteor has it's own pluggable linting system as part of the build process and I am writing standard plugin for it. Currently I am reading globals from file named stadard.json in project's root and it causes problem because text editors obviously don't understand it.

So suggestion is to add support for standard.json or some other file as source of "configuration" for linter?

**Comment by feross** [comment]
How is adding a `standard.json` better than just using `package.json`? If your project isn't a node.js project, you can still have a `package.json` file. In fact, lots of front-end only projects have one to install `gulp` and other tooling.

Just make a `package.json` and do:

```
{
  "standard": {
    "ignore": [ 'path1', 'path2' ]
  }
}
```

None of the usual `package.json` fields are required by `standard`.

Please correct me if I'm misunderstanding what you're asking for.

**Comment by Deadarius** [comment]
For some reason I was thinking that if you add package.json to Meteor project it fails miserably due to generating a more "normal" node app as build step which doesn't seem to be the case. Sorry for wasting time, I should have tried it first:)

**Comment by feross** [comment]
No problem. You can also use the command line flag `--global` if you don't want to add a package.json.

See `standard --help` for more.
