### ISSUE TITLE
link breakage on website

### ISSUE THREAD

**Issue by flying-sheep** [feross/standard#250]
github and whatever you use on http://standardjs.com/ slugify differently:

the “Never start a line with ( or [ … More details” link points to `#automatic-semicolon-insertion-asi`, but on standardjs.com, the actual anchor is `#automatic-semicolon-insertion-asi-` with a trailing dash.

you’ll have to fix the code creating the anchors to behave like on github.

**Comment by Flet** [comment]
Will check this out today thanks

**Comment by feross** [comment]
Confirmed this is an issue. Thanks for reporting this, @flying-sheep.

**Comment by feross** [comment]
Leaving this one to you, @Flet ;)

**Comment by Flet** [comment]
Cool. I am elbow deep on this now...

**Comment by Flet** [comment]
Moving this issue to feross/standard-www#4
