### ISSUE TITLE
Share list of test repos with standard-engine

### ISSUE THREAD

**Issue by feross** [feross/standard#253]
There are repeated repo lists at https://github.com/feross/standard/blob/master/test/clone.js and https://github.com/Flet/standard-engine/blob/master/test/clone.js.

Let's move the list to https://github.com/feross/standard-packages and save the duplicate effort.

**Comment by Flet** [comment]
Agree, thanks for opening the issue for tracking!

**Comment by feross** [comment]
Pushed this to both `standard` and `standard-engine` repos. :+1:
