### ISSUE TITLE
Peer dependencies in npm 3+

### ISSUE THREAD

**Issue by vsimonian** [feross/standard#255]
Getting these warnings:

```
npm WARN peerDependencies The peer dependency eslint@>=0.24.1 included from eslint-config-standard-react will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint@^1.0.0 included from eslint-config-standard will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint@^1.0.0 included from eslint-plugin-standard will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by dcousens** [comment]
Indeed, seems a bit explicit?

**Comment by julien-f** [comment]
@feross I don't think removing the peer dependencies is a good idea, they are here to express the compatibility of the configs with specific versions of ESLint. However, what should be done is adding eslint as a dependency to standard.

**Comment by mcollina** [comment]
A good way to remove the `peerDependency` is to check for versions explicitly when we require those modules. An example on how this can be done is in levelup's codebase: https://github.com/Level/levelup/blob/master/lib/util.js#L28-L56

I would say that it is the best possible solution, peerdependencies do not really work in complex cases anyway.

**Comment by julien-f** [comment]
Hmmm, it seems like a bad idea doing this by hand when npm has a support for it.
And the use case here is far for complex: standard just requires `eslint` and `eslint-config-*`.

**Comment by julien-f** [comment]
LevelUp does it manually because it can works with other backends than LevelDown.

**Comment by mcollina** [comment]
I'm just saying that either:

1. we add each peerDependency as dependency
2. or we require and check those manually if they are needed.

The warning is quite annoying.

**Comment by feross** [comment]
These warnings are gone in the latest versions of `standard`. :+1: 

@julien-f It would be confusing to add `eslint` as a dependency to `standard` since the version that actually gets used is installed by `standard-engine`.

We want these shared configs to work with `standard-engine` and well as `eslint` directly. In this way, it's actually similar to the the leveldown backend situation.
