### ISSUE TITLE
Chained calls with object argument indentation

### ISSUE THREAD

**Issue by albertorestifo** [feross/standard#257]
Before the latest Standard update I could do this:

```js
promiseFooBar({
    foo: true,
    bar: false
  })
  .then(fooBar => console.log(fooBar))
  .catch(err => console.log(err))
```

Now the new indentation rules forces me to do either of the following:

```js
// 1
promiseFooBar({
  foo: true,
  bar: false
})
  .then(fooBar => console.log(fooBar))
  .catch(err => console.log(err))

// 2
promiseFooBar({
  foo: true,
  bar: false })
  .then(fooBar => console.log(fooBar))
  .catch(err => console.log(err))

// 3
promiseFooBar({
  foo: true,
  bar: false
}).then(fooBar => console.log(fooBar))
  .catch(err => console.log(err))
```

I was **very** happy using the first example, now not allowed. I understand and respect that the Standard rules are not up to discussion, so I just want to ask:

What way should I indent them?

**Comment by albertorestifo** [comment]
Forgot one:

```js
let options = { foo: true, bar: false }

promiseFooBar(options)
  .then(fooBar => console.log(fooBar))
  .catch(err => console.log(err))
```

**Comment by yoshuawuyts** [comment]
they all lgtm except:
```js
promiseFooBar({
  foo: true,
  bar: false })
  .then(fooBar => console.log(fooBar))
  .catch(err => console.log(err))
```

**Comment by reg4in** [comment]
What about that (is more semantic IMO):

```javascript
promiseFooBar({
  foo: true,
  bar: false
})
.then(fooBar => console.log(fooBar))
.catch(err => console.log(err))
```

**Comment by albertorestifo** [comment]
@reg4in It makes it harder to detect a chained call when looking at a lot of code.

But yeah, it also satisfies the Standard rules, so it's a valid option

**Comment by reg4in** [comment]
@albertorestifo I personally don't think so but I won't force anyone to use it :stuck_out_tongue:

**Comment by dcousens** [comment]
> Before the latest Standard update I could do this:

Which versions specifically?

**Comment by emgeee** [comment]
I did some digging into this and it looks to have cropped up starting in v5.0.0 when the `indent` rule got stricter. As far as I can tell, this is an issue relating to how eslint handles the `indent` rule and isn't something standard can do much about.

There looks to be an open issue for eslint here: https://github.com/eslint/eslint/issues/3614 that discusses adding more customization around indentation and chaining.

**Comment by albertorestifo** [comment]
@emgeee :+1: Exactly, update to `5.0.0` is what did it for me

**Comment by feross** [comment]
Yeah, unfortunately eslint reimplemented the `indent` rule and it got stricter in some edge cases.

There's nothing we can do about it.
