### ISSUE TITLE
Better explanation for style rules

### ISSUE THREAD

**Issue by rstacruz** [feross/standard#259]
"take a look at a sample file" is a pretty lazy way to explain the style rules. i've started to maintain a better documentation on the rules:

https://github.com/rstacruz/standard-doc

perhaps we should consider merging them into `standard`?

**Comment by feross** [comment]
This is excellent. I merged your document into `RULES.md` file and added you as a GitHub collaborator so you can modify the file as you see fit :+1:

**Comment by feross** [comment]
Published to http://standardjs.com/rules.html
