### ISSUE TITLE
Allowing `debugger` statements during development

### ISSUE THREAD

**Issue by jameslnewell** [feross/standard#260]
I know `standard` is all about no-configuration but could there be a `--dev` or `--debug` flag that allows the `debugger` statement? It's really helpful during debugging - manually having to find and set breakpoints sucks!

I'm also curious as to why `no-debugger` is enabled but `no-console` isn't?

**Comment by feross** [comment]
Thanks for the thoughtful issue. `console.log` statements won't break your app in production, but a stray `debugger` left in your code will certainly do that. That's the key difference.

If `standard` failures are preventing you from running your app, consider moving it from your regular tests to a separate `lint` task so you can test your app even with code style failures.

We haven't added any flags that change rules yet and I don't think it's worth the added complexity just to support this use case. Sorry.

**Comment by jameslnewell** [comment]
I like fast feed feedback with linting as part of the default/watch tasks. Thanks for the explanation though. :smile:

**Comment by rstacruz** [comment]
Also, there's legitimate uses of `console.log` when writing CLI apps

**Comment by feross** [comment]
@jameslnewell No problem :) FWIW, the [eslint page](http://eslint.org/docs/rules/no-debugger) for this rule says this:

> The debugger statement is used to tell the executing JavaScript environment to stop execution and start up a debugger at the current point in the code. **This has fallen out of favor as a good practice with the advent of modern debugging and development tools.** Production code should definitely not contain debugger, as it will cause the browser to stop executing code and open an appropriate debugger.

The dev tools are a great way to set breakpoints!

**Comment by feross** [comment]
@rstacruz That's another good point!

**Comment by jameslnewell** [comment]
Yeah good point about cli apps. 

Not sure why `debugger` statements would have fallen out of favor unless people let them slip into prod code??? Its a lot easier to insert a `debugger` statement where I'm editing code in an IDE and reload the page than it is to edit code, trawl the source code panel in a browser, set a breakpoint and reload the page - usually for multiple breakpoints. Especially when breakpoint line numbers may change between builds and you might have to set the breakpoints all over again.

**Comment by rstacruz** [comment]
You can use this:

```js
debugger // eslint-disable-line
```

**Comment by jameslnewell** [comment]
ty good point

**Comment by m5rk** [comment]
@rstacruz Your post from over 2 years ago is my goto:

I add `debugger` in some eslint-monitored code that disallows it. I see the error. I can't remember how to allow it. I google, "eslint debugger allow", I find this issue and your post, and copy what you provided. Thanks!
