### ISSUE TITLE
Installing >v5.0.0 with node v0.10 errors on eslint

### ISSUE THREAD

**Issue by maxbeatty** [feross/standard#261]
When installing standard at any version above 5.0.0 using node v0.10.40, an error occurs. [Here is a sample travis job failing to install "^5.3.0"](https://travis-ci.org/motdotla/dotenv/jobs/80773606). [Travis passes](https://travis-ci.org/motdotla/dotenv/jobs/80774422) when [we explicitly set "5.0.0"](https://github.com/motdotla/dotenv/commit/8f45ba61daad7c42e7a174e54fb01c1996d2e9e9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33).

As a maintainer of [dotenv](https://github.com/motdotla/dotenv), I'd like to continue supporting v0.10 like [the LTS plan](https://github.com/nodejs/LTS) lays out. Is there anything we can do besides stay with 5.0.0?

**Comment by dcousens** [comment]
@maxbeatty this seems very odd,  I'm sure we'll be able to find the reason and allow you to use `^5.3.0`.

**Comment by feross** [comment]
This issue will be fixed soon (hopefully within 24 hours) when eslint publishes a new version. The issue is caused by `standard-engine` depending on a package from GitHub, to get a bug fix that hasn't been published yet. See: https://github.com/Flet/standard-engine/blob/master/package.json#L13

**Comment by watson** [comment]
@feross is there anything I can do to help with this?

**Comment by watson** [comment]
Hmm... this actually seems to affect all versions of Node - not just 0.10.x: https://travis-ci.org/watson/async-state

**Comment by watson** [comment]
My bad - it's not related to the version of Node, but the version of npm. I've made a pull request in `standard-engine` that should fix it: https://github.com/Flet/standard-engine/pull/15

**Comment by watson** [comment]
@maxbeatty The issue with `standard-engine` not being able to install with older versions of npm have been fixed now in v2.1.1. If you reinstall standard it should automatically fetch the new version of `standard-engine` and everything should work again

**Comment by Flet** [comment]
@watson Nice! Thanks!

**Comment by ginman86** [comment]
I'm getting a similar error on eslint, just tried. 5.0.0 does work.
```
A786391-DEN-OEM:client-generator A786391$ npm install standard --save-dev
npm ERR! fetch failed https://github.com/eslint/eslint.git#9d6223040316456557e0a2383afd96be90d28c5a
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
```

**Comment by maxbeatty** [comment]
Thanks everyone for your help! I re-ran the build and everything is working again :white_check_mark:

**Comment by watson** [comment]
@ginman86 weird - can I get you to run `npm --version` to see what version of npm you have?

**Comment by ginman86** [comment]
@watson just confirmed this is working after your PR was merged. It must not have been published yet when i was trying. Thanks for the followup.

**Comment by watson** [comment]
:+1:

**Comment by feross** [comment]
Thanks for your help @watson – I've added you as a GitHub collaborator and npm owner :+1: 

Also, eslint 1.5.0 was published earlier today, so I've removed the git dependency entirely, as promised. Sorry for the trouble, everyone.
