### ISSUE TITLE
Missing space before function parentheses after formatting code

### ISSUE THREAD

**Issue by chenxsan** [feross/standard#264]
I'm playing on the site http://standardjs.com/demo.html, after pressing **Format Code** button, I got these:

<img width="1071" alt="screen shot 2015-09-19 at 21 30 38" src="https://cloud.githubusercontent.com/assets/1091472/9976421/12ddd0ce-5f16-11e5-8ca5-6b6465bec2d4.png">

I have to insert a space after `hello` function as `hello () {}`, then something is wrong with the **Format Code**?

**Comment by reg4in** [comment]
No, that actually is a part of the standard. Read the Readme carefully.
https://github.com/feross/standard#rules
The seventh bullet.

**Comment by chenxsan** [comment]
@reg4in The **Format Code** button would give me `hello() {}`, not `hello () {}`.

**Comment by dcousens** [comment]
@chenxsan I'm pretty certain this is a bug to be filed over at https://github.com/maxogden/standard-format.

You are correct that `hello () {}` is what **should** have been output.

**Comment by feross** [comment]
Yeah, this is a bug in standard-format. I moved the issue there: https://github.com/maxogden/standard-format/issues/116
