### ISSUE TITLE
Standard allows different style for ifs

### ISSUE THREAD

**Issue by sweco-sebhar** [feross/standard#266]
This is standard:
```js
if (1) { } else { }
```
This is also standard:
```js
if (1) { }else { }
```

I prefer the former, my coworker prefers the latter. Can't (shouldn't?) standard make us stop fighting? :)

**Comment by julien-f** [comment]
Yes, standard makes all of us stop fighting because it chooses for us to avoid unnecessary debates over trivial things. :)

**Comment by sweco-sebhar** [comment]
Yes? :)

**Comment by julien-f** [comment]
My bad, I did not understood the issue ^^

I think the first one is the most commonly used and if one should ever been enforced that will be it!

**Comment by rstacruz** [comment]
> `if (1) { }else { }`
> my coworker prefers the latter. 

oh god. why?

**Comment by dcousens** [comment]
``` javascript
if (1) { }else { }
```

I've never seen that documented as being acceptable,  and in fact it'd be my understanding that this is in fact a bug. 

@feross ?

**Comment by feross** [comment]
If you use the latest standard, `if (1) { }else { }` is an error.

```
  /Users/feross/code/standard/standard/t.js:1:11: Missing space before keyword "else".
```

Try reinstalling standard and give it another shot. :+1:
