### ISSUE TITLE
Protected branches

### ISSUE THREAD

**Issue by dcousens** [feross/standard#267]
@feross any chance we could protect master such that PRs are still the norm?
I'd rather not keep up with the commit log directly if possible.

**Comment by rstacruz** [comment]
Protected branches won't prevent people from directly committing to `master`, only `push --force`s.

**Comment by dcousens** [comment]
@rstacruz true,  for some reason I mis-interpreted:

> Choose which status checks must pass before branches can be merged into master. When enabled, commits must first be pushed to another branch, then merged or pushed directly to master after status checks have passed.

To mean that you can only merge,  with no direct commits,  to master.
Well that sucks.

**Comment by Flet** [comment]
Its probably still a good idea turn on protection to disallow `push --force` :)

**Comment by feross** [comment]
Enabled it:

<img width="716" alt="screen shot 2015-09-21 at 10 03 56 am" src="https://cloud.githubusercontent.com/assets/121766/9998836/1859280e-6048-11e5-8c5f-721175d15a51.png">

**Comment by Flet** [comment]
Ah, so the status checks option is close to what @dcousens was asking for? If I'm reading it right, then it means everything must be pushed to a separate branch first to allow checks to run...

**Comment by feross** [comment]
Yep, seems that this does what @dcousens wants.

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected
To git@github.com:feross/standard.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:feross/standard.git'
```

Happy to try it out for a while. I like the idea that it increases visibility of changes by making it impossible to sneak in commits without people getting email notifications.

**Comment by rstacruz** [comment]
:+1:

**Comment by Flet** [comment]
Yeah, lets try it!

**Comment by dcousens** [comment]
@rstacruz right,  so it seems that specific option allows you to push to master **unless** you have status checks.

**Comment by dcousens** [comment]
@feross for it to align with your idea that those with access are still free to make changes, it just means they can self-merge. 
Its still a win for visibility.

**Comment by feross** [comment]
Yep, definite win for visibility.
