### ISSUE TITLE
Update version of standard on website "Try It Out" page

### ISSUE THREAD

**Issue by feross** [feross/standard#270]
From the `#standard` channel on IRC (freenode):

```
<•feross> flet: hey, i'm trying to make the "Try it Out" page on the standard website run the latest version
<•feross> having trouble getting the code in https://github.com/flet/standard-demo to run
<•feross> getting messages about missing packages
<•feross> also, we should show the version of standard and standard-format that's running on the page somewhere
<•feross> because people are using it for debugging purposes :)
```

http://standardjs.com/demo.html

@Flet - can you take a look?

**Comment by Flet** [comment]
For sure, this has been on my mind too... updating to latest version as well as showing version numbers.

**Comment by feross** [comment]
Nice! Thanks a lot!

**Comment by Flet** [comment]
what do you think, @feross
http://flet.github.io/standard-demo/

**Comment by Flet** [comment]
I am unsure on placing the versions in the message list like this... I'm afraid they may be bumped down too far... outside of a potential screenshot.

**Comment by feross** [comment]
They look like warnings or errors where they are now. How about moving them above or below the text editor field and making the font super small (like 8 or 10px)?

**Comment by rstacruz** [comment]
lol. what does this label mean @feross?

**Comment by feross** [comment]
http://youtu.be/2gR3moQ8hXQ

It's for non urgent issues that make the project the best it could possibly be :) It's like extra credit in school.

**Comment by Flet** [comment]
OK, moved version to the tippy-top of the editor. I also tweaked the font a bit on the messages.

http://standardjs.com/demo

Also btw, `standard-demo` is in a better state; you should not get the missing deps messages anymore.

**Comment by feross** [comment]
Nice :+1:
