### ISSUE TITLE
isNaN and isFinite on window

### ISSUE THREAD

**Issue by Calvein** [feross/standard#271]
I'm quoting the readme:

> Always prefix browser globals with window – except document and navigator are okay

I mostly agree with it except for those 2 because they're not really tied to the window (and they are slightly different from `Number.isNaN/Finite`).

**Comment by dcousens** [comment]
@Calvein,  but, they are globals on the `window`?

**Comment by dcousens** [comment]
Standard doesn't require `isFinite` and `isNaN` to be prefixed with `window` AFAIK.
Sounds like the README isn't correct.

**Comment by feross** [comment]
`isNaN` is not a global that's unique to the browser. It's available in all JS environments. So you're free to use it without prefixing it with `window`.
