### ISSUE TITLE
Not handles error locally, but handle it on travis ci

### ISSUE THREAD

**Issue by tunnckoCore** [feross/standard#272]
I was surprised. I don't know what, but it seems something is not okey.
I have try catch block like that in which dont have space between parenthesis and the end of catch keyword.

```js
try {
  // stuff
} catch(err) {
  throw err
}
```

Running `standard` it not outputs any errors (locally), but it fails in travis with

```
standard: Use JavaScript Standard Style (https://github.com/feross/standard) 
  /home/travis/build/tunnckoCore/octet/index.js:53:7: Keyword "catch" must be followed by whitespace.
```

Just wanted to notify you :)

**Comment by Flet** [comment]
Looking at https://github.com/tunnckoCore/octet/blob/master/.travis.yml I see that `standard` is installed via travis.

Also looking at `package.json` there is no dependency on `standard`, so locally you must have `standard` installed globally? 

Perhaps your global copy of `standard` is not up to date? Have you tried running `npm i -g standard` locally to update?

It seems unconventional to me to have travis install standard in this way. Is there a reason you're doing it like this? Usually I have `standard` in devDependencies.

**Comment by tunnckoCore** [comment]
Yea I have it globally, as many other tools. There's few reasons why i do it like that:

- I absolutely don't like to have them in devDeps
- they are too big (eslints, istanbuls, coverage tools, testing runners/frameworks and etc)
- there's no logic to loose time to install them every time

I usually keep it up-to-date, currently it is 5.2.2 and just noticed that it is outdated from a while. And yea [that's the key](https://github.com/feross/eslint-config-standard/commit/656ba93cda9cd4ab38e032649aafb795993d5176#diff-1761f4f4ee815f0c4156b931d737ff32R117).

Just forgot to check before open the issue. :)

**Comment by tunnckoCore** [comment]
It's a lot better and enough to set one badge to say "*this repo use standard code style*" and one contributing file which guides you how to contribute correctly. Meanwhile it answers why your PR may fail.
