### ISSUE TITLE
"Use standard style"

### ISSUE THREAD

**Issue by feross** [feross/standard#275]
`standard` has seen pretty incredible adoption! [1700+ packages](https://github.com/feross/standard-packages/blob/master/standard.json) already depend on it.

But how can we bring the benefits of `standard` to more packages? What about getting the top 200 packages to adopt it?

Developers get better by inspecting how popular packages work and looking at their `package.json` files. Getting more of the top 200 to adopt `standard` would likely have an outsize effect on overall adoption.

I see two possible approaches:

1. Use `standard --format` and/or manual work to transform packages and send PRs. This would probably be most effective for simple, small packages.
2. Open an issue ("Use standard style"), explain the benefits of `standard`, answer any questions the maintainers might have. This would probably be most effective if the issues are opened by existing contributors, or users who are invested in the package.

Points to mention in PRs, issues:

- 1700+ npm packages already use `standard`, including Google's Karma and npm itself. [Full list](https://github.com/feross/standard-packages/blob/master/standard.json).
- Link to the website: http://standardjs.com/
- Link to the full list of rules: http://standardjs.com/rules.html

Who wants to help?

This is the current top 200 list:

- [ ] 1. [mocha](https://github.com/mochajs/mocha) 50696
- [ ] 2. [chai](https://github.com/chaijs/chai) 21354
- [ ] 3. [grunt](https://github.com/gruntjs/grunt) 19903
- [ ] 4. [lodash](https://github.com/lodash/lodash) 15819
- [ ] 5. [should](https://github.com/shouldjs/should.js) 13148
- [ ] 6. [async](https://github.com/caolan/async) 12897
- [ ] 7. [grunt-contrib-jshint](https://github.com/gruntjs/grunt-contrib-jshint) 12357
- [ ] 8. [request](https://github.com/request/request) 12028
- [ ] 9. [gulp](https://github.com/gulpjs/gulp) 11845
- [ ] 10. [underscore](https://github.com/jashkenas/underscore) 11280
- [ ] 11. [coffee-script](https://github.com/jashkenas/coffeescript) 10246
- [ ] 12. [express](https://github.com/strongloop/express) 9987
- [ ] 13. [istanbul](https://github.com/gotwarlost/istanbul) 8819
- [ ] 14. [tape](https://github.com/substack/tape) 8717
- [ ] 15. [sinon](https://github.com/cjohansen/Sinon.JS) 8179
- [ ] 16. [grunt-contrib-clean](https://github.com/gruntjs/grunt-contrib-clean) 7601
- [ ] 17. [grunt-contrib-watch](https://github.com/gruntjs/grunt-contrib-watch) 7263
- [ ] 18. [browserify](https://github.com/substack/node-browserify) 7125
- [ ] 19. [jshint](https://github.com/jshint/jshint) 6885
- [ ] 20. [commander](https://github.com/tj/commander.js) 6694
- [ ] 21. [chalk](https://github.com/chalk/chalk) 5710
- [ ] 22. [debug](https://github.com/visionmedia/debug) 5666
- [ ] 23. [gulp-util](https://github.com/wearefractal/gulp-util) 5505
- [ ] 24. [mkdirp](https://github.com/substack/node-mkdirp) 5347
- [ ] 25. [coveralls](https://github.com/nickmerwin/node-coveralls) 5078
- [ ] 26. [grunt-contrib-nodeunit](https://github.com/gruntjs/grunt-contrib-nodeunit) 5060
- [ ] 27. [grunt-contrib-uglify](https://github.com/gruntjs/grunt-contrib-uglify) 5013
- [ ] 28. [q](https://github.com/kriskowal/q) 4901
- [ ] 29. [babel](https://github.com/babel/babel) 4861
- [ ] 30. [colors](https://github.com/Marak/colors.js) 4835
- [ ] 31. [bluebird](https://github.com/petkaantonov/bluebird) 4535
- [ ] 32. [glob](https://github.com/isaacs/node-glob) 4442
- [ ] 33. [through2](https://github.com/rvagg/through2) 4418
- [ ] 34. [uglify-js](https://github.com/mishoo/UglifyJS2) 4254
- [ ] 35. [jshint-stylish](https://github.com/sindresorhus/jshint-stylish) 4167
- [ ] 36. [eslint](https://github.com/eslint/eslint) 4153
- [ ] 37. [rimraf](https://github.com/isaacs/rimraf) 3909
- [ ] 38. [grunt-cli](https://github.com/gruntjs/grunt-cli) 3817
- [ ] 39. [moment](https://github.com/moment/moment) 3568
- [ ] 40. [gulp-rename](https://github.com/hparra/gulp-rename) 3535
- [ ] 41. [gulp-mocha](https://github.com/sindresorhus/gulp-mocha) 3517
- [x] **42. [karma](https://github.com/karma-runner/karma) 3437**
- [ ] 43. [yeoman-generator](https://github.com/yeoman/generator) 3418
- [ ] 44. [gulp-uglify](https://github.com/terinjokes/gulp-uglify) 3358
- [ ] 45. [optimist](https://github.com/substack/node-optimist) 3348
- [ ] 46. [load-grunt-tasks](https://github.com/sindresorhus/load-grunt-tasks) 3328
- [ ] 47. [gulp-jshint](https://github.com/spalger/gulp-jshint) 3217
- [ ] 48. [expect.js](https://github.com/LearnBoost/expect.js) 3157
- [ ] 49. [grunt-mocha-test](https://github.com/pghalliday/grunt-mocha-test) 3113
- [ ] 50. [minimist](https://github.com/substack/minimist) 3071
- [ ] 51. [sinon-chai](https://github.com/domenic/sinon-chai) 2961
- [ ] 52. [grunt-contrib-concat](https://github.com/gruntjs/grunt-contrib-concat) 2815
- [ ] 53. [grunt-contrib-copy](https://github.com/gruntjs/grunt-contrib-copy) 2757
- [ ] 54. [react](https://github.com/facebook/react) 2716
- [ ] 55. [tap](https://github.com/isaacs/node-tap) 2715
- [ ] 56. [body-parser](https://github.com/expressjs/body-parser) 2617
- [ ] 57. [supertest](https://github.com/visionmedia/supertest) 2545
- [ ] 58. [cheerio](https://github.com/cheeriojs/cheerio) 2518
- [x] **59. [fs-extra](https://github.com/jprichardson/node-fs-extra) 2509**
- [ ] 60. [jquery](https://github.com/jquery/jquery) 2488
- [ ] 61. [jade](https://github.com/jadejs/jade) 2477
- [ ] 62. [webpack](https://github.com/webpack/webpack) 2367
- [ ] 63. [nodeunit](https://github.com/caolan/nodeunit) 2284
- [ ] 64. [babel-core](https://github.com/babel/babel) 2162
- [x] **65. [karma-chrome-launcher](https://github.com/karma-runner/karma-chrome-launcher) 2160**
- [x] **66. [karma-phantomjs-launcher](https://github.com/karma-runner/karma-phantomjs-launcher) 2151**
- [ ] 67. [del](https://github.com/sindresorhus/del) 2129
- [ ] 68. [semver](https://github.com/npm/node-semver) 2120
- [ ] 69. [node-uuid](https://github.com/broofa/node-uuid) 2060
- [ ] 70. [redis](https://github.com/NodeRedis/node_redis) 2039
- [ ] 71. [socket.io](https://github.com/Automattic/socket.io) 2025
- [ ] 72. [connect](https://github.com/senchalabs/connect) 1987
- [ ] 73. [grunt-contrib-coffee](https://github.com/gruntjs/grunt-contrib-coffee) 1963
- [ ] 74. [gulp-concat](https://github.com/wearefractal/gulp-concat) 1961
- [ ] 75. [babel-eslint](https://github.com/babel/babel-eslint) 1956
- [ ] 76. [handlebars](https://github.com/wycats/handlebars.js) 1912
- [ ] 77. [jscs](https://github.com/jscs-dev/node-jscs) 1904
- [ ] 78. [mocha-lcov-reporter](https://github.com/StevenLooman/mocha-lcov-reporter) 1850
- [ ] 79. [winston](https://github.com/winstonjs/winston) 1807
- [ ] 80. [mongoose](https://github.com/Automattic/mongoose) 1794
- [x] **81. [yargs](https://github.com/bcoe/yargs) 1763**
- [ ] 82. [through](https://github.com/dominictarr/through) 1753
- [ ] 83. [karma-jasmine](https://github.com/karma-runner/karma-jasmine) 1740
- [ ] 84. [phantomjs](https://github.com/Medium/phantomjs) 1690
- [x] **85. [standard](https://github.com/feross/standard) 1661**
- [x] **86. [karma-mocha](https://github.com/karma-runner/karma-mocha) 1660**
- [ ] 87. [time-grunt](https://github.com/sindresorhus/time-grunt) 1646
- [ ] 88. [shelljs](https://github.com/arturadib/shelljs) 1645
- [ ] 89. [ember-cli](https://github.com/ember-cli/ember-cli) 1637
- [ ] 90. [vows](https://github.com/cloudhead/vows) 1624
- [ ] 91. [yosay](https://github.com/yeoman/yosay) 1621
- [ ] 92. [ejs](https://github.com/mde/ejs) 1619
- [ ] 93. [mongodb](https://github.com/mongodb/node-mongodb-native) 1618
- [ ] 94. [jsdom](https://github.com/tmpvar/jsdom) 1611
- [ ] 95. [jasmine-node](https://github.com/mhevery/jasmine-node) 1589
- [ ] 96. [broccoli-asset-rev](https://github.com/rickharrison/broccoli-asset-rev) 1589
- [ ] 97. [marked](https://github.com/chjj/marked) 1575
- [ ] 98. [ember-cli-inject-live-reload](https://github.com/rwjblue/ember-cli-inject-live-reload) 1573
- [ ] 99. [superagent](https://github.com/visionmedia/superagent) 1572
- [ ] 100. [vinyl-source-stream](https://github.com/hughsk/vinyl-source-stream) 1566
- [ ] 101. [underscore.string](https://github.com/epeli/underscore.string) 1560
- [ ] 102. [ember-cli-qunit](https://github.com/ember-cli/ember-cli-qunit) 1554
- [ ] 103. [gulp-sourcemaps](https://github.com/floridoo/gulp-sourcemaps) 1532
- [ ] 104. [babel-loader](https://github.com/babel/babel-loader) 1522
- [ ] 105. [ember-cli-ic-ajax](https://github.com/rjackson/ember-cli-ic-ajax) 1516
- [ ] 106. [ember-export-application-global](https://github.com/ember-cli/ember-export-application-global) 1514
- [ ] 107. [extend](https://github.com/justmoon/node-extend) 1511
- [ ] 108. [mime](https://github.com/broofa/node-mime) 1494
- [ ] 109. [karma-firefox-launcher](https://github.com/karma-runner/karma-firefox-launcher) 1489
- [ ] 110. [grunt-contrib-connect](https://github.com/gruntjs/grunt-contrib-connect) 1480
- [ ] 111. [ember-cli-content-security-policy](https://github.com/rwjblue/ember-cli-content-security-policy) 1468
- [ ] 112. [chai-as-promised](https://github.com/domenic/chai-as-promised) 1441
- [ ] 113. [xml2js](https://github.com/Leonidas-from-XIV/node-xml2js) 1437
- [ ] 114. [ember-cli-dependency-checker](https://github.com/quaertym/ember-cli-dependency-checker) 1427
- [ ] 115. [event-stream](https://github.com/dominictarr/event-stream) 1417
- [ ] 116. [grunt-release](https://github.com/geddski/grunt-release) 1407
- [ ] 117. [bower](https://github.com/bower/bower) 1380
- [ ] 118. [js-yaml](https://github.com/nodeca/js-yaml) 1351
- [ ] 119. [gulp-plumber](https://github.com/floatdrop/gulp-plumber) 1347
- [ ] 120. [nock](https://github.com/pgte/nock) 1336
- [ ] 121. [less](https://github.com/less/less.js) 1327
- [ ] 122. [concat-stream](https://github.com/maxogden/concat-stream) 1307
- [ ] 123. [ember-cli-htmlbars](https://github.com/ember-cli/ember-cli-htmlbars) 1302
- [ ] 124. [ember-data](https://github.com/emberjs/data) 1298
- [ ] 125. [run-sequence](https://github.com/OverZealous/run-sequence) 1296
- [ ] 126. [watchify](https://github.com/substack/watchify) 1285
- [ ] 127. [gulp-babel](https://github.com/babel/gulp-babel) 1284
- [ ] 128. [grunt-bump](https://github.com/vojtajina/grunt-bump) 1275
- [ ] 129. [xtend](https://github.com/Raynos/xtend) 1251
- [ ] 130. [gulp-load-plugins](https://github.com/jackfranklin/gulp-load-plugins) 1247
- [ ] 131. [ember-cli-uglify](https://github.com/ember-cli/ember-cli-uglify) 1246
- [ ] 132. [ember-cli-app-version](https://github.com/embersherpa/ember-cli-app-version) 1244
- [ ] 133. [gulp-istanbul](https://github.com/SBoudrias/gulp-istanbul) 1234
- [ ] 134. [object-assign](https://github.com/sindresorhus/object-assign) 1212
- [ ] 135. [tap-spec](https://github.com/scottcorgan/tap-spec) 1210
- [ ] 136. [grunt-shell](https://github.com/sindresorhus/grunt-shell) 1198
- [ ] 137. [gulp-coffee](https://github.com/wearefractal/gulp-coffee) 1196
- [ ] 138. [grunt-browserify](https://github.com/jmreidy/grunt-browserify) 1152
- [x] **139. [karma-coverage](https://github.com/karma-runner/karma-coverage) 1138**
- [ ] 140. [ember-cli-babel](https://github.com/babel/ember-cli-babel) 1130
- [ ] 141. [inquirer](https://github.com/sboudrias/Inquirer.js) 1101
- [ ] 142. [babelify](https://github.com/babel/babelify) 1067
- [ ] 143. [co](https://github.com/tj/co) 1060
- [x] **144. [grunt-karma](https://github.com/karma-runner/grunt-karma) 1059**
- [ ] 145. [matchdep](https://github.com/tkellen/node-matchdep) 1059
- [ ] 146. [requirejs](https://github.com/jrburke/r.js) 1035
- [ ] 147. [ws](https://github.com/websockets/ws) 1034
- [ ] 148. [blanket](https://github.com/alex-seville/blanket) 1022
- [ ] 149. [webpack-dev-server](https://github.com/webpack/webpack-dev-server) 1005
- [ ] 150. [gulp-eslint](https://github.com/adametry/gulp-eslint) 996
- [ ] 151. [promise](https://github.com/then/promise) 991
- [ ] 152. [stylus](https://github.com/stylus/stylus) 987
- [x] **153. [minimatch](https://github.com/isaacs/minimatch) 987**
- [ ] 154. [mysql](https://github.com/felixge/node-mysql) 980
- [ ] 155. [morgan](https://github.com/expressjs/morgan) 970
- [ ] 156. [grunt-simple-mocha](https://github.com/yaymukund/grunt-simple-mocha) 969
- [ ] 157. [proxyquire](https://github.com/thlorenz/proxyquire) 967
- [ ] 158. [es6-promise](https://github.com/jakearchibald/ES6-Promises) 964
- [ ] 159. [prompt](https://github.com/flatiron/prompt) 961
- [ ] 160. [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) 946
- [ ] 161. [ember-disable-prototype-extensions](https://github.com/rwjblue/ember-disable-prototype-extensions) 941
- [ ] 162. [cookie-parser](https://github.com/expressjs/cookie-parser) 930
- [ ] 163. [babel-runtime](https://github.com/babel/babel) 929
- [ ] 164. [gulp-minify-css](https://github.com/murphydanger/gulp-minify-css) 926
- [ ] 165. [ember-try](https://github.com/kategengler/ember-try) 924
- [ ] 166. [aws-sdk](https://github.com/aws/aws-sdk-js) 910
- [ ] 167. [when](https://github.com/cujojs/when) 907
- [ ] 168. [readable-stream](https://github.com/nodejs/readable-stream) 897
- [ ] 169. [gulp-jscs](https://github.com/jscs-dev/gulp-jscs) 891
- [ ] 170. [pre-commit](https://github.com/observing/pre-commit) 876
- [ ] 171. [esprima](https://github.com/jquery/esprima) 868
- [ ] 172. [backbone](https://github.com/jashkenas/backbone) 866
- [ ] 173. [inherits](https://github.com/isaacs/inherits) 860
- [ ] 174. [grunt-contrib-cssmin](https://github.com/gruntjs/grunt-contrib-cssmin) 860
- [ ] 175. [gulp-header](https://github.com/tracker1/gulp-header) 839
- [ ] 176. [jasmine-core](https://github.com/jasmine/jasmine) 832
- [ ] 177. [wrench](https://github.com/ryanmcgrath/wrench-js) 806
- [ ] 178. [open](https://github.com/pwnall/node-open) 804
- [ ] 179. [gulp-bump](https://github.com/stevelacy/gulp-bump) 801
- [ ] 180. [gulp-watch](https://github.com/floatdrop/gulp-watch) 799
- [ ] 181. [uuid](https://github.com/shtylman/node-uuid) 791
- [ ] 182. [lab](https://github.com/hapijs/lab) 778
- [ ] 183. [socket.io-client](https://github.com/Automattic/socket.io-client) 773
- [ ] 184. [koa](https://github.com/koajs/koa) 745
- [ ] 185. [ember-disable-proxy-controllers](https://github.com/cibernox/ember-disable-proxy-controllers) 738
- [ ] 186. [css-loader](https://github.com/webpack/css-loader) 738
- [ ] 187. [grunt-coffeelint](https://github.com/vojtajina/grunt-coffeelint) 732
- [ ] 188. [grunt-jscs](https://github.com/jscs-dev/grunt-jscs) 729
- [ ] 189. [style-loader](https://github.com/webpack/style-loader) 724
- [ ] 190. [jsdoc](https://github.com/jsdoc3/jsdoc) 721
- [x] **191. [npm](https://github.com/npm/npm) 715**
- [ ] 192. [temp](https://github.com/bruce/node-temp) 708
- [ ] 193. [nan](https://github.com/nodejs/nan) 705
- [ ] 194. [benchmark](https://github.com/bestiejs/benchmark.js) 702
- [ ] 195. [path](https://github.com/jinder/path) 700
- [ ] 196. [browser-sync](https://github.com/browsersync/browser-sync) 698
- [ ] 197. [assert](https://github.com/defunctzombie/commonjs-assert) 693
- [ ] 198. [vinyl-buffer](https://github.com/hughsk/vinyl-buffer) 690
- [ ] 199. [ava](https://github.com/sindresorhus/ava) 682
- [ ] 200. [passport](https://github.com/jaredhanson/passport) 681

**Comment by rstacruz** [comment]
>  11. coffee-script 10247

lol

**Comment by yoshuawuyts** [comment]
How about getting Node core to adopt standard? I thought about it before, but never felt in a comfortable enough position to suggest it.

A possible entry point into Node core could be the [readable-stream](https://github.com/nodejs/readable-stream) repo, which contains the streams implementation used in core.

**Comment by dcousens** [comment]
ping @calvinmetcalf

**Comment by calvinmetcalf** [comment]
naw readable-stream is just a bunch of regexes that pull it out of node core

**Comment by LinusU** [comment]
I would love to help out! :rocket: 

Could we maybe draft a good pull request text that we can use?

**Comment by LinusU** [comment]
First pull request submitted!

**Comment by feross** [comment]
After discussion on IRC, consensus was that this approach is a little too aggressive. I agree. Was worth sharing the idea for feedback, nonetheless!

**Comment by LinusU** [comment]
@feross Maybe we could try and find repositories that already have a similar coding style, and make pull requests to them?

It would be really cool to run standard on every npm package and count the number of errors, then start from the bottom at that list.

**Comment by Alhadis** [comment]
@feross : I staunchly oppose your "standard style", your preference for hideous 2-space soft tabs and your blatant disregard for [common sense](https://github.com/Alhadis/CSC). Seriously dude, stop trying to fix what isn't broken.

**Comment by LinusU** [comment]
Just because you have made a repository called "Common Sense Coding" doesn't mean that it's actually common sense. If you prefer tabs, then by all means, use them. Two spaces seems to be the most widely used in the JavaScript community though, a standard style needs to take that into account in order to get adoption.

**Comment by feross** [comment]
@Alhadis No one's forcing anyone to use standard. If it's not your cup of tea, feel free to not use it. Cheers!
