### ISSUE TITLE
Incremental lint

### ISSUE THREAD

**Issue by scottcorgan** [feross/standard#277]
Have there been any discussions or attempts and speeding up linting a large codebase with incremental linting (only lint the files that have changed)?

Or, is this a thing already with eslint?

**Comment by sindresorhus** [comment]
ESLint recently got a [`cache` option](http://eslint.org/docs/developer-guide/nodejs-api.html#cliengine) which can be used by Standard.

**Comment by scottcorgan** [comment]
Appreciate that.

Also, https://github.com/eslint/eslint/blob/2e17e69e879d507a55936ea7e8d92067fbdb2e6e/tests/lib/cli-engine.js#L1303

**Comment by Flet** [comment]
Why close?

**Comment by scottcorgan** [comment]
It's not an issue. More like a reference to an answer now. The solution is with eslint

**Comment by Flet** [comment]
I guess I'm confused. I don believe `standard` (or `standard-engine` set the `cache` or the `cacheFile` options at all...

...so this issue could be a request to conder turning on eslint caching?

**Comment by scottcorgan** [comment]
Oh duh, you're right. Re-opening.

**Comment by rstacruz** [comment]
yes please.

**Comment by nelix** [comment]
On the subject of incremental linting, an option to only lint files in git diff would be good for commit hooks, CI and perf.

**Comment by dcousens** [comment]
That would also be great for incremental linting,  where a repository doesn't want to refactor the entire code base at once, but enforce it on new commits.
Very interested in whether someone has a solution for that.

**Comment by scottcorgan** [comment]
Is this something still on the roadmap. I saw that 2 PRs were closed on standard-engine, and I'm not sure why.

https://github.com/Flet/standard-engine/pull/18
https://github.com/Flet/standard-engine/pull/17

**Comment by feross** [comment]
Yes, this is something that I'd like to ship since it could greatly improve the time it takes to run `standard`. It's ~2sec for me on most projects. Would be nice to get that <1sec.

I gave this a go once, but didn't get it working reliably. @scottcorgan If you can make it work, we'll ship it!

**Comment by feross** [comment]
PR to add support to `standard-engine`: https://github.com/Flet/standard-engine/pull/125

**Comment by feross** [comment]
Merged the PR! 🎉

Running `standard` on a large codebase like [electron/electron](https://github.com/electron/electron) is now more than 2x faster on repeat runs, thanks to the ESLint cache feature!

- Before: 3.68s
- After: 1.59s

👍 👍 👍 👍 👍 👍 

This will ship as part of standard v8.

**Comment by LinusU** [comment]
Awesome!! 🎉

**Comment by samhatoum** [comment]
I can't see anywhere in the docs how to enable caching this from the `package.json`. Is this possible?

**Comment by feross** [comment]
@samhatoum There's nothing to enable. If you're using the `standard` CLI then the feature is already enabled.
