### ISSUE TITLE
Question: x == null rule

### ISSUE THREAD

**Issue by rstacruz** [feross/standard#279]
The readme says:

> Always use === instead of == – but obj == null is allowed to check null || undefined.

Why is `==` being permitted in this exception?

**Comment by dcousens** [comment]
Probably because it broke a lot a lot of peoples code/assumptions otherwise.

**Comment by rstacruz** [comment]
in that case, perhaps it should be considered for deprecation?

**Comment by dcousens** [comment]
Possibly,  there might be more to it. @feross?

**Comment by feross** [comment]
It's a very common idiom in JS to check for `null` and `undefined` in one shot by using `== null`.

`x == null` is far nicer than `x === null || x === undefined` to the trained eye.

**Comment by dcousens** [comment]
IMHO,  if they can afford to be that loose with their arguments,  I'd prefer just `if (!x) {`.
If they need to be specific enough such that `== null` is an option, IMHO they should be doing `=== null || === undefined`.
But,  that is just my opinion.

**Comment by feross** [comment]
`!x` catches a bunch of other things like the empty string and the number 0. The `== null` idiom is common in node.js core and on npm.

@dcousens Maybe you're right, but this ship has sailed and it's not worth a breaking change.

**Comment by dcousens** [comment]
@feross not even in a `6.0.0` if/when that happens?
