### ISSUE TITLE
Force promise arguments name

### ISSUE THREAD

**Issue by LinusU** [feross/standard#282]
One common problem that often hits me when dealing with promises is in what order the parameters are in the executor.

```javascript
new Promise(function (resolve, reject) {

})
```

Is it `resolve, reject` or `reject, resolve`? The correct answer is the first one, but wouldn't it be awesome if `standard` forced this for you? It's kind of how we force you to handle the first parameter if it's named `err`.

Sounds good? :roller_coaster:

**Comment by rstacruz** [comment]
what about those who use `new Promise((ok, fail) => {})` or `(success, error)`? should they be coerced to use `resolve, reject` too?

**Comment by LinusU** [comment]
I don't know, I would prefer forcing everyone to use the same, but another approach could be to not allow `fail`, `reject`, `error` as the first argument; and not allow `resolve`, `ok`, `success` as the second.

I think that the best approach is to try the stricter and see how many of the packages we break. The infrastructure for this is already in place and is easy enough to use.

**Comment by rstacruz** [comment]
I'm all for the idea, but I see people do [something like this](https://github.com/search?q=resolve1+reject1&type=Code&utf8=%E2%9C%93) with nested promises:

```js
		return new Promise(function (resolve1, reject1) {
	  		return new Promise(function (resolve2, reject2) {
```

**Comment by LinusU** [comment]
In that search there is actually only 5 occurrences of the pattern, most was some type of testing code that did `state = 'resolve1'`.

**Comment by yoshuawuyts** [comment]
@rstacruz Regardless if this should be caught, I suspect that's generally done by authors that lack understanding of how closures work. e.g. In the [first example](https://github.com/samueljun/Pomodoro-Clock/blob/66a9c43d6ce7daa1abbccca1a1a2418987c7fe77/Source/Platform/Chromium/panel.browser.js) `resolve1` could be renamed to `resolve` without any problems.

**Comment by feross** [comment]
Is there even an eslint rule to enforce this with?

**Comment by jden** [comment]
+1 to this. I made an eslint plugin for this rule, https://github.com/jden/eslint-plugin-promiseparams

**Comment by LinusU** [comment]
@jden Awesome! :+1:

**Comment by jden** [comment]
re @rstacruz's example
```js
  return new Promise(function (resolve1, reject1) {
            return new Promise(function (resolve2, reject2) {
```
this is never necessary because of closure scoping. It doesn't make sense for an inner promise to resolve or reject an outer promise. I suppose it's possible to contrive some example that is a valid JavaScript program, but it's a confusing style which breaks the wrapper abstraction of promises in favor of cross-scope shared state with the added dimension of asynchronous execution time - exactly the sort of unnecessarily complex and unusual code style that an opinionated linter can protect you from.

**Comment by Flet** [comment]
This makes sense to me. Thanks for putting together the rule @jden!

**Comment by jden** [comment]
Is `standard` currently using custom eslint rules? Or only builtins? What's the best way forward for turning this issue into a `standard` PR?

**Comment by Flet** [comment]
@jden Yeah there is at least one custom plugin. Submit this to https://github.com/feross/eslint-config-standard

**Comment by feross** [comment]
This is :+1: from me. Let's ship it in `standard` v6.

**Comment by feross** [comment]
```
# tests 427
# pass  421
# fail  6
```

**Comment by dcousens** [comment]
@feross that is quite surprising!  Good to see people are consistent :+1:
