### ISSUE TITLE
UTF-8 BOM causes error

### ISSUE THREAD

**Issue by beakdoctor** [feross/standard#283]
I just noticed if you have a file with a UTF-8 BOM standard will throw an error like:
test2.js:1:1: Irregular whitespace not allowed
Is this intentional? Either way it's a confusing error because you can't actually see it visually. Also, Visual Studio apparently loves to add these to your files which will cause a lot of headaches along with this rule.

**Comment by dcousens** [comment]
Can you post a file we can use for reproduction?
If you have trouble copy pasting it,  just paste the file base64 encoded.

**Comment by beakdoctor** [comment]
I can't attach any files for some reason, but here is the base64:
77u/dmFyIHggPSA0Mg0KbW9kdWxlLmV4cG9ydHMgPSB4DQo=

I have no idea if the bom is preserved, but there is another way. In npm there is a tool called add-bom:

    > standard nobom.js
    

    > add-bom -f nobom.js
    BOM was appended to nobom.js

    > standard nobom.js
    standard: Use JavaScript Standard Style (https://github.com/feross/standard)
      C:\kod\oltest\VS-OL\VS-OL\src\nobom.js:1:1: Irregular whitespace not allowed

There is also another tool called strip-bom-cli that is invoked like this:

    > strip-bom nobom.js > nobom2.js

    > standard nobom2.js

    >

**Comment by dcousens** [comment]
Bug confirmed.

@feross I'm guessing this is an eslint issue?

**Comment by Flet** [comment]
I believe this is a feature of the rule:
http://eslint.org/docs/rules/no-irregular-whitespace.html
>With this rule enabled the following characters will cause warnings outside of strings:
`\ufeff - Zero Width No-Break Space - <BOM>`

**Comment by feross** [comment]
There's no need for a BOM character in a plaintext UTF-8 file. It's neither required, nor recommended by the Unicode spec.

It appears there's an option to disable this behavior in Visual Studio: https://stackoverflow.com/questions/5406172/utf-8-without-bom

**Comment by dcousens** [comment]
@Flet that'll teach me for not investigating what a BOM character is.
Not a bug.

**Comment by feross** [comment]
@dcousens Yeah, I hadn't heard of them before this either.
