### ISSUE TITLE
JSX Params check for '{...}'

### ISSUE THREAD

**Issue by allenmanning** [feross/standard#292]
One thing for consideration is the common error of putting quotes around jsx params.  This seems to be a common source of errors.  I can't think of a good reason why you would want to do this, and if you do you could always assign a variable like this

```
let myString = '{...}'

<element param={myString}/>
```

**Comment by dcousens** [comment]
I've never seen this,  is it really common?
In any case, this would be impossible to detect due to its ambiguity with valid strings.
