### ISSUE TITLE
Infix operators within default argument declaration

### ISSUE THREAD

**Issue by reggi** [feross/standard#293]
Found it odd that standard isn't looking to change the first argument to `state = {count: 0}` instead.

```js
function counter (state={count: 0}, action) {
  let count = state.count
  switch (action.type) {
    case 'increase':
      return {count: count + 1}
    default:
      return state
  }
}
```

**Comment by reggi** [comment]
Turns out the `standard` command does report this, however the atom plugin does not.

**Comment by feross** [comment]
You might want to check that you don't have two different copies of `standard`, one global and one local.

**Comment by reggi** [comment]
Updated the plugin, I'm good now.
