### ISSUE TITLE
Enforce "Never start a line with ( or ["

### ISSUE THREAD

**Issue by caesarsol** [feross/standard#295]
Don't you think the rule:

> Never start a line with ( or [. This is the only gotcha with omitting semicolons.

should be enforced by the `eslint` configuration?

**Comment by rstacruz** [comment]
:+1:

**Comment by feross** [comment]
Never starting a line with a `(` or `[` is already enforced. Check it out:

```js
console.log('hi')
[1, 2, 3].forEach(console.log)
```

`Unexpected newline between object and [ of property access. (no-unexpected-multiline)`

**Comment by feross** [comment]
For the record, you can add a leading semicolon in this situation, if desired:

```js
console.log('hi')
;[1, 2, 3].forEach(console.log)
```

`No errors.`

**Comment by feross** [comment]
Also for the record, you can test this stuff out easily on http://standardjs.com/demo.html :+1:

**Comment by rstacruz** [comment]
interesting... i just tripped into a JS error because of this and standard didnt catch it. Guess i was on an old version

**Comment by feross** [comment]
@rstacruz if you have a test case, please share so we can catch it!
