### ISSUE TITLE
npm3 script, use deprecated version of estraverse

### ISSUE THREAD

**Issue by adriengibrat** [feross/standard#296]
I'm having  `ExportDefaultDeclaration` error with npm3 using standard v5.3.1 in npm script ... but no error when using it in cli!

This bug [is resolved](https://github.com/eslint/eslint/issues/1965).

But with npm3, when using standard via a npm script, a deprecated version of estraverse (see https://github.com/RReverser/estraverse-fb/issues/5) is used.

It's related on how npm3 resolves dependencies. I did not checked the dependency tree to check if there is peer dependencies...

It's not a bug in standard, but I created an issue here to avoid anyone to spend too much time to track this down.

**Comment by feross** [comment]
It sounds like you have two copies of `standard` installed. One global (used by the CLI) and one local (used by npm run scripts). You can update both to the latest version by running:

```
npm install standard -g
npm install standard@latest --save-dev
```

**Comment by dcousens** [comment]
@feross is `@latest` not required for `-g`?

**Comment by feross** [comment]
`npm install -g` uses the latest version on npm. The reason you need `@latest` for local install is that there could be a old version specified in `package.json` and `npm install` will obey the semver restrictions.

**Comment by dcousens** [comment]
TIL, thanks :)

**Comment by feross** [comment]
https://docs.npmjs.com/cli/install is really interesting, fwiw :+1:

**Comment by adriengibrat** [comment]
Yep, I have both global and local standard installed. But both are v5.3.1, so it's not just a version pb.

The pb is when local standard is called via npm script, it use the deprecated version of estraverse because of estraverse-fb deprecated dependency.

The bug seems to be related to npm3 dependencies collision handling: https://github.com/npm/npm/issues/9708

I worked around the pb, doing this:  https://github.com/npm/npm/issues/9708#issuecomment-144667135

**Comment by feross** [comment]
Closing this now, since it's not a standard issue.
