### ISSUE TITLE
Use npm config object over custom.

### ISSUE THREAD

**Issue by killswitch** [feross/standard#297]
Is there any specific reason that `standard` exists on the root `package.json` object and not in the global `config` object? https://docs.npmjs.com/files/package.json#config

**Comment by feross** [comment]
Interesting. Didn't know about the "config" property when we added the "standard" option. There's already a popular practice of just adding config options directly to the root of `package.json`, for example: "browserify" and ["browser"](https://gist.github.com/defunctzombie/4339901) are two that I'm aware of.
