### ISSUE TITLE
'"$" is undefined' errors when using JQuery methods

### ISSUE THREAD

**Issue by ckib16** [feross/standard#301]
Hey all - noob question that I couldn't find an answer for.

I'm getting multiple ` "$" is undefined ` errors from the linter when entering standard JQuery code. Do I have to add `$` to the "ignored list", or is there better integration with JQuery that I'm missing to avoid these errors?

Thanks,
Chris
![screen shot 2015-10-21 at 17 20 53](https://cloud.githubusercontent.com/assets/2160186/10650567/246b03e6-7818-11e5-86a5-fb9060ac7784.png)

**Comment by ckib16** [comment]
Apologies - wrong thread! Closing now.

**Comment by yoshuawuyts** [comment]
As `$` is a non-standard property you probably want to do
```js
const $ = window.$
```

**Comment by jprichardson** [comment]
Or declare `$` as a global in the file itself or package.json. See for more info: http://standardjs.com/#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors-

**Comment by ckib16** [comment]
@yoshuawuyts @jprichardson Thanks guys. I mistakenly posted this here. I've closed it out and have moved it to the more relevant linter-js-standard repo - https://github.com/ricardofbarros/linter-js-standard/issues/63

@jprichardson - if able, can you tell me how to actually get to `package.json`? I'm not sure I understand the path to that file.

**Comment by yoshuawuyts** [comment]
@ckib16 ah yeah, `package.json` is an `npm` / `commonjs` thing. It allows you to declare dependencies and configuration in a central place, and pull them in separate from your source code.

If you want to learn more about `npm`, `package.json` and bundling tools such as `browserify` http://nodeschool.io/ might be a good place to start.

**Comment by ckib16** [comment]
@yoshuawuyts Oh wow, OK. Much different than what I thought package.JSON was. I'm actually learning Node next week so I'll check into that then. Much appreciated!

**Comment by yoshuawuyts** [comment]
🙌
