### ISSUE TITLE
Linter does not work with two default function arguments

### ISSUE THREAD

**Issue by KevinGrandon** [feross/standard#305]
I'm seeing weird behavior when passing two arguments which default to a fat arrow function. This is linting correctly for me when using vanilla eslint, so my guess is that something between standard and eslint is causing this to fail (though there is a chance that it is an eslint problem if some config is triggering it). Opening this to hopefully track it down further and see if anyone has an idea of what's wrong.

```js
// Lints correctly:
var workingLinter = ({
  foo,
  bar = x => x
}) => window.alert('it worked.')

workingLinter()


// Lints incorrectly:
// Error: Parsing error: Unexpected token =>
var brokenLinter = ({
  foo,
  bar = x => x,
  baz = x => x
}) => window.alert('it broke.')

brokenLinter()
```

**Comment by feross** [comment]
This works fine on the `v6` branch, so it sounds like the eslint AST parser has gotten better and can handle this now.

`standard` v6 will be released very soon.
