### ISSUE TITLE
Standard Flow Typing

### ISSUE THREAD

**Issue by thomas-jeepe** [feross/standard#306]
I'm just putting this out there because the formatter doesn't work with flow.

If you were to put it in, I would just go with 

```javascript
// colon on variable
var foo: string = 'blah'

// regular array type
var array: Array<string> = ['hi']

// semi colons on each property
var obj: {a: string; b: number;} = {a:'hi',b:1}
```

or something of the sort

**Comment by jprichardson** [comment]
@penguinsoccer why not just do typing via the comments? http://flowtype.org/blog/2015/02/20/Flow-Comments.html

**Comment by penguinsoccer** [comment]
That is a lot more code. It will add up over time

**Comment by yoshuawuyts** [comment]
Meh, the `jsx` part of `standard` is already bloated and huge (it has a significant impact on download time). Support for more non-standard extensions to the language is probably a bad idea.

Instead consider forking `standard` to create a `standard-flow` or similar using the necessary dependencies to satisfy your needs.

**Comment by thomas-jeepe** [comment]
@yoshuawuyts The problem with that is that the parser does not support flow typing so it is impossible with that unless I take the flow parser and make it custom which would take far too long :(

**Comment by Flet** [comment]
Sorry, I don't think this will be possible without significant enhancements to upstream dependencies or custom code. Closing this for now.
