### ISSUE TITLE
space before await in array

### ISSUE THREAD

**Issue by LinusU** [feross/standard#307]
Is this intentional?

```javscript
const [bread, butter] = [await breadPromise, await butterPromise]
```

> Missing space before keyword "await".

As you can see I don't use initial spaces in arrays (`[a, b]` vs. `[ a, b ]`) which standard is totally fine with, so it seems weird that I need to do it when using await.

**Comment by LinusU** [comment]
Probably a duplicate of #268, sorry

**Comment by feross** [comment]
Yepo
