### ISSUE TITLE
Vim plugin

### ISSUE THREAD

**Issue by mightyiam** [feross/standard#31]
My VIM doesn't recognize that a project is Standard.

Is the presence of `standard` in `package.json`'s `devDependencies` enough to flag that the package is Standard?

Perhaps both ESLint and JSCS should be patched to recognize the presence of Standard and then automatically look for the RC files in the right place?

Then, when used from within the editor, it just happens automagically—well, at least with some editors, who rely on external tools like that.

**Comment by mikesherov** [comment]
JSCS will not be patching itself to recognize standard. The correct way to do this would be to make standard a jscs plugin and an eslint plugin, rather than something that uses both of those tools.

**Comment by mightyiam** [comment]
@mikesherov and @nzakas,

Thank you for commenting.

Perhaps JSCS and ESLint can be patched to recognize to look for something other than an rcfile in the current directory? Are you open for that?

I'm thinking perhaps a property in `package.json`, which provides paths to rcfiles:
``` json
{
  "name": "my-package",
  "rcfiles": ["node_modules/standard/rc"]
}
```

In Standard, I'm looking for the least amount of actions for setting it up.

Editing `package.json` (to prefix the test script with `standard && `) is probably already part of the workflow of setting Standard up, so adding the `rcfiles` property/value is just another step in the same file.

Perhaps addition of `rcfiles` can be made automagical, using `standard`'s npm [`postinstall` script](https://docs.npmjs.com/misc/scripts)?

**Comment by mikesherov** [comment]
You can already run jscs with an file using the `config` option.

**Comment by nzakas** [comment]
Ditto ESLint using the `-c` option.

**Comment by mightyiam** [comment]
I'm looking for a way that will not require anyway to alter the way that ESLint & JSCS are called.

For example, ESLint is called automatically from my VIM plugin.

The current existing way of providing rules is the presence of rcfiles.

But that is not flexible enough for my purpose because that requires Standard to put such files in place in the repo where it is used and that is not such a great possibility, as you can imagine.

The little addition of a property to `package.json` is an acceptable, pleasant, non–destructive alteration.

If only ESLint and JSCS will follow such a property, it will be one possible solution. Are you open to anything like this?

**Comment by nzakas** [comment]
ESLint already allows you to have configuration in package.json: http://eslint.org/docs/configuring/

**Comment by Flet** [comment]
A better approach might be to create a vim plugin specifically for `standard`. It may be worth getting this added to syntastic. 

It looks like someone opened an issue for it already: scrooloose/syntastic/issues/1314

**Comment by feross** [comment]
The correct approach is to create a vim plugin for `standard`.

@Flet already wrote a [Sublime Text plugin](https://github.com/Flet/Sublimelinter-contrib-standard). It's quite easy to do, since the output is easily parseable. You can see the regex to use [here](https://github.com/Flet/SublimeLinter-contrib-standard/blob/master/linter.py#L25).

Ideally, a dedicated vim user would step up and write this plugin! I use vim as my secondary editor (only when I'm ssh'd into a server, and usually without syntax highlighting).

**Comment by mightyiam** [comment]
I'll use VIM so I'll benefit. But what about all the other editors?

@nzakas it allows configuration in package.json but it doesn't allow a directive/rule that allows us to provide a path to an rcfile, right? An include rule would be perfect. Would you be open to an include rule?

**Comment by mightyiam** [comment]
If we do this at the lower, ESLint&JSCS level, we don't need any editors to recognize Standard.

**Comment by feross** [comment]
@mightyiam Please take your feature request directly to the jscs or eslint issue trackers.

Let's use this issue to track progress on a vim plugin. If someone writes this, let me know and we can link it from the README.

**Comment by lcd047** [comment]
@feross Syntastic maintainer here.  Writing a syntastic checker for standard would be mostly trivial, provided that you fix [this](https://github.com/feross/standard/blob/master/bin/cmd.js#L41). :) As it is now, running
```vim
:echo system('standard file.js')
```
from Vim yields nothing, since `stdin` as seen by standard is not a TTY.

**Comment by feross** [comment]
@lcd047 Hey, fixed the issue in 2.6.1. Care to give it a try?

**Comment by lcd047** [comment]
@feross Excellent!  It works now, and I added a syntastic checker for it in c1a2098.

Unrelated however, error highlighting in syntastic seem to imply column numbers for `eslint`, except the ones referring to semicolons, are off by one.

**Comment by mightyiam** [comment]
Thank you very much, @feross and @lcd047.
