### ISSUE TITLE
Nobody write a space after function name

### ISSUE THREAD

**Issue by tkrotoff** [feross/standard#311]
You recommend to write `function name (arg) { ... }` instead of `function name(arg) { ... }`.

It seems you are the only one among the JavaScript style guides (*) to recommend that:

- [Airbnb (25,827 stars btw)](https://github.com/airbnb/javascript#functions)
- [Google](https://google.github.io/styleguide/javascriptguide.xml?showone=Method_and_property_definitions#Method_and_property_definitions)
- [Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#JavaScript_objects)
- [idiomatic.js](https://github.com/rwaldron/idiomatic.js#spacing)
- [Crockford](http://javascript.crockford.com/code.html#function)
- [jQuery](https://contribute.jquery.org/style-guide/js/#comments)
- ...

Consequence, you also recommend to write:
```TypeScript
class Foo {
  name (arg) {
    ...
  }
}
```
instead of
```TypeScript
class Foo {
  name(arg) {
    ...
  }
}
```

None of the popular programming languages out there do that:
- [Java](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141270.html#381)
- [PHP](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md)
- [Python](https://www.python.org/dev/peps/pep-0008/)
- [Ruby](https://github.com/bbatsov/ruby-style-guide)
- [C#](https://msdn.microsoft.com/en-us/library/ff926074.aspx)
- [C++](http://www.stroustrup.com/bs_faq2.html#simple-program)
- [C](https://en.wikipedia.org/wiki/Indent_style#K.26R_style)
- [TypeScript](http://www.typescriptlang.org/Handbook#functions)
- [Scala](http://docs.scala-lang.org/style/types.html#functions)
- [Rust](http://rustbyexample.com/hello.html)
- [Swift](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Functions.html)
- [Go](https://github.com/golang/example/blob/master/hello/hello.go)
- ...

And last, statistics show that most people ([67%](http://sideeffect.kr/popularconvention/#javascript)) don't write a space after function in JavaScript.

Related issues: #89, #164, #217

(*) listed on [Google first page](https://www.google.com/search?q=JavaScript+style+guide)

**Comment by maxogden** [comment]
The title of this issue is inaccurate. Currently every user of this module uses spaces after function names. This is a great example of bikeshedding. Please read https://github.com/feross/standard#i-disagree-with-rule-x-can-you-change-it

**Comment by feross** [comment]
@tkrotoff Thanks for sharing your opinion about this issue. It's not open for discussion, though.

**Comment by tkrotoff** [comment]
The npm name is "standard", the title is "JavaScript Standard Style", the moto is "One Style to Rule Them All" and not something like "Feross JS Style Guide", ["Airbnb JS Style Guide"](https://github.com/airbnb/javascript), ["Google JS Style Guide"](https://google.github.io/styleguide/javascriptguide.xml).

A name like this come with responsibilities.

**Comment by feross** [comment]
Let's be honest: this is an pretty unimportant issue. You might be able to find some minor reasons why your preferred style is better than the other style, but others can come up with reasons why their choice is better than yours. This leads to bike shedding.

It doesn't matter which choice we pick. Both choices are valid. Neither choice will lead to more bugs or programmer errors. So, we just need to *pick something*.

What exactly are you proposing? That we change the rule and force 100K+ monthly users to change all their code? Sorry - not happening.

You're free to use another style guide, to extend [eslint-config-standard](https://github.com/feross/eslint-config-standard), or even to fork `standard` if this issue matters that much to you.

**Comment by dcousens** [comment]
Alternatively, just use arrow functions and you won't even know :smile:
