### ISSUE TITLE
Allow multiple spaces before `=` in variable declarations with standard config

### ISSUE THREAD

**Issue by nmai** [feross/standard#312]
I like to match my `=` assignment operators when declaring multiple variables at once, like so:
```javascript
var from    = data.from
var to      = data.to
var subject = data.subject
var cc      = data.cc
var body    = data.envelopeFrom.text
```
This is the Standard style version:
```javascript
var from = data.from
var to = data.to
var subject = data.subject
var cc = data.cc
var body = data.envelopeFrom.text
```

Is there a way we can allow for this type of behavior without disabling the `no-multi-spaces` rule?

**Comment by feross** [comment]
Please see: https://github.com/feross/standard#i-disagree-with-rule-x-can-you-change-it

If you feel really strongly about aligning your `=` signs, you can use [ESLint](http://eslint.org/) directly and extend [eslint-config-standard](https://github.com/feross/eslint-config-standard) to override this rule.

**Comment by nmai** [comment]
Fair enough, just thought I'd ask.

**Comment by arminrosu** [comment]
@feross could you elaborate on the reason for this rule, why did you set it like that? e.g. "it is simpler & faster to lint".

**Comment by yoshuawuyts** [comment]
From the [FAQ](https://github.com/feross/standard#i-disagree-with-rule-x-can-you-change-it):
> At the end of the day you have to 'just pick something', and that's the whole philosophy of standard -- its a bunch of sensible 'just pick something' opinions.

Please refrain from reviving old issues like this - it's not particularly appreciated. I hope this answers your question though! If you have any other questions you're welcome to open a new issue. Cheers!

**Comment by feross** [comment]
Some practical reasons for not aligning equals signs are:

- aligning equals signs takes time
- doesn't improve program correctness
- it's a lot of work to do by hand without the help of an IDE or text editor plugin
- if you add a longer variable name to the list, then every single item needs to be realigned, creating more work
