### ISSUE TITLE
use double quotes in jsx content?

### ISSUE THREAD

**Issue by leecade** [feross/standard#315]
I think `double quotes` is better, this code is html-like and the code with `double quotes` which auto generated by editor

```jsx
class User extend Component {
  render () {
    return <div className="class">
    </div>
  }
}
```

**Comment by dcousens** [comment]
Doing this would be a major breaking change for me, and inconsistent with our general style.
-1.

**Comment by rstacruz** [comment]
also, it offers no benefit. html supports single-quotes just fine. -1.

**Comment by leecade** [comment]
@dcousens ok, let me see how to change the rule of emmet

**Comment by dcousens** [comment]
`emmet`?

**Comment by leecade** [comment]
@dcousens yeah I use Emmet write jsx
