### ISSUE TITLE
standard gets confused with es6 getter/setter

### ISSUE THREAD

**Issue by diasdavid** [feross/standard#316]
It seems that when `standard --format`catches a es6 getter/setter, it changes its format and than reports a codestyle error, see example below

```JavaScript
var log = ['test']
var obj = {
  get latest () {
    if (log.length === 0) return undefined
    return log[log.length - 1]
  }
}
console.log(obj.latest)
```

The right space was there, but then

```bash
» standard --format troll.js
standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  /Users/david/Documents/code/standard-troll/troll.js:3:13: Missing space before function parentheses.
``` 

Fixing the problem and running `standard` returns no errors, but then if `standard --format`is executed, it will remove the space again and report an error

**Comment by meowlab** [comment]
Hi, I ran into this issue too, it's annoying, any updates?

**Comment by bcomnes** [comment]
Its an issue with [standard-format](https://github.com/maxogden/standard-format) and not standard (which just does the linting).    ES6 support on the formatter is poor at the moment.  PRs and new contributors welcome/wanted!  @diasdavid if you have time can you move this issue over there?  If not I can grab it later.  

I've only had time to peck away at it slowly, and there are definitely going to be some upstream PRs needed to get full ES6 support.

**Comment by feross** [comment]
Moved this issue: https://github.com/maxogden/standard-format/issues/138
