### ISSUE TITLE
error'ing when `npm i standard -g`

### ISSUE THREAD

**Issue by diasdavid** [feross/standard#319]
When installing globally, I get the following error:

```
npm WARN install:concat-stream@1.5.1 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/standard/node_modules/standard-engine/node_modules/eslint/node_modules/concat-stream' -> '/usr/local/lib/node_modules/standard/node_modules/concat-stream'
```

Seems to be a problem coming from the last concat-stream version, I got a similar problem weeks ago with `npm-release`, which was caused by a 'bad publish' (?? I don't have the complete explanation, other than bumping the patch version and publishing again solved the issue)

**Comment by yoshuawuyts** [comment]
@diasdavid what version of Node and npm are you running?

**Comment by diasdavid** [comment]
```bash
» node -v
v4.2.1
» npm -v
3.3.10
```

**Comment by derduher** [comment]
Experienced the same, re ran the install and it worked fine the second time. First time standard command was definitely borked. 
v4.2.2, 3.3.12

**Comment by feross** [comment]
This is a weird issue. But it looks like it was just a temporary npm glitch. Going to close it. If this comes up again, feel free to comment or open a new issue!
