### ISSUE TITLE
Bug: ~/.eslintrc being taken into account for rules not defined in rc/.eslintrc

### ISSUE THREAD

**Issue by Flet** [feross/standard#32]
To reproduce, create a ~/.eslintrc file with this in it:
```json
{
  "rules": {
    "no-var": 2
  }
}
```

Next, checkout the latest copy of `standard` and run `npm test`. You'll see many errors and the test will fail. This seems to be a feature of eslint: http://eslint.org/docs/configuring/#configuration-cascading-and-hierarchy

Note that this only affects rules that are not yet defined in rc/.eslintrc due to the layering/cascading nature. I see two possible solutions:
- define every rule in rc/.eslintrc to stop the possibility of cascading
- figure out a way to explicitly turn off the cascading feature when calling eslint.

Maybe @nzakas knows if there is a flag to stop this behavior? I did not see one in the command line options or on the linked configuration page.

The only workaround for users would be to remove any .eslintrc files from their directory hierarchy, which is probably not acceptable.

**Comment by feross** [comment]
I went ahead and defined every rule, for completeness. Looks like the `--no-eslintrc` option would have done the trick too.

Released as 2.5.0.

**Comment by Flet** [comment]
Ah cool totally missed that option! Assuming this also disables package.json stuff too? Will investigate myself :)
