### ISSUE TITLE
Does it support JSX?

### ISSUE THREAD

**Issue by xwartz** [feross/standard#322]
I wonder if it supports/works with JSX?
Thanks.

**Comment by JHKennedy4** [comment]
+ CSS modules in JSX? I seem to either get an unused var error, or a JSX value should be an expression or quoted JSX text.

**Comment by capaj** [comment]
I have a react project with JSX syntax and it works beautifully, though all my sources are .js files, not .jsx

**Comment by dcousens** [comment]
Standard does support JSX.

**Comment by xwartz** [comment]
https://github.com/maxogden/standard-format/issues/99
