### ISSUE TITLE
standard rejects a common use case for the `while` loop

### ISSUE THREAD

**Issue by 75lb** [feross/standard#324]
this is one of the most common use cases for the `while` loop:
```js
  while (value = getValue(something)) {
    ...
  }
```
unfortunately, standard rejects it (`Expected a conditional expression and instead saw an assignment.`) Is there any particular reason?

**Comment by LinusU** [comment]
Wrap it in double parenthesis to explicitly say that you want assignment. This is a great rule since it catches errors where you've missed an equal sign.

```javascript
while ((value = getValue(something))) {
  ...
}
```

**Comment by dcousens** [comment]
Doesn't make it any less confusing IMHO.  I guess the following is an alternative anyway:

``` javascript
while (true) {
  value = getValue(something)
  if (!value) break
}
```

**Comment by feross** [comment]
@dcousens I've seen the double-paren frequently used as a way to indicate you meant assignment not an equality test. But I agree that this code is generally best avoided. Sometimes though, it's the cleanest way to solve a problem.

**Comment by 75lb** [comment]
well we have two suggested alternative styles but we need one-to-rule-them-all, so let's go with @LinusU 's approach :+1:

**Comment by dcousens** [comment]
@75lb well, you can't rule the latter out, as it is a valid construct in some many different cases.
Compare that to the approach by @LinusU, which is only useful in this one case.

I'm OK with either, just pointing that out.

**Comment by feross** [comment]
Yeah, both approaches are perfectly fine :)

**Comment by rstacruz** [comment]
i just realized the double-parens rule is not documented... we should fix that

**Comment by rstacruz** [comment]
it might be helpful to point out that this is common in `if` conditions too:

```js
if (m = text.match(/...*?/) {
  // ...
} else if (m = text.match(/...*?/) {
  // ...
} else {
  // ...
}
```

**Comment by feross** [comment]
@rstacruz Yep, agree. Do you want to send a PR?
