### ISSUE TITLE
remove non npm dependency

### ISSUE THREAD

**Issue by mafintosh** [feross/standard#326]
Somewhere in the dependency something is depending on the tarball hosted here

```
https://github.com/royriojas/fresh-falafel/tarball/fix-parse-issue
```

This is currently breaking offline installs using the local npm cache. Is there anyway not to depend on this?

**Comment by mafintosh** [comment]
This is breaking my :airplane: development flow :)

**Comment by feross** [comment]
Filed an issue for you: https://github.com/royriojas/esformatter-jsx/issues/40

**Comment by mafintosh** [comment]
@feross :+1:

**Comment by yoshuawuyts** [comment]
Ahhhhh, this is grand!

**Comment by feross** [comment]
This is fixed now!
