### ISSUE TITLE
Standard Stickers!

### ISSUE THREAD

**Issue by Flet** [feross/standard#330]
We made some stickers!

![image](https://d21ii91i3y6o6h.cloudfront.net/gallery_images/from_proof/9318/large/1447300166/javascript-standard-code-stype.png)
https://www.stickermule.com/marketplace/9318-javascript-standard-code-style

We would like to make sure all contributors get a sticker. If you've contributed to `standard`, I'll snail mail a sticker to you! Add your address here and I'll send one out soon: http://postable.com/standardstickers

**Comment by dcousens** [comment]
Awesome @Flet

**Comment by feross** [comment]
:+1: :+1: :+1:

**Comment by watson** [comment]
I have to complain! This is not a [standard sticker](http://terinjokes.github.io/StickerConstructorSpec/) :stuck_out_tongue_winking_eye:

**Comment by feross** [comment]
We're in the business of creating new standards, not following existing ones!

**Comment by feross** [comment]
Jk, for real, I'd like a hexagon sticker if someone wants to make one. Maybe it should just be a hexagon with a semicolon on it.

**Comment by dcousens** [comment]
@feross here here on the 2" hexagon standard.

**Comment by rstacruz** [comment]
> with a semicolon on it

no

**Comment by feross** [comment]
What about a semicolon with a red slash through it?

**Comment by dcousens** [comment]
![example1](https://1.bp.blogspot.com/-p8KRe1GqabM/UIS0VsMvAGI/AAAAAAAABJo/GElmXVgas2E/s1600/semicolon+cross.png)

![example2](http://www.johnoakeswrites.com/wp-content/uploads/2015/04/No-Semicolons-Allowed.jpg)

Not sure

**Comment by tzmanics** [comment]
because with standard your styling problems are as clear as black & white...😁
![badge-hex](https://cloud.githubusercontent.com/assets/3611928/11256772/e14b4624-8e1b-11e5-8735-97723c082655.png)

I have the svg if you like it but I'd be happy to tweak too.

**Comment by bcomnes** [comment]
I dig it!

**Comment by dcousens** [comment]
@tzmanics nice!  Would love the SVG too

**Comment by tzmanics** [comment]
cool, made a pull request w both svg & png

**Comment by watson** [comment]
Thanks @Flet :tophat: :smile: :tada: 

![img_8162](https://cloud.githubusercontent.com/assets/10602/11285065/69df8c38-8ec2-11e5-819b-fb074b9b2287.jpg)
![img_8163](https://cloud.githubusercontent.com/assets/10602/11285064/69dec01e-8ec2-11e5-9211-9b1c02b337b9.jpg)
![img_8165](https://cloud.githubusercontent.com/assets/10602/11285063/69dc7fa2-8ec2-11e5-9415-e69cbfa35f8d.jpg)

**Comment by Flet** [comment]
Excellent! :metal:

**Comment by ngoldman** [comment]
:metal: :neckbeard: :metal:

**Comment by feross** [comment]
What about this?

![standard 3x](https://cloud.githubusercontent.com/assets/121766/11316733/02ade7b0-8fc8-11e5-88f9-8858213841ab.png)

**Comment by ngoldman** [comment]
Most standard indeed!

**Comment by watson** [comment]
@feross :+1:

**Comment by jden** [comment]
\m/ stickers

**Comment by mcdonnelldean** [comment]
I need these in my life :D Are ye uploading them anywhere that will print worldwide? (Ireland here)

**Comment by Flet** [comment]
@mcdonnelldean you can order them in bulk from [stickermule.com](https://www.stickermule.com/marketplace/9318-javascript-standard-code-style) and they will ship internationally.

If you want just one, I'll eat that $1.20 stamp and send one to you :)

**Comment by mcdonnelldean** [comment]
Awesome!! Do you get a kickback from stickermule? If so I'm happy to buy a bunch and give them out when I talk and that, it's a nice way to get people chatting :D I'm sure I can sneak them in as an expense :D

**Comment by Flet** [comment]
Its set to 0% markup on stickermule, so no profit is happening (other than stickermule).

The pricing is exactly the same as what I paid for my run... so 500 stickers is about $103 USD (and looks like international shipping would add $29).

**Comment by mcdonnelldean** [comment]
Perfect! Thanks :D

**Comment by dcousens** [comment]
@feross they would meld well with my tile set up :+1: ,  please make it a thing.

**Comment by feross** [comment]
I just sent a PR with two new designs: https://github.com/feross/standard/pull/365

![standard-outline-white](https://cloud.githubusercontent.com/assets/121766/11915779/826b4294-a71b-11e5-88d5-43ed7554ca79.png)

![standard-outline](https://cloud.githubusercontent.com/assets/121766/11915780/835fd0ca-a71b-11e5-8b15-9e19d426678f.png)

**Comment by feross** [comment]
Just printed 500 of these standard stickers:

![standard](https://cloud.githubusercontent.com/assets/121766/12633750/6f953e00-c574-11e5-969a-e2c252d12ae0.png)

Look out for me at conferences and meetups to pick one up for free! If you've contributed to standard, send a message to my email (on my github profile) with your mailing address and I'll send you one for free!

If you just want to buy one for yourself, here's a link to get one from StickerMule: https://www.stickermule.com/en/marketplace/10199-javascript-standard-style

(I added no markup, so the price is just what StickerMule charges to print the stickers and it goes entirely to them)

**Comment by feross** [comment]
Stickers just arrived! See https://github.com/feross/standard/issues/398 !
