### ISSUE TITLE
Difference in `function *` vs `yield*`

### ISSUE THREAD

**Issue by simonratner** [feross/standard#335]
In `function * () {}`, the star is special-cased as a generator star, requiring spaces on both sides. 
In `yield* fn()`, the star is considered part of the unary operator `yield*`, prohibiting space before it.

In fact, both are expressions, and mirror corresponding `function` and `yield` expressions, so the inconsistency seems strange. Does it make sense to treat the star in `yield*` as a generator star as well?

**Comment by feross** [comment]
Thanks for opening this issue. Now that eslint 2.0.0 has the [`yield-star-spacing`](http://eslint.org/docs/2.0.0/rules/yield-star-spacing) rule we can be consistent about this and enforce a space on both sides.

This will be released in `standard` v6.

**Comment by feross** [comment]
Adding this rule only breaks 2 repos in the test suite:

```
1..427
# tests 427
# pass  425
# fail  2
```

LGTM

**Comment by feross** [comment]
Actually one. The other's due to something else I changed locally :)
