### ISSUE TITLE
standard -F doesn't fix space-before-function-paren in class

### ISSUE THREAD

**Issue by mblakele** [feross/standard#337]
Test case:

```
const ServerBase = require('./server-base')

class ExternalServer extends ServerBase {

  getServerConfig() { return this.config.server.external }

  initRoutes() { require('./routes/external')(this.app) }

  getServerType() { return 'external' }
}

module.exports = ExternalServer
```

Running `standard -F` 5.4.1 I see three `space-before-function-paren` errors, but they aren't automatically fixed. Other minor problems like indent size and eol-last are fixed.

**Comment by bcomnes** [comment]
Moving to https://github.com/maxogden/standard-format/issues/126
