### ISSUE TITLE
poor indentation of object notation

### ISSUE THREAD

**Issue by mblakele** [feross/standard#339]
Running `standard -F` (5.4.1) produces this:

```
  fubar ({a, b}) {
    baz('test', {
      a,
    b})
  }
```

Running standard on the same file reports `Expected indentation of 6 space characters but found 4  indent`

**Comment by bcomnes** [comment]
We are blocked upstream on esformatter on a bunch of ES6 things.  Also moving this over to the `standard-format` repo.

**Comment by bcomnes** [comment]
Moved to https://github.com/maxogden/standard-format/issues/129
