### ISSUE TITLE
Codeclimate engine

### ISSUE THREAD

**Issue by jden** [feross/standard#342]
This is not a feature request for the `standard` cli repo, but rather an enhancement idea for the standard community.

Codeclimate is a popular code quality tool that integrates with github PRs. It supports add-on "engines" via Docker containers. The spec is https://github.com/codeclimate/spec

I'm interested in working on this, but not sure when I'll find the time. Is anyone else interested in this, either in developing or testing?

**Comment by bcomnes** [comment]
Getting standard into code climate would be great!

**Comment by feross** [comment]
I'm not super familiar with docker, but I'm happy to test this.

**Comment by jden** [comment]
I started by making a formatting module to output things in the format that CodeClimate is expecting: https://www.npmjs.com/package/standard-codeclimate

Next step would be to fiddle with the docker stuff. I'll get to it as I have spare time, but if anyone else wants to take the initiative, feel free :)

**Comment by Flet** [comment]
Nice @jden! It should not be difficult to dockerize this at all! I'll try to find time to play.

**Comment by feross** [comment]
Do folks still have interest in this?

**Comment by jden** [comment]
I'd be interested. Currently I have standard running in my travis ci tests and codeclimate running as a separate github integration. Not a huge deal, but nice to see the different between test errors and style / lint errors when reviewing PRs. Codeclimate has a first-party jslint or eshint or whatever engine, but I disable it.

**Comment by feross** [comment]
Looks like there's support for `standard` in codeclimate now. See:

- https://github.com/sfbrigade/brigadehub/pull/328#issuecomment-223775623
- https://github.com/codeclimate/codeclimate-eslint/pull/95

I think this can be closed now, right?

**Comment by martinheidegger** [comment]
I think this needs to be reopened. I tried standard with code climate and the suggested setup uses eslintrc which is not at all cool for following reasons:

1. `eslint-plugin-standard`, etc. require eslint@3 which in turn requires node@>4 which means my lint tests don't run in node@0.12 :cry: 
2. Not having to setup a eslintrc and a eslintignore and adding three lines to my package.json is the reason why I ~~like~~ love standard.

**Comment by feross** [comment]
@martinheidegger I think you might be right - that doesn't sound very easy to use!

I think this issue should be taken up directly with the codeclimate team. I don't know how codeclimate works because I don't use it. This is most likely to get fixed if it's championed by someone who understands the issue better. Feel free to post updates to this issue to keep other codeclimate users like @bcomnes and @jsdnxx up-to-date so they can leave their thoughts in the issue too.

**Comment by bcomnes** [comment]
I'm not using code climate at the moment, so my motivation is low for the time being.
