### ISSUE TITLE
Classes and Missing space before function parentheses. (space-before-function-paren)

### ISSUE THREAD

**Issue by yormi** [feross/standard#346]
Ok, I'm not sure if it's the right place to post the issue but I haven't manage to determine if the problem lies in standard or eslint or babel-eslint... maybe you could help me !

Same problem than posted here(https://github.com/feross/standard/issues/59). I tried to test with Eslint using the rc/.eslintrc of this project but I'm still confuse with all that.

    class foo {
        somefunction () {
        }
    }

giving:
`Missing space before function parentheses. (space-before-function-paren) `

In package.json:
>"standard": {"parser": "babel-eslint"}

**Comment by Flet** [comment]
I don't think setting the parser to babel-eslint is required anymore.

When I take the code above and paste it into http://standardjs.com/demo it comes back valid with no errors.

Could you try reinstalling the latest version of standard and testing again?

**Comment by yormi** [comment]
Everything is up-to-date. I reinstalled Standard just in case but no difference. Still the same error that indeed doesn't appear on the standardjs demo page.

For the parser, without it, I have weird stuff like an `Parsing Error: Unexpected token function` when I use that great async keyword.

**Comment by yormi** [comment]
Ah ha ! Just found the problem ! I'm using vim as well as the auto-format taken from the readme:
    autocmd bufwritepost *.js silent !standard % --format
    set autoread

It was actually removing the space between the function name and the `()` without refreshing the buffer. Got lucky to notice it. 

I guess the problem would rely in the formatter then... and maybe some change to the vim autoformat command would help detect other potential future error ?

**Comment by yura415** [comment]
Does standard actually support ES6 features that are now part of the stable node.js build?


```js
export class Foo {
  constructor (bar) {
    this.baz(bar)
  }
  baz (bar) {
    console.log(bar)
  }
  test () {
    console.log('test')
  }
}

```

Using this code snippet with [standardjs.com/demo](http://standardjs.com/demo), "Format" button not giving a correct result:
```js
export class Foo {
  constructor( bar) {
    this.baz(bar)
  }
  baz( bar) {
    console.log(bar)
  }
  test() {
    console.log('test')
  }
}

```

Of course after code was formatted, linter reports errors. Thats an incorrect behaviour.

Same story with the object shorthand:
```js
let test = {
  foo () {
    console.log('foo')
  }
}

test.foo()

```

After format, becomes the
```js
let test = {
  foo() {
    console.log('foo')
  }
}

test.foo()
```
Generating new "Missing space before function parentheses" error.

**Comment by lipp** [comment]
+1 same problem as @yura415: the formater messes up the parentheses spacing.

**Comment by pnw** [comment]
+1 getting the same thing. The formatter breaks the subsequent lint.

**Comment by feross** [comment]
Yeah, the formatter has issues with some ES6 features. You can help fix these issues by contributing to the [`standard-format`](https://github.com/maxogden/standard-format) project! It will get better with time.

This issue is already open on that issue tracker: https://github.com/maxogden/standard-format/issues/134
