### ISSUE TITLE
React Code Style not applied when extending React.Component subclass

### ISSUE THREAD

**Issue by saschagehlich** [feross/standard#347]
Let's say I have a `BaseComponent`, like this:

```js
import React from 'react'

export default class BaseComponent extends React.Component {
  render () {
    return <div />
  }
}
```

And another class extending this `BaseComponent`:

```js
import BaseComponent from './base-component'
class MyComponent extends BaseComponent {
  render () {
    return <div>{this.props.content}</div>
  }
}
```

Of course `standard` can't know that this is a `ReactComponent` and should comply with the React Code Style (e.g. prop types), since it's extending `BaseComponent` instead of `ReactComponent`. But is there a way to tell `standard` that `MyComponent` is a `ReactComponent`?

**Comment by feross** [comment]
Not sure - there may be a way to accomplish what you want, but you should re-open this as an issue on https://github.com/feross/eslint-config-standard-react.

React-specific rules will be removed from `standard` in v6. You can use `standard-react` which we'll publish when v6 comes out.
