### ISSUE TITLE
Add optional capability to add more restrictive rules.

### ISSUE THREAD

**Issue by ericwooley** [feross/standard#349]
I'm on board with standard, but there are some rules that I want that standard doesn't enforce. I propose a merge of standard with eslint options, where standard overwrites eslintrc rules, but allows additional rules to be enforced. For example I would like to use [no-long-files](https://www.npmjs.com/package/eslint-rules#no-long-files) but don't think it should be included as a standard, because it's too difficult to determine an appropriate size, yet it's very difficult to enforce this rule without two linters fighting eachother.

Standard is great, but it's too hard to use in combination with eslint. Life would be considerably easier if standard respected additional eslint rules that don't conflict with the standard rules. This wouldn't conflict with standards goal, because a more restricted ruleset still satisfies the standard requirements.

**Comment by reg4in** [comment]
:+1:

**Comment by bcomnes** [comment]
What about using eslint directly, while extending the standard rule set? https://github.com/feross/eslint-config-standard  Would that work?

**Comment by dcousens** [comment]
@bcomnes has proposed the suggested solution for dealing with this.

:+1: , closing.

**Comment by feross** [comment]
Yep, as @bcomnes suggests, just add this to your `.eslintrc` and customize away!

```js
{
  "extends": "standard"
}
```
