### ISSUE TITLE
Blocks should have one blank line at the beginning and the end

### ISSUE THREAD

**Issue by andyfleming** [feross/standard#350]
I see that the padding-blocks rule was based on the [padded blocks rule in ESLint](http://eslint.org/docs/rules/padded-blocks).

It states:
> Some style guides require block statements to start and end with blank lines. The goal is to improve readability by visually separating the block content and the surrounding code.
>    ```
>    if (a) {
>    
>         b();
>    
>    }
>    ```
>
> Since it's good to have a consistent code style, you should either always write padded blocks or never do it.

I would propose that code is more readable with single-line-padding inside blocks. Why did we decide to enforce no padding as opposed to single-line padding?

**Comment by dcousens** [comment]
Well, I'll counter-propose your proposal!
I guess that puts us back at the status quo.  Welp,  I guess we'll just stick with the decision already done.

**Comment by andyfleming** [comment]
Haha, fair enough.

I ended up using the [standard extension for ESLint](https://github.com/feross/eslint-config-standard) instead.

After reading more, I understand that the point of standard is to just choose something. While I generally support that notion and the idea that consistency across projects is nice, I think usability has to come first. ESLint is the right fit for us. We'll use standard as the starting point, and adjust from there.

Using ESLint directly actually opens up integrations in the JetBrains editors too. So even if I were going to use standard as-is, I would probably install it via the ESLint plugin instead.

**Comment by dcousens** [comment]
Awesome,  the way you've resolved it is exactly how it should be: :+1: .  Even if its only a few additions of your own, it means if someone has used standard before, they'll be most of the way there before they even start :+1: .

**Comment by dcousens** [comment]
> After reading more, I understand that the point of standard is to just choose something.

Unfortunately,  style is something where you do just have to choose something, and usability/readability is absolutely in the eye of the beholder, otherwise we'd of converged on a solution sooner for all this.

Don't get me wrong, the style choices in `standard` weren't randomly chosen,  it just simply doesn't appeal to everyone.

**Comment by andyfleming** [comment]
> Even if its only a few additions of your own, it means if someone has used standard before, they'll be most of the way there before they even start.

I agree. I think it's beneficial to try to keep close.

> Don't get me wrong, the style choices in standard weren't randomly chosen, it just simply doesn't appeal to everyone.

That's fair. The block spacing was the only change that felt out of place to me.
