### ISSUE TITLE
nsp

### ISSUE THREAD

**Issue by mightyiam** [feross/standard#357]
https://www.npmjs.com/package/eslint-plugin-security

I'm not familiar with the rules themselves. Not have I used it.

Just throwing it in here.

Conceptually, security as a standard fits right in my mind.

**Comment by LinusU** [comment]
> Probably not something you want to just toss and leave in a project. It will help identify potential security hotspots, but finds a lot of false positives that needs triaged by a human.

**Comment by mightyiam** [comment]
Oh right
