### ISSUE TITLE
Assigning to multiple variables in one line throws error

### ISSUE THREAD

**Issue by timwis** [feross/standard#359]
```javascript
var $ = jQuery = require('jquery')
```
I use this to accommodate bootstrap.js in browserify. It throws the error `"jQuery" is not defined`.

Have I misunderstood what this does in JavaScript this whole time? I'm under the impression that it sets both `$` and `jQuery` to the value of `require('jquery')`.

**Comment by Flet** [comment]
That is totally valid JS!

`standard` uses the eslint rule [no-undef](http://eslint.org/docs/rules/no-undef.html) which disallows variables that are not explicitly defined. This helps avoid leaking global variables accidentally.

If defining `jQuery` as a global variable is whats intended, then just add a hint at the top of the file:
```js
/* global jQuery */
var $ = jQuery = require('jquery')
```
If it should not be global, just declare it: 
```js
var jQuery
var $ = jQuery = require('jquery')
```

even this is valid in `standard` too... Maybe its more visually appealing:
```js
var $, jQuery
$ = jQuery = require('jquery')
```

Its also possible to add a "standard" attribute to `package.json` to define globals for your project:
```js
"standard": {
"globals":["jQuery"]
}
```
This would make your original code work without issue in all your files.


I'm going to close this issue for now, but feel free to comment if you have questions/concerns!

**Comment by rstacruz** [comment]
If I may add,

```js
var $ = jQuery = require('jquery')
```

is the same as:

```js
var $ = (jQuery = require('jquery'))
```

which unrolls to:

```js
jQuery = require('jquery')
var $ = jQuery
```

...which is what standard complains about: declaring jQuery as a global. However, this is fine:

```js
var jQuery = require('jquery')
var $ = jQuery
/* ✓ ok */
```

or this:


```js
var $, jQuery
$ = jQuery = require('jquery')
/* ✓ also ok */
```

**Comment by timwis** [comment]
Thanks so much guys - I always assumed it was _declaring_ the second var, but I totally see how it wouldn't. I appreciate the detailed explanation and options!
