### ISSUE TITLE
Nested glob expander doesn't work across platforms

### ISSUE THREAD

**Issue by h2non** [feross/standard#364]
The following glob patterns doesn't work as expected in OSX and Linux:
```bash
standard lib/**/*.js test/**/*.js
```
Expected to the processed:
```
lib/index.js
lib/folder/index.js
lib/folder/subfolder/index.js
```

However, it's only processed:
```
lib/folder/index.js
lib/folder/subfolder/index.js
```

I've been forced to fix it passing the following params:
```bash
standard lib/*.js lib/**/*.js test/*.js test/**/*.js
```

I realized that in Windows the glob patterns behaves properly, which is a bit disquieting.
Perhaps might be an issue of `deglob` package.

I'm running the latest version of `standard`.

**Comment by rstacruz** [comment]
It might be an issue in your shell.  /**/* is not supported in bash.

**Comment by h2non** [comment]
@rstacruz You're right, after wrapping it with quotes, it works. I'm running it from `npm scripts`, and I've assume that the arguments are properly passed to the shell binary.
