### ISSUE TITLE
Uglify or Minimify the standard js files

### ISSUE THREAD

**Issue by juliomatcom** [feross/standard#366]
Hello,
Sorry, this is not a real issue, just a concern, what do you suggest to minimify or uglify the js files without the semicolons ? any package or some thing in the comunity?

Thank you

**Comment by bcomnes** [comment]
I would stay away from any minification tool or uglify tool that does not ensure correct ASI during its transform.  Semicolons are a necessary for those types of tools to work.  So the answer is... any of them (that work presumably)!

Personally I would look for one that works well with my build step via browserify e.g. https://github.com/hughsk/uglifyify (not I have not used this or endorse it, but it looks like something I would try out).

**Comment by rstacruz** [comment]
Any modern minification tool would suffice. Most today would parse based on
AST. These two are what most would use:

- uglifyjs
- Closure compiler

**Comment by juliomatcom** [comment]
Is possible to get the original ASI that use javascript engine with some api ? 
I would give a try to this libs 
There is any mailing list to send or share the results.. a mailing about standard js ?

Thanks

**Comment by bcomnes** [comment]
I have not heard of a module or API that lets you patch in directly to V8's ASI capabilities.  Googling, I came across http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding which actually addresses your first question:

> Yes, [ASI is] quite safe, and perfectly valid JS that every browser understands. Closure compiler, yuicompressor, packer, and jsmin all can properly minify it. There is no performance impact anywhere.
-- http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding

We have https://github.com/Flet/semistandard for people working on projects that need semicolons for political or style reasons.  Not sure if that helps.

If you come up with anything cool that you want to share just open up an issue or hop onto #standard on freenode.

**Comment by juliomatcom** [comment]
+1 thanks @bcomnes

**Comment by rstacruz** [comment]
> Is possible to get the original ASI that use javascript engine with some api ? 

This might help: http://esprima.org/demo/parse.html#

**Comment by feross** [comment]
All the popular minification tools will work just fine on code that passes `standard`. No need to worry.
