### ISSUE TITLE
Standard doesn't like ES6 destructuring?

### ISSUE THREAD

**Issue by nkcmr** [feross/standard#37]
Standard will fail when given ES6 destructuring assignments:
![-projects-owwle-www-public-static-js-src-modules-composer js owwle sublime text today at 11 39 59 pm](https://cloud.githubusercontent.com/assets/1791521/6281520/df8912d2-b890-11e4-97cd-f8d924885bc7.png)

Is it supposed to do this?

**Comment by feross** [comment]
It looks like destructing support has landed in `espree`, `eslint`'s parser, but it hasn't been published to npm yet. See: https://github.com/eslint/espree/commit/04e7a44a06e4b1e782d5acc2f0e7b615a7792870

They publish new versions every few weeks, so this issue should fix itself when they publish the next version!

(cc @nzakas, eslint maintainer)

**Comment by nkcmr** [comment]
Ahh. I will now be watching `eslint` releases like a hawk. Thank you @feross.

**Comment by feross** [comment]
No problem :)

**Comment by feross** [comment]
Just published `standard` 2.8.0 which supports destructuring, as well as rest params and the spread operator!

**Comment by yoshuawuyts** [comment]
@feross :tada::tada::tada::tada:
