### ISSUE TITLE
Double colon (::) operator

### ISSUE THREAD

**Issue by flipjs** [feross/standard#370]
I downloaded a boilerplate from TJ Holowaychuk and he is using :: operator like this ::this.onClick . I guess it has the same effect as this.onClick.bind(this).

My vim editor complains about this and the message is "Parsing error: Unexpected token : (undefined)" .  Is this being added to standard? Or does eslint even support this yet?

Here's the link to TJ's code:

https://github.com/tj/frontend-boilerplate/blob/master/client/components/Header/index.jsx

**Comment by jprichardson** [comment]
This is a ES7 feature. You need to use the custom parser, `babel-eslint`. See: http://standardjs.com/index.html#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support
