### ISSUE TITLE
Add "env" config to package.json

### ISSUE THREAD

**Issue by gsklee** [feross/standard#371]
As a continuation of #18, can we add this?

```json 
{
  "standard": {
    "env": "mocha"
  }
}
```

IMHO it's better than either adding `/* eslint-env mocha */` to all test files, or adding:

```json 
{
  "standard": {
    "globals": ["beforeEach", "describe", "it", ...]
  }
}
```

**Comment by dcousens** [comment]
IMHO, if `/* eslint-env mocha */` is a thing, than this is exactly what should be added to all test files.
I don't think blanket application of a `mocha` env to an entire project is acceptable unless it is 100% applicable.

**Comment by rstacruz** [comment]
bad, mocha. one of the reasons I don't use mocha anymore. :p

**Comment by dmitriz** [comment]
@rstacruz What is better than mocha?

**Comment by rstacruz** [comment]
I personally prefer tape, but that's just me.

Anyway, IMHO this is most certainly doable. Eslint itself has support for environments defined here: http://eslint.org/docs/user-guide/configuring#specifying-environments. These look particularly useful:

- browser
- worker
- mocha
- ...

**Comment by rstacruz** [comment]
Also, @feross, this might be worth documenting:

```js
/* eslint-env mocha */
```

...will consider describe/it/beforeEach/etc as predefined globals.

**Comment by dcousens** [comment]
I guess if it is basically just a direct pass-through for a common eslint feature, then I'm not against it.

**Comment by dcousens** [comment]
Though,  IMHO `/* eslint-env mocha */` is a better pattern than `package.json` defined configuration.

**Comment by rstacruz** [comment]
yes, i agree. there's also the possibility of this:

```json
{
  "scripts": {
    "lint": "standard 'lib/*.js'; standard 'test/**/*.js' --env mocha"
  }
}
```

**Comment by dcousens** [comment]
@rstacruz that I would agree with a lot more than the blanket suggestion.

**Comment by dmitriz** [comment]
@rstacruz Seems like they require to write this in every single test file:
> You always need to `require('tape')` in test files.

Grows old very fast, imo.

**Comment by rstacruz** [comment]
dmitriz: i know this is off tangent in the conversation now, but that's precisely why I like it. It means your tests are runnable on their own (`node test/foo.js`), and perfectly browserifyable (`browserify test/index.js`). This opens up the opportunity to do a lot of things:

```sh
node test    # run in node.js
browserify test | smokestack -b firefox  # run in headless browser
hihat test  # run in electron (hihat is browserify-awake)
budo test  # run in browser (budo is, too)
```

**Comment by dmitriz** [comment]
@rstacruz I see, interesting, have you seen ava - that looks similar!

**Comment by gsklee** [comment]
@rstacruz Interesting info ;-)

**Comment by feross** [comment]
@rstacruz +1 to `tape` and being unfancy and explicit.

It's not worth saving one line if you break compatibility with everything. All tooling has to add custom support for mocha and know about the exact list of globals that mocha assumes. Not a good tradeoff.

**Comment by feross** [comment]
That said, we'll support passing through this option to `eslint`, like we've done for the other options.

**Comment by feross** [comment]
PR to `standard-engine` to add support for the `--env` option: https://github.com/Flet/standard-engine/pull/58

This will be released in standard v6.

**Comment by feross** [comment]
Works in `package.json`:

```json
{
  "standard": {
    "env": {
      "mocha": true
    }
  }
}
```

And the command line:

```
standard --env mocha test/*.js
```
