### ISSUE TITLE
TypeError: (intermediate value)(...) is not a function

### ISSUE THREAD

**Issue by homerjam** [feross/standard#373]
This error pops up when you concat/uglify files and theres a missing semicolon between files. This happens frequently (not everyone includes a semicolon at the start of their files) when using other libs etc.

Can you add a semi colon at the end of the file too to prevent this?

eg.

```
;(function () {
    // code here
})(); // <--- add this semicolon

**Comment by rstacruz** [comment]
(); // eslint-disable-line semi

**Comment by feross** [comment]
You can do what @rstacruz suggests to disable the rule in your file.

**Comment by homerjam** [comment]
Great thanks
