### ISSUE TITLE
Basis for `no-self-compare`?

### ISSUE THREAD

**Issue by Mitranim** [feross/standard#374]
Comparing to self is the best way to test for NaN:

```javascript
const nan = NaN
nan !== nan  // => true
```

The `no-self-compare` rule included into standardjs complains about this being "potentially pointless". I think it's wrong.

**Comment by rstacruz** [comment]
Use isNaN(). 'x === x' is confusing.

**Comment by Mitranim** [comment]
Questionable advice. `isNaN` is so broken, the language now includes a  [_second_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN) version (ES2015 only). It's usable in combination with `typeof`, but verbose. Self-compare is shorter and cleaner.

**Comment by dcousens** [comment]
@Mitranim how is `isNaN` broken?
Works for me.

**Comment by bcomnes** [comment]
@dcousens the mdn link that @Mitranim posted has details on the issue I presume is the reference here.  I don't have any opinion on this matter though.

**Comment by dcousens** [comment]
Right, so `Number.isNaN` is just more strict, sure.  I wouldn't call `isNaN` broken though, as `isFinite` has the same behaviour.

**Comment by Mitranim** [comment]
By broken I mean it doesn't tell you if a value is exactly `NaN`. Here's an example where you need it.

Let's say you're implementing a deep tree comparison algorithm for something like [`emerge`](https://github.com/Mitranim/emerge). Can't use `===` for primitives because of NaN, so you'll need a `SameValueZero` comparator. Here's how it looks with `isNaN`:

```javascript
function sameValueZero (one, other) {
  return one === other ||
    typeof one === 'number' && isNaN(one)
    typeof other === 'number' && isNaN(other)
}
```

Verbose! With self-compare:

```javascript
function sameValueZero (one, other) {
  return one === other || one !== one && other !== other
}
```

**Comment by bcomnes** [comment]
Seems clever enough to warrant a function/module with some semantic value but maybe there are performance concerns. I'm `¯\_(ツ)_/¯` on this one.

**Comment by feross** [comment]
See the [rule page](https://github.com/eslint/eslint/blob/master/docs/rules/no-self-compare.md) for a more complete explanation of the rationale. This is a good default for 99%+ of users.

If you still want to use `a === a` in your code, you can just disable the rule with a comment at the top:

```
/*eslint-disable no-self-compare */
```

**Comment by dcousens** [comment]
> Are there any other situations where you would want to self compare other than this?

Nope,  and in this case,  you don't even need a comment, you can just use the `isNaN` or `Number.isNaN` functions.  Less bike shedding, instantly readable,  no floating point rules to lookup/remember.
