### ISSUE TITLE
Semicolons?

### ISSUE THREAD

**Issue by jantimon** [feross/standard#375]
**Using semicolons is the javascript community convention.**
**All** big community projects are using semicolons:

* [Babel](https://github.com/babel/babel/blob/master/packages/babel-core/index.js)
* [Node](https://github.com/nodejs/node/blob/master/lib/v8.js)
* [React](https://github.com/facebook/react/blob/master/src/React.js)
* [Angular](https://github.com/angular/angular.js/blob/master/src/Angular.js)
* [Gulp](https://github.com/gulpjs/gulp/blob/master/index.js)
* [Grunt](https://github.com/gruntjs/grunt/blob/master/lib/grunt.js)
* [Webpack](https://github.com/webpack/webpack/blob/master/lib/webpack.js)
* [jQuery](https://github.com/jquery/jquery/blob/master/src/jquery.js)
* [lodash](https://github.com/lodash/lodash/blob/master/lodash.js)
* [Modernizr](https://github.com/Modernizr/Modernizr/blob/master/src/Modernizr.js)

Even the **v8 engine itself** is using them: https://github.com/v8/v8/blob/master/src/js/array.js

Could you please give me some examples of huge projects which might pass your "standard"?

If you are using React, Angular, Node, Gulp, Grunt, Webpack, jQuery, Lodash, Modernizr, V8 (...) in the same project where you want to use `feross/standard` your brain has to switch between the real community standard and the feross/standard all the time.

**Comment by rstacruz** [comment]
* [npm](http://github.com/npm/npm)
* [bootstrap](https://github.com/twbs/bootstrap)
* [karma](https://github.com/karma-runner/karma)
* [phantomjs wrapper](https://github.com/Medium/phantomjs/blob/master/install.js)

It isn't necessarily about the number of projects though. semicolon-less JavaScript has been increasing in adoption and more and more people prefer it now.

**Comment by jantimon** [comment]
It feels more like that the coffeescript users realised that coffeescript is dying and try to keep their habits.

**Comment by yoshuawuyts** [comment]
Dupes #5, #78, #79, and #176. Check out the explanation on #78 in particular. You might find semistandard useful: https://github.com/Flet/semistandard.

See also https://github.com/feross/standard#i-disagree-with-rule-x-can-you-change-it
