### ISSUE TITLE
Support for Rails "//= require"

### ISSUE THREAD

**Issue by dalexj** [feross/standard#377]
I would love `=` be added to the allowed characters after comments to support Rails's javascript manifest file

The file has lines such as:

```javascript
//= require jquery
```

**Comment by bcomnes** [comment]
Overloading comments seems inconsistent with standards alignment with commonjs' `require` statement.  Why not just `var $ = require('jquery')` ?

**Comment by rstacruz** [comment]
I develop Rails apps for my dayjob. Sorry, getting a CommonJS require/import workflow with Rails is more trouble than its worth.

As a workaround, use this instead:

```js
/*
 *= require jquery
 *= require turbolinks
 *= require such_and_such
 */
```

**Comment by dalexj** [comment]
this works for me, thanks @rstacruz

**Comment by bcomnes** [comment]
@rstacruz thanks for the clarification.

**Comment by bcomnes** [comment]
Should we add this to the FAQ?

**Comment by rstacruz** [comment]
sure, sounds reasonable.
