### ISSUE TITLE
Rules inconsistency: function declaration and function invocation, with or without space between function name and `(`

### ISSUE THREAD

**Issue by xieranmaya** [feross/standard#379]
Function declaration:
```js
function fun (arg) { //space between fn name and (
}
```
Function invocation:
```js
fun(123) //no space between fn name and (
```

I think it's and inconstancy and the above one do not need SO MUCH spaces and JSbeautifier removes the space between fn name and the `(`, thus large amount old code do not follow the Standard.

Most popular frameworks/libraries also do not reverse the space between function name and the `(`, like Angular, Lodash and React:
Angular: https://github.com/angular/angular.js/blob/master/src/ng/controller.js#L26
Lodash: https://github.com/lodash/lodash/blob/master/lodash.js#L381
React: https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L114

Chrome DevTools also format it without spaces:
![image](https://cloud.githubusercontent.com/assets/2993947/12225924/2d5f8cd4-b84f-11e5-8603-b00255a7dc2f.png)

**Comment by dcousens** [comment]
https://github.com/feross/standard#i-disagree-with-rule-x-can-you-change-it

**Comment by dcousens** [comment]
And related to https://github.com/feross/standard/issues/89
