### ISSUE TITLE
enforce function statements

### ISSUE THREAD

**Issue by davidjamesstone** [feross/standard#381]
I was wondering about folks preference in regards to expression vs statements.

Clearly it's important to understand the differences between the two in regards hoisting and also the use cases of each but there are often times where either could be used.

I can't find a recommendation - is there a guideline or for this in standardjs?

I see there's the "Enforce Function Style (func-style)" rule in ES Lint. I don't think I'm suggesting this be implemented but it would be nice to have an official line on the preferred approach.

Many thanks

Dave

**Comment by dcousens** [comment]
Could you post some example code?  Probably easier to self-parse and understand what you're referring to?

**Comment by davidjamesstone** [comment]
Hi Daniel,

Thanks for your reply.

I'm generally referring to 'private' helper type functions that don't have value outside of their enclosing function. Take the `save` function below.

Here a function expression or declaration would suffice. For consistency, which one should I opt for?

```js
/*
 * Example adding a comment with an optional replyToId
 */
function addComment (body, inReplyToId, callback) {
  // Define the save function with a function declaration
  function save (comment) {
    comment.save(function (err) {
      if (err) {
        callback(err)
      }
      callback(null, comment)
    })
  }

  // The above function could have been a function expression...
  // var save = function (comment) {
  //   comment.save(function (err) {
  //     if (err) {
  //       callback(err)
  //     }
  //     callback(null, comment)
  //   })
  // }
  
  if (inReplyToId) {
    Comment.findById(inReplyTo, function (err, doc) {
      if (err) {
        callback(err)
      }
      save(new Comment({ body: body, inReplyTo: doc.id }))
    })
  } else {
    save(new Comment({ body: body }))
  }
}
```


Hope this helps

Dave

**Comment by dcousens** [comment]
I personally opt for `function save`,  but I don't think there is a hard-rule for this in standard.

Maybe there should be.

@feross ?

**Comment by rstacruz** [comment]
xo has one. I don't mind it.

**Comment by davidjamesstone** [comment]
Likewise I have opted for `function save () {...}` in the past. This is the also the advice from Crockford.

More recently I have noticed people using `var save = function () {...}` quite a lot.

While I don't have a strong preference, I would like to see some consistency within code base/across teams.

**Comment by dcousens** [comment]
> More recently though I have noticed people using var save = function () {...} a lot more.

Probably because you have to use that syntax if you are using context capturing lambdas:
``` javascript
var save = () => {}
```

**Comment by cesarandreu** [comment]
I use arrow functions with callbacks or when I need to preserve context.

I'm not sure this holds true anymore, since it seems most engines have improved this by now... But it used to be that the following would give you worse stack traces:

```js
// Anonymous function
const foo = function () {}

// Could be fixed by giving it a name
const foo = function foo () {}
```

With babel the default behavior seems to be to name the function:

```js
```

**Comment by feross** [comment]
Function declarations are preferred.

Function declarations have more intuitive hoisting behavior, i.e. you can use the function anywhere that's in-scope. With function expressions, only the variable is hoisted, so you can only use the function after the line where the assignment occurs.

**Comment by feross** [comment]
Just tried enabling [`func-style`](http://eslint.org/docs/2.0.0/rules/func-style.html) to enforce function declarations, while making an exception for arrow function expressions, and got this result:

```
# tests 427
# pass  331
# fail  96
```

Full output: https://gist.github.com/feross/0d57fdddde82f55d618a

It's a high number, so leaning toward not enabling this. Much as I like it. Maybe if we do `standard-strict`?

**Comment by feross** [comment]
For documentation, here's the rule I tested with:

```json
"func-style": [2, "declaration", { "allowArrowFunctions": true }]
```

**Comment by dcousens** [comment]
@feross how about V6?   I think it is a reasonable enough change and absolutely in the spirit of our existing rules.

**Comment by feross** [comment]
@dcousens Agreed, but it's quite a bit of breakage (22% of the ecosystem).

**Comment by dcousens** [comment]
@feross its also a break that could probably be resolved with a regex expression.

**Comment by dcousens** [comment]
``` vim
%sno/var \(\.\+\) = function \.\*(/function \1 (/gc
```

**Comment by feross** [comment]
closing - we can move discussion of potential "next gen" or big breaking rule to the standard-strict issue: https://github.com/feross/standard/issues/382
