### ISSUE TITLE
standard-strict

### ISSUE THREAD

**Issue by rstacruz** [feross/standard#382]
What are your thoughts on making `eslint-config-standard-strict`?

This would be extra rules on top of `eslint-config-standard` that would add more checks, like:

- no-div-regex (to catch `return /=foo/`)
- no-invalid-this (to catch `() => this`)
- no-unused-expressions
- camelcase
- and so on...

At first, it can be _not_ integrated into standard at all, but eventually can be added as `standard --strict` and `standard.lintFiles({ strict: true })`. This will also set the precedent that we can have `--no-react` or similar flags.

**Comment by dcousens** [comment]
> no-invalid-this (to catch () => this)

What is wrong with that?

**Comment by rstacruz** [comment]
Because that will raise an error in strict mode.

**Comment by reg4in** [comment]
I like the idea, but I would keep `standard` optionless and create this as `standard-strict`, as a seperate package.

**Comment by yoshuawuyts** [comment]
yeah, we shouldn't have options. @rstacruz have you raised those rules to be considered in individual issues? I'm not familiar with all of them, but perhaps they'd be a good addition.

**Comment by rstacruz** [comment]
aye, a separate package makes sense. they were /sorta/ discussed in #216, with an exhaustive list of differences from xo here: https://github.com/feross/standard/issues/216#issuecomment-127569835

nonetheless, i think it makes sense to do it in a separate package at first (think of it as "standard-staging"), and we can eventually migrate rules into upstream standard. It really is no big deal to build it as a separate package, it's basically:

```js
/* eslintrc */
{
  "extends": [ "standard", "standard-react", "standard-strict" ]
}
```

**Comment by denis-sokolov** [comment]
[Awkward](https://github.com/denis-sokolov/strict-standard)...

**Comment by rstacruz** [comment]
nice one denis!

**Comment by rstacruz** [comment]
@dcousens @feross any thoughts on those additional rules?
https://github.com/denis-sokolov/strict-standard-config/blob/master/src/index.js

**Comment by feross** [comment]
Not completely against this idea. Need to think about it more.

**Comment by feross** [comment]
Here's another rule that would make sense for a stricter mode: https://github.com/feross/standard/issues/381

**Comment by feross** [comment]
Another rule: https://github.com/feross/eslint-config-standard/pull/21

**Comment by dcousens** [comment]
Perhaps `standard-strict` could be allowed to break more often.

Make it the bleeding-edge of what can be expected in the next major version of `standard`?

**Comment by dcousens** [comment]
Maybe `standard-next`? :P

**Comment by feross** [comment]
One more rule: https://github.com/feross/eslint-config-standard/issues/19

**Comment by rstacruz** [comment]
https://github.com/denis-sokolov/strict-standard

@denis-sokolov did some fine work on this.

**Comment by cesarandreu** [comment]
@dcousens @feross Are you familiar with codemods? There's a Facebook library [jscodeshift](https://github.com/facebook/jscodeshift) that lets you apply AST transformations to JS code, instead of doing text transformations.

It may be worth considering writing a few transforms for breaking changes. Even if they don't catch all the cases, it makes it much easier for people to upgrade their projects.

**Comment by feross** [comment]
@cesarandreu Neat. This could come in handy for `standard-format`.

**Comment by dcousens** [comment]
I'd say this has lost steam.  Close?

**Comment by feross** [comment]
We've basically been making `standard` slightly stricter with each release, but not too fast that users get upset or find it disruptive.

Now that we have `--fix` and it works really well, I'm more certain that that this is the right strategy to continue taking in `standard`.
