### ISSUE TITLE
Abandon / Redirect standardjs.com domain to something else

### ISSUE THREAD

**Issue by Meligy** [feross/standard#385]
From the FAQ, emphasis mine

> But this isn't a real web standard!
>
> Of course it's not! The style laid out here is not affiliated with any official web standards groups, which is why **this repo is called feross/standard and not ECMA/standard**.

But the domain is just **standard**JS\.com, right?

There is another case of Standard Markdown, someone who didn't create Markdown ignored the authority of Markdown (here JavaScript), and claimed to own (the domain of) the standard style.

Too many flames later, it became [CommonMark](http://commonmark.org/), NOT StandardMarkdown or StandardMark even.
Is this story something that this project can learn from? It isn't that different of a situation, is it?

This effort to make less argumentative JS style is fine (ignore the 14 standards becoming 15 joke). THANKS FOR THAT.

However, would it make sense if we are avoiding bikeshedding about the style...
To avoid it about the name as well?

Can we step away from StandardJS, or have some prefix for the word Standard or so?

**Comment by dcousens** [comment]
There is [several other threads](https://github.com/feross/standard/issues?q=label%3A%22i+disagree%22+is%3Aclosed) you could have read before opening this.

**Comment by Meligy** [comment]
This is not the same.

It doesn't say Abandon the name completely. If it's to be called "feross/standard" as the FAQ states it is, that's perfectly fine.

So, **keep it as StandardJS** if that's what the project perfers to be, no problem with that at all.

But **the domain** is conflicting with the intention **stated in the FAQ**. It doesn't say FerossStandardJS\.com for example. It just claims the absolute (non constrained) Standard naming.

**Sorry for not making an explicit statement in the issue description about that this is NOT to rename the project itself, only the domain.**

Would that make it a separate issue worth opening and looking into?

Thanks again for the effort put into this.

**Comment by joshmanders** [comment]
Like those before you were told. This isn't going to change. So go be productive instead.

**Comment by Meligy** [comment]
> Like those before you were told

Regarding those, the Github issue is about the domain name not the project rules or any other set of things.

> This isn't going to change

Would that be contradicting the point made in the quoted FAQ?

I wouldn't have created this Github issue if it weren't for it. **Thanks a lot** for the project making that FAQ point clear.

> So go be productive

Thanks for the advice. It's kind of off-topic for the Github issue, but I appreciate your thinking of my time.

P.S.
Just in case I need to repeat this once more, the Github issue is not about the name of the project, the strive to come up with frustration-free standard style or anything, only the domain name, and in the context explained in the Github issue description.

**Comment by joshmanders** [comment]
And if someone goes to standardjs.com and reads http://standardjs.com/#but-this-isnt-a-real-web-standard then the problem is mitigated. But like the name `standard` on the package itself, it's just another way of someone trying to make invalid misconceptions just to get the name changed.

Everyone behind this module has stated multiple times they won't be making any changes to the names. So move on. You can paint the shed a different color, it's still a bike shed.

**Comment by Meligy** [comment]
I truly appreciate your declaration of the name change as a popular request, so popular that the project keeps facing it multiple times. However, I hope you do realise that earlier note that I'm not asking to change the name.

As you state, people might go to to the domain, check the note, read the "feross/standard" part, look back at the URL, and just get confused. There is an obvious contradiction here. It might well be why many people keep asking for a name change. Whether it is or not, there is a contradiction, and potential confusion.

NPM is another story. There is a whole mess in NPM (and bower for that matter) around the authority of package names. This project is not "significant" contributor to this universal issue. That's why I have not included it in this Github issue. If the project is to pick a new domain, it needs to have the word standard in it of course, which will still link it to the NPM package.

**Comment by Meligy** [comment]
I'm happy to donate the new domain name and domain to the project by the way, in case the project makes a choice to go on with a new domain name without changing the project name.

**Comment by joshmanders** [comment]
https://yourlogicalfallacyis.com/slippery-slope

**Comment by Meligy** [comment]
I will not suggest that you are doing this https://yourlogicalfallacyis.com/strawman
And I hope you are not doing anything like: https://yourlogicalfallacyis.com/the-fallacy-fallacy
Thanks.

I'm saying there is a contradiction between the non-constrained domain name, and the explicit note in the docs (FAQ) saying:

> this repo is called feross/standard and not ECMA/standard.

I'm assuming that the explicit docs is the correct source of truth, and suggesting implying this in the domain name to avoid confusion.

**Comment by joshmanders** [comment]
Your main argument is that new comers could be confused and think it is THE official ECMAScript standard, yet nobody has came forward saying they had that issue. Your fallacy is all that it is, a fallacy.

**Comment by Meligy** [comment]
Uh, ok, you have earned this:
https://yourlogicalfallacyis.com/strawman

My main argument is that there is a conflict. I said there will also be a "potential" confusion, but the main argument is that there is a conflict between a global domain name standardJS.com and a specific username repository "feross/standard", which (the repo name) it seemed an explicit (at least correct) choice based on the FAQ.

If the repository was called standardjs/standard for example, this Github issue wouldn't have made any sense. But it's not.

**Comment by joshmanders** [comment]
Look, move on with your life. You can argue your point until you're blue in the face. The maintainers have expressed no desire in deviating away from any of the names. Get on with your life man.

**Comment by Meligy** [comment]
That's not to say that I wasn't confused myself with this as well. When I saw the domain name I was like "Are they claiming to be THE JavaScript standard?!!!".
Then I looked in the FAQ and saw the note, then thought "Oh, so it is feross/standard, or standardJS? Even the logo just keeps it without any affiliation. This is a just not right".

If you choose to ignore my confusion that's all cool. I still hope that you, project coordinators, at least recognize the conflict between the two names and kindly and thankfully work on improving the experience by removing the conflict.

**Comment by joshmanders** [comment]
You know how many businesses claim to be the number 1 in their field, so much that even the most widely known businesses in that field all claim the same feat... Maybe call Comcast and Timer Warner Cable and let them know they need to stop advertising that, because clearly it's going to confuse potential new customers and choose their horrible services over a better provider.

**Comment by Meligy** [comment]
Perfect argument for changing the project name not just the domain name, but remember, the project maintainers have made their mind on project name as obvious in the closed Github issues above.

**Comment by joshmanders** [comment]
So you think that because they won't change their mind on the npm package name, maybe you can convince them to change their mind on the domain name?

**Comment by Meligy** [comment]
> you can argue your point until you're blue in the face. The maintainers have expressed no desire in deviating away from any of the names. 

By looking here https://github.com/feross/standard/graphs/contributors (there was no contributors.md file that I could find), you don't seem to be one of the project maintainers.

So, I'm gently and firmly asking you to not talk in their name or decide what they may choose to listen to or not. A project maintainer has chosen to keep the Github issue as you see.

**Comment by dcousens** [comment]
> the project maintainers have made their mind on project name as obvious in the closed Github issues above.

@Meligy,  I think then, you have your answer.  The website name is a direct representation of the projects name.
I don't see any reason why they should be different.

Any argument to change the former could also be made appropriately for the latter,  for which a decision has already been made.

I appreciate your positivity throughout the thread @Meligy,  but I'm going to close this for now.  @feross if you feel otherwise please don't hesitate to re-open :)

**Comment by Meligy** [comment]
@dcousens Thanks a lot. Regarding "I don't see any reason why they should be different.". I have explained the FAQ note conflict as the reason. Would you agree that there is a conflict in the first place?

Another suggestion that would also make sense (I hope) is to make the domain name redirect to the readme of the file, which can include the FAQ. In that case, the note will make perfect sense because that's where the user has ended up landing anyway.
Right now, as I hope you might agree, it talks about how the repo is name constrained, while is is on the non constrained domain.

**Comment by Flet** [comment]
Apologies for reanimating this issue, but standardjs.com is really just a HTML version of the README itself. It includes the entire text of the README in the repo including the referenced FAQ:
http://standardjs.com/#but-this-isnt-a-real-web-standard
