### ISSUE TITLE
Allow two line breaks

### ISSUE THREAD

**Issue by raphael-boucher** [feross/standard#390]
Double line breaks allow to clearly separate large entities, such as classes. Could we allow them ?

**Comment by rstacruz** [comment]
Wouldn't it be better to add comments to separate large entities?

Or even better: break them apart into smaller functions or multiple modules?

**Comment by dcousens** [comment]
> multiple modules

This is how you deal with this problem.
If the two swaths of code is tightly coupled,  then,  its likely you're not abstracting the problem properly.

**Comment by raphael-boucher** [comment]
My point is to separate clearly modules (whatever their size), with the logic _one line for a function, two lines for a class_.

Taking the following example, these modules are small and a double line break helps to distinguish them.

```javascript
class Polygon {
  constructor(height, width) {
    this.height = height
    this.width = width
  }
  
  get area() {
    return this.calcArea()
  }

  calcArea() {
    return this.height * this.width
  }
}


class Point {
  constructor(x, y) {
    this.x = x
    this.y = y
  }

  static distance(a, b) {
    const dx = a.x - b.x
    const dy = a.y - b.y

    return Math.sqrt(dx * dx + dy * dy)
  }
}
```

The comment idea is interesting, but it feels more like a hack if I don't have a meaningful comment to make.

**Comment by caspervonb** [comment]
The extra new-line is just extra noise IMHO. If your file is large, use syntax based folding.

**Comment by dcousens** [comment]
@raphael-boucher by module, I am referring to a distinct translation unit.  That is,  a different file.

**Comment by yoshuawuyts** [comment]
It seems the concensus of the respondents in this thread is that this should not be adopted for standard, therefor I'm closing this issue. Thanks for the suggestion regardless! :sparkles:

**Comment by raphael-boucher** [comment]
Shouldn't the syntax convention be fine for common file sizes, let's say up to 500 lines ?
We don't always want to make several small files when there is the need for a slightly bigger separation. Reasons I can think of are lots of overhead and file coherence.

**Comment by yoshuawuyts** [comment]
@raphael-boucher all my `.js` files are typically `<150LOC` and definitely `<300LOC`; anything above that I've found to become brittle. If you're writing long files you might want to look into writing shorter files or start using code folding; I don't think adding extra newlines is a workable solution to make code more readable (see also [padded-blocks:never](http://eslint.org/docs/rules/padded-blocks.html)).
