### ISSUE TITLE
rule react/no-unknown-property assumes that you're using jsx with react

### ISSUE THREAD

**Issue by garth** [feross/standard#394]
This rule breaks using jsx with other view libraries

**Comment by dcousens** [comment]
@garth do you have a test-case?

**Comment by garth** [comment]
For example try using `class` prop which is valid in snabbdom and standard gives an error.

**Comment by dcousens** [comment]
@garth can you please just post a piece of code that fails?

**Comment by garth** [comment]
```js
<div class={{ someClassName: true }}/>
```

**Comment by dcousens** [comment]
Oh right,  this ol' girl.
Closing in favour of https://github.com/feross/eslint-config-standard-react/pull/13.
