### ISSUE TITLE
Is this the correct behaviour?

### ISSUE THREAD

**Issue by rahmatawaludin** [feross/standard#395]
My code got formatted like this..

![screen shot 2016-01-30 at 1 56 41 pm](https://cloud.githubusercontent.com/assets/1274849/12694243/5c64d804-c759-11e5-8486-8a7a8c1085d3.png)

Is this correct behaviour?

I thought it should be formatted like this..

![screen shot 2016-01-30 at 1 57 59 pm](https://cloud.githubusercontent.com/assets/1274849/12694248/8678b002-c759-11e5-8726-2dc8e22a9bb2.png)

P.S: I'm using `standard-format` plugin on sublime text

**Comment by feross** [comment]
Can you re-open this issue on the standard-format repo? All formatting issues go there: https://github.com/maxogden/standard-format
