### ISSUE TITLE
Get your `standard` hex stickers!

### ISSUE THREAD

**Issue by feross** [feross/standard#398]
New `standard` stickers just arrived!

![img_9009](https://cloud.githubusercontent.com/assets/121766/12742804/bde2847e-c93d-11e5-8211-8f554211c6ac.jpg)

![6f953e00-c574-11e5-969a-e2c252d12ae0](https://cloud.githubusercontent.com/assets/121766/12742680/e56fcd72-c93c-11e5-92cb-aeae69c7aa30.png)

Look out for me at conferences and meetups to pick one up for free!

If you've contributed to `standard`, send a message to my email (on my github profile) with your mailing address and I'll send you one for free!

If you just want to buy one for yourself, here's a link to get one from StickerMule: https://www.stickermule.com/en/marketplace/10199-javascript-standard-style (lowest price, no markup)

@maxogden @mafintosh @othiym23 @dcposch @Flet @dcousens @jprichardson @xjamundx @watson @rstacruz @reggi @yoshuawuyts @bcomnes @jb55 - send me your address and I'll ship 50 to you (free!).

**Comment by rstacruz** [comment]
ah damn, would've wanted to give em away over at manilajs.com but its this friday haha

neat stickers!

**Comment by feross** [comment]
@rstacruz Ah, oh well! Next time!

**Comment by dcousens** [comment]
@feross ok to send them to my address that I already gave?

**Comment by feross** [comment]
@dcousens yep!

**Comment by feross** [comment]
Alright, last call – I just packed a bunch of envelopes. If you're a contributor and want your free stickers, send your address now!

**Comment by xjamundx** [comment]
Want one!

**Comment by bcomnes** [comment]
I'll take some! Pming you on irc
