### ISSUE TITLE
standard install broken for npm@2?

### ISSUE THREAD

**Issue by gr2m** [feross/standard#408]
The latest update throws an error when running:
https://travis-ci.org/gr2m/initials/builds/107403864

After updating to npm@3, the error went away:
https://travis-ci.org/gr2m/initials/builds/107441491

Does `standard` require npm@3? I couldn't find any info on it. 

Note that the above is just an example, I get the error in every package of mine, examples [here](https://travis-ci.org/hoodiehq/hoodie-client-connection-status/builds/107406018), [here](https://travis-ci.org/hoodiehq/pouchdb-hoodie-api/jobs/107406464) and [here](https://travis-ci.org/hoodiehq/hoodie-zuul-config/builds/107406586) and I got 15 more of these

**Comment by tunnckoCore** [comment]
Doh, why open new issue, when have #406 and #407?
I also have same problem, but will wait few hours.

It's strange to me that it fails on every version except v5, lol
https://travis-ci.org/tunnckoCore/acorn-strip-comments/builds/107431082

**Comment by gr2m** [comment]
@tunnckoCore I’m very sorry, I looked for open issues quickly but that was pre- :coffee: me. Feel free to close as duplicate

**Comment by rstacruz** [comment]
oh man, this happened on pnpm too when it was following npm@2 behavior more strictly.

**Comment by watson** [comment]
@tunnckoCore Thanks for pointing out the duplicate issues.

Everyone: Let's move the discussion to #406

**Comment by gr2m** [comment]
closing in favor of https://github.com/feross/standard/issues/406

**Comment by feross** [comment]
This should be fixed in `standard` 6.0.3. Sorry for the trouble, folks!
