### ISSUE TITLE
ESLint v2.0.0-rc1 required, which is not noted in WebStorm documentation

### ISSUE THREAD

**Issue by vulpino** [feross/standard#409]
Given the .eslintrc file:
```json
{
  "extends": ["standard", "standard-jsx"],
  "plugins": ["react"],
  "ecmaFeatures": {
    "jsx": true
  },
  "env": {}
}
```

The following error ocurrs: 
```
"C:\Program Files\nodejs\node.exe" F:\Projects\mister\node_modules\eslint\bin\eslint.js --format=checkstyle --stdin --stdin-filename src\client\main.js
standard:
	Configuration for rule "no-labels" is invalid:
	Value "2,[object Object]" has more items than allowed.
```

The issue appears to be caused because Standard requires a release candidate version of eslint (v2.0.0-rc1). The documentation for WebStorm recommends running `npm install -g eslint eslint-config-standard eslint-plugin-standard`, but these will install the newer version of eslint-config-standard and eslint-plugin-standard which have rules that apparently depend on a newer version of eslint. The issue is fixed by installing eslint v2.0.0-rc1 explicitly, but the WebStorm documentation should be updated to recommend explicitly installing v2.0.0-rc1 (or somewhere along the process outside of the `standard` package it should be explicitly required).

**Comment by feross** [comment]
Yes, you're right. I jumped the gun a bit and may have released `standard` 6 a bit too early. Next time, I'll wait for the stable `eslint` release.

Documentation is updated.

**Comment by knownasilya** [comment]
Even with 2.0, it fails with Node 5.6 https://travis-ci.org/Strider-CD/core/jobs/109256135#L859

**Comment by vanjan** [comment]
This can now be reverted, since eslint@2.0.0 has been released.

**Comment by feross** [comment]
@vanjan Thanks, reverted.

**Comment by feross** [comment]
@knownasilya Please update to the latest version of `snazzy` (3.0.0) which was just published.
