### ISSUE TITLE
Add helpful text for `standard --format`

### ISSUE THREAD

**Issue by jden** [feross/standard#412]
Issue extracted from conversation at #340 

As of standard@6, standard-format is no longer included in the standard package. This is a feature request to add helpful forwarding text instructing people to instead download `standard-format`  if they try running `standard --format` to ensure a smoother upgrade experience.

**Comment by feross** [comment]
This is already the case.

```
$ standard --format
standard: Formatting is no longer included with standard. Install it separately: "npm install -g standard-format"
```

Is it not for you?

**Comment by jden** [comment]
Ah, it is, my path was picking up an older `standard` bin.

**Comment by feross** [comment]
@jden Excellent :)
