### ISSUE TITLE
Ace Editor Mode?

### ISSUE THREAD

**Issue by coreybutler** [feross/standard#413]
Can anyone point me to an existing [Ace Editor](https://ace.c9.io) mode supporting Standard syntax? I'm embedding a mini IDE in an Electron app and would love to enforce this syntax.

**Comment by feross** [comment]
Ace Editor mode? Why can't you just use the JavaScript mode?

If you're talking about showing errors inline, then you might have a look at https://github.com/ajaxorg/ace/wiki/Syntax-validation and see if you can't hook that up to [standard's API](https://github.com/feross/standard#nodejs-api).

**Comment by coreybutler** [comment]
I was mostly looking for a way to avoid errors. The JavaScript mode enforces the opposite of several of the standard rules.. and the hacks to make it work are.... hacks. Simplest example is semi-colons are explicitly required. I've already been through the Ace wiki and the standard API... and I intend to implement it myself. I was just hoping something already existed :-)

**Comment by feross** [comment]
Yeah, not that I've heard of. When you're done implementing it, you should post the link here, and submit a PR so we can list it in the editors section :)
