### ISSUE TITLE
strict mode syntax

### ISSUE THREAD

**Issue by fibo** [feross/standard#417]
@feross few days ago commented https://github.com/feross/standard/issues/287#issuecomment-179693300

if for example I have a script like

```
#!/usr/bin/env node

const msg = 'Hello world'
console.log(msg)
```

node will complain something like

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

but if I had `"use strict"` as you suggested, standard js will not accept it cause it is double quoted. I tryed  with single quotes, but it does not work. Any hint?

**Comment by feross** [comment]
What version of node are you using? I'm running v4.3.0 and your code example works fine without the need for `'use strict'`.

**Comment by fibo** [comment]
Yes, sorry the error reported when requiring a file, here it is the complete code

## script.js

```
#!/usr/bin/env node
"use strict"

let config = require('./config')

// just a check
console.log(config)
```

## config.js

```
const fs = require('fs')
const mdconf = require('mdconf')
const path = require('path')

const readme = fs.readFileSync(path.join(__dirname, '..', 'README.md'), 'utf8')

let config = mdconf(readme).database.configuration

module.exports = config
```

**Comment by feross** [comment]
You're missing `'use strict'` in config.js. `standard` will not complain about a single quoted `'use strict'` and that will work just fine.

**Comment by fibo** [comment]
Yes it works, thanks. I am glad anout that cause I am using standard js in a lot of my packages, thanks for creating it.

Let me report a working example

## script.js

```
#!/usr/bin/env node
'use strict'

let config = require('./config')

// just a check
console.log(config)
```

## config.js

```
'use strict'

const config = {foo: 1}

module.exports = config
```
