### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by othiym23** [feross/standard#42]
I like `standard`; having gone through the exercise of converting what has to be one of the largest, most complicated code bases to support it so far, I find myself happy (or at least satisfied) with every choice it makes except the fact that it prescribes both the `browser` and `node` modes in eslint (for reasons I can get into in another issue, if desired).

But! I'm doing a lot more work with ES6 in my code now, and it would be nice to just go ahead and enable ES6 features as they roll into `eslint` (and `jscs`). It's probably going to be a little while before `eslint` supports everything (they _just_ landed support for destructuring), but right now I have to keep switching between `standard` and `eslint` in my Syntastic configuration, and that feels suboptimal.

**Comment by yoshuawuyts** [comment]
@othiym23 The latest version of `standard` should have es6 support enabled. What version are you running?

**Comment by feross** [comment]
I'm curious to hear your argument against the `browser` and `node` eslint options – please open a new issue and let's discuss.

As far as ES6 support, I'm with you! I'm enabling the necessary options as they land in `eslint`. Looks like `eslint@0.15.0` was just released, so I just updated our `.eslintrc` to support [destructuring assignment](https://leanpub.com/understandinges6/read#leanpub-auto-destructuring-assignment), [rest parameters](https://leanpub.com/understandinges6/read#leanpub-auto-rest-parameters), and [the spread operator](https://leanpub.com/understandinges6/read#leanpub-auto-the-spread-operator), as well as all the [other ES6 features](https://github.com/feross/standard/blob/master/rc/.eslintrc#L14-L35) that were already supported. This is released as `standard@2.8.0`.

`eslint` is still on semver `0.x` and does make breaking changes in minor releases, and requires new `.eslintrc` rules to enable new ES6 features, so we'll just have to continue staying up-to-date with their releases. :) Not a problem!

**Comment by othiym23** [comment]
Cool! Great! Closing as WORKSFORME
