### ISSUE TITLE
Allow backtick strings to avoid escaping single or double quotes

### ISSUE THREAD

**Issue by LinusU** [feross/standard#421]
I just encountered an interesting situation in which I have to use both single quotes `'` and double-quotes `"` in the same string. I decided that the easiest would be to wrap them in back-ticks `` ` ``.

```javascript
const sql = `INSERT INTO "user" ("firstName", "lastName") VALUES('Linus', 'Unnebäck')`
```

This is however not acceptable by standard since "Strings must use singlequote.". But the rules on the front page clearly states that it okay when it is to avoid escaping:

> **Single quotes for strings** – except to avoid escaping

Therefor I would consider this a bug, any thoughts?

**Comment by oskarhane** [comment]
I would use back-ticks in the query instead:  

```sql
const sql = 'INSERT INTO `user` (`firstName`, `lastName`) VALUES("Linus", "Unnebäck")'
```

Would that be an option?  
If not, then you should probably just wrap with single quotes and escape them within the query.

**Comment by LinusU** [comment]
Postgres wants me to use double-quotes for identifier escaping. Also, there could be other occurrences when I want to use both single- and double-quotes in the same string.

> then you should probably just wrap with single quotes and escape them within the query.

Than I'm not following the rules, and also it looks ugly :(

**Comment by dcousens** [comment]
``` javascript
const sql = "INSERT INTO \"user\" (\"firstName\", \"lastName\") VALUES('Linus', 'Unnebäck')"
```

**Comment by rstacruz** [comment]
I've personally used that convention when both " and ' are needed in the string. backticks for strings are allowed by standard.

**Comment by LinusU** [comment]
@dcousens Is that really better than this though?

```javascript
const sql = 'INSERT INTO "user" ("firstName", "lastName") VALUES (\'Linus\', \'Unnebäck\')'
```

**Comment by feross** [comment]
Yeah, I think this rule is being overly restrictive. I opened an eslint issue for this before releasing v6: https://github.com/eslint/eslint/issues/5147

Ideally we could enforce this:

- default rule – use single quotes
- if string contains a single quote – use single quotes w/ escaping, or double quotes to avoid escaping
- if string contains single and double quotes – use single quotes w/ escaping, or backticks to avoid escaping

There's an ongoing discussion about this and related issues here: https://github.com/eslint/eslint/issues/5234 Weigh in there if you have opinions.

**Comment by feross** [comment]
We should be able to work around this now: https://github.com/eslint/eslint/pull/5661

**Comment by feross** [comment]
This rule change (always allowing template literal strings) will be included in standard v8.

**Comment by yoshuawuyts** [comment]
> if string contains single and double quotes – use single quotes w/ escaping, or backticks to avoid escaping

Does that rule do this ^ ?

**Comment by feross** [comment]
> Does that rule do this ^ ?

No, the rule just always allows template literal strings. So, it's not perfect.

**Comment by yoshuawuyts** [comment]
Ah ok, reasonable enough

**Comment by yoshuawuyts** [comment]
Ah ok, reasonable enough
