### ISSUE TITLE
MutationObserver is not defined

### ISSUE THREAD

**Issue by maxfrigge** [feross/standard#424]
It seems that standard doesn't recognise the `MutationObserver` class to be globally available when writing browser JS. 

What's the recommended way of dealing with this?

**Comment by rstacruz** [comment]
```js
window.MutationObserver
```

or

```js
/* eslint-env browser */
```

or

```js
/* global MutationObserver */
```

from the rules:

> Always prefix browser globals with window – except document and navigator are okay

**Comment by maxfrigge** [comment]
Thanks a billion!
