### ISSUE TITLE
Add rules for import checking

### ISSUE THREAD

**Issue by dignifiedquire** [feross/standard#425]
I feel this might be a great edition for everyone using es module syntax to get checks that all imports are actually resolvable: https://www.npmjs.com/package/eslint-plugin-import

what do you think?

**Comment by jprichardson** [comment]
While I like the idea of this, Babel can be configured to dynamically resolve paths. If we did this, we would have to accommodate that as well and thus add more complexity. I'd vote to hold off on this for awhile.

**Comment by cesarandreu** [comment]
The loader spec isn't finalized, so module resolution is not set in stone.

For example, how would a browser know it has to request e.g. `bar.js` vs `bar/index.js`? I think it won't even support this, so it's not clear how interop is expected to work, unless you keep a manifest? 

With that said, I have no plans of giving up browserify / webpack, and will keep transpiling forever, so I don't think I'd be affected.

**Comment by dignifiedquire** [comment]
As far as I understand it currently supports nodes resolve mechanisms, based on substacks work for browserify and webpack. That means it is capable of handling the current ways resolving is done. When the module resolution actually gets finalised and implemented I'm pretty sure it can be updated to reflect those changes.

**Comment by dignifiedquire** [comment]
@jprichardson what dynamic resolution are you referring to exactly?

**Comment by feross** [comment]
If we support this, then folks will be asking for hooks to customize how module resolution works for their specific setup, since not everyone uses browserify. Then there will be pressure to add hooks for those folks, or to disable these checks. I'm -1 for now, until things shake out a bit more.

**Comment by dcousens** [comment]
This sounds like hell.

**Comment by benmosher** [comment]
Hello, I maintain that plugin.

To support different loaders (browserify/node, Webpack, Babel plugins, etc.) the plugin itself has pluggable loaders. The default Node one uses substack's node-resolve, Webpack one uses webpack/enhanced-resolve, etc.

So y

**Comment by feross** [comment]
@benmosher Thanks for the explanation :)
