### ISSUE TITLE
Failing to parse ES7 features, due to espree

### ISSUE THREAD

**Issue by andywer** [feross/standard#426]
Hey there!

I just recognized that standard fails to parse files in which we use class properties like:

```js
class MyComponent extends React.Component {
  static propTypes = {}      # This is were shit hits the fan

  render () {
    return null
  }
}
```

It fails to parse the file and complains about `Unexpected token =`. Maybe it would make sense to use `babel-eslint`?
(See: https://github.com/yannickcr/eslint-plugin-react/issues/43#issuecomment-107101415)

I am a big fan, but not familiar with the inner workings of `standard` and how it utilizes eslint, though.

**Comment by LinusU** [comment]
This is covered in the documentation: [Can I use a custom JS parser for bleeding-edge ES6 or ES7 support?](https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support)

**Comment by andywer** [comment]
Ohh sorry, I did not even expect it to be in the Readme. Thank you for the quick response!

**Comment by LinusU** [comment]
No problem :ok_hand:
