### ISSUE TITLE
v6.0.6 silently fails

### ISSUE THREAD

**Issue by ahmadnassri** [feross/standard#429]
I'm looking through the changes since `v6.0.5` but not seeing why this is occurring, though easily repeatable between `v6.0.5` and `v6.0.6`

###### test.js
```js
function test() {
  console.log('hello world')
}
```

###### v6.0.5
```bash
$ standard 
standard: Use JavaScript Standard Style (http://standardjs.com) 
  /home/ahmad/Projects/test/test.js:1:10: 'test' is defined but never used
  /home/ahmad/Projects/test/test.js:1:14: Missing space before function parentheses.
```
produces correct output.

###### v6.0.6
```standard
$ standard 
```

produces no output.

**Comment by feross** [comment]
Confirmed. Working on it.

**Comment by feross** [comment]
Released as v6.0.7.

**Comment by feross** [comment]
https://github.com/feross/standard/commit/e4f3ba4865eee3d0d602d7043fc820936ed695ba

**Comment by ahmadnassri** [comment]
:clap: thanks for the quick turn around!
