### ISSUE TITLE
Space after function name

### ISSUE THREAD

**Issue by mvolkmann** [feross/standard#433]
I think I could get on board with all of these conventions except "space after function name". I can honestly say that I have never seen that done in any JavaScript code. In fact, I have never seen that done in ANY programming language. I wish at least that was configurable.

**Comment by feross** [comment]
Sorry, this has been discussed many times before. See https://github.com/feross/standard/issues/318 https://github.com/feross/standard/issues/89 https://github.com/feross/standard/issues/311 https://github.com/feross/standard/issues/217.

If you want to configure rules, you can fork `standard` or use `eslint` directly with the [standard config](https://github.com/feross/eslint-config-standard). That would work like this:

.eslintrc
```json
{
  "extends": [ "standard" ],
  "rules": {
    // ... go wild here...
  }
}
