### ISSUE TITLE
v6.x.x looks not working with 3rd-party parser(babel-eslint)

### ISSUE THREAD

**Issue by rapidia** [feross/standard#437]
I'm using `standard` with `babel-eslint` parser.
on v5.4.1, It works perfectly(to me.)
but on v6.0.7, arrow-parens violation occurred at async arrow function statement.

this resolved when I just downgrade to v5.4.1, nothing changes on the codes.
Is it a bug?

**Comment by LinusU** [comment]
Duplicate of #416

**Comment by rapidia** [comment]
@LinusU 
thanks. I didn't know that.
