### ISSUE TITLE
new.target support

### ISSUE THREAD

**Issue by 75lb** [feross/standard#441]
is [new.target](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target) supported? 

using node 5.7, this code: 
```js
'use strict'

class Example {
  constructor () {
    console.error('new.target.name:', new.target.name)
  }
}

new Example()
```

outputs: 
```
new.target.name: Example
```

however, standard v6.0.7 doesn't seem to recognise `new` or `target` as valid:
```
$ standard tmp/target.js
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/lloyd/Documents/jsdoc2md/testbed/tmp/target.js:5:39: 'new' is not defined.
  /Users/lloyd/Documents/jsdoc2md/testbed/tmp/target.js:5:43: 'target' is not defined.
  /Users/lloyd/Documents/jsdoc2md/testbed/tmp/target.js:9:1: Do not use 'new' for side effects.
```

**Comment by feross** [comment]
This is a known eslint issue (see https://github.com/eslint/eslint/issues/5420). It looks like it's already fixed and is just waiting a release on npm.

Hopefully this will be working for you in a few days!

**Comment by 75lb** [comment]
ok, thanks @feross
