### ISSUE TITLE
How to defined multiple file extensions

### ISSUE THREAD

**Issue by alanrubin** [feross/standard#442]
First thanks for the great package.

Not sure this a newbie question but I'm trying to run standard for different file extensions (js, jsx and es6). I know js and jsx comes configured by default but how do I configure it to run for all those 3 extensions ?

I have tried to run the below command but get an error.

`
$: standard webpack/**/*(.js|.jsx|.es6)
`

Thanks !

**Comment by alanrubin** [comment]
Ok found the solution. The above command syntax works for running in command line but when running as an npm task, you should declare each file extension separately such as:

Inside package.json
`
scripts: {
  "lint": "standard ./webpack/**/*.js ./webpack/**/*.jsx ./webpack/**/*.es6"
}
`

otherwise it won't work. Is that something we want to document ? If yes I can create a PR.

**Comment by LinusU** [comment]
Have you tried `standard webpack/**/*.{js|jsx|es6}`

**Comment by rstacruz** [comment]
Actually the bash expansion syntax is {js,jsx,es6} -- try that!

**Comment by alanrubin** [comment]
So actually the solution I though was working is not. If I run "npm run lint", only js and jsx files are expected but es6 are ignored. As you suggested I have tried to configure the lint task as

`script: { "lint": "standard webpack/**/*.{js|jsx|es6}" }`

but still getting the error below. Any ideas ?

`➜  app git:(apply-standardjs) ✗ npm run lint

> my@0.0.1 lint /Users/alanrubin/app
> standard webpack/**/*.{js|jsx|es6}

sh: jsx: command not found
sh: es6}: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/alanrubin/.nvm/versions/node/v5.0.0/bin/node" "/Users/alanrubin/.nvm/versions/node/v5.0.0/bin/npm" "run" "lint"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! app@0.0.1 lint: `standard webpack/**/*.{js|jsx|es6}`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the app@0.0.1 lint script 'standard webpack/**/*.{js|jsx|es6}'.
npm ERR! This is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     standard webpack/**/*.{js|jsx|es6}
npm ERR! You can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alanrubin/app/npm-debug.log
`

**Comment by LinusU** [comment]
@alanrubin use comma instead of pipe, my fault...

**Comment by alanrubin** [comment]
Works ! It should be `script: { "lint": "standard webpack/**/*.{js,jsx,es6}" }`. But now I have another problem... the syntax for searching in any level "**" only looks one level below not in any level deeper. What should be the syntax to search for files in any level ? (In the command line "/**/*" syntax works).

I realise that this could be a off topic question but I'm very grateful if you could help, could not find any reference to this anywhere.

**Comment by feross** [comment]
@alanrubin Try wrapping another set of quotes around the file path:

```
script: { "lint": "standard 'webpack/**/*.{js,jsx,es6}'" }
```

Otherwise I think bash does expansion for you, but you want to actually pass through the `**` to standard.
