### ISSUE TITLE
Installation error on windows

### ISSUE THREAD

**Issue by omerts** [feross/standard#446]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "standard"
npm ERR! node v4.3.1
npm ERR! npm  v3.7.3
npm ERR! path C:\Program Files\nodejs\node_modules\standard
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Program Files\nodejs\node_modules\standard' -> 'C:\Program Files\nodejs\node_modules\.standard.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Program Files\nodejs\node_modules\standard' -> 'C:\Program Files\nodejs\node_modules\.standard.DELETE'
npm ERR!     at Error (native)
npm ERR!  [Error: EPERM: operation not permitted, rename 'C:\Program Files\nodejs\node_modules\standard' -> 'C:\Program Files\nodejs\node_modules\.standard.DELETE']
```

It looks like the paths are wrong. 
Nothing under C:\Program Files\nodejs\node_modules, that has to do with standard. There are two folders, npm and babel-cli.
Node version 4.3.1
Npm version 3.7.3

**Comment by LinusU** [comment]
I think that this is a bug in npm

**Comment by omerts** [comment]
updated node + npm, still same error
node v 5.7.1
npm v 3.8.0

**Comment by feross** [comment]
Looks like you installed standard from an Adminstrator command line and now
you're trying to install it again from a normal command line.

This won't work because it can't delete the old one. Use an Administrator
command line.

**Comment by omerts** [comment]
I am using administrator command line. It looks like it is trying to delete ".standard.DELETE", from a wrong path, which does not exist.

**Comment by LinusU** [comment]
If it didn't exist it would trigger `ENOENT`, not `EPERM`...

**Comment by feross** [comment]
Sorry, this is not a `standard` issue. You might have better luck posting this issue at https://github.com/npm/npm

**Comment by omerts** [comment]
uninstalling and reinstalling node.js fixed it for me. sorry :)
