### ISSUE TITLE
static class members cause standard to end parsing

### ISSUE THREAD

**Issue by mattwigway** [feross/standard#447]
Standard does not support static class members, à la

```
export default class RemoveTrips extends Component {
  static propTypes = {
    modification: PropTypes.object.isRequired,
    replaceModification: PropTypes.func.isRequired,
  };
  ...
}
```
([full file](https://github.com/conveyal/scenario-editor/blob/master/lib/remove-trips.js))

When I run standard across this file, I get:

`remove-trips.js:17:20: Parsing error: Unexpected token =`

and then standard does not find any other errors.

This may be an upstream eslint issue, see yannickcr/eslint-plugin-react#43.

**Comment by feross** [comment]
Thanks for posting to bring to our attention, but like you said, this seems like an upstream issue.

**Comment by LinusU** [comment]
The problem is that you need to use `"parser": "babel-eslint"`, look in the readme for more info
