### ISSUE TITLE
`no-undef-init` makes defining a const with undefined impossible

### ISSUE THREAD

**Issue by despairblue** [feross/standard#456]
```js
const nothing1 = undefined // does not lint
const nothing2 = null // does lint
// etc
```

This may look weird, but it's part of a spec and I want to have all fixtures as consts, instead of copying them to all assertions. Maybe later I decide that the function I'm testing should work with empty strings instead of `undefined`, so I can simply change one line.

I do see that this is a very specific edge case. If this is a wont-fix, I'm fine with it. I can simply change it to `let nothing1`.

**Comment by yoshuawuyts** [comment]
> I do see that this is a very specific edge case

I think I agree; I don't see a compelling reason to relax the rule - wonder what others think

**Comment by feross** [comment]
@despairblue What's the error you get?

**Comment by despairblue** [comment]
@feross on one computer I get `It's not necessary to initialize 'nothing1' to undefined` on the other it works as expected. I suppose it was fixed and I have an old eslint version installed on one computer.

Thanks for the help :+1:

**Comment by feross** [comment]
Cheers!
