### ISSUE TITLE
.jshintrc config for standard?

### ISSUE THREAD

**Issue by taoeffect** [feross/standard#459]
Before you ask, yes I did read the README and this line:

> No .eslintrc, .jshintrc, or .jscsrc files to manage.

However, eslint, which standard is based on, is ["2-3x slower" than jshint](https://github.com/eslint/eslint#how-does-eslint-performance-compare-to-jshint-and-jscs), and this really shows up during normal development.

I would be willing to sacrifice having an extra dot file in our project's directory for the 2-3x performance boost. So is there a .jshintrc file that someone has made that's compatible with standard? And if so maybe it can be linked to from the README?

**Comment by feross** [comment]
There was some discussion of this topic in this issue: https://github.com/feross/standard/issues/123

If you decide to enhance that basic `.jshintrc` with more of standard's rules, feel free to post it as a comment to help other people like yourself in the future.
