### ISSUE TITLE
Avoid Passing Null

### ISSUE THREAD

**Issue by xjamundx** [feross/standard#460]
Not sure if there is a rule for this yet, but it could probably done in a plugin.

Bad:

```
if (err) return cb(err, null)
```

Good:

```
if (err) return cb(err)
```

Why is that better?

```
getName(err, name = 'Default') {
   console.log(name); // might end up as `null`
});

**Comment by feross** [comment]
In other words: functions that get called with a parameter named `err` should only have one parameter.

**Comment by xjamundx** [comment]
`cb(null, "name")` in this case is great, but `cb(err, null)` is bad news.

I think people are used to typing `cb(null, data)` when things go well, so sometimes they do `cb(err, null` when things go wrong.

There may be a case where you'd want to do `cb(err, data)`, so I'm not sure you'd want to ban anything except `null` explicitly.

**Comment by dcousens** [comment]
> functions that get called with a parameter named err should only have one parameter.

Unless you're callback is just a pass-through:

``` javascript
f(..., function (err, result) {
  console.log('Wrapper called with ', x)

  callback(err, result)
})
```

**Comment by feross** [comment]
@dcousens Good point. So there's no way to reliably enforce this.

@xjamundx I think it would be a mistake to write code that assumes that the value will be `undefined` just because there's an `err`. You should check if there's an `err` explicitly every time.

**Comment by xjamundx** [comment]
Hmm probably a good point (this came up at work today and we found it was
happening in a few places). Probably we should avoid null in general at
this point, but community isn't there yet :)
