### ISSUE TITLE
Define globals only for a specific directory

### ISSUE THREAD

**Issue by ilearnio** [feross/standard#462]
I have `src/client` and `src/server` directories in my project. The one is for the client side (WebPack), the second one is for a Node backend. On the backend, I am using some global variables (e.g `ROOT_DIR`), that I don't have on the client. How do I tell standard to allow to use these globals only on the backend?

My package.json config for standard looks like so:

```js
"standard": {
    "parser": "babel-eslint",
    "globals": [
      "ENV",
      "IS_CLIENT",
      "IS_SERVER"
    ],
    "ignore": [
      "node_modules/**"
    ]
  }
```

It would be nice to have something like `.standardrc` that might be placed into any children directory and would inherit settings from other `.standardrc` files that are located in parent directories. But it seems it only supports for a single package.json and doesn't look back for other parents `package.json`s. I tried to create a `src/server/package.json` and it works but that way I need to duplicate all the settings and then add some more options. It might go as a temporal solution, but it so hackish to create a package.json​ everywhere I need to add some option to standard. It's there for a different purpose – for Node's NPM

**Comment by feross** [comment]
Your options are:

1. Don't worry about users using the globals that don't exist in one environment. Linters aren't going to catch 100% of errors anyway.

2. Use `eslint` directly. That way you can use `.eslintrc` files and make things as complicated as you want.

Standard isn't going to add `.standardrc` files, sorry. The whole reason standard was created was to avoid littering your project with configuration files.
