### ISSUE TITLE
"Expected error to be handled." perhaps should account for arguments

### ISSUE THREAD

**Issue by will123195** [feross/standard#466]
This code fails with `Expected error to be handled.`

```js
test('should get something', function (t) {
  request.get({
    uri: 'http://localhost:3000'
  }, function (err, res, body) {
    handleError(arguments)
    t.equal(res.statusCode, 200)
    t.end()
  })
})
```

Although, technically the error is being handled.

**Comment by feross** [comment]
This is a limitation of the [handle-callback-err](http://eslint.org/docs/rules/handle-callback-err) rule and definitely an edge case. Feel free to open an issue on the [eslint repo](https://github.com/eslint/eslint).

It's easily worked around though:

```js
handleError(err, res, body)
```
