### ISSUE TITLE
remove 'jspm_packages' by default

### ISSUE THREAD

**Issue by la-yumba** [feross/standard#467]
since it's smart enough to avoid linting node_modules and bower_components, let's also remove jspm_packages

**Comment by feross** [comment]
We don't currently ignore `bower_components`. This is a slippery slope. I don't want `standard` to be responsible for ignoring files for every new alternative package manager. You can ignore folders manually by following [these instructions](https://github.com/feross/standard#how-do-i-ignore-files) in the readme.

**Comment by chenxsan** [comment]
@la-yumba If you are using any editors like VS Code with standard extension, you can ignore those `jspm_packages` globally by configuring `settings.json` instead of configuring every `package.json` of your projects.
