### ISSUE TITLE
Invalid number: number in octal form

### ISSUE THREAD

**Issue by grunjol** [feross/standard#484]
the same way you write 0xFF as hexadecimal (and it validates), should `standard` allow `0755` be a valid number in octal representation?

In https://github.com/feross/webtorrent-desktop/issues/326 ended up using `parseInt('0755',8)`

**Comment by LinusU** [comment]
iirc there is some inconsistency between runtimes so it's better to just not use it...

**Comment by feross** [comment]
@mafintosh Do you remember the simple way to use octals that we came up with?

**Comment by feross** [comment]
@grunjol You can actually prefix the number with `0o` and it will be treated as octal in ES6.

```js
    > 0xFF // ES5: hexadecimal
    255
    > 0b11 // ES6: binary
    3
    > 0o10 // ES6: octal
    8
```

We can use ES6 freely in WebTorrent Desktop since it's an Electron app and there's no old browsers to worry about :)

**Comment by grunjol** [comment]
great!

**Comment by mafintosh** [comment]
@feross https://github.com/mafintosh/octal

**Comment by feross** [comment]
@mafintosh right!
