### ISSUE TITLE
Honor .eslintignore ?

### ISSUE THREAD

**Issue by sterpe** [feross/standard#485]
I guess its not guaranteed that standard is `eslint` under the hood, but since it is, does it make sense to also read ignore paths from the local `.eslintignore`?

**Comment by dcousens** [comment]
I think you answered your own question.

> I guess its not guaranteed

**Comment by feross** [comment]
We want `standard` to work exactly the same way for everyone, with as little unpredictable behavior as possible. You can configure which files to ignore in `package.json` with the `ignore` property.
