### ISSUE TITLE
Rule Suggestion: comma-dangle: always-multiline

### ISSUE THREAD

**Issue by Schtauffen** [feross/standard#486]
`comma-dangle: ["error", "always-multiline"]`

It saves time when editing and prevents stupid errors. 
If you've ever used golang then you probably know how awesome this rule is.

I am forced to use https://github.com/feross/eslint-config-standard until this is changed :'(

**Comment by dcousens** [comment]
https://github.com/feross/standard/issues/240
https://github.com/feross/standard/issues/400
https://github.com/feross/standard/issues/464

**Comment by qm3ster** [comment]
1. ES8 brings this to function parameter lists and calls (but lists and objects are more often multilined)
1. If you write for old browsers, you should transpile
1. It's one commit to `--fix` a codebase, much better than years of diffs with spurious highlighting
