### ISSUE TITLE
Badge background color

### ISSUE THREAD

**Issue by simov** [feross/standard#489]
![badge](https://cloud.githubusercontent.com/assets/1694112/14572002/04b36b06-0355-11e6-9e80-170379eca6e1.png)

Can we have a white background on the badge, cause right now it looks a bit unprofessional :)

It's probably not that uncommon someone to put it on a dark background like for example when using the [GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark) theme.

**Comment by simov** [comment]
![badge2](https://cloud.githubusercontent.com/assets/1694112/14572296/b474f75c-0356-11e6-81a5-e9979dd3f5bc.png)


Wait, the badge in the repo seems to be ok, so I guess the docs needs updating.

**Comment by simov** [comment]
Nope this link seems to be all over the place.

**Comment by feross** [comment]
This works fine for me.
