### ISSUE TITLE
Make 'ignored file' output go away

### ISSUE THREAD

**Issue by howdoicomputer** [feross/standard#500]
```
  /Users/doctordoom/workspace/personal/calidrought/app.js:0:0: File ignored because of a matching ignore pattern. Use --no-ignore to override.
```

I know the file is ignored. I put the matcher there. The output is just noise I have to parse through to get to real style violations. Is there a way to not have the CLI output these errors? I didn't see anything in the documentation or the CLI help output to make it less verbose.

**Comment by feross** [comment]
You're getting this message because you're using an `.eslintignore` file. You should follow the instructions in the readme instead.

You should not get that error in the future, as of https://github.com/Flet/standard-engine/pull/104

**Comment by howdoicomputer** [comment]
@feross Alright! Thanks for responding. This was mostly because I was trying to integrate this with an online CI system.
