### ISSUE TITLE
Document how to use with eclipse

### ISSUE THREAD

**Issue by matthewadams** [feross/standard#501]
We have a mixed dev environment, and most of the configuration for the tools we use are documented on your site, except for eclipse.  We use an eclipse distro that includes Web Tools Platform (WTP).  Since eclipse Orion (Mars is current as of this writing), eslint is the [default](http://eslint.org/docs/user-guide/integrations) [formatter/validator](http://dev.eclipse.org/mhonarc/lists/orion-dev/msg02718.html).

Please document near the WebStorm howto how to use standardjs with eclipse Orion & later's eslint validator.

**Comment by feross** [comment]
PR welcome!

**Comment by feross** [comment]
It's been a few months and no one's taken this on yet, so I'm going to close it to keep the issue tracker clean. PR is still welcome, of course.
