### ISSUE TITLE
Document project-specific styling configuration

### ISSUE THREAD

**Issue by matthewadams** [feross/standard#502]
When you work on multiple open source projects concurrently, it's a pain to have to keep changing your style settings as you switch between projects.

Your site is helpful with regard to setting up, say, WebStorm, for global code style preferences, however, I'm trying to configure project-specific settings so that my project will use `standard`, regardless of any other IDE style settings.  It appears that WebStorm does this via a JetBrains-supplied [EditorConfig](http://editorconfig.org) plugin:  https://www.jetbrains.com/help/webstorm/2016.1/configuring-code-style.html#editorconfig

There is an npm module https://www.npmjs.com/package/eslint-to-editorconfig that is supposed to translate from `eslint` to `editorconfig`, but I (and others) are running into https://github.com/sun1x/eslint-to-editorconfig/issues/3.

I thought it might be just that `eslint-to-editorconfig`'s dependencies needed to be updated -- the current release (`1.1.1`) depends on `eslint` version `^1.10.3`, so I forked, cloned, branched and tried updating the `eslint` dependency to `^2.8.0`, but I'm still seeing the same error.  I don't know if it's because I `npm link`ed from the fork then `npm link eslint-to-editorconfig`ed in the target project that caused the configuration parsing to fail.

I'll continue trying to figure out the issue with https://github.com/sun1x/eslint-to-editorconfig/issues/3, but it'd be helpful for you to document how to configure `standard` to be used with various editors/IDEs (specifically WebStorm in my case) as _project-specific_ settings as opposed to global settings.

**Comment by feross** [comment]
Sounds to me like `eslint` didn't get updated correctly. That error means that you're still using `eslint` v1.

I don't use WebStorm, and I have no idea how to configure it the way you want. If you figure it out, please send a PR and we're happy to merge it 👍

**Comment by LinusU** [comment]
For users of Atom I can recommend the [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) plugin which looks in your package.json and detects which standard package you are using 👍

**Comment by feross** [comment]
It's been a few months and no one's taken this on yet, so I'm going to close it to keep the issue tracker clean. PR is still welcome, of course.
