### ISSUE TITLE
New rule suggestion: Object key names should only be quoted if necessary

### ISSUE THREAD

**Issue by scouten** [feross/standard#503]
Good:

```js
let response = {id: 'foo', ok: true}
```

Bad:

```js
let response = {'id': 'foo', 'ok': true}
```

**Comment by LinusU** [comment]
How do we feel about objects where some keys require quoting? I think it's more readable if they are all quoted:

```js
const map = {
  'test-1': 73,
  'normal': 843,
  'other-key': 386,
  '1pass': 284,
  'sword': 83,
  'heavy-sword': 738
}
```

**Comment by yoshuawuyts** [comment]
I think quotes in keys should be allowed only for escaping, the same way we apply the rule to double quotes for strings.

**Comment by feross** [comment]
The reason that I initially did not enable this rule is because of the case that @LinusU points out. 

As with all new rule proposals, the first step is to see how many repos would fail with it enabled.

**Comment by scouten** [comment]
@LinusU: That works, too. I guess I thought part of the purpose of this standard was to reduce wiggle room. I recently came across a case in my own code where I had been inconsistent in my use of quoting and it seemed like something that fit neatly into what standard was trying to accomplish.

**Comment by dcousens** [comment]
I think quote only if necessary is fine.  It is consistent with our other idiosyncrasies (e.g semicolons).

**Comment by feross** [comment]
Adding the rule:

```
    "quote-props": [2, "as-needed"]
```

Results in the following failures:

```
1..423
# tests 423
# pass  388
# fail  35
```

which seems fairly high for a purely stylistic rule addition. Maybe we can add it once the rule is automatically fixable with ESLint's `--fix` feature?

**Comment by feross** [comment]
Let's re-open this issue once ESLint makes `quote-props` fixable. Right now there's nothing actionable for us to do.
