### ISSUE TITLE
How to use it with flow type annotations 

### ISSUE THREAD

**Issue by giacomorebonato** [feross/standard#507]
Is there any recommended way to use standard linting together with Flow Type annotations?

**Comment by feross** [comment]
Try using https://www.npmjs.com/package/eslint-plugin-flowtype

```
npm install eslint-plugin-flowtype
```

And add this to `package.json`:

```js
{
  "standard": {
    "plugins": [
      "flowtype"
    ]
  }
}
```

**Comment by giacomorebonato** [comment]
Did you mean .eslintrc right? Thanks.

**Comment by feross** [comment]
No. standard does not use `.eslintrc`.

**Comment by giacomorebonato** [comment]
ok, thank you for pointing me in the right direction
