### ISSUE TITLE
Emacs install: Flycheck documentation link is a 404

### ISSUE THREAD

**Issue by HaQadosch** [feross/standard#509]
This section is the culprit:
> Emacs
> Install Flycheck and check out the manual to learn how to enable it in your projects.

The link to the manual is http://www.flycheck.org/manual/latest/index.html but this is a 404
Maybe use http://www.flycheck.org/en/latest/user/installation.html ?

Thanks.

**Comment by feross** [comment]
Thanks - fixed.
