### ISSUE TITLE
Fail to check setters in objects.

### ISSUE THREAD

**Issue by nickmessing** [feross/standard#51]
Missing space before function parentheses.
Example:
  https://gist.github.com/anonymous/239cfd747eca6072c53e

Fails on "set variable (value) {}"

**Comment by feross** [comment]
This looks like a bug in eslint. I opened an issue: https://github.com/eslint/eslint/issues/1920

**Comment by feross** [comment]
This is fixed in eslint `master` now, so we'll get the fix when they publish a new version :) Closing this now.
