### ISSUE TITLE
using `return` in the top level of a node.js script

### ISSUE THREAD

**Issue by 75lb** [feross/standard#510]
using standard v7, trying to validate this node.js script:
```
console.log('one')
return 
console.log('two')
```

throws this issue:
```
Parsing error: 'return' outside of function
```

In node.js, the top level script is [wrapped by a function](http://stackoverflow.com/questions/28955047/why-does-a-module-level-return-statement-work-in-node-js). Even though it might *look* like use of `return` outside a function, it is not.. 

what to do here? This is a valid use of `return`..

**Comment by LinusU** [comment]
I thought that this had been the case for a long time. I would recommend using `process.exit(0)` instead.

**Comment by 75lb** [comment]
@LinusU  if `return` and `process.exit()` were equivalent, i would.. they are not related and have different consequences.

**Comment by feross** [comment]
Yes, this has been an issue for a long time.

This is an unfortunate side effect of two bad decisions made by TC39:

1. Top-level return is an error.
2. ES modules have a completely different parsing mode ("module") than the normal mode ("script").

The decision to have two modes means that every piece of tooling that parses JS has to expose this decision to the user.

To keep `standard` simple, we just assume "module" which makes the ESLint parser support all the module syntax (`export`, etc.) but has the downside of preventing top-level return. :(

If we assumed "script" then many more things would not work, so this is the right compromise I think.

**Comment by 75lb** [comment]
could you leave the "module" or "script" mode decision to the user with a `--mode` option or similar? 

The current behaviour prevents me using Standard in CI as it will always fail when linting my `bin.js` scripts (which typically contain `return` in a `catch` handler to gracefully exit the process).

**Comment by feross** [comment]
It's an intentional decision to not have modes or options in `standard`. I understand that this is painful right now, but adding a mode would add complexity for every user of `standard`, in perpetuity.

We'll have to find a better long-term workaround for this.

For now, consider not linting the files which contain top-level return.
