### ISSUE TITLE
Include violated rule name in output

### ISSUE THREAD

**Issue by matthewadams** [feross/standard#512]
I'm getting output from standard that doesn't include the name of the violated rule:
```
$ node_modules/.bin/standard
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/matthew/Documents/github/.../socketApi.js:11:43: Getter is not present
```
This makes it difficult to conveniently add an `// eslint-ignore-line` or `// eslint-ignore-next-line` directive to include the name of the violated rule (which, in this case is `accessor-pairs`).  For example:
```
$ node_modules/.bin/standard
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/matthew/Documents/github/.../socketApi.js:11:43: Getter is not present:  accessor-pairs
```
would make it pretty easy to add.

Bonus points for emitting not just the rule name, but also something like `to ignore:  // eslint-ignore-line ..` for quick copy & paste.  For example, the above output could be augmented with:
```
$ node_modules/.bin/standard
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/matthew/Documents/github/.../socketApi.js:11:43: Getter is not present:  accessor-pairs: to ignore, // eslint-disable-line accessor-pairs
```

**Comment by feross** [comment]
You can get the rule name by running `standard --verbose`.

**Comment by matthewadams** [comment]
Ok, but it'd still be nice to change the current output, `(<rule-name>)` to something like `<rule-name>: ignore with // eslint-disable-next-line <rule-name>` for easy copy/paste, don't you think?  Reopen issue? #easeofusemakeskillerapps

**Comment by LinusU** [comment]
I have yet to come up with one single case where I have had to ignore a rule, I don't think it should be in the output since we don't want to encourage anyone to do it. The real solution is to fix the problem, not ignore it...
