### ISSUE TITLE
Does not accept __dirname

### ISSUE THREAD

**Issue by davidbarton** [feross/standard#513]
Standart does not accept node __dirname global variable. Is it intended? Do you have suggestion for workaround? Maybe should we put this into FAQ?

**Comment by watson** [comment]
@davidbarton It does work for me using this program:

```js
console.log(__dirname)
```

Are you using the latest version (v7.0.1)?
What is the exact error you get?

**Comment by davidbarton** [comment]
Ahh, my bad. I forgot I am using sublime package Flet/SublimeLinter-contrib-standard and they did not updated for months now.

**Comment by davidbarton** [comment]
Plus I see it got fixed after I installed latest standard version globally. Thanks.
