### ISSUE TITLE
Odd Indentation Error In Function Default Arguments

### ISSUE THREAD

**Issue by backspaces** [feross/standard#518]
When using a function call for a default function argument, I get an indentation error:

<img width="693" alt="snap 05 11 16-17 10 24" src="https://cloud.githubusercontent.com/assets/124366/15199468/9216702e-179b-11e6-8de8-301c98ba91ef.png">

This seems odd seeing that there is no indentation rules for function parameters, right?

**Comment by backspaces** [comment]
Never mind, it really was an indentation error, .. cut/paste failed. Sigh. Sorry!

**Comment by feross** [comment]
No problem :)
