### ISSUE TITLE
standard output is truncated using node v6

### ISSUE THREAD

**Issue by 75lb** [feross/standard#519]
using node v6, the output from standard is only partially logged to stdout.. it's caused by the new [process.exit()](https://nodejs.org/dist/latest-v6.x/docs/api/process.html#process_process_exit_code) behaviour.

for now, i can get the full output by piping to a file or `pbcopy`.

**Comment by feross** [comment]
Wow, that's unfortunate.

**Comment by 75lb** [comment]
one work-around to this new node v6 behaviour is to replace `process.exit()` calls with 
```js
process.exitCode = 1
return 
```
This allows the process to exit gracefully, without losing any buffered IO, but ironically causes standard to fail every time due to #510 .

**Comment by feross** [comment]
There's discussion of fixing this bug in Node v6 here: https://github.com/nodejs/node/issues/6456

**Comment by feross** [comment]
Turns out this was a pretty easy fix in `standard-engine`.

https://github.com/Flet/standard-engine/pull/108

@75lb If you `npm rm standard && npm install standard` in a few minutes you should get the fix.

**Comment by 75lb** [comment]
confirmed.. cheers brother 👍

**Comment by feross** [comment]
Cheers 🍻

**Comment by Flet** [comment]
Wow this is good info to know regarding v6...

**Comment by feross** [comment]
@Flet Yeah... hoping they find a way to keep writes to stdout async but flush the pending data before exit.
