### ISSUE TITLE
Is it possible to have an optional success message?

### ISSUE THREAD

**Issue by yavorski** [feross/standard#522]
Hi, first of all this project is great. Thank you.
Is it possible to have an optional success message passed via option? 
If answer is yes, should it be in this project or in `standard-engine`?
Thanks in advance.

**Comment by feross** [comment]
> 	
The rule of silence, also referred to as the silence is golden rule, is an important part of the Unix philosophy that states that when a program has nothing surprising, interesting or useful to say, it should say nothing. It means that well-behaved programs should treat their users' attention and concentration as being valuable and thus perform their tasks as unobtrusively as possible. That is, silence in itself is a virtue.

`standard` follows the [Rule of Silence](http://www.linfo.org/rule_of_silence.html).

**Comment by yavorski** [comment]
Hi, thank you for answer!
That makes sense.
