### ISSUE TITLE
sublime plugin and script tags in html

### ISSUE THREAD

**Issue by ncrawlins** [feross/standard#526]
If the script tag is indented, is there a way to get standard to not complain about the space before the closing script tag?
```
  <script>
    console.log('hello')
  </script>
```
this will give the error for trailing spaces not allowed as well as no newline at and of file, but if I don't indent the closing script tag, it's fine, but my OCD hates having script tags nested in other tags not be indented.

is there a way to suppress that error without having to add an ignore rule to every script tag block?

**Comment by feross** [comment]
Yeah, I've run into this before too because I use Sublime Text. But this is really an issue for [SublimeLinter-contrib-standard](https://github.com/Flet/SublimeLinter-contrib-standard). Can you open this issue there?
