### ISSUE TITLE
Badge style guide

### ISSUE THREAD

**Issue by stevemao** [feross/standard#527]
[![js-standard-style](https://cdn.rawgit.com/feross/standard/master/badge.svg)](https://github.com/feross/standard)
Could you please provide the style guide of your badge? I need to make a variant for standard-changelog. EG: font-sizes, font-names, and image size etc.

@maxogden

**Comment by yoshuawuyts** [comment]
Some info about this was posted like a year back in https://github.com/feross/standard/issues/93#issuecomment-87216855 - perhaps it's useful. Cheers!

**Comment by stevemao** [comment]
Thanks @yoshuawuyts ! I think it's still worth to write it some where.

**Comment by feross** [comment]
@stevemao Where should we write it? This seems not useful to users of standard. Let's just use this issue as documentation.

**Comment by stevemao** [comment]
Maybe a wiki page?
