### ISSUE TITLE
async/await - Parsing error: Unexpected token => (null)

### ISSUE THREAD

**Issue by purepear** [feross/standard#528]
```javascript
export function loadThings (creds) {
  return async (dispatch, getState) => {
    try {
      const response = await fetch('http://localhost/api/things')
      return response
    } catch (err) {
      throw (err)
    }
  }
}
```

**Comment by LinusU** [comment]
Totally unrelated but I couldn't help myself, you don't need to `catch` and then `throw` the same error. This function would be functionally equivalent:

```js
export function loadThings (creds) {
  return async (dispatch, getState) => {
    return await fetch('http://localhost/api/things')
  }
}
```

**Comment by purepear** [comment]
@LinusU The code is actually out of context. Got it from a demo source and stripped it. But thanks for the advice.

**Comment by LinusU** [comment]
Cool, I happened to press send a bit early, did you see the solution to your problem?

**Comment by purepear** [comment]
I did now :)
Thanks!
