### ISSUE TITLE
standard exiting non-zero on failure in 0.10

### ISSUE THREAD

**Issue by searls** [feross/standard#529]
Take a look at this build to see the issue:

https://travis-ci.org/testdouble/test-smells/builds/131741480

Standard clearly had a failure on all three VMs, but must have exited code 0 erroneously on Node v0.10.36. To reproduce, you can just clone the repo and check out that commit.

**Comment by feross** [comment]
We dropped 0.10 support in `standard-engine`.

PR to add it back: https://github.com/Flet/standard-engine/pull/109

**Comment by feross** [comment]
Just released standard-engine 4.0.3. If you reinstall `standard` it should work again.
