### ISSUE TITLE
Question about allowed function call

### ISSUE THREAD

**Issue by LinusU** [feross/standard#530]
Should this style of function calling be allowed? I haven't seen it anywhere in the wild until a coworker tried merging it to one of our repos today...

```js
window.addEventListener
  ('keydown', myKeydownHandler, false)
```

I feel that the allowed options should be

```js
window.addEventListener('keydown', myKeydownHandler, false)
```
,
```js
window.addEventListener(
  'keydown',
  myKeydownHandler,
  false
)
```
and possibly
```js
window.addEventListener(
  'keydown', myKeydownHandler, false
)
```

as this is what I've seen being used by the community the most.

**Comment by yoshuawuyts** [comment]
```js
window.addEventListener
  ('keydown', myKeydownHandler, false)
```
seems definitely off. All the other ones feel like a bit of a smell to me, but sure - there's probably a valid use case for them

**Comment by timoxley** [comment]
I use the others on occasion, but parens on a new line seems bad

**Comment by feross** [comment]
Agreed. The paren should not go on a separate line. I don't think there is an eslint rule for this.

Does someone want to volunteer to open an issue / send a PR to eslint to add this?

**Comment by dcousens** [comment]
Agreed,  that is incredibly confusing.
I use the others on occasion, but never parens on a new line.

**Comment by feross** [comment]
This will be fixed in standard v8! I just replaced the deprecated "no-spaced-func" rule with "func-call-spacing" which checks for this!

Commit: https://github.com/feross/eslint-config-standard/commit/f419de5127e83f6e64d2f887bb8615ad1f8c792b

Rule: http://eslint.org/docs/rules/func-call-spacing
