### ISSUE TITLE
disable no-multi-str

### ISSUE THREAD

**Issue by NodeGuy** [feross/standard#532]
I'm being warned that multiline support is limited to browsers supporting ES5 only. (no-multi-str)

```JavaScript
foobar = 'This is a multiline \
string that is allowed by the rules \
but I am being warned anyway.'
```

Multiline strings aren't prohibited by the rules here: https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style

I don't imagine we want the warnings to prevent usage of features found only in ES5 and above.  Let's disable this warning.

Standard version is `7.1.1`.

**Comment by feross** [comment]
This is preferred:

```js
foobar = 'This is a multiline \n' +
'string that is allowed by the \n' +
'rules'
```

**Comment by NodeGuy** [comment]
Ugh.  Mind telling me why?

**Comment by jprichardson** [comment]
https://github.com/feross/standard#i-disagree-with-rule-x-can-you-change-it

> At the end of the day you have to 'just pick something', and that's the whole philosophy of standard -- its a bunch of sensible 'just pick something' opinions. Hopefully, users see the value in that over defending their own opinions.

**Comment by NodeGuy** [comment]
I agree wholeheartedly with the philosophy of the standard.  I'm genuinely curious about the rationale for this one.

**Comment by feross** [comment]
They're exactly equivalent, so we prefer having only one way to do things.

**Comment by NodeGuy** [comment]
Got it, thank you.

**Comment by rstacruz** [comment]
Also, if the js runtime youre using supports multiline strings, then it
probably also supports template strings, which you can use for multiline
too with a much better syntax.

**Comment by NodeGuy** [comment]
THANK YOU!  You just made my night!
