### ISSUE TITLE
Adding extra rules for stricter checks?

### ISSUE THREAD

**Issue by jzaefferer** [feross/standard#534]
I want to disallow `console.log` on my project, using the no-console rule: http://eslint.org/docs/rules/no-console

I read the links in #404 that explained how `rules` was added and removed, but couldn't find a replacement except for "forking". Since I want to make the linter more strict, not less, I'm hoping there is another option here. I tried [this suggestion](https://github.com/feross/standard/issues/159#issuecomment-114810208), but the `.eslintrc` file was ignored - I guess there's more than just adding the file? I didn't find anything related in the docs.

**Comment by ifraixedes** [comment]
Maybe isn't the right solution, but I did that having `.eslintrc.json` extending from standardjs and with the rules that I want to apply added in `rules` property.

Then I run `eslint` command; I think that standardjs doesn't read any `.eslintrc.X` configuration file, that is what have you tried?

**Comment by dcousens** [comment]
> Maybe isn't the right solution, but I did that having .eslintrc.json extending from standardjs and with the rules that I want to apply added in rules property.

This is the right way to do this.

**Comment by jzaefferer** [comment]
> This is the right way to do this.

Is there an example somewhere that shows this setup? I still can't tell how to make this work.

**Comment by dcousens** [comment]
See https://github.com/feross/eslint-config-standard

**Comment by ifraixedes** [comment]
I usually this [`.eslintrc.json` file](https://github.com/ifraixedes/dev-toolbox/blob/master/nodejs/eslintrc.json)

And Installing what is said in the [eslint-config-standard](https://github.com/feross/eslint-config-standard) `eslint` works fine

**Comment by feross** [comment]
@jzaefferer You have to use the `eslint` command directly in order for this to work. The `standard` command is not customizable, by design.
