### ISSUE TITLE
ASI exceptions

### ISSUE THREAD

**Issue by maciejhirsz** [feross/standard#535]
You list `[` and `(` as exceptions for starting new lines without semicolon, someone also added the template string backtick `` ` ``. There is actually more of those:

1) unary `+` and `-` operators:

```
foo = bar
+new Date
```
becomes
```foo = bar + new Date```

2) the regex `/`

```
foo = bar
/baz/g.test('baz')
```
becomes
```foo = bar / baz / g.test('baz')```

That makes it a total of 6 exceptions you have to look out for: `[`, `(`, `` ` ``, `+`, `-`, `/`

**Comment by dcousens** [comment]
> look out for

Is a strong word,  seeing as all of these emit glaring warnings

**Comment by maciejhirsz** [comment]
All of those examples parse fine and produce valid code, it can fail on execution with an exception, but if you are unlucky enough with variable naming, it can also execute fine and produce unexpected behavior.

**Comment by maciejhirsz** [comment]
Aye, I get that, and it's certainly great to have a tool that statically checks against it. My comment is solely about the readme, apologies if that wasn't clear. I think people should make informed decisions, but that only works if the information you get is accurate.

**Comment by feross** [comment]
@maciejhirsz Thanks for your comments. The reason we omitted the other cases in the readme is that they usually don't appear in real code.

```js
foo = bar
+new Date
/baz/g.test('baz')
```

is most likely to be:

```js
foo = bar
myFn(+new Date)
var isBaz = /baz/g.test('baz')
```

The full details are explained in `RULES.md` which is linked at the bottom of the bulleted list in the `README.md`. See here: https://github.com/feross/standard/blob/master/RULES.md#helpful-reading
