### ISSUE TITLE
Need for exclusion of files while running `standard`

### ISSUE THREAD

**Issue by sahildua2305** [feross/standard#536]
While using standardJs in one of my projects which uses MaterializeCSS and JScolor, I felt that I should be able to exclude some files while checking for rules-violations. In my case, I would have excluded these library files to make sure I focus on my own code formatting rather than library's.

Feedback about this idea? I'd be happy to take this and implement it.

**Comment by feross** [comment]
Ignoring files is already supported. See the [readme](https://github.com/feross/standard#how-do-i-ignore-files).
