### ISSUE TITLE
New rule: unicode-bom

### ISSUE THREAD

**Issue by feross** [feross/standard#538]
http://eslint.org/docs/rules/unicode-bom

This was previously covered by `no-irregular-whitespace` but BOM characters at the beginning of files are now stripped by eslint, so adding this rule just gets us the old behavior again.

**Comment by dougwilson** [comment]
What is the suggested value for the rule? `"never"` I assume?

**Comment by feross** [comment]
Yep. Setting it to `"never"` would match the old behavior of the `no-irregular-whitespace` rule.

**Comment by yoshuawuyts** [comment]
I'm only like half-understanding this rule; not spotting any way it affects anything I've ever done with JS so :+1: I guess

**Comment by feross** [comment]
@yoshuawuyts See #283 for some more context, if you're interested.

**Comment by feross** [comment]
This rule will be included in standard v8
