### ISSUE TITLE
Bring --format back

### ISSUE THREAD

**Issue by sheerun** [feross/standard#540]
Isn't auto-formatting a free feature with new eslint? Could you bring it back to standard?

**Comment by rstacruz** [comment]
npmjs.com/package/standard-format

It was a very huge dependency which was wasteful when not needed. You can
still install it separately.

**Comment by sheerun** [comment]
You already depend on `eslint`, and nowadays it has `--fix` flag that does exactly it. No need for extra dependencies.

**Comment by rstacruz** [comment]
ohh... that's a very interesting development. @feross?

**Comment by sheerun** [comment]
Plesae also consider renaming it to "fix". `eslint` and `xo`  already use this convention.

**Comment by Flet** [comment]
There is an issue open on `standard-engine` proposing that the eslint fix flag be added into it.. which could trickle down into `standard`

https://github.com/Flet/standard-engine/issues/107

**Comment by feross** [comment]
Yep, I'm cool with this. The right place to add it is `standard-engine`.

**Comment by feross** [comment]
Sent a PR to `standard-engine` to implement a `--fix` command line flag: https://github.com/Flet/standard-engine/issues/107

This will be included in the next major version release of `standard`.
