### ISSUE TITLE
Usage in Webstorm with ES7

### ISSUE THREAD

**Issue by Alexsey** [feross/standard#542]
There is a <a href="https://github.com/feross/standard/blob/master/docs/webstorm.md">guide of how to config standard for Webstorm</a> and there is a <a href="https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support">guide of how to configure it to use ES7 features</a>. Unfortunately installation of ```babel-eslint``` and mentioning it in ```package.json``` will not help Webstorm to understand ES7 syntax. Is there some other way to do that or Webstorm can't support such?

**Comment by feross** [comment]
I'm not a Webstorm user, but if you figure out a solution please send a PR to update the documentation.

**Comment by Alexsey** [comment]
PR is merged, answers now are in the docs
