### ISSUE TITLE
vim indent plugins

### ISSUE THREAD

**Issue by pomke** [feross/standard#544]
Since our team moved to Standard, I'm having difficulty finding a vim indentation plugin for JS that dos the correct thing, some examples of code structures that break most/all vim indenters I've tried:

single line if statements: 
```javascript
if(foo) return foo
  return bar
```
ending brackets or braces after last item:
```javascript
let foo = [something, somethingElse, somethingExtra, batarang, purpleBallons,
  cats, dogs, lions, tigers, bears]
  // bad indent!
```
I'm jut wondering if any Standard/Vim users have found a better indent, or have workarounds for these issues.

**Comment by mcchrish** [comment]
https://github.com/pangloss/vim-javascript has some recent updates. Seems to do just fine in most cases.

**Comment by feross** [comment]
@pomke Have you given @mcchrish's suggestion a try?

I'm going to close this issue now, as it's been open for a month and I want to keep the issue tracker tidy 👍 Feel free to continue discussion.
