### ISSUE TITLE
Clarify README wording.

### ISSUE THREAD

**Issue by kevinSuttle** [feross/standard#548]
Look, I hate to be _that_ guy, but you can't say "**no configuration**" and "you can't ignore rules", and then admit later on that there _is_ configuration and you _can_ ignore rules, and oh it's actually ESLint.

**Comment by feross** [comment]
Thanks for sharing your concerns.

"No configuration" means "no configuration out of the box". And we don't ever say "you can't ignore rules". The first time we mention ignoring rules, we mention `/* eslint-ignore */` comments (since eslint is used under-the-hood).
