### ISSUE TITLE
Object deconstruction vs. shorthand property name.

### ISSUE THREAD

**Issue by leocavalcante** [feross/standard#549]
`{foo}`

I've seeing people deconstructing just like they construct new objects using shorthand property names. Since there is such standard like space after function name to distinguish function declarations from function calls, then should be nice to have a pattern for this case too.

I usually use spaces for deconstructing:
`{ foo } = bar`

And non-spaces for shorthand property names
`const bar = {foo}`

**Comment by ifraixedes** [comment]
My personal opinions on these kind of rules, is to choose one an used everywhere, less rules are easy to remember than having more and special case; at the end these kind of rules are a matter of style

**Comment by dcousens** [comment]
Related https://github.com/feross/standard/issues/182

**Comment by leocavalcante** [comment]
My bad, I searched for *deconstruction* instead of *destructuring*.
