### ISSUE TITLE
Arrow function should not return assignment

### ISSUE THREAD

**Issue by vdclouis** [feross/standard#552]
Hello!

Just switched to standard with our team. Loving the simplicity!
I do have one question.

Can you somehow hide the `Arrow function should not return assignment` error?
I feel like it should not be an error.

I love the simplicity of
`tags.map(tag => tag.name  = text.text)`

Cheers

**Comment by LinusU** [comment]
I think it's very good, since it can be used to avoid confusion when you missed one of the `=`, e.g.

```js
tags.filter(tag => tag.name = text.text)
```

**Comment by dougwilson** [comment]
And I believe you can just signal that you really meant an assignment by wrapping in parenthesis:
```js
tags.filter(tag => (tag.name = text.text))
```

**Comment by dcousens** [comment]
As pointed out by @dougwilson,  this error is easily averted in a quite aesthetically pleasing way, especially given the safety net it provides as pointed out by @LinusU.

Closing,  but don't let that end the conversation :+1:

**Comment by Alexsey** [comment]
Another argument **against** this rule is usage of immutable data like with <a href="https://facebook.github.io/immutable-js/">`immutable.js`</a> where only way to 'change' something is to reassign. Consider even trivial example
```
let todos = [
  {text: 'first stuff', done: false}, 
  {text: 'second stuff', done: true}, 
   ...
]

todos = todos.map(item => item.done = true)
```
Point is not that it is too hard to parenthesis expression but that the return of assignment is absolutely intended and part of ultra casual operation for working with immutable data but parenthesis is more kind of a way to chit the validation system
