### ISSUE TITLE
Rule suggestion: No spaces in empty array/object declaration

### ISSUE THREAD

**Issue by LinusU** [feross/standard#555]
I would like to propose a rule that prohibits writing empty objects as `{ }` and instead enforces the shorter `{}` which I think is more commonly used. The same would be true for arrays, it should enforce `[]` instead of `[ ]`.

Thoughts? If this is wanted I could probably whip up a pull request towards es-lint.

**Comment by yoshuawuyts** [comment]
Not particularly fussed on this one, I'm fine with it either way

**Comment by LinusU** [comment]
I would also be fine with either way, would prefer it if one of them was enforce though, and I have almost only seen without spaces being used in the community...

**Comment by dcousens** [comment]
+1 for `{}`,  I've almost never seen `{ }` without it being a typo.

**Comment by feross** [comment]
This sounds good to me. Surprised that this isn't already part of the [`object-curly-spacing`](http://eslint.org/docs/rules/object-curly-spacing) rule.

**Comment by feross** [comment]
@LinusU Can you open this as an issue on ESLint to see what the ESLint team thinks? There's nothing we can do in `standard` until there's a rule in ESLint, so I'm going to close this to keep only actionable issues in the issue tracker.

Once this is part of ESLint, I will notice it in the changelog when I upgrade the ESLint version or you can open an issue/PR to add the rule.

**Comment by LinusU** [comment]
Done: eslint/eslint#7380

**Comment by feross** [comment]
Re-opened as https://github.com/eslint/eslint/issues/7927

**Comment by LinusU** [comment]
Thank you ❤
