### ISSUE TITLE
new Image() is no-undef

### ISSUE THREAD

**Issue by sospedra** [feross/standard#562]
When using [HTMLImageElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement) as `new Image()` standard triggers a `no-undef` warning. Is this expected? I mean, `Image` is global... always :/

**Comment by rstacruz** [comment]
It is, in the "browser" environment. Use /* eslint-env browser */ at the
beginning of your file, or (recommended) simply use window.Image.

**Comment by yoshuawuyts** [comment]
@sospedra we tend to limit the amount of globals exposed in the browser, because there are so many of them. Only `window` and `document` are typically exposed. Try running `new window.Image()` instead. Cheers!
