### ISSUE TITLE
New rule: no-constant-condition

### ISSUE THREAD

**Issue by feross** [feross/standard#563]
Disallow constant expressions in conditions.

http://eslint.org/docs/rules/no-constant-condition

This rule is overly broad by default, preventing things like `while (true)` with a `break` inside, which is really common when writing low-level modules like parsers, etc. which is why it was not enabled before now.

However, there is now a `checkLoops` option that can be set to `false` so that only things like this get checked:

```js
if (false) {
  // ...
}
```

So I propose we enable this now.

**Comment by jprichardson** [comment]
Ah, sometimes I use this to "trick" standard (`if (true) return`) with the unreachable code error during development. But overall, this is a good change 👍

**Comment by yoshuawuyts** [comment]
Aye, works for me

**Comment by feross** [comment]
This rule will be included in standard v8
