### ISSUE TITLE
generator function

### ISSUE THREAD

**Issue by pguth** [feross/standard#568]
```js
function* lonelyGenerator () {
  yield "Standard doesn't like me... ꒰•̥̥̥̥̥̥̥ ﹏ •̥̥̥̥̥̥̥̥๑꒱"
}
var gen = lonelyGenerator()
console.log(gen.next().value)
```
```sh
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/user/Desktop/test.js:1:9: Missing space before *.
```

[function*](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/function*)

**Comment by yoshuawuyts** [comment]
Reckon this should do the trick:
```js
function * lonelyGenerator() {}
```

**Comment by pguth** [comment]
Yes, that works but I can hardly think that this is what we want 🙈

**Comment by saadq** [comment]
Personally, I would also prefer either `function* lonelyGenerator () {}` or `function *lonelyGenerator () {}`.

But I think the point of `standard` is that the style rules are already chosen and we have a consensus to follow them instead of arguing about arbitrary spacing and such.

**Comment by feross** [comment]
This is actually an intentional decision. It makes the `*` stand out more. It's been part of standard for several releases now/

**Comment by pguth** [comment]
> This is actually an intentional decision.
Oh, good to know. But weird. Let's see how that feels after a couple of uses.

**Comment by feross** [comment]
Sounds good 👍
