### ISSUE TITLE
Never start a line with `[` - what about nested arrays?

### ISSUE THREAD

**Issue by NeonPaul** [feross/standard#569]
The one potential edge case of this rule that I can see causing a problem:
```javascript
var matrix = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 0]
]
```
In this case, does the standard have any recommendations for styling this code?

**Comment by qzb** [comment]
It's not a problem, standard doesn't raise any errors for this example.

**Comment by feross** [comment]
Yep, there's nothing wrong with the code you posted!
