### ISSUE TITLE
Encourage new users to use v8 beta

### ISSUE THREAD

**Issue by mcchrish** [feross/standard#570]
They might install v7 now, and they might get into problems with huge breaking changes comes v8 release.
(Especially the JSX single quote to double quotes change)
Probably should endorse v8 in the README.md where it will be the most visible?

**Comment by feross** [comment]
Thanks for opening this issue, @mcchrish. There are benefits to mentioning v8 in the readme, but I think we'll hold off on that, as we're still testing the JSX change and waiting for feedback from the other collaborators.
