### ISSUE TITLE
'children' missing in props validation

### ISSUE THREAD

**Issue by ntomallen** [feross/standard#574]
So I reviewed a few of the other issues I saw related to getting this error, but I'm not sure why the issue still persists for me after adding:
```
propTypes: {
  children: React.PropTypes.node
}
```
Here's my code:

.\Components\MainLayout1.jsx
```
import React, { Component } from 'react'
import Navbar from './Navbar.jsx'

// Needed for onTouchTap
// http://stackoverflow.com/a/34015469/988941
import injectTapEventPlugin from 'react-tap-event-plugin'
injectTapEventPlugin()

export default class MainLayout extends Component {
  propTypes: {
    children: React.PropTypes.node
  }
  render () {
    return (
      <div>
        <Navbar />
          <div>{this.props.children}</div> // The error occurs here.
          {/* Put a footer here */}
      </div>
    )
  }
}
```
However, if I change it to this, the error goes away:

.\components\MainLayout2.jsx
```
import React, { Component } from 'react'
import Navbar from './Navbar.jsx'

// Needed for onTouchTap
// http://stackoverflow.com/a/34015469/988941
import injectTapEventPlugin from 'react-tap-event-plugin'
injectTapEventPlugin()

class MainLayout extends Component {
  render () {
    return (
      <div>
        <Navbar />
          <div>{this.props.children}</div>
          {/* Put a footer here */}
      </div>
    )
  }
}

MainLayout.propTypes = {
  children: React.PropTypes.node
}

export default MainLayout
```
Why does the second method work, while the first does not?

**Comment by feross** [comment]
It looks like you're using an old version of `standard`. The latest version is 7.1.2. Can you update to the latest version?

```js
npm install standard@latest --save-dev
```

Or if you have it installed globally:

```js
npm install -g standard
```

**Comment by ntomallen** [comment]
I tried a global install of standard run on that specific file and there were no issues. I'm still getting the issue inside Atom, however. (7.1.2 is installed locally as well.) Should I make an issue for `linter-js-standard`?

**Comment by feross** [comment]
There's an issue on `linter-js-standard` about this: https://github.com/ricardofbarros/linter-js-standard/issues/124

But according to a comment from the maintainer @ricardofbarros, it sounds like if you're using the latest version of `linter-js-standard` then your local version of `standard` *should* be used instead of the version they're shipping.

Can you ensure you're using the latest version of `linter-js-standard`?

**Comment by ntomallen** [comment]
Standard is specified in my package.json as `"standard": "^7.1.2"` since I just set up the project today.. I ran the `install standard@latest` command again but it doesn't look as if anything changed. Also running `linter-js-standard` v3.4.1 so that looks fine.

**Comment by feross** [comment]
@ntomallen This sounds like it's either a bug in `linter-js-standard`, or you still have an old version of `standard` somewhere that's getting used.

**Comment by ntomallen** [comment]
@feross It could be an issue with my installation, but since I installed it for the first time two days ago, I don't think there would be any old `standard` installations. I'm guessing `linter-js-standard`, but I'll try to replicate it on a different machine before creating an issue over there.

**Comment by feross** [comment]
@ntomallen Sorry you're having trouble getting this to work. Best of luck figuring it out!

**Comment by ntomallen** [comment]
No worries!
