### ISSUE TITLE
Spaces for indentation? 

### ISSUE THREAD

**Issue by mauvm** [feross/standard#58]
I really like this forced standard! It's simple and will be effective. The only thing I can't get my head around is the 2 space indentation.

Why not use tabs instead? So that everyone in the team can configure their own horizontal depth?

**Comment by mauvm** [comment]
Oh and sorry for being a b*tch about this. I just want to use this in my projects, but probably won't get everyone on board..

**Comment by maxogden** [comment]
@mauvm there are lots of debates online about tabs vs spaces. at the end of the day you have to 'just pick something'. thats the whole philosophy of `standard` -- its a bunch of sensible 'just pick something' opinions, and users will have to see the value in using that over defending their own opinions

**Comment by feross** [comment]
Yep, what max said. :)

**Comment by hugomallet** [comment]
For me this is a bad choice. But this debate will probably never end.
So why not keep this choice configurable? (maybe using ".editorconfig"?)

**Comment by dcposch** [comment]
Locking for the same reason as #78 
If you care a lot about tabs vs spaces, standard isn't for you. 
You can always use eslint directly.
