### ISSUE TITLE
Sourcing multiple files?

### ISSUE THREAD

**Issue by maasha** [feross/standard#582]
If I have a function defined in one file that is used in another file I get warnings on defined but not used and not defined. What can be done?

**Comment by feross** [comment]
If you're using a module loading system, like browserify's `require()` then this won't be an issue.

### a.js

```js
exports.foo = function () {}
```

### b.js

```js
var a = require('./a')
a.foo()
```

But it sounds like you're just including both a.js and b.js in a page via `<script>` tags.

### a.js

```js
function foo () {}
```

### b.js

```js
foo()
```

### index.html

```html
<script src="a.js"></script>
<script src="b.js"></script>
```

To make the relationship between these files, clear to the linter (and to readers of your code), you should explicitly reference where the `foo()` function is coming from in `b.js`.

### b.js

```js
window.foo()
```

That should fix your issue!

**Comment by maasha** [comment]
Great, thanks!

**Comment by maasha** [comment]
One note. The `window.foo()` explicit call does silence the warning in `b.js` but in `a.js` I still get a `foo is defined but never used` warning

**Comment by imjoehaines** [comment]
In `a.js`, if you assign your function to `window.foo` instead of just `foo` then the warning should go away

**Comment by feross** [comment]
Yep, what @imjoehaines said.

**Comment by LinusU** [comment]
Also see #619 which might influence your decision to use, or not to use, `window`
