### ISSUE TITLE
Standard add semicolon to beginning of onChange jsx callback

### ISSUE THREAD

**Issue by kasperpeulen** [feross/standard#588]
```jsx
        <FormControl
          type='text'
          value={exerciseId}
          placeholder='Enter exercise id'
          onChange={;(e) => dispatch(new Actions.ChangeExerciseId(e.target.value))} />
        {helpBlock}
        <FormControl.Feedback />
```

Look at the onChange callback.

**Comment by timoxley** [comment]
But why

**Comment by kasperpeulen** [comment]
Context: I used `standard-format` package of atom. Before I formatted, there was no semicolon there, it also breaks the code.

**Comment by feross** [comment]
The latest version of `standard-format` fixed this issue already. See: https://github.com/maxogden/standard-format/issues/165

Anyway, I recommend using `standard --fix` going forward (once standard v8 is released), or you can try it out today using `npm install standard@beta`.
