### ISSUE TITLE
Standard removes my line breaks in jsx, makes it one big line

### ISSUE THREAD

**Issue by kasperpeulen** [feross/standard#589]
I had this code:
```jsx
            <FormControl
                componentClass='select'
                value={selectedAction}
                onChange={e => dispatch(new Actions.ChangeSelected(e.target.value))}>
              {actions.map(action => <option key={action} value={action}>{action}</option>)}
            </FormControl>
```

Now standard formatter (atom package) turns it into this:

```jsx
            <FormControl componentClass='select' value={selectedAction} onChange={e => dispatch(new Actions.ChangeSelected(e.target.value))}>
              {actions.map(action => <option key={action} value={action}>
                                       {action}
                                     </option>)}
```

I normally try to make my lines not longer than 80. I think 120 is also fine. But this is 150 chars or something on one line. Way too long.

**Comment by Flet** [comment]
For clarity, is this `standard --fix` or `standard-format`?

**Comment by kasperpeulen** [comment]
I use atom `standard-format` so I think `standard-atom`.

**Comment by feross** [comment]
@kasperpeulen Since this is an issue for standard-format, please open it on that repo. https://github.com/maxogden/standard-format But know that the maintainers of `standard-format` are currently very overwhelmed, so consider sending a PR if you want this fixed.

I recommend using `standard --fix` going forward (once standard v8 is released), or you can try it out today using `npm install standard@beta`.

**Comment by kasperpeulen** [comment]
Ah, okay, do I understand correctly that `standard --fix` and `standard-format` are two different things doing the same thing, where the first one is a new official one?

**Comment by feross** [comment]
The first one is integrated directly into `standard` and comes from the auto-fixing feature built into eslint, so it's 100% based on the eslint configuration file. It will never be out-of-date like `standard-format` (which is based on a separate tool `esformatter`).

If your code is ES5, `standard-format` is actually a more thorough tool.
If you need ES6 support, `standard --fix` works better, though it covers slightly fewer cases at the moment. But it's getting better with each eslint release.

See http://eslint.org/docs/rules/ and look at the rules with the wrench icon to see which rules `standard --fix` can automatically fix.

**Comment by kasperpeulen** [comment]
Sounds good! Is there a way to get this working in atom as well?

**Comment by feross** [comment]
You can ask the maintainers of one of these modules:

https://atom.io/packages/linter-js-standard
https://atom.io/packages/standard-formatter
