### ISSUE TITLE
Support for flow syntax extensions.

### ISSUE THREAD

**Issue by Gozala** [feross/standard#592]
Is there way to support [flow](https://flowtype.org) syntax extensions for projects that want to use that ?

**Comment by jprichardson** [comment]
You can, just use the `babel-eslint` parser for Standard and add the necessary plugins for Babel. This is what I use: https://github.com/codemix/babel-plugin-typecheck

**Comment by Gozala** [comment]
So I run into following issue https://github.com/gajus/eslint-plugin-flowtype/issues/72 when using standard with `babel-eslint` and `eslint-plugin-flowtype`

**Comment by Gozala** [comment]
Also https://github.com/babel/babel-eslint/issues/293 seems relevant here.

**Comment by feross** [comment]
@Gozala Are you specifying the flowtype plugin in your `package.json` config for `standard` like this?

```json
{
  "standard": {
    "plugins": ["flowtype"]
  }
}
```

Setting a custom parser and plugins are the only ways you can try to solve this issue with `standard`. We intentionally don't support enabling/disabling rules.

If you require enabling extra rules from the flowtype plugin and/or disabling rules in `standard` to get your code to pass, then I would suggest using eslint directly in your project. You can extend from [eslint-config-standard](https://github.com/feross/eslint-config-standard) and just change the few rules you need to change.

**Comment by Gozala** [comment]
@feross Yeap that is pretty much what I use:

```json
{
  "standard": {
    "parser": "babel-eslint",
    "plugins": [
      "flowtype"
    ]
}
```

The problem as described in babel/babel-eslint#293 is that babel-eslint does not seem to have a way of informing eslint that type import is different from value import & there for eslint will report duplicate imports.

> If you require enabling extra rules from the flowtype plugin and/or disabling rules in standard to get your code to pass, then I would suggest using eslint directly in your project. You can extend from eslint-config-standard and just change the few rules you need to change.

That is what I end up doing for now, but I would much rather not do that. Maybe standard could avoid this issue by using [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) instead of stock no-duplicates ?

**Comment by feross** [comment]
The import plugin actually looks really well done. Adding another eslint plugin is not ideal for running time, but if there are other rules in there that would make `standard` catch more errors, I'm open to considering it. (As an added bonus, flow type annotations would work again.)

**Comment by Gozala** [comment]
> but if there are other rules in there that would make standard catch more errors, I'm open to considering it.

@feross I believe it primary selling point is:

> prevent issues with misspelling of file paths and import names

Also should I open new issue regarding duplicate imports issue caused by `import type ` ?

**Comment by Gozala** [comment]
> Setting a custom parser and plugins are the only ways you can try to solve this issue with standard. We intentionally don't support enabling/disabling rules.

Would not it be reasonably to allow configuring those plugins ? It would not solve the duplicate imports issue I'm afraid, but I did also notice that I'm unable to configure `flowtype` plugin which can catches bunch of errors otherwise.

**Comment by Gozala** [comment]
Created a separate issue in regards to `no-duplicate-imports`  casted by `import type`:
https://github.com/feross/standard/issues/599

**Comment by feross** [comment]
> Would not it be reasonably to allow configuring those plugins ? It would not solve the duplicate imports issue I'm afraid, but I did also notice that I'm unable to configure flowtype plugin which can catches bunch of errors otherwise.

This is a slippery slope. When you see `standard` is being used on a repo, we want that to mean something. If you can configure rules, then it means less because contributors will need to see exactly which rules you have added before jumping in. This was discussed extensively in https://github.com/feross/standard/issues/399 and it was decided not to support this.

If you really want a flow-type variant of `standard`, I suggest writing a fork like `standard-flow`. You can see https://github.com/feross/standard-react or https://github.com/Flet/semistandard for an example of how to write a fork of `standard` that extends the existing rules and modifies a few of them.

**Comment by Gozala** [comment]
> If you really want a flow-type variant of standard, I suggest writing a fork like standard-flow. You can see https://github.com/feross/standard-react or https://github.com/Flet/semistandard for an example of how to write a fork of standard that extends the existing rules and modifies a few of them.

Thanks. I have followed this advice and created https://github.com/Gozala/standard-flow and https://github.com/Gozala/eslint-config-standard-flow to add flow support and lint type annotations with the same rules as rest of the code.

**Comment by ArmorDarks** [comment]
I think that forcing forks is terrible idea, because they almost always lags behind main library and ends up unmaintained.
