### ISSUE TITLE
Consider alternative style for ternary operators

### ISSUE THREAD

**Issue by Gozala** [feross/standard#598]
Is there a chance I could persuade you to adopt alternative style for ternary operators:

```js
var location =
  ( env.development
  ? 'localhost'
  : 'www.api.com'
  )
```

It has better readability than case where first condition is placed on the same line as assignment, especially if many ternaries are chained.

Note that this is almost accepted by standard it just does not like space after `(`:

```js
var location =
  (env.development
  ? 'localhost'
  : 'www.api.com'
  )
```

Thanks for taking time to read & consider.

**Comment by LinusU** [comment]
I don't think that it looks that readable, have you considered the following style? 

```js
var location = env.development
  ? 'localhost'
  : 'www.api.com'
```

**Comment by Gozala** [comment]
Well proposed style is also more compatible with ternaries as arguments, while currently recommended option is not.

**Comment by feross** [comment]
Thanks for the suggestion, but I think the current style is clearest. Also, there's not even a way to configure ESLint to allow the style you've suggested, since it's pretty unique (I've never seen it before)

**Comment by Gozala** [comment]
@feross mind clearing up how following examples should be formatted then ?

```js
export const clip =
  (min:number, max:number, n:number):number =>
  ( n < min
  ? min
  : n > max
  ? max
  : n
  )
```


Or case with multiple branches:


```js
const thingy =
  ( message.type === "ForFoo"
  ? ( model.kind === "Foo"
    ? doSomething(model, message.payload)
    : panic(model, message)
    )
  : message.type === "ForBar"
  ? ( model.kind === "Bar"
    ? doOtherThingk(model, message.payload)
    : panic(model, message)
    )
  : panic(model, message)
  )
```
 
Thanks

P.S.: Just trying to figure out how to reformat our current code base to standard & run into things that look little odd with standardjs

**Comment by yoshuawuyts** [comment]
@Gozala first time I'm seeing code like you wrote it. Perhaps this valid standard syntax might be closer to liking:
```js
const thingy = (message.type === 'ForFoo')
  ? (model.kind === 'Foo')
    ? doSomething(model, message.payload)
    : panic(model, message)
  : (message.type === 'ForBar')
    ? (model.kind === 'Bar')
      ? doOtherThingk(model, message.payload)
      : panic(model, message)
    : panic(model, message)
```

**Comment by dcousens** [comment]
Multi-ternary expressions... smells like an eslint feature request.
