### ISSUE TITLE
selectively disabling rules on a case-by-case basis. maybe.

### ISSUE THREAD

**Issue by timoxley** [feross/standard#6]
Sometimes I do actually want `==`. I can't think of any usecases now but I find that on occasion I explicitly opt for `==`. 

I'm wondering if some of these style restrictions could be selectively 'disabled' for a particular case if a comment is present to explain why an ill-advised practice was used instead of best practice. 

```js
"use strict"
var items = getCurrentItems()
// style: my religion speaks of a prophecy where vile, dark beings
// enter this realm and do unspeakable things to its inhabitants should 
// the chosen one (me, lol) fail to protect the semicolon of the 7th line of
// the 7th file. Remove this semicolon at your peril.
items = items.map(function(n) { return n * 2});
console.log(items)
```

maybe.

**Comment by feross** [comment]
Hahahah, nice.

I just added documentation for how to ignore specific warnings. See: https://github.com/feross/standard#how-do-i-hide-a-certain-warning

**Comment by feross** [comment]
The most useful use-case for `==` is to check if a value is equal to `undefined` or `null`, like this:

```js
if (obj == null) {
  // obj is `null` or `undefined`
}
```

Which is nicer than:

```js
if (obj === null || obj === undefined) {
  // obj is `null` or `undefined`
}
```

**Comment by feross** [comment]
JavaScript Standard Style allows `== null` out-of-the-box without needing to hide any warnings.

If you want to use it in other ways, you'll need to ignore that warning.

**Comment by soyuka** [comment]
+1 about `==`, this is the one case that is really usefull! You can't just use `===` everywhere, but you should know the difference.

**Comment by feross** [comment]
Since the common case of `== null` is allowed by default, and there's a way to hide the warnings in other cases, I'm going to close this issue now. But you can feel free to continue discussion if there's interest.

**Comment by timoxley** [comment]
Perfect.

**Comment by feross** [comment]
Yay!
