### ISSUE TITLE
Document/add programmatic use?

### ISSUE THREAD

**Issue by bcomnes** [feross/standard#60]
I'm trying to write some tests for `standard-format` and want to run standard against some strings inside the test.  So far the CLI seems to be the only thing documented.  It would be nice to have some documentation on how/what I can do once I `require('standard')`.  I'll try to contribute some after I get my head wrapped around what is available and opening this issue in the meantime.

**Comment by bcomnes** [comment]
For example, it would be great to have some kind of interface that lets me pass in a file or string to standard, and get back an array of error objects or something.

**Comment by feross** [comment]
There is some documentation here: https://github.com/feross/standard/blob/master/index.js#L37-L47

Right now `require('standard')` doesn't let you test strings. Only stdin, or a list of file paths. I'd accept a PR that makes it support testing strings, though you'd need to get this working with eslint and jscs.

Also, `index.js` currently prints to stdout instead of returning an array of errors. We should change this to do the printing in `cmd.js`.

PRs welcome!

**Comment by bcomnes** [comment]
I'll see what I can do sometime soon.

**Comment by feross** [comment]
If you get this done in the next day or two, we can include this in the v3.0.0 release.

**Comment by bcomnes** [comment]
I'm going to try and look at it in the morning tomorrow.  Don't wait around for me though ;)

--
Bret Comnes
http://bret.io

**Comment by bcomnes** [comment]
I have checking of strings working in jscs here: https://github.com/bcomnes/standard/tree/dev  Ill try for eslint tomorrow.

**Comment by bcomnes** [comment]
Arg... getting distracted over here.  I think im going to finish up https://github.com/bcomnes/sublime-standard-format before I can get to this issue so please dont wait for me.

**Comment by feross** [comment]
This is done! But it's currently on the `speed` branch. We'll merge into `master` soon, but feel free to give it a try now and confirm that it works for your purposes :+1: 

`standard` now exports two functions: [`lintText`](https://github.com/feross/standard/blob/c2a231e7aa1bb1b02989f700c0c2d31330ff45fb/index.js#L27-L35) and [`lintFiles`](https://github.com/feross/standard/blob/c2a231e7aa1bb1b02989f700c0c2d31330ff45fb/index.js#L52-L60). They are documented inline in the source.

**Comment by bcomnes** [comment]
Thanks maaan! Sorry I couldn't pull through on this.  Will help with writing standard-format tests.

**Comment by feross** [comment]
No problem :+1:

**Comment by feross** [comment]
Let's leave this open until `speed` is merged into `master`.

**Comment by bcomnes** [comment]
Oh derp.  Good point

**Comment by feross** [comment]
This is released as 3.3.0.

**Comment by bcomnes** [comment]
Boo ya!
