### ISSUE TITLE
Allow configuring plugin rules

### ISSUE THREAD

**Issue by Gozala** [feross/standard#600]
For example ESLint [flowtype](https://github.com/gajus/eslint-plugin-flowtype) plugin provides bunch of linting rules for flow syntax extensions. Without it's standard kind of completely ignores flow annotations and no actual style is enforced.

Would not it be reasonable to allow configuring plugins given that you can use them with standard ?

**Comment by feross** [comment]
See https://github.com/feross/standard/issues/592#issuecomment-241137907
