### ISSUE TITLE
standard flow

### ISSUE THREAD

**Issue by Gozala** [feross/standard#601]
So standard sort of works with flow, but not really see: #599 #600 I wonder if it would make sense to support flow out of the box ? Or maybe there should be a sibling project like `flowtype/standard` preconfigured to be used with flow type projects ?

**Comment by thejameskyle** [comment]
Can't you use https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support

**Comment by Gozala** [comment]
@thejameskyle Please see mentioned issues #599 and #600 which should explain why just custom parser is not enough.

**Comment by Gozala** [comment]
There is also https://github.com/babel/babel-eslint/issues/366

**Comment by feross** [comment]
See https://github.com/feross/standard/issues/592#issuecomment-241137907

**Comment by Gozala** [comment]
I have created https://github.com/Gozala/standard-flow and https://github.com/Gozala/eslint-config-standard-flow based off react standard-react and eslint-config-standard-react

**Comment by feross** [comment]
@Gozala Thanks for the link and publishing that module.

**Comment by GantMan** [comment]
Awesome @Gozala -  I LOVE standard, but I need static type checking to write even better code.  I'll be using your library.  Please let me know if there's any way I can help.
