### ISSUE TITLE
`async` syntax causes `Parsing error: Unexpected token`

### ISSUE THREAD

**Issue by zeke** [feross/standard#602]
This test passes, and [babel](http://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=const%20%7Btest%7D%20%3D%20require('ava')%0A%0Atest('foo'%2C%20t%20%3D%3E%20%7B%0A%20%20t.pass()%0A%7D)%0A%0Atest('bar'%2C%20async%20t%20%3D%3E%20%7B%0A%20%20const%20bar%20%3D%20Promise.resolve('bar')%0A%20%20t.is(await%20bar%2C%20'bar')%0A%7D)%0A) doesn't seem to have a problem with it:

```js
const {test} = require('ava')

test('bar', async t => {
  const bar = Promise.resolve('bar')
  t.is(await bar, 'bar')
})
```

but standard doesn't like it:

```
standard: Use JavaScript Standard Style (http://standardjs.com) Try `standard --fix` to automatically fix problems.
  /Users/zeke/zeke/repos-using-electron/test/index.js:3:19: Parsing error: Unexpected token t
```

```
❯ ./node_modules/.bin/standard --version
8.0.0-beta.5
```

**Comment by feross** [comment]
@zeke I think you may have accidentally run a global version of `standard`. Can you check if `standard --version` is an older version?

**Comment by sotojuan** [comment]
Try doing [this](https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support).

`npm install --save-dev babel-eslint`

Then in `package.json`:

```js
 "standard": {
  "parser": "babel-eslint"
}
```

I'm on the AVA team and this has happened to me many times 😅

**Comment by zeke** [comment]
I'm running the local version, 8.0.0-beta.5

```
❯ ./node_modules/.bin/standard          
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/zeke/zeke/repos-using-electron/test/index.js:3:19: Parsing error: Unexpected token t

❯ ./node_modules/.bin/standard --version
8.0.0-beta.5

❯ cat test/index.js                     
const {test} = require('ava')

test('bar', async t => {
  const bar = Promise.resolve('bar')
  t.is(await bar, 'bar')
})
```

**Comment by feross** [comment]
@zeke Try following @sotojuan's advice in an earlier comment.

You need to specify `babel-eslint` as your eslint parser if you want to use the `async` syntax. Once you do that, it'll work!

```
$ ./node_modules/.bin/standard --version
8.0.0-beta.5
$./node_modules/.bin/standard t.js
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/feross/code/test/t.js:3:19: Parsing error: Unexpected token t
$ ./node_modules/.bin/standard --parser babel-eslint t.js
```

Though it's easier to use the `package.json` method to specifying the parser, IMO.

**Comment by zeke** [comment]
Thank you @sotojuan and @feross

**Comment by timdp** [comment]
@feross Per your recent tweet, isn't `async` supported out of the box with standard@8.2.0? I'm still getting errors.

**Comment by feross** [comment]
@timdp See this issue (https://github.com/feross/standard/issues/645)

The last release (`8.2.0`) added ES7 support, but `async` actually is part of the ES8 spec. Fortunately, we just enabled ES8 support in `8.3.0` -- released just a couple minutes ago.

Give `8.3.0` a shot -- should work really nicely, without the need for `babel-eslint`!

**Comment by timdp** [comment]
@feross That's awesome, thanks!
