### ISSUE TITLE
Update docs to remove standard-format references

### ISSUE THREAD

**Issue by 0x00A** [feross/standard#606]
I recently started using the vim integration and realized a behavior that I'm not sure is correct.

I have vim set up to use `standard-format` when I save. Some code that looks like this...

``` js
SomeModule.someMethod({ foo }, cb)
```

It is re-written as...

``` js
SomeModule.someMethod({ foo}, cb)
```

But then I also get a message saying...

``` txt
Expected consistent spacing (standard/object-curly-even-spacing)
```

**Comment by dcousens** [comment]
Latest version?

**Comment by 0x00A** [comment]
Yes

**Comment by Flet** [comment]
This would be an issue with `standard-format`. 

I believe there are a few open issues regarding this kind of spacing: 
https://github.com/maxogden/standard-format/issues?utf8=%E2%9C%93&q=spacing

You may want to try the latest version of `standard` and use `standard --fix` instead. It uses eslint's fix flag which seems to be a bit more consistent (but does not cover as many things).

Closing this issue as it should already be covered over at `standard-format` +1

**Comment by timoxley** [comment]
@0x00A there's a bunch of issues with `standard-format` and modern syntax. I suggest perhaps adjusting your vim integration to use `standard --fix` instead.

**Comment by 0x00A** [comment]
@Flet Maybe the `standard-format` module is broken. The *real* problem though, is that the documentation advises using something that directly conflicts/breaks the `standard` module. Maybe the fix is to just update the documentation?

**Comment by LinusU** [comment]
@0x00A Standard v8 (current release) recommends using `--fix` instead of the standalone `standard-format`

**Comment by 0x00A** [comment]
@LinusU hey, i'm already on the current release and you are the second person in this thread to suggest using `--fix` (https://github.com/feross/standard/issues/606#issuecomment-243327741). But that's not the issue. The issue is that the documentation is wrong (https://github.com/feross/standard/blob/master/README.md#vim).

**Comment by LinusU** [comment]
Didn't realize that there where vim-specific instructions, yes those should probably be updated...

**Comment by feross** [comment]
Re-opening this issue since the documentation should not encourage use of `standard-format` going forward. It's too much of a maintenance burden IMO and `standard --fix` works better with ES6+ syntax.

Would a vim user be kind enough to update the docs to use `standard --fix`, confirm everything works, and send a PR?

**Comment by mgonzaleza** [comment]
@feross You already fixed this issue on commit [4c82bc8](https://github.com/feross/standard/commit/4c82bc846ec3e869f481df76137d8b62a54e111a#diff-04c6e90faac2675aa89e2176d2eec7d8)

**Comment by mgonzaleza** [comment]
@feross You already updated the doc for VIM on commit [4c82bc8](https://github.com/feross/standard/commit/4c82bc846ec3e869f481df76137d8b62a54e111a#diff-04c6e90faac2675aa89e2176d2eec7d8).

**Comment by feross** [comment]
@mgonzaleza Thanks for pointing out. This issue can be closed now.
