### ISSUE TITLE
supporting foreach style for-loops

### ISSUE THREAD

**Issue by matthewmueller** [feross/standard#607]
One pattern I use a lot is a for-loop that looks like this:

```js
for (let i = 0, token; token = tokens[i]; i++) {
  // do something with token
}
```

This errors out, saying: 

```
Expected a conditional expression and instead saw an assignment
```

I think this is totally appropriate. Unfortunately there's no way to get around this error without changing the loop completely. Here's a syntax that I think should work:

```js
for (let i = 0, token; (token = tokens[i]); i++) {
  // do something with token
}
```

Since it's explicit that there's an assignment, but it'll give the same error as previously.

**Comment by yoshuawuyts** [comment]
hah, this feels like such a hack but I quite like it :sparkles: - I might just stop writing `forEach` style loops if we can make this pass C:

**Comment by LinusU** [comment]
I think it makes sense as well, using parenthesis to indicate that you want assignment _and_ comparison is okay in other places :ok_hand:

Also, I think that the following syntax should work in newer runtimes:

```js
for (const [i, token] of tokens.entries()) {
  // ...
}
```

**Comment by matthewmueller** [comment]
@yoshuawuyts it's great for async/await and generator environments because there's no new `async function` or `function *` you need to create.

Just have to be a bit more careful about falsey values. In practice I've only run into that issue like 3 times over the last couple years though.

**Comment by jieverson** [comment]
What about:
```
tokens.forEach((token, i) => { // do something with token })
```

**Comment by dcousens** [comment]
> for (let i = 0, token; token = tokens[i]; i++) {

Lets hope you're not using numbers, or anything falsy...

**Comment by matthewmueller** [comment]
@jieverson 

This approach saves a function allocation and allows you to do this more easily:

```js
for (let i = 0, url; (url = urls[i]); i++) {
  await fetch(url)
}
```

@dcousens yep:

> Just have to be a bit more careful about falsey values. In practice I've only run into that issue like 3 times over the last couple years though.

**Comment by jieverson** [comment]
Still kind unreadable

**Comment by matthewmueller** [comment]
That's your opinion. Discussing how this code looks and the potential pitfalls of this approach is completely besides the point of this issue. 

Please assume that the user knows the pitfalls and doesn't share your opinion on how it looks.

**Comment by timoxley** [comment]
@dcousens unreadable vs unfamiliar perhaps. I think if this were more common it could be parsed with a glance – so long as people don't hide other fancy logic in there.

I've not used this pattern but it's kinda nice in that it removes the crappy extra line to assign a variable to the current iteration in a `for` i.e.

```js
for (let i = 0; tokens.length; i++) {
  const token = tokens[i] // gross
}
```

From a quick benchmark on node 6.3.1 and performance for this pattern is somewhere between `for` and `forEach`. See the `ForAlt` result below, where each pattern iterates over 10,000,000 items.

```
For: 186.791ms
ForAlt: 270.132ms
ForEach: 458.686ms
ReduceFunction: 321.777ms
ReduceArrows: 334.990ms
ForOf: 1565.900ms
```

[benchmark gist](https://gist.github.com/timoxley/b6463357aaea004711d8583142299de4)

> Discussing how this code looks and the potential pitfalls of this approach is completely besides the point of this issue.

@matthewmueller 
If I'm not mistaken "how the code looks" and "helping the user avoid pitfalls" are some of the key concerns of `standard`, right?

**Comment by matthewmueller** [comment]
> If I'm not mistaken "how the code looks" and "helping the user avoid pitfalls" are some of the key concerns of standard, right?

@timoxley Not really sure if "how the code looks" with regards to readability is a goal of standard or not, definitely standardization of the syntax though.

I'm not sure standard should prevent a useful pattern altogether, because there's a potential pitfall. It'll still fail if you just do that outright, but the `( ... )` is more of an "opt-in" to this pattern.

**Comment by dcousens** [comment]
@timoxley to be clear,  I never commented on the readability,  just the fact it is less safe and potentially not going to be part of "helping the user avoid pitfalls".

**Comment by timoxley** [comment]
> Still kind unreadable

@dcousens whoops somehow I read this as your comment, my bad.

**Comment by feross** [comment]
I think it's fine to allow this behavior as an opt-in with explicit parens. We already allow this type of opt-in in other places in `standard` so this change would be consistent.

**Comment by feross** [comment]
@matthewmueller Are you using the latest version of `standard`, v8.0.0?

This code lints without any issues for me.

```js
var tokens = []
for (let i = 0, token; (token = tokens[i]); i++) {
  console.log(i, token)
}
```

Apparently this [used to be a bug](https://github.com/eslint/eslint/issues/4023) in an old version of eslint, but it was fixed a while ago.

**Comment by matthewmueller** [comment]
interestinggg. yep upgrading seems to fix it. sorry for the false alarm!
