### ISSUE TITLE
Can't ignore files

### ISSUE THREAD

**Issue by mvaragnat** [feross/standard#608]
This lib is great, thank you. However I ran into a small issue with one project. I read the readme, but I am not able to ignore files when running standar.

I would like to excluse a specific lib in /public/js/, but to illustrate I went as far as having the following block in package.json. In spite of that, standard runs on all files. Any idea of what I'm doing wrong? 

```
"standard": {
      "ignore": [
        "public/*",
        "**/*.js"
      ]
    }
```

Related question, how do you ignore files if standard is installed locally on the machine and not as a project dependency? I tried both options but the result is the same, files are not ignored.

Thanks for your help!

**Comment by jonathan-potter** [comment]
👍  for simple way to turn this off for a file or directory.

Sometimes you have to read code from projects that you do not control, so it would be nice to be able to turn this off.

maybe `standard --disable` or somesuch which would just dump a .standardrc file in the directory.

**Comment by feross** [comment]
To ignore a specific folder (say "public/js/ignoredlibrary"), you can add the following to `package.json`:

```json
{
  "standard": {
    "ignore": [
      "public/js/ignoredlibrary/**/*.js"
    ]
  }
}
```

> Related question, how do you ignore files if standard is installed locally on the machine and not as a project dependency?

This shouldn't matter. `standard` will still look for the nearest `package.json` from the current working directory that you run `standard` from. So your ignore rules should be obeyed.

**Comment by mvaragnat** [comment]
Thanks @feross ! Actually, my mistake was to add that "standard" object into the "depencies" field of package.json ! I thought it was an option to add to the depency.

I hope others are not as stupid as me :-)

**Comment by feross** [comment]
@mvaragnat No worries. Glad you got it figured out.
