### ISSUE TITLE
support app node_modules

### ISSUE THREAD

**Issue by ahdinosaur** [feross/standard#61]
we use the [`src/node_modules` pattern](https://medium.com/node-js-javascript/working-without-frameworks-part-1-b948f281f782) in our apps (e.g. [here](https://github.com/cobudget/cobudget-ui) and [here](https://github.com/holodex/app)), so the default ignore of `**/node_modules/**` doesn't work for us.

previous discussion in https://github.com/feross/standard/pull/35.

possible solutions already brought up:
1. ["we could ignore node_modules if a package.json is present in the same directory"](https://github.com/feross/standard/pull/35#issuecomment-74837466)
2. [implement a way to un-ignore a directory](https://github.com/feross/standard/pull/35#issuecomment-74775195)

1 makes a lot of sense, i don't see how [it wouldn't work](https://github.com/feross/standard/pull/35#issuecomment-74993242) as the `src/node_modules` pattern as i understand it doesn't involve a `src/package.json`. keen to hear what people think, am happy to implement a PR for this.

**Comment by feross** [comment]
Yeah, I actually think 1 would work. Happy to consider a PR for it.
