### ISSUE TITLE
padded-blocks for classes and switches

### ISSUE THREAD

**Issue by caesarsol** [feross/standard#610]
As of now, the `padded-blocks` rule is configured as:

```
"padded-blocks": [2, "never"],
```

Since:

> "always" requires empty lines at the beginning and ending of block statements (except `switch` statements and classes)
> "never" disallows empty lines at the beginning and ending of block statements

And this implies that in classes and switch statements the never-padded-blocks is not enforced, wouldn't it be coherent to modify the rule as this?

```
"padded-blocks": [2, { "blocks": "never", "switches": "never", "classes": "never" }],
```

Here is the reference: http://eslint.org/docs/rules/padded-blocks#classes

**Comment by feross** [comment]
@caesarsol Yes, you're right. It looks like these additional cases were added to eslint but aren't covered by the current "never" setting.

We'll add this in standard v9.

**Comment by caesarsol** [comment]
Perfect, thanks!

**Comment by feross** [comment]
This will be part of standard v9. No ecosystem impact.
