### ISSUE TITLE
RegExp

### ISSUE THREAD

**Issue by simone-sanfratello** [feross/standard#611]
Using RegExp in cases like this

`source.match(/FUNCTION.+\(([\w\s\,]*)\)/)`

the "\s" is marked as violation
**Unnecessary escape character: \,. (no-useless-escape)**

**Comment by timoxley** [comment]
Based on the error message it's probably the `\,` that's actually the violation.

**Comment by simone-sanfratello** [comment]
It si, thank you.
Sorry for opening an useless issue.
