### ISSUE TITLE
[question] jsx config 

### ISSUE THREAD

**Issue by crobinson42** [feross/standard#612]
I'm new to using `standard` and linters in general (I know, burnn!) I'm getting errors on my JSX and would like to know how to config/setup `standard` to recognize JSX.

I simply installed with `npm i standard` and run `standard` on a simple React component w/ JSX and get this error:

```
$ node_modules/standard/bin/cmd.js
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/willlyrob/projects/react-job-app-form/src/index.jsx:11:7: Parsing error: Unexpected token <
```

I don't see any specific configuration options for `standard` to use with JSX in my `.js` files. I also tried renaming the file to `.jsx` and did not help anything.

**Comment by timoxley** [comment]
Standard supports jsx. This doesn't look like the latest standard. Try reinstalling with the latest version.. If that doesn't work perhaps post the code you are trying to lint.

**Comment by crobinson42** [comment]
I checked the `package.json` and it's `"version": "8.0.0"`

Here's the code:

```
import React from 'react'

export default class Component extends React.Component {
  constructor (props) {
    super(props)
    this.state = {}
  }

  render () {
    let title = this.props.title

    return {
      <div>
        {title}
      </div>
    }
  }
}
```

**Comment by crobinson42** [comment]
Oh! Duh- I have a config for JSX set :-/ Sorry. It's expecting `(<div></div>)` not `<div></div>`!

**Comment by crobinson42** [comment]
thx for the quick response btw- AWESOME util/tool!
