### ISSUE TITLE
unable to parse ReactJS contextTypes using Standard + babel-eslint in SublimeText 3 (SublimeLinter)

### ISSUE THREAD

**Issue by dustypomerleau** [feross/standard#613]
I am using this React Native sample code as a template to add tabbed navigation to a React Native mobile app:
https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/NavigationExperimental/NavigationCardStack-NavigationHeader-Tabs-example.js

In my project, the following code can't be parsed:

```javascript
function createAppNavigationContainer (ComponentClass) {
  const key = '_containerNavigateCall'

  class Container extends Component {

    // commenting out the two contextTypes declarations below returns normal behavior
    static contextTypes = { // unable to parse this => 'unexpected token'
      [key]: PropTypes.func
    }; // dropping the semi here also results in a parsing error

    static childContextTypes = { // same issue here
      [key]: PropTypes.func.isRequired
    };

    getChildContext () {
      return {
        [key]:
          this.context[key] ||
          this.props.navigate
      }
    }

    render () {
      const navigate =
        this.context[key] ||
        this.props.navigate

      return <ComponentClass
        {...this.props}
        navigate={navigate}
      />
    }

  }

  return Container
}
```

In my SublimeLinter settings I have:
```json
"linters": {
  "standard": {
      "@disable": false,
      "args": [],
      "excludes": [],
      "parser": "babel-eslint",
      "plugins": [
          "react"
      ]
  }
},
```

All npm packages are installed globally:
  standard@8.0.0
  babel-eslint@6.1.2
  eslint-plugin-react@6.2.0

I have installed SublimeLinter-contrib-standard via ST3 package control, and I don't have any other linters.

EDIT: I should mention that the app performs as expected, without errors. Thanks in advance,

DP

**Comment by feross** [comment]
The correct place to add the `"parser": "babel-eslint"` line is in the "standard" property of "package.json".

See the instructions here: http://standardjs.com/#can-i-use-a-custom-js-parser-for-bleeding-edge-es-next-support

**Comment by dustypomerleau** [comment]
Outstanding, thanks (for the answer and the linter)!
