### ISSUE TITLE
Defining a variable to itself that is undefined raises no errors

### ISSUE THREAD

**Issue by pinn3** [feross/standard#615]
Example:

``` js
var variable1 = variable1
let variable2 = variable2
const variable3 = variable3
```

**Comment by not-an-aardvark** [comment]
Relevant ESLint rule: [`no-use-before-define`](http://eslint.org/docs/rules/no-use-before-define)

**Comment by feross** [comment]
Good catch. We could try enabling the following rule:

```
    "no-use-before-define": [2, { "functions": false, "classes": false }]
```

Even with the most lax options to `no-use-before-define`, there are still way too many false positives.

```
```

If eslint adds an option that doesn't flag the following as invalid, then we can consider enabling `no-use-before-define`:

```js
function myFn () {
  // Variable "a" is not necessarily used before it is defined
  console.log(a)
}
var a = 5
```

**Comment by feross** [comment]
I opened an issue on eslint to add the necessary option: https://github.com/eslint/eslint/issues/7111

**Comment by feross** [comment]
Duplicate of https://github.com/feross/standard/issues/636

**Comment by feross** [comment]
(Btw, this will be part of standard v9.)
