### ISSUE TITLE
Prevent confusing if-statement usage

### ISSUE THREAD

**Issue by willsoto** [feross/standard#616]
As per the suggestion [here](https://github.com/yargs/yargs/pull/615), I am opening up a an issue to discuss extending the rules around `if` blocks.

The blocks were originally indented like so:

``` js
if (condition) {
  // stuff
} if (anotherUnrelatedCondition) {
  // more
} 
```

I found this confusing because at first glance it looks like `if; else if` blocks.

---

I would image the rule could be something like: 

> ensure 1 newline between `if` blocks

Other suggestions are welcome.

**Comment by dcousens** [comment]
That really should be disallowed.  The wriggle room for accidents is pretty high.

**Comment by KhaledMohamedP** [comment]
Totally agree here. It should be disallowed 👍

**Comment by feross** [comment]
Agreed. This should be prevented. However, there's no eslint rule that allows us to catch this case.

I just opened an issue to get the eslint team's thoughts: https://github.com/eslint/eslint/issues/7116

**Comment by feross** [comment]
Closing this, as we're blocked. I'll re-open if the ESLint issue makes any progress.
