### ISSUE TITLE
Add timoxley, LinusU as contributors

### ISSUE THREAD

**Issue by feross** [feross/standard#617]
I'd like to add @timoxley and @LinusU as GitHub collaborators to `standard`.

While neither has any commits on the project (as far as the GitHub contributor graph shows), they've both been extremely active and helpful in GitHub issues, testing beta releases, and providing feedback about proposed changes. They feel like part of the core team to me, and they both deeply "get" the philosophy of `standard`.

I'd like to hear what other collaborators think of this idea. This feels like an appropriate way to recognize useful non-code contributions.

@timoxley @LinusU What do you two say?

**Comment by dcousens** [comment]
:+1:

**Comment by timoxley** [comment]
@feross I am honoured. :+1:

**Comment by LinusU** [comment]
I would be honoured as well, thank you 🎉

**Comment by feross** [comment]
Nice! Just added you to the relevant `standard` repos on GitHub.
