### ISSUE TITLE
ignore: for projects that doesn't use package.json

### ISSUE THREAD

**Issue by skepticfx** [feross/standard#62]
Am using the `standard` command line tool from this project and am working on a Chrome project. Does that mean that I need to use package.json and add the standard.ignore array? Or is there any generic way to ignore files?

**Comment by feross** [comment]
Yeah, just add a minimal package.json:

```json
{
  "standard": {
    "ignore": [ "file1", "file2" ]
  }
}
```

**Comment by skepticfx** [comment]
:+1:
