### ISSUE TITLE
standard way to ignore an error

### ISSUE THREAD

**Issue by timoxley** [feross/standard#620]
This is mostly just a discussion item rather than a serious issue.

Currently `standard` uses [handle-callback-err](http://eslint.org/docs/rules/handle-callback-err) which complains if you do not "handle" callback errors. 

Sometimes you do want to _not_ handle an error e.g. ignore `mkdirp` errors.

The current rule is good as it encourages you to explicitly flag intentionally ignored errors rather than just leaving the future reader wondering whether the error was left ignored accidentally or for some purpose.

Even prior to using standard, I try to always flag explicitly ignored errors with a comment like so

``` js
mkdirp('/dir/might/exist', err => {
  // ignore error
  doStuff()
})
```

This only changed slightly upon starting to use standard:

``` js
mkdirp('/dir/might/exist', err => {
  err // ignore error 
})

try {
  mkdirp.sync('/dir/might/exist')
} catch (err) {
  err // ignore err
}
```

Another option could be to use a different variable name for ignored errors:

``` js
mkdirp('/dir/might/exist', ignoreErr => {
  doStuff()
})
```

**Does anyone else have a standard pattern they use for flagging "ignored" errors?**

It's a possibility that even with the comment this is still a crappy workaround and I really should be explicitly whitelisting the `error.code === 'EEXIST'` case and `throw err`/`return callback(err)` otherwise.

Note that it's also still valid to not add any comment, which makes it again unclear whether the error is being ignored intentionally or not:

``` js
mkdirp('/dir/might/exist', err => {
  err
  doStuff()
})
```

This should perhaps be disallowed.

In fact, I'm not sure there's any valid reason for a statement to solely contain a reference to a variable like that since it's a noop so perhaps I'm really requesting a rule for something like "no useless statements".

**Comment by dcousens** [comment]
> so perhaps I'm really requesting a rule for something like "no useless statements".

:+1: ,  I wonder if we can apply to `standard` to politics.

In any case,  agreed.  My go-to for ignoring errors is:

``` js
mkdirp('/dir/might/exist', () => {
  doStuff()
})
```

**Comment by timoxley** [comment]
@dcousens what if you need to access the other arguments? 

Yeah I personally wish that particular case were detectable to and required some explicit signal that you hadn't inadvertently invited chaos into your program by forgetting to handle the `err`.  It'd be possible to detect for node core functions I guess.

**Comment by dcousens** [comment]
Yeah,  I suppose I just use `_` in that case.
You're right `ignoredErr` would be better or some such maybe.

**Comment by LinusU** [comment]
I think `_` is good enough, most people knows that it means ignored variable and I believe that standard doesn't even complain of unused variables if it's named `_`...

**Comment by feross** [comment]
Yeah, `_` is a nice solution. That's what I use. But this is a pretty rare occurrence.

**Comment by feross** [comment]
Closing, since discussion has concluded 😄
