### ISSUE TITLE
Enforce comparing `typeof` expressions against string literals

### ISSUE THREAD

**Issue by feross** [feross/standard#629]
I propose adding `{ "requireStringLiterals": true }` to the `valid-typeof` rule that we already enforce.

This requires `typeof` expressions to only be compared to string literals, and disallows comparisons to any other value.

Examples of incorrect code:

``` js
typeof foo === undefined
typeof bar == Object
typeof baz === 'strnig'
typeof qux === 'some invalid type'
typeof baz === anotherVariable
typeof foo == 5
typeof bar === typeof qux
```

Examples of correct code:

``` js
typeof foo === 'undefined'
typeof bar == 'object'
typeof baz === 'string'
```

http://eslint.org/docs/rules/valid-typeof

**Comment by feross** [comment]
No ecosystem impact:

```
# tests 422
# pass  422
```

**Comment by Flet** [comment]
:shipit:

**Comment by dcousens** [comment]
Make it so

**Comment by dcousens** [comment]
Why not standard <9 too?

**Comment by feross** [comment]
@dcousens I fear users will get fatigue from too many releases of `standard`. Rule changes in a non-major version are especially onerous.

Also, frankly, it's a lot of work to do a release. It takes a few hours to properly test everything, write the changelog, update the various packages, etc. I'd prefer to hold back most of these rule changes until `standard` v9.

**Comment by dcousens** [comment]
@feross I feel like we don't thank you enough :+1:

**Comment by feross** [comment]
@dcousens Thanks. I appreciate your contributions, too! It's really nice to not be in this all alone. 😄

**Comment by feross** [comment]
This will be part of standard v9. Only one repo was impacted and it was doing this:

```js
const OBJ = 'object'

module.exports = function merge (a, b, checked) {
  if (checked || typeof a === OBJ) {
```

Can't see a reason that's preferable to `typeof a === 'object'`, so not too worried about this case.
