### ISSUE TITLE
lowercase contructor names with Rxjs

### ISSUE THREAD

**Issue by piq9117** [feross/standard#631]
```
const myArrayWithDuplicatesInARow = new Rx.Observable
  .fromArray([1, 1, 2, 2, 3, 1, 2, 3])
```
This gives me a warning
```
A constructor name should not start with a lowercase letter
```
Rxjs has its constructors setup this way. How do I make it work with standardjs? 

P.S 
I ❤️❤️❤️ standardjs! It has saved me from a lot of hassle.

**Comment by feross** [comment]
It looks like `Rx.Observable.fromArray()` is meant to be used as a factory method. That is, without the `new` keyword.

Source: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromarray.md#example

If you remove `new` does the code still work?

**Comment by piq9117** [comment]
Cool! that totally worked! Thank you @feross!

**Comment by feross** [comment]
Cheers :neckbeard:
