### ISSUE TITLE
How do you use Standard with modules?

### ISSUE THREAD

**Issue by izolate** [feross/standard#634]
I'm stuck in a catch 22 situation trying to verify all internal code adheres to Standard. For example:

📄 **app.js**
```js
const external = require('some-npm-module')
const internal = require('./some/local/module')
// ...
```

Standard checks `app.js`, but not `./some/local/module.js`.

Solution? Perhaps by using Browserify/Gulp:

📄 **gulpfile.js**
```js
const gulp = require('gulp')
const standard = require('gulp-standard')

gulp.task('scripts', function () {
  return browserify('/path/to/app.js')
    .transform(require('babelify'))
    .bundle()
    .pipe(require('vinyl-source-stream')('app.compiled.js'))
    .pipe(require('vinyl-buffer')())
    .pipe(standard())
    .pipe(standard.reporter('default', opts)
    .pipe(gulp.dest('/path/to/dest'))
})
```

Now this task executes standard on the complete bundle, which (rightfully) includes the `internal` module, but also (wrongly) includes the `external` npm module too. If any npm module NOT written in standard (most) is included in the bundle, the task will fail.

Any solutions around this?

**Comment by dcousens** [comment]
``` bash
$ mkdir test
$ cd test/
$ mkdir some
$ mkdir some/local
$ echo "var a, b;" > some/local/module.js
$ standard
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  ./test/some/local/module.js:1:5: 'a' is defined but never used.
  ./test/some/local/module.js:1:8: 'b' is defined but never used.
  ./test/some/local/module.js:1:9: Extra semicolon.
```

**Comment by izolate** [comment]
Okay, my bad. Standard is recursive by default then? Cheers @dcousens

**Comment by dcousens** [comment]
Indeed,  with some smarts to avoid `node_modules` and [other things](https://github.com/feross/standard#how-do-i-ignore-files) by default too.
