### ISSUE TITLE
Runs locally but fails on CI

### ISSUE THREAD

**Issue by bartonhammond** [feross/standard#635]
My `package.json` has this line `"test": "./node_modules/standard/bin/cmd.js  && jest",`, using version `8.0.0`.  I'm running the local installed version.

Locally this runs w/o error

On my CI I get the following:
```
./node_modules/standard/bin/cmd.js  && jest

standard: Use JavaScript Standard Style (http://standardjs.com)
  /bitrise/src/src/components/Header.js:153:13: Expected indentation of 10 space characters but found 12.
  /bitrise/src/src/components/Header.js:159:13: Expected indentation of 8 space characters but found 12.
  /bitrise/src/src/components/LoginRender.js:273:12: Expected indentation of 14 space characters but found 11.
  /bitrise/src/src/containers/Main.js:122:12: Expected indentation of 12 space characters but found 11.
npm ERR! Test failed.  See above for more details.
```

These reported issues are from React-Native JSX code.   For example, the first one has this:
```
          </TouchableHighlight>
            {this.props.isFetching   //<<<<<<<<<<<<<<<<<< line 153 - expected 10 but found 12
             ? <ActivityIndicator animating size='large' />
             : null
          }
```

**Comment by bartonhammond** [comment]
I edited the files that were described above and once I changed the particular line and modified it just one space and then reran, the error would show up for that particular file.  It `smells` like there's some cache that doesn't get cleaned.

**Comment by feross** [comment]
You might be running the newly-released 8.1.0 on your CI server, but 8.0.0 locally. Can you see if that's the issue?

You can try deleting the `~/.standard-cache` folder and see if your issues go away.

**Comment by bartonhammond** [comment]
I changed the `package.json` entry for `test` to run the local version of standard with this: ` "test": "./node_modules/standard/bin/cmd.js  && jest",` so as to use my installed version of `8.0.0` from the `devDependencies` with `"standard": "8.0.0"` so to make sure it used my version rather then a global one that may be present.  I got the same error on the CI BitRise.  

Again, just to be clear, when I ran locally on my mac I got not errors.  But once I touched the line in each of the files that were reported in error from the CI, then I started to get the errors reported.  I then fixed each line w/ the now reported issues.  Once I repeated this for each of the three files in question, again the local ran fine and then the CI ran fine also.  But, again, I had to change each file on the line reported to get the local errors to report.  The errors weren't reported until I changed the lines a little to get the errors reported.  "Smelled" like a cache issue to me.

**Comment by feross** [comment]
This is really weird. Sounds like a cache bug, you're right. But without more info on how to reproduce it there's nothing I can do. Also, we're just using the `cache` option to ESLint.

Let's keep our eyes open for this one. If we see it in the wild again, we can file an issue on the ESLint repo.
