### ISSUE TITLE
Feature request: Node API for 'standard --fix'

### ISSUE THREAD

**Issue by stephenkubovic** [feross/standard#640]
Are there any plans to expose 'standard --fix' in the Node API, something like `standard.fixText()` and `standard.fixFiles` to go along with `lintText()` and `lintFiles()`?

I'm currently trying to support `standard --fix` in the Atom plugin for standard formatter. Currently the plugin uses the programatic API from standard-format module, but it's sounding like `standard --fix` is the way forward so I would like to support this as well (tracking here: https://github.com/stephenkubovic/atom-standard-formatter/issues/39)

Based on the existing functionality of `standard`, my approach right now is to `--stdin` option in combination with `--fix` in a child process and handle the transformation that way. Obviously a programatic way would be more intuitive.

Let me know your thoughts on this feature (I'd be willing to take a crack at a PR, maybe with a nudge in the right direction and/or agreed API spec).

**Comment by feross** [comment]
This is already supported! Just pass a `{fix: true}` option to `standard.lintFiles()`. I just added this to the documentation.

**Comment by stephenkubovic** [comment]
I just discovered this 30s ago 👍  Thanks for the prompt reply @feross !

**Comment by feross** [comment]
Sure thing. 👍 

Also, note that `{fix: true}` is not supported for `lintText` because ESLint doesn't expose the right functionality. If that's important for your plugin, consider filing an issue with them to see if they think that's a reasonable thing to support.

**Comment by stephenkubovic** [comment]
Ah, good to know.

I see `fix: true` is documented as available here https://github.com/Flet/standard-engine#standardenginelinttexttext-opts-callback and in the [changelog](https://github.com/Flet/standard-engine/blob/master/CHANGELOG.md#500---2016-08-10), but I guess that's just a documentation error.

**Comment by feross** [comment]
Oh, I guess you're right! Sorry -- I was speaking from memory. The docs are correct.

**Comment by feross** [comment]
Just updated the `standard-engine` docs as well: https://github.com/Flet/standard-engine/pull/128/files Thanks for making take a second look at all this :)
