### ISSUE TITLE
Proposal: allow developers to use write prettier comments

### ISSUE THREAD

**Issue by crccheck** [feross/standard#641]
(ugh, return in github submits instead of doing a line break, submitted this too early)

Currently, standard does not allow code to have comments like:
```
// MY HEADING
/////////////
```

The relevant rule with a `--verbose` of "Expected space or tab after '//' in comment. (spaced-comment)"

I'm not sure why it's not [spaced-line-comment] but anyways, if you see the docs for [spaced-line-comment] or [spaced-comment], there's a way to make an exception.

Why `/////` and not `//----` or something fancier? Because in VIM, you can copy paste a line, then replace all characters with `/` to make a fast heading. The uniformity of `/` also looks better IMHO.

Searching the issues shows this hasn't come up for discussion before.

[spaced-comment]: http://eslint.org/docs/rules/spaced-comment
 [spaced-line-comment]: http://eslint.org/docs/rules/spaced-line-comment

**Comment by feross** [comment]
> I'm not sure why it's not spaced-line-comment 

`spaced-line-comment` was deprecated, so we use `spaced-comment` now.

> Why ///// and not //---- or something fancier?

If you want a comment to stand out, consider using a block comment:

```js
/**
 * MY HEADING
 */
```

Inside a block comment, you can do whatever extra formatting you want, for example:

```js
/*
 * MY HEADING
 * ==========
 */
```
