### ISSUE TITLE
Any filename standard recommendations?

### ISSUE THREAD

**Issue by dandv** [feross/standard#642]
As long as filenames are within the scope of the project.

See also [Node.js project naming conventions for files & folders](http://stackoverflow.com/questions/18927298/node-js-project-naming-conventions-for-files-folders).

**Comment by dcousens** [comment]
standard v20 with the breakage this would cause :laughing:

**Comment by feross** [comment]
Standard doesn't operate on the level of multiple files. It currently looks at each file in isolation, so linting directory structure is out of scope.
