### ISSUE TITLE
Multi-Line String

### ISSUE THREAD

**Issue by Beastio** [feross/standard#646]
There is a lot of differing styles out in the wild for multi-line and template, strings. I have a simple proposal that makes multi-lines much nicer ensuring the first-line maintains its internal alignment and doesn't use a function that manipulates the string to strip indentation.
```javascript
;(()=> {
  const func = ()=> {
    const multi = `\
1. Escape first return
2. Dedent to page edge`
    return multi //move back to previous indentation level
  }
  return func()
})()
```

**Comment by feross** [comment]
Looks reasonable to me. But this isn't something that we can enforce with ESLint. Feel free to use this style in your code!
