### ISSUE TITLE
New rule: no-nested-ternary

### ISSUE THREAD

**Issue by qzb** [feross/standard#647]
Disallow nested ternary expressions.

http://eslint.org/docs/rules/no-nested-ternary

Nested ternary expressions makes code really difficult to understand.

**Comment by yoshuawuyts** [comment]
I'm :-1: on this; with proper indentation nested ternary's are fine imo - I don't use them often, but given JS doesn't have macro support sometimes they're the cleanest and most efficient solution for a problem. I'd rather have the option to use them when I need to

**Comment by feross** [comment]
Yeah, I use them too. Haven't run the numbers, but I suspect that this would break a lot of modules and the rule is not automatically fixable.

**Comment by dcousens** [comment]
An example of where I have used nested ternary expressions would be in https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/bufferutils.js#L129-L134.

```  js
function varIntSize (i) {
  return i < 253 ? 1
  : i < 0x10000 ? 3
  : i < 0x100000000 ? 5
  : 9
}
```

I can't think of how using verbose `if` statements in this scenario would increase readability in any way.

**Comment by rstacruz** [comment]
On a devil's advocate note, Standard asks you to do this:

```js
a
? b
: c
  ? d
  : e
```

so it's a bit more readable:

```js
user.isAdmin()   // if
? 'Manage'  // then
: user.isEditor()  // elseif
  ? 'Edit'   // then
  : 'Unauthorized'   // else
```

**Comment by dcousens** [comment]
@rstacruz interesting, I find that less readable since in my head,  chained ternary expressions are instead more like:

``` js
if (a) return b
else if (c) return d
else return e
```

You  wouldn't do

``` js
if (a) return b
  else if (c) return d
    else return e
```
