### ISSUE TITLE
Failed to load plugin promise: Cannot find module 'eslint-plugin-promise'

### ISSUE THREAD

**Issue by mmmathur** [feross/standard#648]
Hi I'm getting this error in Visual Studio Code. However I see this module is available in node_modules locally as well as globally along with eslint. linting is not working in my editor, may be because of this. 
Error:
Failed to load plugin promise: Cannot find module 'eslint-plugin-promise'

**Comment by feross** [comment]
If you have installed `eslint-plugin-promise` globally and locally, then I'm not sure what could cause this error. It sounds like a bug in your editor integration.

I think you'll have a better shot at getting help if you open an issue there: https://github.com/chenxsan/vscode-standardjs

**Comment by feross** [comment]
Actually, looks like Issues are disabled on that repo (because that's the default for GitHub forks). cc @chenxsan -- any ideas about this issue?

**Comment by crmpicco** [comment]
```
npm i eslint --save-dev
npm install eslint-plugin-promise --save-dev

```
