### ISSUE TITLE
Syntastic has stopped working with standard@3.0.0-beta4

### ISSUE THREAD

**Issue by othiym23** [feross/standard#65]
Which makes me sad because now it seems like most of the ES6 stuff I use is handled properly. ;_;

I updated Syntactic to `HEAD`, and have verified that `standard` is working by running `:!standard` against an erroneous file from inside vim. If nothing obvious occurs to you about how the formatting might have changed in `beta4`, I can dig into this more tomorrow.

**Comment by yoshuawuyts** [comment]
The fix for me was to use `io.js@>=1`.

**Comment by othiym23** [comment]
@yoshuawuyts 
```
bauchelain% iojs --version
v1.5.1
```

This is probably an eslint issue, because the diff between `beta3` and `beta4` is pretty much entirely the change to `eslint@0.17.0`.

**Comment by feross** [comment]
I can't think of anything that might have caused this, except maybe a change in Syntastic. Does `3.0.0-beta3` work fine with Syntasic `HEAD`?

**Comment by othiym23** [comment]
> Does 3.0.0-beta3 work fine with Syntastic HEAD?

It sure does! I didn't try changing the Syntastic version until after `beta4` stopped working, but even then, I can switch between `beta3` and `beta4` and it starts and stops working accordingly. I really need this to work, so I'm going to dig in a bit further.

**Comment by feross** [comment]
Hey @othiym23, can you try again with `v3.2.0`? I removed automatic detection of stdin, which is error-prone and may have been confusing Syntastic/vim.

**Comment by othiym23** [comment]
So, to capture here what we discussed on IRC, when I go into `bin/cmd.js` and comment out the line that sets the default value for `stdin` to `!process.stdin.isTTY`, everything starts magically working again. It's probably best to require users to explicitly call `--stdin`, or follow browserify's lead and observe the Unix convention of using `-` as the way of indicating that input should come from stdin.

**Comment by feross** [comment]
Yep, that change is already released as 3.2.0!

**Comment by feross** [comment]
Oh, I see you were just clarifying for posterity.

**Comment by othiym23** [comment]
Yep! `standard@3.2.0` works again! :tada:
