### ISSUE TITLE
PhpStorm `no-unused-var` highlight issue in JSX

### ISSUE THREAD

**Issue by kinyat** [feross/standard#650]
My PhpStorm generates wrong highlights for `no-unused-var` in JSX when using the given default `.eslintrc` by StandardJS.

If I run eslint or standard in command line, there are no any rule conflicts.

By changing the default `.eslintrc` to the following, it will solve the issue in PhpStorm.

```
{
  "extends": ["standard"],
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "rules": {
    "react/jsx-uses-vars": "error"
  }
}
```

**Comment by feross** [comment]
Oh, this is because the Webstorm instructions don't tell users to install [eslint-config-standard-jsx](https://github.com/feross/eslint-config-standard-jsx). Your solution works, but you're not getting the full set of rules that `standard` adds for JSX.

I'll send a PR to update the instructions.

**Comment by feross** [comment]
PR is sent: https://github.com/feross/standard/pull/651
