### ISSUE TITLE
please update eslint depends version for support class-static-props

### ISSUE THREAD

**Issue by leecade** [feross/standard#652]
There is a problem prevent remove `babel-eslint`

```js
export default class extends Component {
  static propTypes = {   // this line cause syntax error
```

**Comment by dustypomerleau** [comment]
First, make sure you are using babel-eslint as your parser:

```js
npm i -g babel-eslint
```

and then modify your package.json like so:
http://standardjs.com/#can-i-use-a-custom-js-parser-for-bleeding-edge-es-next-support

If you are still getting a syntax error, put a semicolon in front of the word static.

**Comment by feross** [comment]
Pretty sure that this is a feature that only works with Babel, since it's not in ES stage 4 yet. @dustypomerleau is correct, you still need babel for this.
