### ISSUE TITLE
Supporting experimental language features

### ISSUE THREAD

**Issue by treshugart** [feross/standard#658]
I'm wondering what the best way to support a feature such as property initialisers, where it's a syntax error without using the specific babel plugin. I've tried specifying the `babel-eslint` parser, but you also need to be able to explicitly enable the `babel-plugin-transform-class-properties` plugin. I believe it's now at stage 2, so I don't think it's too far out of line to want to use.

**Comment by feross** [comment]
Just enable that plugin in your `.babelrc` and the `babel-eslint` parser will pick it up.

**Comment by treshugart** [comment]
That moment when you realise the solution was right under your nose :p

Thank you and sorry for wasting your time!

**Comment by feross** [comment]
No problem 😀
