### ISSUE TITLE
Standard allows you to use a var before it's declared

### ISSUE THREAD

**Issue by dcposch** [feross/standard#659]
I don't know if this is intentional, but standard doesn't warn about this:
```js
function foo () {
  console.log('' + x) // prints undefined
  var x = 5
}
```

**Comment by qzb** [comment]
Yes, it is intentional: #636

**Comment by feross** [comment]
I would like `standard` to catch this issue, but can't enable the relevant rule until https://github.com/eslint/eslint/issues/7111 is fixed.

So, yes, this is intentional for now. See https://github.com/feross/standard/issues/636#issuecomment-250021633 for explanation.
