### ISSUE TITLE
Flowtype comments markers

### ISSUE THREAD

**Issue by qzb** [feross/standard#661]
Flowtype supports [annotating code with comments](https://flowtype.org/blog/2015/02/20/Flow-Comments.html) (only block comments `/* ... */`). It uses three different markers ( `:`, `::`, `flow-include`), none of them is currently recognized by _standard_. Flowtype ignores whitespaces before markers, so _standard_ doesn't brake anything, but placing spaces before these markers is inconsistent - they are not required before other markers like `*` and `!`. My proposition is to add `:` and `::` to list of markers for block comments. I'm not sure if `flow-include` should be also added, it is just an alias for `::`, and markers like this looks kind of strange without whitespace:

``` js
/*flow-include declare type foo = number */    // looks strange, currently disallowed
/* flow-include declare type foo = number */   // looks ok
```

On other hand space before `:` marker could actually improve readability:

``` js
function foo (arg /* : number */) {}   // with whitespace - currently valid
function foo (arg /*: number */) {}    // without whitespace - currently invalid
```

**Comment by josephfrazier** [comment]
I just ran up against this, but didn't know that Flowtype ignores whitespace before markers. Thanks for pointing out how to work around it!

It looks like https://github.com/gajus/eslint-plugin-flowtype/issues/87 might be the place to add support for the syntax without whitespace.

**Comment by feross** [comment]
I think it's probably fine to add an exception for `:` and `::`. The point of this rule is generally to avoid writing comments like `//this is a comment`. 

Can you provide a link to the Flow documentation where this comment marker is discussed?

**Comment by cesarandreu** [comment]
[Comment Syntax](https://flowtype.org/docs/syntax.html#comment-syntax) section in the docs points to the following [blog post](https://flowtype.org/blog/2015/02/20/Flow-Comments.html).

**Comment by feross** [comment]
This will be part of standard v9. Since it's relaxing a rule, there is no impact on the ecosystem. Except of course, now you can use Flow Comments!

🎉
