### ISSUE TITLE
Use typographic apostrophe

### ISSUE THREAD

**Issue by zemtu** [feross/standard#662]
> Single quotes for strings – except to avoid escaping

If you’d use the typographic apostrophe you wouldn’t have to make this exemption.

Typewriter apostrophe: 'we\'d have to escape'
Typographic apostrophe: 'we don’t have to escape'

Typographic apostrophe:
Mac: Shift + Alt + #
Linux: Alt Gr + #
Windows: Alt + 0146
HTML: `&rsquo;`

See also:
https://en.wikipedia.org/wiki/Apostrophe#Computing
http://practicaltypography.com/apostrophes.html
http://typefacts.com/artikel/apostroph

**Comment by mightyiam** [comment]
I'm happy to learn about this unicode character and I know I'm going to use it.

**Comment by mightyiam** [comment]
So funny. Above, I didn’t use it. So, here it is, in this comment!

**Comment by Flet** [comment]
This is a neat way to get around escaping apostrophes! 👍 There are some cases where a `'` is really intended though :)

Closing this as there is no issue here, just sweet, sweet typography tricks 🏄 

Feel free to continue to discuss!

**Comment by mightyiam** [comment]
How about #666?
