### ISSUE TITLE
Allow semicolon at the end of an IIFE

### ISSUE THREAD

**Issue by dalelotts** [feross/standard#663]
Since converting to standard, users of my directives are having problems with concatenating and minifying my directive with other code. The root cause of the problem is that standard does not allow `;` at the end of an IIFE.

If my directive is concatenated with another file that starts with an IIFE they get a parser error and report defects like the following:
https://github.com/dalelotts/angular-bootstrap-datetimepicker/issues/347
https://github.com/dalelotts/angular-bootstrap-datetimepicker/issues/338

If I could terminate my IIFE with a `;`, this would fix the issues they are having.

**Comment by qzb** [comment]
I'm afraid that eslint doesn't support such exception. Currently all you can do is suppressing error raised by *semi* rule for last line of the file: 

```js
;(function () {
  // ...
})()

; // eslint-disable-line semi
```

**Comment by dalelotts** [comment]
Thanks for the update! At least I have a work around.

**Comment by Flet** [comment]
Thanks for the help @qzb!

I found a related issue in eslint: https://github.com/eslint/eslint/issues/6271

Unfortunately it looks like they did not decide to implement this option. Sorry!

Closing this for now, but feel free to continue discussion.
