### ISSUE TITLE
Expected { after 'if' condition

### ISSUE THREAD

**Issue by fanatid** [feross/standard#664]
source:

``` js
var x = require('crypto').randomBytes(1)[0]
if (x % 2 === 0) console.log('hello standard')

;(() => {})()
```

output:

```
standard: Use JavaScript Standard Style (http://standardjs.com)
  /home/kirill/tmp/test/t.js:2:1: Expected { after 'if' condition.
```

**Comment by Flet** [comment]
This seems like an obscure bug in the `curly` rule provided by eslint. It will most likely need to be opened as an issue on https://github.com/eslint/eslint and resolved there.

**Comment by fanatid** [comment]
@Flet I know that this bug related with eslint related packages, not with standard. I hoped that you open issue in right eslint repository. Thanks.

**Comment by not-an-aardvark** [comment]
This is fixed in https://github.com/eslint/eslint/commit/ea0970d184358fa99f2d16730c65b42c84e8c9a1.

**Comment by Flet** [comment]
Nice! Thanks for doing this @not-an-aardvark!

Looks like we need to wait for the next eslint release (and bump the eslint dependency here).

**Comment by feross** [comment]
@not-an-aardvark You're the best!

**Comment by feross** [comment]
I'm working on a release to update the ESLint dependency. Closing.
