### ISSUE TITLE
IIFE not checkt for semicolon at the start?

### ISSUE THREAD

**Issue by borisdiakur** [feross/standard#669]
https://github.com/feross/standard/blob/master/RULES.md#semicolons suggests the following:

> ``` js
> // ✓ ok
> ;(function () {
>   window.alert('ok')
> }())
> ```
> 
> ``` js
> // ✗ avoid
> (function () {
>   window.alert('ok')
> }())
> ```

However, when I navigate to http://standardjs.com/demo.html and paste the following code, the linter tells me it’s fine:

``` js
(function () {
  window.alert('ok')
})()
```

I’m new to the no semicolons style, so now I’m confused. Either the documentation or the linter is wrong.

**Comment by Flet** [comment]
If there is no code above the IIFE, it will work ok,

It becomes more clear when adding a line at the top:
http://standardjs.com/demo.html?gist=f925d40642900c782d2b9d9e18731ece

**Comment by borisdiakur** [comment]
Here is an example with code above. It’s still ok:
http://standardjs.com/demo.html?gist=7382351fed23caf08381c01669b0900d

**Comment by Flet** [comment]
Indeed, this one is a funny edge case :)

Somewhat related: https://github.com/feross/standard/issues/70

**Comment by Flet** [comment]
There is not a specific rule that enforces semicolons before IIFEs, but other rules will catch problems if they arise (like `func-call-spacing`).

>Never start a line with (, [, or `. This is the only gotcha with omitting semicolons, and standard protects you from this potential issue.

The guideline above will ensure code always works, even if there is a special edge case where its not required (like a preceding `if` block).

If this is uncomfortable, there is always [semistandard](https://github.com/flet/semistandard) :)

**Comment by borisdiakur** [comment]
As long as standard catches all problems related to missing semicolons I feel comfortable.

> There is not a specific rule that enforces semicolons before IIFEs, but other rules will catch problems if they arise (like func-call-spacing).

Maybe that should be noted in the RULES.md?

**Comment by feross** [comment]
`standard` catches all problems related to missing semicolons. 👍
