### ISSUE TITLE
Question: idiomatic.js

### ISSUE THREAD

**Issue by morenoh149** [feross/standard#67]
How does `standard` compare to https://github.com/rwaldron/idiomatic.js/
I've enjoyed using `standard` due to the cli. It's very easy to run before committing code.
idiomatic.js looks very good from skimming the website. Are they pretty much the same? yes/no

**Comment by othiym23** [comment]
They're pretty different – idiomatic.js is a style guide, and is a much more prescriptive standard that covers many things `standard` doesn't. It also mandates semicolons, which is pretty much the opposite of `standard`. That said, I think the quote at the head of idiomatic.js is pertinent:

> **"Arguments over style are pointless. There should be a style guide, and you should follow it"**
>
> _Rebecca Murphey_

Pick one and go with it, and you'll be in better shape than without either.

**Comment by feross** [comment]
What @othiym23 said! :+1:
