### ISSUE TITLE
Unnecessary escape character: \$. (no-useless-escape)

### ISSUE THREAD

**Issue by kilianc** [feross/standard#671]
-e "REGISTRY=\\$(cat -)" \\\\

In this case I am escaping the `\` since I am printing a bash script and eslint thinks I am escaping `$`. This is a 70L file and it's basically a big string template. I can't even use `// eslint-disable-line` because is the string is a multiline string :(

**Comment by feross** [comment]
Sorry, I can't reproduce this issue. Can you post a more complete example of the code that's causing an issue and I'll re-open this.
