### ISSUE TITLE
Question: browser objects

### ISSUE THREAD

**Issue by charlespeters** [feross/standard#672]
<img width="611" alt="screenshot 2016-11-02 00 33 09" src="https://cloud.githubusercontent.com/assets/4588060/19920100/f3850f92-a093-11e6-88ef-517fae811837.png">

any ideas how to not get this error? `HTMLElement` is apart of the `window` object but if i use the import statement webpack can't resolve it. (originally i was thinking webpack would resolve it like `path` in node or something similar)

**Comment by dcousens** [comment]
https://github.com/feross/standard#how-do-i-hide-a-certain-warning

``` javascript
/* global HTMLElement */
```

But honestly,  just use `window.HTMLElement` and avoid the ambiguity.
