### ISSUE TITLE
Property Initializers of Class

### ISSUE THREAD

**Issue by Rokt33r** [feross/standard#675]
```js
class KeyBinding {
  static currentIndex = 1 // <-- This

  constructor(source, command, keystrokes, selector, priority) {
    this.source = source;
    this.command = command;
    this.keystrokes = keystrokes;
    this.priority = priority;
    this.keystrokeArray = this.keystrokes.split(" ");
    this.keystrokeCount = this.keystrokeArray.length;
    this.selector = selector.replace(/!important/g, "");
    this.specificity = calculateSpecificity(selector);
    this.index = this.constructor.currentIndex++;
  }
...
}
```

Will this feature be available on Standard?

**Comment by dcousens** [comment]
@Rokt33r what do you mean?

If ESLint supports parsing it,  then I suppose it is supported.
But I don't think we have any specific rules related to it yet...

**Comment by Rokt33r** [comment]
@dcousens Thanks for your comment. 
Yes, I always got an error, `Parsing error: Unexpected token =`, when I using the static initializer.
Btw,I found the answer. It seems to need `babel-eslint` as a parser to using this syntax.

**Comment by feross** [comment]
If you're using experimental JavaScript features (which I personally don't advise doing), then you'll need `babel-eslint`. Once a feature reaches `stage-4`, ESLint and `standard` will support it, but not before then!
