### ISSUE TITLE
Empty line between blocks

### ISSUE THREAD

**Issue by menzow** [feross/standard#676]
Hey,

The rules about empty blank lines currently say:  "Multiple blank lines not allowed."

From this I assume that a single blank line is allowed:
```
var a = 'foo'

var b = 'bar'
```

I can't find any specification for this, and when running `standard --fix` it does remove the blank lines.

I think the goal is disallowing blank lines within blocks, but require a single blank line between blocks. If this is correct, please specify it in the rules.

```
// bad
function foo(){
  var foo = 'foo'

  return foo
}
function bar() {
  var bar =  'bar'

  return bar
}

//good
function foo(){
  var foo = 'foo'
  return foo
}

function bar() {
  var bar = 'bar'
  return bar
}
```

**Comment by feross** [comment]
Your analysis is correct. Would you be willing to send a PR to clarify the rules in a way that's clearest to you? Thanks in advance!

**Comment by dcousens** [comment]
> function foo(){

bad :P
