### ISSUE TITLE
do-while semicolon

### ISSUE THREAD

**Issue by bounceme** [feross/standard#678]
https://github.com/mishoo/UglifyJS2/issues/893

I think that the do-while is a exception and should have a semicolon to prevent inconsistent behaviour and dev confusion

**Comment by feross** [comment]
Thanks for the issue, @bounceme. I don't time to read that entire issue. Can you clarify what exactly you're proposing we do?

**Comment by bounceme** [comment]
the semicolon is only *necessary* (browsers may behave differently) when not followed by a newline or `}` .  I don't expect that that breaks a lot of code because I see it often, but I find it easier to tell whether the following lines are the while statements or not when the semicolon is there. it draws attention being either a null loop's semicolon, or the end of a do-while

**Comment by bounceme** [comment]
if it is configurable with eslint, i think that missing a semi should give a warning

**Comment by feross** [comment]
There isn't an ESLint rule to enforce what you're asking for, so I'm going to close this issue.

**Comment by dcousens** [comment]
@bounceme maybe open an eslint issue for it?
