### ISSUE TITLE
Error on parsing octal numbers

### ISSUE THREAD

**Issue by linuxenko** [feross/standard#679]
It seems like `standard` does not support octal numbers

```
Parsing error: Invalid number
```

**Comment by dcousens** [comment]
If you don't mind me asking,  why are using octal numbers?

**Comment by linuxenko** [comment]
Because it simple to understand and read  . for an instance `012000 | 0755` .. can you imagine something like this in decimal ? aha

**Comment by feross** [comment]
This type of octal literal is very confusing and error-prone. I recommend you use the ES6 octal literal format: `0o10` is 8, for example. More info here: http://www.2ality.com/2015/04/numbers-math-es6.html
