### ISSUE TITLE
Adding custom rules

### ISSUE THREAD

**Issue by web2style** [feross/standard#681]
If I want to add a rule, I can't do this right? There's no `rules` and `extends` configuration options.

So if I just want to add a single rule which is very important for my team (`react/prop-types`), I have to use eslint instead. Or I overlooked something?

**Comment by dcousens** [comment]
@web2style https://github.com/feross/standard#can-you-make-rule-x-configurable

**Comment by web2style** [comment]
"Can you make rule X configurable" section says nothing about adding rules. Configure (edit/override) is not add.

In my case I just can't use Standard because it is missing a single rule - `react/prop-types`. This is absolutely necessary for any React project.

**Comment by dcousens** [comment]
> If you just want to tweak a couple rules, consider using this shareable config and layering your changes on top.

> consider using this shareable config and layering your changes on top.

> **consider using this shareable config** and layering **your changes on top**.

Then, add this to your .eslintrc file:

```
{
  "extends": "standard"
}
```

Example:
``` json
{
    "extends": "standard",
    "rules": {
      "react/prop-types": ["error", "always"]
    }
}
```

**Comment by chuyik** [comment]
@yantakus Hi I just write a repo to make it happen, if that's really what you want: https://github.com/o2team/standard-own
