### ISSUE TITLE
No warning for 4 spaces indent

### ISSUE THREAD

**Issue by TAQ2** [feross/standard#688]
The following code does not raise an error when there are four spaces (lines 3 and 4). I am using the latest version of standard

```
export default db => {
  return db.collection('option').insertMany([
      { },
      { }
  ])
}
```

**Comment by feross** [comment]
This is a bug with the `indent` rule in ESLint. I filed an issue for you. You can follow the progress there:

https://github.com/eslint/eslint/issues/7637

**Comment by NoraGithub** [comment]
@feross  Do you know is it fixed?  It happened here but it's the newest version.

`standard --fix` doesn't fix extra indent.
```
  10:5  error  Expected indentation of 2 spaces but found 4  indent
  11:9  error  Expected indentation of 6 spaces but found 8  indent
  13:5  error  Expected indentation of 2 spaces but found 4  indent
  14:9  error  Expected indentation of 6 spaces but found 8  indent
```
