### ISSUE TITLE
making () optional in constructor and space around methods/names (generators)

### ISSUE THREAD

**Issue by jimmywarting** [feross/standard#689]
I have two questions

1) I like the hole "No semicolons – It's fine. Really!" principle. I have done it some time before I started to look into your standard and i found out npm is doing it. But for the same principle i have avoided the `()` when constructing a new object without arguments
like this:
```js
var today = new Date // It's fine. Really
```
So I'm just wondering why you haven't thought about making it optional...

2) The second thing has to do with space around `functions`... I could agree with space after `function` and the `name` but ever since I have found out about this nice [async-class](https://github.com/danielstjules/async-class) i have been writing lots of class methods that are generators, much like dose the examples in the other github page<br>Let me demonstrate what i have:

```js
class FakeDataStore {
  constructor () {
    this.store = new Map()
  }

  /*
   * retrieves the user from the database
   *
   * @param Number   id 
   * @return Object      the user
   */
  *getUser (id) {
    return yield Promise.resolve(user)
  }

  *entries () {
    for (let {name, age} of users) {
      yield {name, age}
    }
  }

  /**
   * The class itself is iterable (like Headers and FormData in html5)
   * alias for entries()
   *
   * @return  Iterator
   */
  [Symbol.iterator] () {
    return this.entries()
  }
}
```
But today i try to use async/await if possible but it still comes times where i use `*` when i want to support for...of for example

With your set of rules you would need space after the `*` and the method name
```js
  * getUser (id) {
    return yield Promise.resolve(user)
  }

  * entries () {
    for (let {name, age} of users) {
      yield {name, age}
    }
  }
```
I think this looks very weird to me having a loose hanging `*` in the beginning with space around them. Don't you agree?

The code starts at the same index as the method name
It's almost as if you where to write code like this 

```js
function getUser (id) {
         if (typeof id !== 'number') { 
           throw new TypeError("not a valid number")
         }
         return Promise.resolve(user)
}
```
(quite idiotic but i try to prove my point and make you feel what i feel)

**Comment by dcousens** [comment]
> var today = new Date // It's fine. Really

NACK because it just adds 1 more way to do something with potential confusion thrown in for good measure.

**Comment by feross** [comment]
Thanks for the issue.

> So I'm just wondering why you haven't thought about making it optional...

Standard isn't really about "optional". We prefer to encourage one way to do things, whenever there is an eslint that allows us to enforce this.

Ditto to your second question. Standard has spaces around the stars in generators, in all situations.
