### ISSUE TITLE
eslint-plugin-react required?

### ISSUE THREAD

**Issue by donpdonp** [feross/standard#69]
its not clear why this module would be necessary, or why its not in the pre-req modules if it is necessary.

```
$ npm install standard
npm WARN prefer global standard@3.1.1 should be installed with -g
standard@3.1.1 node_modules/standard

$ ./node_modules/.bin/standard api.js 
Error: Use JavaScript Standard Style (https://github.com/feross/standard)

Unexpected Linter Output:
module.js:340
    throw err;
          ^
Error: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
```

**Comment by maxogden** [comment]
@donpdonp hmm its in the `dependencies` here https://github.com/feross/standard/blob/master/package.json#L19

maybe try installing `standard` again and seeing if that fixes it? might be an npm bug or something...

**Comment by donpdonp** [comment]
I tried it in a project directory that had dozens of other npm packages installed. using standard from a clean directory appears to work fine. thx.

```
donp@wafer:~$ mkdir a
donp@wafer:~$ cd a
donp@wafer:~/a$ npm install standard
standard@3.1.1 node_modules/standard
├── get-stdin@4.0.1
...
donp@wafer:~/a$ touch blank.js
donp@wafer:~/a$ ./node_modules/.bin/standard blank.js 
donp@wafer:~/a$
```

**Comment by maxogden** [comment]
I chalk this one up to npm gremlins, which are rarer than past days, but still lurk in the shadows from time to time
