### ISSUE TITLE
Use semicolons

### ISSUE THREAD

**Issue by jeffersoncarpenter** [feross/standard#691]
Omitting semicolons is unprofessional.  Semicolons improve readability by indicating the ends of expressions.

**Comment by jprichardson** [comment]
This has been discussed so many times already, I'd strongly encourage you to read up on the history here: https://github.com/feross/standard/search?p=2&q=semicolons&type=Issues&utf8=%E2%9C%93

Also, if you really want to use standard with semicolons, use https://github.com/Flet/semistandard.

**Comment by jeffersoncarpenter** [comment]
don't shoot the messenger, I'm just letting you know there's a right way and a wrong way to write javascript.

**Comment by dcousens** [comment]
@jeffersoncarpenter I love the dedication to your piety,  but,  we're not interested, please knock on the next door on this street.

**Comment by jeffersoncarpenter** [comment]
You know I'm right.
