### ISSUE TITLE
Disallow redundant return statements (no-useless-return)

### ISSUE THREAD

**Issue by feross** [feross/standard#694]
A `return` statement with nothing after it is redundant, and has no effect on the runtime behavior of a function. This can be confusing, so it’s better to disallow these redundant statements.

http://eslint.org/docs/rules/no-useless-return

**Comment by yoshuawuyts** [comment]
Yup, sounds good

**Comment by dcousens** [comment]
What about early exits?

**Comment by feross** [comment]
@dcousens Yep, those will still work. The rule only prevents useless returns like:

```js
function foo () {
  if (cond) {
    console.log('hi')
    return
  }
}
```

**Comment by dcousens** [comment]
ACK then

**Comment by feross** [comment]
This will be part of standard v9. The ecosystem impact is 3 repos, with one statement in each requiring modification.
