### ISSUE TITLE
Semicolons and using 'standard' with React/client-side Javascript

### ISSUE THREAD

**Issue by karloespiritu** [feross/standard#698]
I'm using `standard` for all of my new Node.js projects, and it works great so far. I'm wondering if `standard` would also be ideal for React projects. I really like using `standard` as my linter because I prefer my JS code without the semicolons.

Based on the `standardjs` docs, the only gotcha with omitting semicolons is when starting a line with `(`, `[`, or `. And then, I came across this discussion - [https://forum.shakacode.com/t/es6-airbnb-style-guidelines-and-semicolons/235](https://forum.shakacode.com/t/es6-airbnb-style-guidelines-and-semicolons/235)

It was mentioned by someone from AirBnb that these three characters are NOT the only gotchas, but also -- **arithmetic operators** and **template literals**.

I also noticed that most React-based projects, including Facebook's `create-react-app` project still use semicolons. Most of the boilerplate projects for React use Airbnb's JS style guide, which requires using semicolons and dangling commas. 

My question is -- Will there be any issues if I use `standard` as a style guide for React or any client-side Javascript code that is transpiled to ES5? 

It would be really nice to use `standard` for React/client-side javascript projects so I can unify my JS code style guide for both Node.js and React. Thanks.

**Comment by dcousens** [comment]
> Will there be any issues if I use standard as a style guide for React or any client-side Javascript code that is transpiled to ES5?

Nope :+1: 

`standard` will warn you about any of the crazy gotchas thanks to `eslint`.

**Comment by Guria** [comment]
@karloespiritu just try this on cases on [demo](http://standardjs.com/demo.html). Both **arithmetic operators** and **template literals** emits warnings.

**Comment by karloespiritu** [comment]
Awesome thank you very much @dcousens @Guria for the confirmation. 👍  I'll proceed with my plans to use also `standard` for my React projects. I will finally have a unified code style guide for Node.js and React. 🍻

**Comment by LinusU** [comment]
Glad to hear it 🙌
