### ISSUE TITLE
auto-style as much as possible with jsbeautifier

### ISSUE THREAD

**Issue by mvayngrib** [feross/standard#7]
to make it as easy as possible to adhere to this style for the devs

**Comment by yoshuawuyts** [comment]
Alternatively there's also [esformatter](https://github.com/millermedeiros/esformatter) which is used in the [rdio/jsfmt](https://github.com/rdio/jsfmt) project.

**Comment by bcomnes** [comment]
Was able to get a compatible auto format with jsfmt.

**Comment by Flet** [comment]
@bcomnes do you have a .jsfmtrc file handy with everything defined?

**Comment by bcomnes** [comment]
https://gist.github.com/bcomnes/8cba8a9253e47fdb2958

I use it from within sublime, bit it could be adapted to a .jsfmtrc pretty quickly.

Its not perfect but provides an okay auto format that doesn't collide with standard.

**Comment by feross** [comment]
First pass at a `standard --format` command is on the `formatter` branch: https://github.com/feross/standard/commit/11187a65bca014f82441df4409a1a8efdad099d5

Please try it and give feedback / improve it.

**Comment by Flet** [comment]
I'll find some time to play with this tomorrow :)

**Comment by feross** [comment]
awesome!

**Comment by feross** [comment]
[`standard-format`](https://github.com/maxogden/standard-format) is shaping up quite nicely! They've adopted the `esformatter`-based strategy that I prototyped on the `formatter` branch.

Just `npm install standard-formatter -g` for a pretty helpful (not perfect yet!) formatter.

**Comment by bcomnes** [comment]
Cool!

@flet Do you know how to turn this into a sublime plugin?

**Comment by Flet** [comment]
Yeah they have some excellent docs on how to do it here:
http://www.sublimelinter.com/en/latest/creating_a_linter.html

Its really geared for outputting errors from pure linters, but it certainly could be used to trigger a formatter too...

I'd love for there to eventually be a `--format` option built into standard with an exposed option in the `standard` Sublime plugin... maybe when `standard-format` is closer to awesome... IMO @feross should just add it as an experimental flag :)

**Comment by feross** [comment]
@Flet No time right now, but I'd accept a PR that added a `--format` option that just called into `standard-format`.
