### ISSUE TITLE
JS API Error message should contain `index` position

### ISSUE THREAD

**Issue by futurist** [feross/standard#701]
When using JS API, code as below:

```js
standard.lintText('var a = 1\n1var b=2;', {fix: true}, (err, result)=>{
	console.log(err, result)
})
```

the error object of callback result 

```
null { filePath: '<text>',
  messages:
   [ { ruleId: null,
       fatal: true,
       severity: 2,
       source: 'var a = 1\n1var b=2;',
       message: 'Parsing error: Identifier directly after number',
       line: 2,
       column: 2 } ],
  errorCount: 1,
  warningCount: 0,
  source: 'var a = 1\n1var b=2;' }
```

There's should add aditional `index: 12`  in the above result, for better locating the error.

This will good for editors like `Emacs`, to `goto-char` in source position instead of `line+column` combination.

**Comment by feross** [comment]
We're currently just returning the object that ESLint provides. If you want that additional information, you can read in the file and calculate the index yourself.

**Comment by futurist** [comment]
That's ok, for anyone encountered the same problem, I've created a tool for adding `index` field:

https://github.com/futurist/src-location
