### ISSUE TITLE
'FileReader' is not defined

### ISSUE THREAD

**Issue by dalkir** [feross/standard#706]
Hello, I'm having this warning `'FileReader' is not defined.` when I use: `const reader = new FileReader()`. standard see this like a lint error.

How could I fix this?

**Comment by yoshuawuyts** [comment]
Use `window.FileReader` - there's too many globals in the browser to allow
them all

**Comment by dalkir** [comment]
Thank you @yoshuawuyts it's fixed now. I didn't know how to solve it, but it was easy haha.
