### ISSUE TITLE
Object literal throws parse error

### ISSUE THREAD

**Issue by futurist** [feross/standard#709]
Below code will throw **Parse Error**:

```js
echo '{a:1, b:2}' | standard --stdin
```

Throws:

> <text>:1:8: Parsing error: Unexpected token :

But it's valid javascript code.

It's important for this issue, since some times a JS file only store data, to feed other JS to read.

**Comment by rstacruz** [comment]
You probably mean echo('{a:1,b:2}') with parenthesis.

**Comment by rstacruz** [comment]
Oops, actually its not a valid JavaScript. It needs to be ({a: 1}) with
parenthesis because the curlies will otherwise mean a block statement
instead of an object literal.

**Comment by feross** [comment]
@rstacruz Nice to know!

@futurist If you're just storing data in a file, you might want to consider using a .json extension instead of .js.

**Comment by maxlath** [comment]
for the record, the same issue seem to arise with object destructuring assignment:

* valid
```js
var { ids, languages, props, format } = obj
```

* invalid
```js
var ids, languages, props, format
{ ids, languages, props, format } = obj // Parsing error: Unexpected token =
```
* valid
```js
var ids, languages, props, format
({ ids, languages, props, format }) = obj
```
