### ISSUE TITLE
Support @jsx pragma

### ISSUE THREAD

**Issue by brandonhorst** [feross/standard#71]
It's awesome that standard supports jsx now.

In addition to supporting React, babel supports [generic JSX transforms](https://github.com/babel/babel/issues/841), using a pragma like this:

```
/** @jsx mypackage.doSomething */
```
[demo](https://babeljs.io/repl/#?experimental=false&playground=false&evaluate=false&loose=false&spec=false&code=%2F**%20%40jsx%20mypackage.doSomething%20*%2F%0A%0A%3CTest%20%2F%3E)

Of course, when using them, standard is peppered with `'React' must be in scope when using JSX`. Would it be possible to respect this pragma. It's not a Babel invention, React itself required it until recently.

**Comment by feross** [comment]
`standard` just uses [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react) to support jsx. We could just disable the [`"react-in-jsx-scope"`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md) rule - but it seems useful for most users.

I would suggest opening an issue on `eslint-plugin-react` and ask them to support the pragmas you want.

**Comment by brandonhorst** [comment]
Will do, thanks.

**Comment by feross** [comment]
Yep :)
