### ISSUE TITLE
Use `eslint-plugin-import` instead of `no-duplicate-imports`

### ISSUE THREAD

**Issue by ajhyndman** [feross/standard#712]
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md

This is just a more robust implementation.  The use-case I want to support is working with type definition imports, which must necessarily be separate but from the same source file as real imports.

e.g.

```js
import MyComponent from 'components/MyComponent';
import type { Props } from 'components/MyComponent';
```

**Comment by cesarandreu** [comment]
Right now this is probably the biggest pain-point with using standard with flow. This change would rock.

**Comment by feross** [comment]
I hear you loud and clear 👍  Closing this as duplicate issue: #599

**Comment by feross** [comment]
Just a heads up that this will be part of the standard v10 beta. See #599
