### ISSUE TITLE
New rule no-restricted-properties & no-restricted-globals?

### ISSUE THREAD

**Issue by davesnx** [feross/standard#716]
Hello @feross 

I would like to discuss about adding this 2 properties on the standard config. I'm not sure if this is the right repo or I should open it on https://github.com/feross/eslint-config-standard

- `no-restricted-properties`: disallow certain object properties
- `no-restricted-globals`: disallow specific global variables

Basically, adds more options to make the **linter** capable to keep the code healty.
You seem worried about how many repos would you affect and adding this woudn't break anything, just adding a property on the package.json.

Thanks

**Comment by feross** [comment]
@davesnx Sorry - it wasn't clear to me. Are you proposing adding configuration options to allow `standard` users to set the ESLint options you listed? `standard` intentionally doesn't support that kind of configuration. If that's what you're after, I suggest using ESLint directly with the [`eslint-config-standard`](https://github.com/feross/eslint-config-standard) configuration.

**Comment by davesnx** [comment]
I was just proposing a new rule for https://github.com/feross/eslint-config-standard @feross

**Comment by feross** [comment]
I'm still unclear what you're asking for. The http://eslint.org/docs/rules/no-restricted-properties rule for example lets you prevent certain property names from being used. What should `standard` set this to? If you want to configure this option to something specific for your codebase, then you can use eslint directly.

**Comment by dcousens** [comment]
@davesnx just submit the PR.

It will likely answer all questions as to what you have written so far (and isn't clear to me either).
