### ISSUE TITLE
'Try it out' broken

### ISSUE THREAD

**Issue by jonaswindey** [feross/standard#717]
The demo page on http://standardjs.com/demo.html is not working at the moment.

It seems like it's loading https://standardizer.flet.io/ which is broken too.

However, http://flet.github.io/standard-demo/ is still working

**Comment by dcousens** [comment]
Closing in favour of https://github.com/feross/standard/issues/721

**Comment by Flet** [comment]
BTW this is fixed now @jonaswindey
