### ISSUE TITLE
Expected { after 'if' condition even with single lines

### ISSUE THREAD

**Issue by jonaswindey** [feross/standard#718]
Using `standard@8.6.0`, the following code fails:

```javascript
const test = false
if (test)
  console.log(false)
else
  console.log(true)
```
Error:
```
  /Users/jonas/Development/sandbox/test/test.js:2:1: Expected { after 'if' condition.
  /Users/jonas/Development/sandbox/test/test.js:4:1: Expected { after 'else'.
``` 

whereas this one works:

```javascript
const test = false
if (test) console.log(false)
else console.log(true)
```

Could be related to https://github.com/feross/standard/issues/664 , but the issue has been closed and this issue still exists

This makes it difficult to use single-line `if` blocks when they are too long to fit on the same line.

**Comment by LinusU** [comment]
I think this is intentional, I at least prefer this behaviour

**Comment by jonaswindey** [comment]
The error says `Expected { after 'if' condition.`

If I add the curly brackets like this:
```javascript
const test = false
if (test) {
  console.log(false)
}
else {
  console.log(true)
}
```

It says there's an unnecessary { after if (due to being 1 line)

This is confusing to say the least.

**Comment by LinusU** [comment]
I think that it's like so,

single line:

```js
if (thisIsAll) onOneLine()
```

multiple lines:

```js
if (thisIsActually)
  twoLine()
```

**Comment by dcousens** [comment]
@jonaswindey 

```
const test = false
if (test) {
  console.log(false)
} else {
  console.log(true)
}
```

**Comment by jonaswindey** [comment]
Ok, I guess that rule changed than? I remember that 
```javascript
const test = false
if (test) {
  console.log(false)
} else {
  console.log(true)
}
```

Gave ` Unnecessary { after 'if' condition.` because it only contained one line (or other `if`s)

Thanks for clarifying
