### ISSUE TITLE
CORS issue on demo page (also https issue)

### ISSUE THREAD

**Issue by joeytwiddle** [feross/standard#721]
If I visit the demo page [http://standardjs.com/demo.html](http://standardjs.com/demo.html), I cannot format the code. I see this in the Firefox console:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://standardizer.flet.io//lint. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

And this in Chrome's console:

    XMLHttpRequest cannot load https://standardizer.flet.io//version. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://standardjs.com' is therefore not allowed access. The response had HTTP status code 404.

I am running UBlockOrigin in both browsers, but I still get the error even if it's disabled.

And by the way, I also tried accessing the demo page over `https`, but both browsers complained because the certificate is assigned to `*.github.com`.

**Comment by joeytwiddle** [comment]
Oh sorry, this is a duplicate of #717

**Comment by Flet** [comment]
huh, checking this out.

**Comment by Flet** [comment]
fixed! Can you give it a try?

**Comment by feross** [comment]
Works for me, thanks @Flet!
