### ISSUE TITLE
feature request: use .eslintrc to simplify configure

### ISSUE THREAD

**Issue by septs** [feross/standard#722]
I want to detect that the `.eslintrc` file exists by reusing the `.eslintrc` configuration
This avoids repeating the `.eslintrc` configuration once again in `package.json`

**Comment by septs** [comment]
see https://en.wikipedia.org/wiki/Don't_repeat_yourself

**Comment by LinusU** [comment]
There is no configuration of standard, that is the point of it. Or maybe I'm misunderstanding what you are trying to do?

**Comment by septs** [comment]
@LinusU https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es-next-support

**Comment by LinusU** [comment]
But with standard you don't need an `.eslintrc` config at all, so it isn't repeating?

**Comment by feross** [comment]
Standard doesn't recognize `.eslintrc` files, intentionally. This is to ensure that `standard` rules can't be modified unexpectedly by random `.eslintrc` files on your filesystem.

**Comment by chuyik** [comment]
@septs Here's the configurable `standard` for you:
https://github.com/o2team/standard-own

Git it a try if you like :D.

**Comment by jcrben** [comment]
Stuffing more things into `package.json` is annoying. Also another tool `standard` isn't that interesting - I'd rather just stick with `eslint`.

`standard-own` seems cool, but I'd rather not have an underlying dependency on a project which doesn't make it easy to customize. That runs contrary to the customizable philosophy of `eslint`. So I'm switching to `eslint-config-airbnb`.

**Comment by LinusU** [comment]
You can use [`eslint-config-standard`](https://github.com/feross/eslint-config-standard) the same way you would use `eslint-config-airbnb` 👍

**Comment by feross** [comment]
@jcrben If you want to use standard as your starting point, but add/remove/change some of the rules, take a look at [`eslint-config-standard`](https://github.com/feross/eslint-config-standard).

The `standard` cli is for users who want to use that same ESLint configuration but **without knowing anything about ESLint** and **without allowing rules to be customized**. For many teams, the mere option to customize the tool can lead to endless bike-shedding and wasted time, so this is a feature, not a bug.

For those who want customizability, we offer [`eslint-config-standard`](https://github.com/feross/eslint-config-standard).

Cheers!
