### ISSUE TITLE
standard confuses string with missing quotes and new class instance without brackets

### ISSUE THREAD

**Issue by lukechilds** [feross/standard#725]
If I have the code:

```js
const onionoo = new Onionoo()
```

to create a new instance of the `Onionoo` class but leave off the brackets:

```js
const onionoo = new Onionoo
```

standard says:

```
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.

/Users/lukechilds/Dev/oss/onionoo-node-client/test/unit.js
  18:19  error  Missing '
```

It seems like maybe it assumes `Onionoo` is a string without quotes. It would be better if it would warn that there are no parenthesis on the class (or not warn at all, not sure of the pros/cons of leaving off parenthesis). I would assume this would be fairly easy to fix by checking if the `new` keyword is directly before the string.

**Comment by lukechilds** [comment]
Just realised `standard` uses `eslint` under the hood, should I be reporting this there?

**Comment by dcousens** [comment]
@lukechilds yup :+1:

**Comment by lukechilds** [comment]
@dcousens according to ESLint this appears to be an issue with `standard`. It gets reported correctly as `Missing '()' invoking a constructor. (new-parens)` with vanilla ESLint.

https://github.com/eslint/eslint/issues/7792

**Comment by dcousens** [comment]
@lukechilds actually, it appears to be an issue with you :laughing: 

``` js
var Onionoo
const onionoo = new Onionoo

console.log(onionoo)
```
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /home/daniel/test.js:2:17: Missing '()' invoking a constructor.
```

**Comment by lukechilds** [comment]
Ahhhh, found the culprit!

It's not doing it if I call `standard` directly but if I call `snazzy` it does with the exact same input.

```
$ standard
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/lukechilds/Dev/oss/onionoo-node-client/test/unit.js:14:19: Missing '()' invoking a constructor.

$ snazzy
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.

/Users/lukechilds/Dev/oss/onionoo-node-client/test/unit.js
  14:19  error  Missing '

✖ 1 problem
```

Should I open the issue on `snazzy`? 😆

**Comment by dcousens** [comment]
@lukechilds I think so,  feel free to post back and we'll re-open if needed :+1:
