### ISSUE TITLE
js-standard Error Parsing error: Unexpected token = (null) in Atom

### ISSUE THREAD

**Issue by PascalPixel** [feross/standard#726]
```js
import React, {Component} from 'react'

export default class Jake extends Component {
  mathmatical = (ingredient) => { // js-standard Error Parsing error: Unexpected token = (null)
    return `${ingredient} pancakes!`
  }
  render () {
    return (
      <div>'YAYYYY!'</div>
    )
  }
}
```

**Comment by PascalPixel** [comment]
Compiles fine, just get an error from the linter

**Comment by kimsk** [comment]
If you want to use some `es7` syntax, you could use `babel-eslint` by following this [instruction](https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es-next-support).

**Comment by feross** [comment]
The syntax you are using is experimental, so it's not built into ESLint/standard. Once it progresses to stage-4 of the standardization process then it will work out-of-the-box. You can set up babel-eslint here: https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es-next-support
