### ISSUE TITLE
npm debug logs piling up

### ISSUE THREAD

**Issue by kellyrmilligan** [feross/standard#727]
is there an option to just have the reporting output, and not do an exit code that produces the npm debug log?  in dev mode I have a watcher constantly running standard and the logs just pile up

**Comment by LinusU** [comment]
You could probably invoke it as `standard || true` if you are invoking via a shell...

**Comment by kellyrmilligan** [comment]
i discovered it was because I was piping it through snazzy to get better output. seems like if I just use the tool straight up then its fine. would like better output for sure, but can't stand the logs piling up like that.

**Comment by kellyrmilligan** [comment]
I was incorrect in my earlier assumption. it didn't seem to be piling up before(like a month or so ago). i'm invoking it via npm scripts. 

`"standard":  "standard --fix"`

and am now getting npm logs alll the time. i'm wondering if something like 

`standard --fix --failonerror false` could make sense? display the output but don't fail?

**Comment by kellyrmilligan** [comment]
@LinusU that totally worked.

**Comment by feross** [comment]
Glad you got it figured out.
