### ISSUE TITLE
Never start a line with regular expression literal

### ISSUE THREAD

**Issue by academyofzhuang** [feross/standard#728]
If one start a line with a regular expression, it causes parsing error, too.

````js
var s = 'About'
// if string begins with a Capital letter, print it
/^[A-Z].+/.test(s) && console.log(s)
````

Adding a semicolon before regex solved the problem.

Shall we add this exception to the rule.

**Comment by ifraixedes** [comment]
I don't understand what you meant.

Without semicolon, `standard` reports an error, because it's an actual syntax error, if you add a semicolon then the syntax is correct and `standard` doesn't report any error.

**Comment by dcousens** [comment]
@ifraixedes I think @academyofzhuang means these rules:

``` md
Never start a line with (, [, or `
```

**Comment by feross** [comment]
The list is intentionally incomplete. I listed only characters that have I've seen used in actual code, and ignored characters that are usually never used. A more complete list appears later in the rules in the quote from [An Open Letter to JavaScript Leaders Regarding Semicolons](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding):

> The next line starts with [, (, +, *, /, -, ,, ., or some other binary operator that can only be found between two tokens in a single expression.

**Comment by dcousens** [comment]
@ifraixedes a better solution to your problem:

``` js
if (/^[A-Z].+/.test(s)) console.log(s)
```

**Comment by ifraixedes** [comment]
@dcousens I think that you ping the wrong person.

I have never written something how it was expressed in the question, I prefer forms as the one that you described above.

Cheers

**Comment by dcousens** [comment]
Apologies @ifraixedes, I meant @academyofzhuang

**Comment by academyofzhuang** [comment]
I agreed with you. Using boolean shortcut to save a few key strokes isn't best practice to start with. 

The reason I brought up the issue is the parsing error message by js engine was cryptic:

````bas
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/bai/academyofzhuang/test/std.js:2:2: Parsing error: Unexpected token ^
````

When I look at the code, it doesn't make any sense.

````js
var s = 'About'
/^[A-Z].+/.test(s) && console.log(s) // quick and dirty debug
````

Since I believed, as stated in the project readme

> This is the only gotcha with omitting semicolons – automatically checked for you!

 It took me some time to realize a semicolon might be needed.

I agree this is a non-issue. To quote the project readme:

> Clever short-hands are discouraged, in favor of clear and readable expressions, whenever possible.

Thank you for the detailed explanation and example code!
