### ISSUE TITLE
Lint inside Markdown

### ISSUE THREAD

**Issue by mightyiam** [feross/standard#73]
I've some examples in the README.md and it would be great if Standard could lint those.

    ```js
    // code
    ```

etc.

**Comment by jprichardson** [comment]
While I want a tool to do this as well, I think it's out of scope for
standard. Now that standard supports using its features programmatically,
someone could build a tool on top of standard to offer this functionality.

On Friday, March 20, 2015, Shahar Or <notifications@github.com> wrote:

> I've some examples in the README.md and it would be great if Standard
> could lint those.
>
> ```js
> // code
> ```
>
> etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feross/standard/issues/73>.
>


-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson
