### ISSUE TITLE
Reference responsible rule in RULES.md

### ISSUE THREAD

**Issue by googol7** [feross/standard#730]
It would be nice if the respective rule of [eslintrc.json](https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json) responsible would be mentioned for every described rule in [RULES.md](https://github.com/feross/standard/blob/master/RULES.md)

**Comment by feross** [comment]
That's a cool idea. PRs welcome to make this happen!

**Comment by joshuacolvin** [comment]
I can work on this if no one else is. Any formatting or placement preference?
