### ISSUE TITLE
Duplicate errors when reassigning native globals

### ISSUE THREAD

**Issue by nickmccurdy** [feross/standard#731]
I have some test code that needs to reassign `global` because the implementation code is instrumenting the global scope with a DSL, but I don't want this to pollute my tests.

According to eslint, this should be as simple as disabling `no-native-reassign`, or the new `no-global-assign` which deprecates it. I would except that I would only need to disable one of these rules, but `standard -v` produces two errors for the same line, one for each rule. I would expect to only need to disable the latter. This looked like an issue with `standard` to me, but I'll reopen this upstream if you think it's internal to `eslint`.

# Reproduction
With `standard@8.6.0`:
```js
var oldGlobal = global
global = oldGlobal
```

# Expected
```
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/nick/Repos/purified/test/example.js:2:1: Read-only global 'global' should not be modified. (no-global-assign)
```

# Actual
```
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/nick/example.js:2:1: Read-only global 'global' should not be modified. (no-global-assign)
  /Users/nick/example.js:2:1: Read-only global 'global' should not be modified. (no-native-reassign)
```

# Workaround
Disabling a single rule doesn't work, you must disable both.
```js
var oldGlobal = global
global = oldGlobal // eslint-disable-line no-native-reassign, no-global-assign
```

**Comment by feross** [comment]
@nickmccurdy You're correct. We currently have both rules enabled. I'll disable the deprecated one.

**Comment by feross** [comment]
This will go out in the next release of `standard`

**Comment by nickmccurdy** [comment]
Cool, thanks!
