### ISSUE TITLE
Convert all configs to use new "error" style

### ISSUE THREAD

**Issue by feross** [feross/standard#734]
Right now our configs do this:

```js
{
  "rule-name": 2
}
```

But this can be rewritten to:

```js
{
  "rule-name": "error"
}
```

The latter is more readable.

**Comment by dcousens** [comment]
Agreed

**Comment by joshuacolvin** [comment]
I can take this one.

**Comment by feross** [comment]
@joshuacolvin Actually, I think I should take this one, if you haven't started it yet. There are some pending rule change PRs that I need to merge for v9. They won't apply cleanly if we change every line of the config first. Hopefully you haven't started this uet.

**Comment by joshuacolvin** [comment]
No worries! I haven't started yet.

**Comment by feross** [comment]
This is now resolved.
