### ISSUE TITLE
Disallow await inside of loops (no-await-in-loop)

### ISSUE THREAD

**Issue by feross** [feross/standard#737]
Performing an operation on each element of an iterable is a common task. However, performing an `await` as part of each operation is an indication that the program is not taking full advantage of the parallelization benefits of `async`/`await`.

Usually, the code should be refactored to create all the promises at once, then get access to the results using `Promise.all()`. Otherwise, each successive operation will not start until the previous one has completed.

http://eslint.org/docs/rules/no-await-in-loop

**Comment by feross** [comment]
No ecosystem impact.

**Comment by dougwilson** [comment]
There may be no current ecosystem impact (maybe from lack of widespread async function usage?), but I'm a little iffy on this rule. Maybe I just don't understand what I'm missing :) So my thought is that sometimes you _want_ to go through an async loop in series, not parallel. This rule would seem to make that difficult, unless I'm missing something.

**Comment by feross** [comment]
You're precisely right. This rule does make going through an async loop in series an error.

I was iffy as well. My thinking with these rules that I'm iffy on has always been to enable them and then remove them at the first sign of trouble, i.e. if any users report legit code that they're being prevented from writing. The nice thing about relaxing a rule is that you can do it in a minor version :)

Happy to go either way on this one. Anyone else have input?

**Comment by jprichardson** [comment]
I use await inside of for-loops frequently. The common use case? Http requests. If it's all parallel, I could inadvertently blast the service and hit rate limitations.

**Comment by feross** [comment]
Okay, that's enough for me. Let's skip this rule.
