### ISSUE TITLE
Disallow async functions which have no await expression (require-await)

### ISSUE THREAD

**Issue by feross** [feross/standard#738]
Async functions which have no `await` expression may be the unintentional result of refactoring. This rule warns `async` functions which have no `await` expression.

http://eslint.org/docs/rules/require-await

**Comment by not-an-aardvark** [comment]
It might be worth reviewing [this discussion](https://github.com/eslint/eslint/issues/6820#issuecomment-257117990) before adding this rule to Standard.

**Comment by feross** [comment]
@not-an-aardvark Good point. We actually didn't add `require-yield` to `standard` because, despite what that eslint issue thread says, there apparently are use cases for generators without `yield`, namely when interacting with third-party libraries that expect a generator. See https://github.com/feross/standard/issues/192#issuecomment-123297837

For that reason, maybe we should also refrain from this rule, since it's very similar in spirit.

Those who upvoted, do you have any new thoughts? (@timoxley, @ifraixedes, @LinusU, @dougwilson)

**Comment by LinusU** [comment]
Hmm, that was actually very good points. I think I'm leaning towards not enabling this rule now :)

**Comment by jsdnxx** [comment]
I would be against adding this to standard. I use `asysnc` to mean "this function is gonna return a promise no matter what," not "I intend to use `await` in the body of this function."

**Comment by feross** [comment]
Thanks for the feedback @LinusU and @jsdnxx. Closing this for now.
