### ISSUE TITLE
Webstorm/IntelliJ integration

### ISSUE THREAD

**Issue by olegam** [feross/standard#74]
Has anyone tried to make a code style scheme for Webstorm they want to share?

**Comment by feross** [comment]
I haven't seen that one yet, but please share it here if you make one. We can add it to the README, with the [other editors](https://github.com/feross/standard#editor-plugins).

**Comment by feross** [comment]
This isn't really an issue with `standard` so I'm going to close. Anyone who creates a text editor plugin is welcome to send a PR to add a link to the readme!
