### ISSUE TITLE
Ignore a file by comment

### ISSUE THREAD

**Issue by Rokt33r** [feross/standard#740]
Could I ignore a file by adding a comment like the below example?

```js
/* skip-lint */

function defenitelyNotStandardSum(a, b) {
  return a+b;
}
```

I always appreciate your work. 👍

**Comment by feross** [comment]
You can ignore an entire file by adding this to the top of the file:

```js
/* eslint-disable */
```

**Comment by Rokt33r** [comment]
Thanks for your answer! 👍 👍
