### ISSUE TITLE
curated-linter

### ISSUE THREAD

**Issue by mightyiam** [feross/standard#742]
Thank you so much for standard and standard-engine and the wonderful ecosystem that had evolved around them.

Having read through the code for standard-engine and contemplated the API for several hours, I have spent more than a day coming up with an initial readme for an alternative. It is called curated-linter and it lives here: https://github.com/mightyiam/curated-linter.

Although not written in the readme, I have intention for it to be able to provide the users of linters produced by standard-engine full compatibility, with deprecation warnings. Off the top of my head the incompatibilites are the format of the user's `package.json` configuration property feature and also the signature of the `lintFiles` and `lintText`. There are probably more.

**Comment by feross** [comment]
So this is basically a fancy version of `standard-engine`? Neat.
