### ISSUE TITLE
Which companies are using `standard`?

### ISSUE THREAD

**Issue by feross** [feross/standard#744]
**If you use `standard` at your company or organization, please leave a comment here.** Include a link to proof, if you can!

Context: I just got a message from someone trying to convince his co-workers to adopt `standard`. He asked for a list of companies who are currently using `standard` to make them feel more comfortable. Then I realized that we don't actually have such a list. Let's make one!

**Comment by feross** [comment]
I'll start things off with my company, [Study Notes](https://www.apstudynotes.org/). Here is [proof](https://github.com/feross/studynotes/blob/471e24da21c83ed460ef431b10d387e286266a30/package.json#L106).

**Comment by watson** [comment]
- Opbeat ([proff](https://github.com/opbeat/opbeat-node/blob/10dbc33193e026f725fa14c1ab116ac50ddf8c7f/package.json#L79))

**Comment by southpolesteve** [comment]
Bustle [proof](https://github.com/bustlelabs/shep/blob/master/package.json#L66)

**Comment by andresmijares** [comment]
Shiftgig (all private :-( sry)

**Comment by dcousens** [comment]
* crypto-browserify (https://github.com/crypto-browserify/browserify-aes/blob/master/package.json#L11)
* cryptocoin-js (https://github.com/cryptocoinjs/secp256k1-node/blob/master/package.json#L43)
* bitcoinjs (https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/package.json#L42)

**Comment by skellock** [comment]
* [Ignite](https://github.com/infinitered/ignite) - A React Native Boilerplate ([proof](https://github.com/infinitered/ignite/blob/master/ignite-base/package.json#L66)) - by [Infinite Red](https://infinite.red) + all our client's apps
* [Reactotron](https://github.com/reactotron/reactotron) - An Electron app for debugging React Native & React JS ([proof](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-app/package.json#L67)) + 13 modules in all
* [apisauce](https://github.com/skellock/apisauce) - axios + a few opinions ([proof](https://github.com/skellock/apisauce/blob/master/package.json#L49))

**Comment by cesarandreu** [comment]
* [Treasure Data](https://www.treasuredata.com) (proof: [digdag-ui](https://github.com/treasure-data/digdag/blob/master/digdag-ui/package.json), [td-js-sdk](https://github.com/treasure-data/td-js-sdk/blob/master/package.json))

We're also using it in our main product's frontend, which is a large SPA.

**Comment by feross** [comment]
@cesarandreu Is your front-end open source by chance? I'm looking for more codebases that use babel, JSX, and all the modern fanciness to add to our test suite. We over-represent modules vs. apps in our current test suite.

**Comment by hkjorgensen** [comment]
* Zendesk

use it in multiple products and internal tools. Private repos, so no proof.

**Comment by jsdnxx** [comment]
here's some Zendesk proof in an open source repo https://github.com/zendesk/radar/blob/master/package.json#L76

**Comment by bcomnes** [comment]
We use a slightly [customized eslint](https://github.com/ZHealth/eslint-config-esmanning/blob/master/package.json#L12) @zhealth 

Last year when I worked at [Jaguar Land Rover](https://www.jlrtechincubator.com/jlrti/)'s @PDXostc our team used standard on some closed source projects I'm not allowed to talk about.

**Comment by bcomnes** [comment]
Also there was this pic of @timbl  😉 

![ckcdjzlugaam8qy jpg-large](https://cloud.githubusercontent.com/assets/166301/21874876/b0a87eea-d82c-11e6-95fd-230862d9af80.jpeg)
-- https://twitter.com/feross/status/740592720230518784/photo/1

**Comment by bcomnes** [comment]
Also @brendaneich (Same thread as above) can be seen reppin standard 🙌

<img width="645" alt="screen shot 2017-01-11 at 6 38 17 pm" src="https://cloud.githubusercontent.com/assets/166301/21874968/49345daa-d82d-11e6-9334-b668e2b9e641.png">

https://twitter.com/BrendanEich/status/741277499376603138

**Comment by michealparks** [comment]
MongoDB uses standard for quite a few of its web properties! (including mongodb.com) Unfortunately since the repos are private, the only proof I can present is a stamp on a package:
https://www.npmjs.com/package/@mongodb-js/mongodb-ui-components

**Comment by timdp** [comment]
* [Zentrick](https://www.zentrick.com/) ([proof](https://github.com/zentrick/iab-vast-model))

**Comment by xicombd** [comment]
- [Typeform](https://www.typeform.com/)

We started using it for more than a year ago, in multiple projects including internal tools, node services, web apps and our mobile app. All private repos, no proof :(

**Comment by jprichardson** [comment]
[All repos](https://github.com/ExodusMovement/) that Exodus Movement, Inc. owns including the [main app](https://www.exodus.io/) (private) itself use it.

**Comment by davidmarkclements** [comment]
We use `standard` at [nearForm](http://npm.im/nearform)

**Comment by olizilla** [comment]
- [TABLEFLIP](https://tableflip.io/) ([proof](https://github.com/tableflip/i18nify/blob/5fbf0bb4e05a38888cdf4fdf81afd76ee197b867/package.json#L33))

**Comment by VictorBjelkholm** [comment]
[Protocol Labs](http://ipn.io/) (Behind IPFS & libp2p) across basically all JavaScript projects that are using [aegir](https://github.com/dignifiedquire/aegir) ([proof](https://github.com/dignifiedquire/aegir/blob/master/package.json#L39-L41))

**Comment by garretto** [comment]
We use it on one product at TASER (no proof) https://www.taser.com/

**Comment by gimenete** [comment]
Clevertech. We have many projects and we use `standard` in a few of them.

**Comment by rstacruz** [comment]
- [Mashupgarage](http://mashupgarage.com/) :)

**Comment by 0x00A** [comment]
[![voltra.co](https://voltra.co/images/voltra-goldscript.svg)](https://voltra.co)

**Comment by gismodo** [comment]
Unnamed folderUnnamed folder

**Comment by feross** [comment]
I just learned that the UK government is using `standard`. Specifically, it's used by the UK Government Digital Service (GDS). Here's the [proof](https://github.com/alphagov/govuk_frontend_toolkit/blob/949803ef1ec810dbf1997d310927527047bf88b8/package.json#L12).

**Comment by 2color** [comment]
[OptioPay](https://www.optiopay.com) uses it in the core product and internal tools. 

Private repos, so no proof.

**Comment by Fenwil** [comment]
@feross would be great to have a section on the website "Who's using it?"

**Comment by feross** [comment]
@Fenwil Agreed – let's convert this issue into a section in the readme/website. Until then, let's keep this issue open so we can continue to learn about new users.

**Comment by watson** [comment]
@feross let me know if you want help with adding this to the README.md

**Comment by jsdnxx** [comment]
here's zendesk logos for whoever starts gathering this: https://www.zendesk.com/company/brand-assets/#logo

**Comment by watson** [comment]
Here's Opbeats: http://brand.opbeat.com

**Comment by feross** [comment]
Thanks for volunteering to help @watson. I just sent a PR: https://github.com/feross/standard/issues/744 Feedback welcome.

**Comment by watson** [comment]
PR is: #764

**Comment by feross** [comment]
It's merged. Looks pretty cool if you ask me! https://github.com/feross/standard#who-uses-javascript-standard-style

**Comment by dsingleton** [comment]
> I just learned that the UK government is using standard. Specifically, it's used by the UK Government Digital Service (GDS). Here's the proof.

GDS-dev here 👋  

We're using it on our shared frontend tooling repos, like the one you linked, and we recommend it in our [coding styleguides](https://github.com/alphagov/styleguides/blob/master/js.md#running-standard-manually) repo. 👍

**Comment by feross** [comment]
@dsingleton Nice :)

**Comment by kt3k** [comment]
- [Karma](https://github.com/karma-runner/karma/blob/v1.4.1/package.json#L352)
- [greenkeeper](https://github.com/greenkeeperio/greenkeeper/blob/v4.2.0/package.json#L42)
- [engine.io](https://github.com/socketio/engine.io/blob/2.0.1/package.json#L39) of socket.io

**Comment by feross** [comment]
Thanks, @kt3k. Added Karma and Greenkeeper to the readme. (Engine.io doesn't have a logo)

**Comment by feross** [comment]
Closing this issue now. Thanks to everyone who shared where they're using `standard`, whether at work or in an open source project. Cheers!

If you want to be on the list, you can still leave a comment or send a PR and I'll add you.

**Comment by hanford** [comment]
Eaze is using standard!

Here is a photo from one of our many private repos.

![package.json](http://d.pr/i/YS8zY+)

And our logo!

![logo](https://cloud.githubusercontent.com/assets/2148168/26326214/2783bc86-3eef-11e7-9145-e3fdfc3264e5.png)

**Comment by paulmelnikow** [comment]
I'm making an argument to choose `standard` over `semistandard` for a project I maintain, and found the list at standardjs.com. I started down the list, and initially was confused, because a number of the big projects projects I checked, like the Mongo and Neo4j JavaScript drivers and express, have semicolons. I understand why these projects are on the list. Though, I still need to identify major projects which are not using semicolons.

These are the most prominent open-source projects I could find, using standard with no semicolons:

- Karma
- Github projects: atom, electron, node-fetch
- npm
- Zeit projects: next.js, hyper, styled-jsx
- Greenkeeper
- body-parser (part of express)

Other prominent projects not using semicolons (though not using standard):

- Bootstrap
- Vue

I'm curious if there are other major ones I'm missing…

**Comment by LinusU** [comment]
@paulmelnikow In express, you'll see that we convert every line that we touch to be standard compliant, so we are slowly getting there. We don't want to convert everything in one go because it would make maintaining our old versions harder...

**Comment by paulmelnikow** [comment]
> In express, you'll see that we convert every line that we touch to be standard compliant, so we are slowly getting there. We don't want to convert everything in one go because it would make maintaining our old versions harder...

Wow! That's really good to know. It makes sense why you wouldn't change it all in one go.

Do you have tooling that enforces that the changed lines are brought up to standard? I imagine that would be very difficult to check without tooling.

**Comment by dougwilson** [comment]
I just run standard against the PR using a bash script that only shows the errors on the changed lines.

**Comment by paulmelnikow** [comment]
Does that run in CI?

**Comment by dougwilson** [comment]
No, because I couldn't figure out how to get that running with the correct diff, as it would see lines changed in Travis CI that the user never changed. Since GitHub is not used to merge PRs anyway, easier just to automatically fix lint errors for contributors during landing instead of forcing the contributor to figure it out anyway.
