### ISSUE TITLE
Errors for 'HTMLFormElement' is not defined and similar

### ISSUE THREAD

**Issue by lukasoppermann** [feross/standard#745]
Hey, standard yells at me:

```
   20:31  error  'HTMLFormElement' is not defined
   22:31  error  'HTMLBodyElement' is not defined
  116:1   error  'ShadyCSS' is not defined
  120:30  error  'HTMLElement' is not defined
  126:5   error  'ShadyCSS' is not defined
  263:1   error  'customElements' is not defined
```

`ShadyCSS` makes sense, but the rest should be fine. Is this something to do with #46?

**Comment by feross** [comment]
You have three options.

1. Explicitly get the variable from the global `window` object, for example: `window.HTMLFormElement`. (`standard` only exposes `window`, `document`, and `navigator` globals in the browser.)

2. Whitelist the global variables with a comment at the top of the file: `/* global HTMLFormElement */`

3. Whitelist all browser globals with a comment at the top of the file: `/* eslint-env browser */`

**Comment by feross** [comment]
Also, this is a dupe of https://github.com/feross/standard/issues/672

**Comment by lukasoppermann** [comment]
Ahh, thanks. Sorry I searched but did not find the other issue.

**Comment by feross** [comment]
No problem 👍
