### ISSUE TITLE
Catch 22

### ISSUE THREAD

**Issue by jescalan** [feross/standard#749]
If you run the following code:

```js
true ? 'hello' : (function () { return 'hi' }).call()
```

Standard will warn you that you have _"Gratuitous parentheses around expression"_. However, if you remove the parens, it will warn you to _"Wrap an immediate function invocation in parentheses"_.

Is there any way out of this?

> While the code example is silly, it was meant to be for simplification. I am actually running an expression like this with real code, promise.

**Comment by gismodo** [comment]
分享Blasterjaxx/Breathe Carolina的单曲《Soldier (Extended Mix)》: http://music.163.com/song/408140272/?userid=89343541 (来自@网易云音乐)



发自我的小米手机http://m.browser.baidu.com/
On Jeff Escalante <notifications@github.com>, Jan 18, 2017 7:19 AM wrote:

If you run the following code:

true ? 'hello' : (function () { return 'hi' }).call()

Standard will warn you that you have "Gratuitous parentheses around expression". However, if you remove the parens, it will warn you to "Wrap an immediate function invocation in parentheses".

Is there any way out of this?

While the code example is silly, it was meant to be for simplification. I am actually running an expression like this with real code, promise.

**Comment by feross** [comment]
This works:

```js
true ? 'hello' : (function () { return 'hi' }.call())
```
