### ISSUE TITLE
importScripts incorrectly reported

### ISSUE THREAD

**Issue by JakeChampion** [feross/standard#75]
```
// worker.js
importScripts('../../pouchdb.min.js')
```

If you run this file through `standard`, it returns 

``` bash
worker.js:2:0: 'importScripts' is not defined.
```

`importScripts` is a valid function in a worker context and as such, shouldn't error.

**Comment by JakeChampion** [comment]
`self` is also another property that exists in workers that `standard` returns a false positive for.

**Comment by feross** [comment]
This edge case is documented in the readme now: https://github.com/feross/standard#what-about-web-workers

The recommendation is to just add a comment to the top of your worker:

```js
/* global self, importScripts */
```
