### ISSUE TITLE
Nested 'import' with code splitting support

### ISSUE THREAD

**Issue by hanford** [feross/standard#751]
In my code for code-splitting, I'm getting:

`index.js:156:9: Parsing error: 'import' and 'export' may only appear at the top level`

However, according to the webpack2 guides and the proposed ES6 modules spec, import _can_ in fact be nested.

https://webpack.js.org/guides/migrating/#code-splitting-with-es2015

**Comment by feross** [comment]
It looks like `import()` is still in stage 3 of the standardization process. ESLint has a policy of only implementing features in their parser once they're in stage 4. You can try installing this babel plugin (https://babeljs.io/docs/plugins/syntax-dynamic-import/) and tell standard to use babel as it's parser. To do that:

```
npm install babel-eslint
standard --parser babel-eslint
```

**Comment by hanford** [comment]
Thanks for the speedy response!
