### ISSUE TITLE
Unexpected token = (null) on x = {}

### ISSUE THREAD

**Issue by mustafawm** [feross/standard#756]
Hi, 

I have the following in my code:

```
export default class App extends React.Component {

  state = { 
    aa: {},
    bb: {},
    cc: []
  }
...
```
keep getting `Parsing error: Unexpected token = (null)` on 3:9 (the `=`) even when I try to ignore the warning with `// eslint-disable-line` or other forms of ignoring/hiding warning. 

Any advice on how to ignore/pass this error, as it's blocking StandardJS from scanning the rest of the file.

**Comment by falmar** [comment]
You need to put the state of the react component inside the constructor that receive a props parameter then call the `super` method and pass the props parameter to call the constructor of the React.Component you inherit from..

Here is an example:

```jsx
export default class App extends React.Component {
  constructor (props) {
    super(props)

    this.state = {
      aa: {},
      bb: {},
      cc: {},
    }
  }

  render () {
    return <div />
  }
}
```

**Comment by mustafawm** [comment]
Thanks, I know that but the team is using `babel-preset-stage-2` which allows defining the state in the format I put above.

So there is no other way to ignore/skip this type?

**Comment by falmar** [comment]
Ah well. I tried it out myself and yes this warning raise up. May it be that ESLint does not quite understand this feature yet?

**Comment by mustafawm** [comment]
Thanks. Yeah, I think you're right, it is an ESLint issue.

**Comment by feross** [comment]
`standard` only supports stage 4 features. If you want to use earlier features, then you need to set a custom parser. See: https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es-next-support

**Comment by p4bloch** [comment]
Proper link to what @feross mentions above: https://github.com/feross/standard#how-do-i-use-experimental-javascript-es-next-features
