### ISSUE TITLE
Disallow Magic Numbers

### ISSUE THREAD

**Issue by Kikobeats** [feross/standard#757]
What do you think about this rule?

- Definition: http://eslint.org/docs/rules/no-magic-numbers
- Context: https://twitter.com/Kikobeats/status/821361036532006914

My start points are:

**PROS**

- Magic numbers are too clever, use a name for avoid it is always helpful.

**CONS**

- Maybe too restrictive related with the live cycle of the code.

**Comment by mafintosh** [comment]
👎 - Plenty of use cases for inlining numbers (file permissions etc)

**Comment by yoshuawuyts** [comment]
Agree, while I like this rule in theory I don't think it's practical
