### ISSUE TITLE
Add missing rules to RULES.md

### ISSUE THREAD

**Issue by joshuacolvin** [feross/standard#758]
As discussed in #741 

Add missing rules from `eslintrc.json` to RULES.md. I am about halfway done with this. Opening issue for discussion, feedback, etc.

**Comment by feross** [comment]
@joshuacolvin Great news!

If want, you can open a work-in-progress (WIP) PR for early feedback. If you put "WIP" in the title, the contributors will know not to merge it before it's ready.
