### ISSUE TITLE
fix code style badge markdown

### ISSUE THREAD

**Issue by callmecavs** [feross/standard#760]
noticed in trying to add the code style badge (the shields.io one) to some of my READMEs that copy/pasting the code on the README doesn't work.

GitHub seems to get tripped up on the URL encoded space - replacing the `%20` encode with an `_` yields the same text, and fixes the badge embed.

Submitted a PR too: #761

**Comment by yoshuawuyts** [comment]
Noticed this too today, I think given the wide spread use of this badge it
should probably either be brought up with shields.io or GitHub support

**Comment by feross** [comment]
Thanks for the PR, merged it. I wasn't able to reproduce the issue, though. Maybe it was a transient issue? Can you check and see if it `%20` still causes problems for you?

**Comment by callmecavs** [comment]
@yoshuawuyts @feross still seeing the problem on my end - also not seeing `es6` work for codeblock highlighting on README's anymore (though `javascript` correctly highlights ES6 syntax now). noticed it around the same time as I noticed the badge is

**Comment by feross** [comment]
@callmecavs Do you have a link to a readme that exhibits the issue?

Sounds like they updated the version of https://github.com/github/markup ?

**Comment by callmecavs** [comment]
@feross highlighting is broken [here](https://github.com/callmecavs/layzr.js) for me, code style broken [here](https://github.com/yoshuawuyts/choo) for me

**Comment by feross** [comment]
The badge is not broken for me in Chrome Stable. See:

<img width="950" alt="screen shot 2017-01-24 at 5 09 32 pm" src="https://cloud.githubusercontent.com/assets/121766/22273885/30b0298c-e258-11e6-8e41-8a9a030b871a.png">

What is the http response codes that you get for the following URLs?

1. https://img.shields.io/badge/code%20style-standard-brightgreen.svg?style=flat-square
2. https://camo.githubusercontent.com/60b623caed11e738da0b201abab8b8d2de66a7b0/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636f64652532307374796c652d7374616e646172642d627269676874677265656e2e7376673f7374796c653d666c61742d737175617265 (github's cached version)

**Comment by dougwilson** [comment]
Many shields io badges have a space. I have been seeing over the past week at least github flipping between them broken and not broken. I assume this is a general github issue.

**Comment by callmecavs** [comment]
@feross @dougwilson getting random 504's on some cached badges - looking at the choo repo again, now its the npm badge. could be related to GitHub caching issue

<img width="1440" alt="screen shot 2017-01-24 at 8 38 07 pm" src="https://cloud.githubusercontent.com/assets/2293641/22274542/202fd75c-e275-11e6-84f1-5ac5a74979bf.png">

**Comment by feross** [comment]
I've reached out to GitHub support on Twitter. Closing this, as it's not a `standard` issue.

**Comment by feross** [comment]
@callmecavs GitHub is asking if you can open an issue about this here http://git.io/c

**Comment by callmecavs** [comment]
@feross i opened one yesterday when I pinged GitHub [on twitter]() about it, ill submit another in a bit

**Comment by feross** [comment]
No worries if you already opened an issue

**Comment by callmecavs** [comment]
will let you known when i hear back
