### ISSUE TITLE
no-new is incompatible with no-unused-vars in testing environments

### ISSUE THREAD

**Issue by Jakobud** [feross/standard#762]
`no-new` and `no-unused-vars` is a weird combination of rules when it comes to building tests. For example, I want to test that an error is caught when instantiating an object incorrectly using Mocha for testing:

```
asset.throws(function () {
  new MyObject();  // object is expecting parameters but I'm not providing them in order to purposely force an error to be thrown
})
```

Because I'm missing some parameters when instantiating my object here, I would expect my object to throw an error, which is does and Mocha tests it correctly. However, `new` is used by itself without assigning it to a variable and StandardJS does not like this. So easy fix right:

```
asset.throws(function () {
  let foo = new MyObject(); 
})
```

Fixed one issue but introduces another. Now StandardJS does like this because `foo` is defined but not used. 

What am I supposed to do in this situation? Seems kind of bogus that I would to write additional dummy code to use `foo` just to satisfy StandardJS. Any advice?

**Comment by feross** [comment]
Both these rules are usually quite useful in the general case, but there are always circumstances where you may need to override certain rules. `standard` provides an easy mechanism for this. Just add a comment:

```js
asset.throws(function () {
  new MyObject() // eslint-disable-line 
})
```

**Comment by Jakobud** [comment]
Oh man I don't know how I missed that option. Thank you,

**Comment by feross** [comment]
No problem!
