### ISSUE TITLE
window.Math

### ISSUE THREAD

**Issue by yukulele** [feross/standard#768]
> Always prefix browser globals with `window.`.
> Exceptions are: `document`, `console` and `navigator`.
> 
> eslint: `no-undef`

also for `Math`?

**Comment by dcousens** [comment]
`Math` is a global on its own

**Comment by yukulele** [comment]
Not sure to understand...
So I can use `Math` directly because it's not a "browser global" but "global on its own"?

**Comment by dcousens** [comment]
Yes :+1:

**Comment by feross** [comment]
@yukulele That's right. `Math` is part of the JavaScript language itself, not just something that the browser or Node.js adds into the global context.
