### ISSUE TITLE
how to check all subdirectories

### ISSUE THREAD

**Issue by matart15** [feross/standard#769]
I have following structure

```
src/app.js
src/utils/a.js
src/utils/b.js
src/component/post/a.js
src/component/post/b.js
src/component/user/a.js
src/component/user/b.js
src/component/user/posts/a.js
src/component/user/posts/b.js
...
```

`standard --fix src/**/*.js` does not lint `src/component/user/posts/a.js`

currently I am using
```
standard --fix src/**/*.js src/**/**/*.js src/**/**/**/*.js 
```

is there any other way?

**Comment by matart15** [comment]
https://github.com/feross/standard/issues/135

**Comment by feross** [comment]
This is happening because your shell is expanding the ** in a different way than `standard` does: only one level deep. Put the glob pattern in quotes and then your shell won't touch it.

```
standard --fix "src/**/*.js"
```
