### ISSUE TITLE
Programatic API

### ISSUE THREAD

**Issue by emgeee** [feross/standard#77]
There was previously a `lintText()` method that would allow you to `require('standard')` and lint a string but it appears this functionality has been removed, was there a reason for this?

**Comment by feross** [comment]
`lintText()` is available on the [`speed`](https://github.com/feross/standard/tree/speed) branch. You can see it here: https://github.com/feross/standard/blob/speed/index.js#L30-L39

We're waiting for https://github.com/eslint/eslint/pull/2115 to get merged and released before we can release this branch as the next version of `standard`.

**Comment by feross** [comment]
I'm going to close this, as there's already an issue for adding a programmatic API here: https://github.com/feross/standard/issues/60

:)
