### ISSUE TITLE
momentJS var 'not modified' in while loop 

### ISSUE THREAD

**Issue by benjaminhoffman** [feross/standard#770]
Noticed that linter yells that my while-loop variable _"is not modified in this loop"_, even though I am  (via momentJS).  You'll see from the code & screenshot below that I subtract one month with momentJS on each iteration.  Here's the relevant part:

```javascript
    const dateStart = moment('2016-02-01')
    const dateEnd = moment()
    while (dateStart < dateEnd) {
      //
      //subtract 1mnth
      dateEnd.subtract(1, 'month')
    }
```

<img src="https://puu.sh/tJQsJ/4c52937a94.png">

Thoughts on this one?

**Comment by feross** [comment]
This is a limitation of the `no-unmodified-loop-condition` rule. More info about it here: https://github.com/eslint/eslint/issues/6984

In short, what's happening is that the identity of the `dateEnd` object isn't actually changing in the loop body, as the `subtract` method just makes some changes to an internal `Date` object. But when the condition is executed, it is implicitly being coerced to a `Number`, which is of course changed by the `subtract()` call.

So, you can work around it by explicitly calling [`valueOf()`](https://momentjs.com/docs/#/displaying/unix-timestamp-milliseconds/):

```js
while (dateStart.valueOf() < dateEnd.valueOf()) {
}
```

(You could also use `d.unix()` or `d.toDate()`)

**Comment by feross** [comment]
There is a proposal to eslint that would let us relax this rule a bit so that *any reference* to the condition variables in the loop body would be treated as a modification. Then it would only be an error to completely omit a condition variable from the body.

You can follow this here: https://github.com/eslint/eslint/issues/8021

**Comment by dcousens** [comment]
> it is implicitly being coerced to a Number

I always found the nature of `Date` doing that really funky and weird
