### ISSUE TITLE
vim modeline for "standard"?

### ISSUE THREAD

**Issue by kaihendry** [feross/standard#772]
For vim users, used to using tabs in their ~/.vimrc, e.g.

    set softtabstop=4
    set tabstop=4

Is there a gateway modeline you could please document for the 2 spaces to look like tabs? http://vimdoc.sourceforge.net/htmldoc/options.html#'softtabstop'

Many thanks,

**Comment by feross** [comment]
I'm not an advanced user of vim, so I don't know how to do what you're suggesting. If you (or another Vim user) wants to send a PR for this, I'll merge it.

**Comment by kaihendry** [comment]
The modeline seems to be:

    // vim: set ts=2 sw=2 sts=2 expandtab:
