### ISSUE TITLE
Disallow Use of Chained Assignment Expressions (no-multi-assign)

### ISSUE THREAD

**Issue by feross** [feross/standard#776]
This rule disallows using multiple assignments within a single statement.

http://eslint.org/docs/rules/no-multi-assign

```js
var a = b = c = 5 // avoid

var a = 5  // ok
var b = a
var c = a
```

Rule: 

```
no-multi-assign: "error"
```

**Comment by dcousens** [comment]
``` js
var a = 5  // ok
var b = a
var c = a
```

Is probably more likely how it would as an example for alternatives

**Comment by feross** [comment]
@dcousens Yep, you're right. Updated the example.

**Comment by feross** [comment]
This rule fails in 34 repos, and prevents a bit more than I'm comfortable with. For example:

```js
exports.no = exports.noCase = require('no-case')
exports.dot = exports.dotCase = require('dot-case')
```

```js
exports.randomBytes = exports.rng = exports.pseudoRandomBytes = exports.prng = require('randombytes')
```

```js
self.readable = self.writable = false
```

```js
self.socket = socketPool[self.announceUrl] = new Socket(self.announceUrl)
```

These all seem fine to me, so thinking we should skip this rule. Thoughts?

**Comment by timoxley** [comment]
I don't see many negatives of allowing multiple assignments on one line. I use it often like in @feross's example above. I think it's good for condensing low value noise onto a single line.

**Comment by timoxley** [comment]
For similar reasons I often lament standard including the "no return assignment" rule, but I do appreciate the danger of accidentally returning an assignment when you meant a conditional. Not sure this pattern suffers from that risk as much. Vote skip.

**Comment by dcousens** [comment]
For me,  this is purely a readability issue, and the only class of bugs it could relate to is:
``` js
var x = 1
var y = x = 2
```

instead of `x + 2`.
I don't think I can recall a time that has happened to me though.

**Comment by feross** [comment]
Agree, it's mainly a readability issue and not a potential source of bugs. And it prevents valid code that we don't want to rewrite, like multiple exports on one line.
