### ISSUE TITLE
Escape mustaches symbols

### ISSUE THREAD

**Issue by liquid36** [feross/standard#779]
I'm wondering if there is a way to escape double mustaches symbols ({{ }}'). I'm developing a vue-cli template and I want to format the files to the standard. 

```
import Vue from 'vue'{{#if_eq lintConfig "airbnb"}};{{/if_eq}}
{{#vuex}}
import store from '../store'{{#if_eq lintConfig "airbnb"}};{{/if_eq}}
{{/vuex}}

const API_URL = process.env.API_URL{{#if_eq lintConfig "airbnb"}};{{/if_eq}}
```

Thanks!

**Comment by feross** [comment]
Are you linting that file *with* the `{{` symbols included? That won't work. I assume you want to lint it after the template is applied, right?

**Comment by liquid36** [comment]
I'm writing a templete, so i am not liting that file but i want to format it in order to the resulting file follow the standar and could be liting.

**Comment by feross** [comment]
Sorry, I don't understand your question. If you're linting the output, *after* the template has been processed, then you shouldn't have any `{{` left in the file. So, what is your question?
