### ISSUE TITLE
Vim installation not working

### ISSUE THREAD

**Issue by matthewepler** [feross/standard#781]
Syntastic has been installed and is confirmed to be working by running `:SyntasticInfo` from inside Vim. That produces this:

```
Syntastic version: 3.6.0
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
Press ENTER or type command to continue
```

Inside my .vimrc file, I have the following:

```
let g:syntastic_javascript_checkers=['standard']
```

And when I run a standard command, `standard ./test.js`, I get good output:
```
standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/matthewepler/test.js:2:24: Parsing error: Unterminated string constant
```

So if all the individual parts are working, why isn't `standard` showing up as the checker for Syntastic? 

Forgive me if this is a Syntastic error, but because it seems to give good output with the `:SyntasticInfo` I assume the error is elsewhere.

**Comment by feross** [comment]
Maybe Syntastic can't show errors if there is a serious error like a parse error? Can you try a simple error like a semicolon:

```js
console.log('hi');
```

📢  Any Syntastic users able to lend a hand here?

**Comment by matthewepler** [comment]
Cleared my .vimrc of a bunch of garbage and all was fine. My bad. will close immediately and proceed to shame myself.

**Comment by feross** [comment]
@matthewepler Glad you got it figured out. No shame needed.
