### ISSUE TITLE
why Use single quotes for strings & Extra semicolon ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [feross/standard#788]
# After you did this, the codes looks very ugly & not conform with the ECMAScript standard & JSON standard！

**Comment by ltngames** [comment]
Then don't use it, totally an optional thing, no one is going to force you to use it.

**Comment by xgqfrms-GitHub** [comment]
# ofcourse!

**Comment by LinusU** [comment]
> not conform with the ECMAScript standard

What do you mean with this? The code style that we are providing is 100% in line with the ECMAScript standard as far as I can understand...

**Comment by xgqfrms-GitHub** [comment]
# JSON recommanded to using double quotes!

https://jsonformatter.curiousconcept.com/

```
{
    "key1":"value1",
    "key2":"value2",
    "key3":"value3"
}
``` 
![json-valid double quotes](https://cloud.githubusercontent.com/assets/18028768/23103950/fecc0db2-f6fe-11e6-9f2a-5f2815b06624.png)

```
{
     'key1': "value1",
    "key2": "value2",
    "key3": "value3"
}

{
    "key1": 'value1',
    "key2": "value2",
    "key3": "value3"
}

{
      key1: 'value1',
    "key2": "value2",
    "key3": "value3"
}
``` 
## RFC 4627
![json-invalid single quotes](https://cloud.githubusercontent.com/assets/18028768/23103955/0e29efae-f6ff-11e6-85b7-412af4a8aa27.png)
![json-invalid single quotes 2](https://cloud.githubusercontent.com/assets/18028768/23103956/0e2e445a-f6ff-11e6-8b4f-7f41f9243d52.png)
![json-invalid single quotes 3](https://cloud.githubusercontent.com/assets/18028768/23103957/0e348cfc-f6ff-11e6-8a26-70066ebe9cc1.png)

https://www.ietf.org/rfc/rfc4627.txt  
https://tools.ietf.org/html/rfc4627
```
2.5.  Strings

   The representation of strings is similar to conventions used in the C
   family of programming languages.  A string begins and ends with
   quotation marks.  All Unicode characters may be placed within the
   quotation marks except for the characters that must be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).

   Any character may be escaped.  If the character is in the Basic
   Multilingual Plane (U+0000 through U+FFFF), then it may be
   represented as a six-character sequence: a reverse solidus, followed
   by the lowercase letter u, followed by four hexadecimal digits that
   encode the character's code point.  The hexadecimal letters A though
   F can be upper or lowercase.  So, for example, a string containing
   only a single reverse solidus character may be represented as
   "\u005C".

   Alternatively, there are two-character sequence escape
   representations of some popular characters.  So, for example, a
   string containing only a single reverse solidus character may be
   represented more compactly as "\\".

   To escape an extended character that is not in the Basic Multilingual
   Plane, the character is represented as a twelve-character sequence,
   encoding the UTF-16 surrogate pair.  So, for example, a string
   containing only the G clef character (U+1D11E) may be represented as
   "\uD834\uDD1E".
```

![rfc-4627](https://cloud.githubusercontent.com/assets/18028768/23104030/b70c68b2-f700-11e6-89b7-2799a2ef20c7.png)

## ECMA-404
![json-invalid ecma-404](https://cloud.githubusercontent.com/assets/18028768/23103954/0e29e72a-f6ff-11e6-95a6-3c63341564a3.png)
> ECMA-404 The JSON Data Interchange Standard.
![ecma-404 double quotes](https://cloud.githubusercontent.com/assets/18028768/23103991/df75768c-f6ff-11e6-807c-6f87486aead8.png)

http://www.json.org/  
https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

**Comment by ltngames** [comment]
That is JSON not JavaScript which has nothing to do with this Standard. This is a Javascript standard not a JSON standard.

**Comment by LinusU** [comment]
As previous comment said, you are talking about JSON, not JavaScript...

I don't think that many people at all are always quoting their keys when they write javascript, and anyhow, we would be able to change that at this point...

Closing since I don't think that we need to change anything...
