### ISSUE TITLE
No correct way to create an empty Array.

### ISSUE THREAD

**Issue by lukasoppermann** [feross/standard#789]
Hey, so I have the following issue:

```javascript
[].slice.call(this.querySelectorAll(…
```

Gives me an error:

> /Users/lukasoppermann/Code/page-sections/src/page-section-container.js
>   67:10  error  Parsing error: Unexpected token ]

However, if I change it to:

```javascript
Array().slice.call(this.querySelectorAll(…
```

It works, but I get this error:

> /Users/lukasoppermann/Code/page-sections/src/page-section-container.js
>   67:9  error  The array literal notation [] is preferrable

I feel like one notation should be allowed.

**Comment by lukasoppermann** [comment]
Okay, so for my case `Array.prototype.slice` works, however, I am leaving the issue open, so you can consider if it is still valid. If not, feel free to close it.

**Comment by LinusU** [comment]
How about `Array.from(this.querySelectorAll(…))`?

**Comment by lukasoppermann** [comment]
Hey @LinusU,
I had looked at `Array.from` already, its pretty neat, but lacks the required browser support. 😞 

Your other suggestions works well. I will however stick top `Array.prototype.slice` as I find it more understandable. 

Maybe it would be a nice idea to mention the `;[]` trick in the docs? Or did I miss it?

**Comment by LinusU** [comment]
![screen shot 2017-02-20 at 11 07 46 am](https://cloud.githubusercontent.com/assets/189580/23120496/d6ed0c48-f75c-11e6-8137-3132f64fdc05.png)

It's in the documentation :)

Sticking to `Array.prototype.slice` sounds sane 👍

**Comment by lukasoppermann** [comment]
@LinusU okay, I did not read this as "start with a semicolon" 😉. But thanks anyway.

**Comment by LinusU** [comment]
Hehe, yeah that was actually why I didn't close it, maybe this could benefit from some clarification... On the other hand, it's not something that is that common...

**Comment by lukasoppermann** [comment]
@LinusU I think using `[]` for wrapping nodeLists into arrays is still quite common, especially when you are in the browser, where `.from` is not an option due to compatibility.
