### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by goatslacker** [feross/standard#79]
FYI if you're on ES6 then you can't start lines with the template literal syntax either, so that needs to be preceded by a semicolon.

```js
// bad
`hello${world}`

// good
;`hello${world}`
```

This is because if an identifier precedes the statement then the parser will parse it as a tagged template.

```js
foo

`trololol`
```

is the same as 

```js
foo`trololol`
```

**Comment by maxogden** [comment]
Thanks for the feedback.

We no longer recommend starting lines with semicolons. It's hacky. Start lines with `void`, `var`, `const` or something that makes more sense. Starting lines with e.g. `(`, `[`, or ``` is always avoidable. See also https://github.com/feross/standard/issues/78#issuecomment-85625863

**Comment by goatslacker** [comment]
This issue still applies to this section in particular:

![screen shot 2015-03-24 at 1 03 45 pm](https://cloud.githubusercontent.com/assets/10632/6811604/402087fc-d226-11e4-85fd-3f6187c3663d.png)

If you're using ES6 then templates are a gotcha too.

**Comment by dcousens** [comment]
@goatslacker could you submit a test to clearly outline this?

**Comment by mattdesl** [comment]
I can't imagine a scenario where a line starts with a template string, or any of these other gotchas:

```js
+ * / - ` , . 
``` 

But the readme and standard should discourage these explicitly from the start of the line. `[` and `(` I'm not so sure about, but I'll open another issue.

**Comment by goatslacker** [comment]
I don't mean to talk about scenarios where you would start a line with any particular character. I think starting lines with any character that fails ASI is poor style anyway.

I'm just pointing [this](http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=var%20foo%20%3D%201%0A%0Avar%20x%20%3D%201%20%3D%3D%3D%20foo%0A%0A%60bar%60%20%2F%2F%20oops) out.
