### ISSUE TITLE
Force using parens around single argument on arrow functions?

### ISSUE THREAD

**Issue by tunnckoCore** [feross/standard#790]
I kinda like it more. It says more that this thing is a function.

force using 

```js
const foo = (abc) => 123
```

instead of

```js
const foo = abc => 123
```

Currently, both styles are allowed. The reason I want that is, because it seems that ESLint fix does not remove them if you set them, but `prettier` seems to respect the second style more.

I'm kinda trying to start using Atom. And I have maybe kinda strange config:

- Atom Linter
- Atom Linter-ESLint
- standard as devDependency
- npm lint script that use that standard cli (mainly for contributors that dont have such editor config)
  * mainly for contributors that dont have such editor config, because that config flow just does not allow me to push wrong code at repo, hehe
- eslingConfig field in package.json that has `extends: standard` to allow LinterESLint to do autofix
  * yea it may looks kinda strange that you have standard cli and also have eslintConfig field
  * another cool benefit from that is that contributors can use their global eslint cli if they want
- Atom Prettier-ESLint plugin - that respects that eslintConfig and formats the code with it.

I kinda think that it is okey to do that change since v9 is upcoming. Not sure for the impact on the community, but please @feross at least try the tests to see the results - i'm curious :) Or maybe it can land for v10.

**Comment by timoxley** [comment]
Previous related discussion: #414, #309

**Comment by tunnckoCore** [comment]
Thanks.

Hm. It seems it was landed, but later remove? Because I can't see it in the config currently?

**Comment by dcousens** [comment]
NACK

**Comment by feross** [comment]
Closing this, as this was previously decided in #414. I don't think there's a compelling reason to revisit this discussion at this time.
