### ISSUE TITLE
Proposal: Disallow await in loops

### ISSUE THREAD

**Issue by tunnckoCore** [feross/standard#793]
Digging more and more in ESLint rules, i found some good ones which enforces good style and more readable code. This issue is for [no-await-in-loop](http://eslint.org/docs/rules/no-await-in-loop) rule - **not fixable**.

Suggested configuration.

```json
{
  "no-await-in-loop": "error"
}
```

I believe it is good practice to not do that and ban such things, since each loop iteration is delayed until the entire asynchronous operation completes.

**Comment by jprichardson** [comment]
👎  there are good reasons to use an `await` in a for-loop. For example, let's assume you want to make a number of rate-limited HTTP requests. A for-loop using `await` makes for a very clean way to do this.

**Comment by tunnckoCore** [comment]
Maybe. I believe we should run tests, to see ecosystem impact and if it is not so big everyone can add disable comment.

**Comment by feross** [comment]
Duplicate: https://github.com/feross/standard/issues/737 Please use search before creating new issues.
