### ISSUE TITLE
Proposal: No deep nested hell - max-depth and max-nested-callbacks

### ISSUE THREAD

**Issue by tunnckoCore** [feross/standard#794]
Digging more and more in ESLint rules, i found some good ones which enforces good style and more readable code. This issue is for [max-depth](http://eslint.org/docs/rules/max-depth) and [max-nested-callbacks](http://eslint.org/docs/rules/max-nested-callbacks) rules - **both not fixable**.

Suggested configuration.

```json
{
  "max-nested-callbacks": ["error", { "max": 3 }],
  "max-depth": ["error", { "max": 3 }]
}
```

The `max` option, may be more sensible like `5` for example. But i believe it should not be more. I kinda feel it is too restrictive if it is 3 or 4, because with combination of arrow functions you can easily get 3-4 depths nesting. But separation is good thing.

**Comment by feross** [comment]
I think this rule is too restrictive. In test code, I often deeply nest callbacks because it's easier and tests are easier to write when they're verbose and repetitive.

**Comment by tunnckoCore** [comment]
> In test code, I often deeply nest callbacks because it's easier and tests are easier to write when they're verbose and repetitive.

I'm agree with that and also has such cases, but that's why i suggested 5, because it is completely enough in that cases.
