### ISSUE TITLE
Proposal: Not too much semicolons

### ISSUE THREAD

**Issue by tunnckoCore** [feross/standard#797]
Digging more and more in ESLint rules, i found some good ones which enforces good style and more readable code. This issue is for [no-extra-semi](http://eslint.org/docs/rules/no-extra-semi) rule - **fixable**.

Suggested configuration.

```json
{
  "no-extra-semi": "error"
}
```

Why we will need such thing, when we are okey to completely don't use semicolons, except in some places, where we just need one semicolon, no more.

Loops like that, **won't be** affected by this rule

```js
let i = 0
for (;;i++) {
  console.log(i)
}
```

but just these

```js
let i = 0;;;

for (;;i++) {
  console.log(i);;;
}
```

**Comment by feross** [comment]
Duplicate: https://github.com/feross/standard/issues/786 Please use search before creating new issues.

**Comment by tunnckoCore** [comment]
Damn sorry! I seen that issue and read it, before i gone to sleep last night :scream: Sleep is a bad thing! :rocket:

**Comment by feross** [comment]
No worries!
