### ISSUE TITLE
Proposal: one statement per line

### ISSUE THREAD

**Issue by tunnckoCore** [feross/standard#798]
Digging more and more in ESLint rules, i found some good ones which enforces good style and more readable code. This issue is for [max-statements-per-line](http://eslint.org/docs/rules/max-statements-per-line) rule - **not fixable**.

Suggested configuration.

```json
{
  "max-statements-per-line": ["error", { "max": 1 }]
}
```

**Invalid**

```js
var bar; var baz

if (condition) bar = 1; if (condition) baz = 2

for (var i = 0; i < length; ++i) { bar = 1 }

switch (discriminant) { default: break }

function foo () { var bar = 1 }
```

**Valid**

```js
var bar, baz

if (condition) bar = 1

for (var i = 0; i < length; ++i);

switch (discriminant) { default: }

function foo () { }
```

Semicolon in `for` is required, since it will be autofixed by other rule to

```js
for (var i = 0; i < length; ++i) { switch (discriminant) { default: } }
```

**Comment by dcousens** [comment]
ACK

**Comment by tunnckoCore** [comment]
Yea it is, that's good example too.

**Comment by timoxley** [comment]
I think this is decent. Interested in ecosystem impact.

**Comment by jhabdas** [comment]
FWIW, in CoffeeScript, I write my early terminations like <code>unless bar; return</code>. IMHO the more "rules" we pile into Standard the less portable it becomes. And for those who will raise the arguments against CoffeeScript, please note it's the primary authoring language of Framerjs and a great way to get designers writing code.

**Comment by feross** [comment]
This rule would disrupt the way that too many people write code and it doesn't prevent bugs or improve code consistency enough to justify the cost to users, in my opinion.

Here are the results of the test suite: 24% breakage.

```
# tests 238
# pass  182
# fail  56
```

**Comment by dcousens** [comment]
@feross what were some of those failures? OOI

**Comment by yoshuawuyts** [comment]
I'm assuming for-loops would be a big part of this

**Comment by feross** [comment]
I can't remember... From memory, things like:

```js
if (condition) { foo() } else { bar() }
```

And for loops too.
