### ISSUE TITLE
Proposal: New line per chained call

### ISSUE THREAD

**Issue by tunnckoCore** [feross/standard#799]
Digging more and more in ESLint rules, i found some good ones which enforces good style and more readable code. This issue is for [newline-per-chained-call](http://eslint.org/docs/rules/newline-per-chained-call) rule - **not fixable**.

Suggested configuration.

```json
{
  "newline-per-chained-call": "error"
}
```

In the rule page is shown great example of `diff` and why it is more readable and clean. It reminds me to one other rule, but can't remember what it was. I also seen discussion in some issues here about that is's better.

**Invalid**

```js
d3.select("body").selectAll("p").style("color", "blue")
```

**Valid**

```js
d3
  .select("body")
  .selectAll("p")
  .style("color", "blue")
```

Very good for git diffs.

**Comment by feross** [comment]
Duplicate: https://github.com/feross/standard/issues/720
