### ISSUE TITLE
allow blank lines at the end of a file

### ISSUE THREAD

**Issue by joshhartigan** [feross/standard#8]
this is a fairly common practice. some reasoning can be seen here: http://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-file
  here's 'proof' it is counted as an error:
  ![](http://i.imgur.com/5ZMh0aH.png?1)

**Comment by jprichardson** [comment]
Agree with this one. It's my understanding that a lot of UNIX utilities require the extra LF at the end of a file to determine if it's a text file or not.

**Comment by feross** [comment]
100% agree with you guys about always terminating a file with an LF.

However, in the example @joshhartigan posted, x.js actually has *two* line breaks at the end of the file. Multiple consecutive line breaks are disallowed. I don't feel strongly about this rule, but I do think that:

```js
function one (x) {
  return x
}

function two (x) {
  return x * 2
}
```

is better than:

```js
function one (x) {
  return x
}


function two (x) {
  return x * 2
}
```

**Comment by dcousens** [comment]
Agreed with @feross.

As mentioned, the example given has 2 line breaks.

**Comment by mafintosh** [comment]
Agreed. Current behavior seems fine.

**Comment by feross** [comment]
Cool, I'm going to close this issue.
