### ISSUE TITLE
Allow _ to be an unused variable

### ISSUE THREAD

**Issue by feross** [feross/standard#800]
In React, it's common to do:

```js
const { width, height, ...restProps } = props
return <div ...restProps>
```

This assigns all the properties of `props` except `width` and `height` to the `<div>`.

Currently `standard` warns about `width` and `height` being unused. Would be nice if we could assign these variables to `_` and `_2` to mark them as unused (since we can't assign them both to `_` in one assignment).

```js
const { width: _, height: _2, ...restProps } = props
return <div ...restProps>
```

@dcousens Didn't you say that you have a rule modification that you use for this purpose? Can you share it?

**Comment by dcousens** [comment]
https://github.com/feross/standard/issues/419#issuecomment-270816644

``` json
"no-unused-vars": [2, { "vars": "all", "args": "all", "argsIgnorePattern": "^_$" }],
```

Is what I am using.

**Comment by dcousens** [comment]
@feross this already exists!

``` json
"ignoreRestSiblings": true
```

``` js
/*eslint no-unused-vars: ["error", { "ignoreRestSiblings": true }]*/
// 'type' is ignored because it has a rest property sibling.
var { type, ...coords } = data;
```

**Comment by feross** [comment]
@dcousens Oh, nice. Let's use `ignoreRestSiblings` then!

**Comment by feross** [comment]
No ecosystem impact. This will be included in the standard v10 beta.

**Comment by tdd** [comment]
ZOMG this is SO going to make my day 😄  — the inability to rest on objects has been bugging me for a while.
