### ISSUE TITLE
0.9.0 is breaking chai.js

### ISSUE THREAD

**Issue by Jimexist** [feross/standard#803]
It reports that statement like this is unused statement (it is, but it's fine in chai):
```js
expect(something).to.be.empty
```

**Comment by Jimexist** [comment]
See http://chaijs.com/api/bdd/#method_empty

**Comment by dcousens** [comment]
See https://github.com/feross/standard/issues/690#issuecomment-262680509,  with the expectation further discussion can go there too :+1:

**Comment by feross** [comment]
@Jimexist Specifically, here is the comment that explains what you can do to fix the issue: https://github.com/feross/standard/issues/690#issuecomment-278533482
