### ISSUE TITLE
Add readme & rules in traditional chinese

### ISSUE THREAD

**Issue by Asoul** [feross/standard#804]
Hi,

I've beed used this for a long time, and want to share with my friends in Taiwan. So I want to add an Traditional Chinese version (zh-TW).
This may take me a few days to translate.

Thanks!

**Comment by feross** [comment]
@Asoul Awesome, happy to accept your translation when it's ready!

**Comment by Asoul** [comment]
@feross, I've finished the translations, thanks!

**Comment by feross** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉
