### ISSUE TITLE
What is the effect of making `lintText` synchronous?

### ISSUE THREAD

**Issue by feross** [feross/standard#807]
In `standard-engine` 6.0.0, the `standard.lintText` method was changed to be sync instead of async.

From the [changelog](https://github.com/Flet/standard-engine/blob/master/CHANGELOG.md#600---2017-02-20):

> BREAKING: make lintText into a sync method
>
> Before: `standard.lintText(text, [opts], callback)`
> After: `results = standard.lintText(text, [opts])`
>
> If an error occurs, an exception is thrown. Otherwise, a results object is returned.

How will this change effect the various editor plugins? I don't want the editor plugins to have to detect the version of `standard` in use in order to call the method correctly.

Let's find out what the effect of this is, and if it's an annoying change, we can either revert, or make the method work the same as before if a callback is passed in.

**Comment by tunnckoCore** [comment]
> or make the method work the same as before if a callback is passed in.

that's the right move for me, because in any way it is totally sync process. Cost nothing to support both style APIs here, since standard is higher level api on top of ESLint and StandardEngine.

Won't be good to revert it in standard-engine. Support both - I call such APIs "hybrids".

**Comment by feross** [comment]
Rather than make the `lintText` behavior change depending on whether a callback is passed or not, I opted to add a `lintTextSync` method and restore the old `lintText` method. See: https://github.com/Flet/standard-engine/pull/159

`standard` will upgrade directly from 5.x to 7.x, so the `lintText` method will not change at all. This means that editor plugins will not be affected by this upgrade.
