### ISSUE TITLE
Proposal: Disallow needless `else` statements

### ISSUE THREAD

**Issue by tunnckoCore** [feross/standard#810]
Enforces more clean code. For years I have very rare cases when I need `else` or even `else if` statements.

Fixable, [no-else-return](http://eslint.org/docs/rules/no-else-return)

**Comment by feross** [comment]
This seems overly prescriptive to me.

**Comment by feross** [comment]
@tunnckoCore Thanks for the proposal. This rule would disrupt the way that too many people write code and it doesn't prevent bugs or improve code consistency enough to justify the cost to users, in my opinion.

Here are the results of the test suite:

```
# tests 238
# pass  213
# fail  25
```

10.5% breakage is too high to really even consider a change like this.

**Comment by tunnckoCore** [comment]
> 10.5% breakage is too high to really even consider a change like this.

Daaamn :D Okey, no problem. We only can hope these numbers to get low in time.
