### ISSUE TITLE
no unused expression

### ISSUE THREAD

**Issue by fibo** [feross/standard#814]
I have a test like this

```js
describe('emptyGraph', function () {
  it('is a valid graph', function () {
    validate(emptyGraph).should.be.ok
  })
})
```

and now standard v9 complains with

> Expected an assignment or function call and instead saw an expression

Why it is considered a warning? I don't get it. How it could be rewritten?

**Comment by dcousens** [comment]
Duplicate of https://github.com/feross/standard/issues/803

> @Jimexist Specifically, here is the comment that explains what you can do to fix the issue: https://github.com/feross/standard/issues/690#issuecomment-278533482

**Comment by fibo** [comment]
Thank you for the asnwer, it was solved using

     validate(emptyGraph).should.be.True()
