### ISSUE TITLE
Avoid reassign parameters

### ISSUE THREAD

**Issue by foisonocean** [feross/standard#818]
I think it's very useful: http://eslint.org/docs/rules/no-param-reassign.html

**Comment by dcousens** [comment]
Ecosystem breakage isn't going to be pleasant.
And honestly,  you could just as easily encourage people **not** to use the `arguments` object except in limited circumstances.

**Comment by yoshuawuyts** [comment]
Huge no no on this one, this would make using standard impossible for me.
Default params using `foo = foo || {}` is staple. Also using arguments is a
common thing to do

**Comment by feross** [comment]
@yoshuawuyts is right that `foo = foo || {}` is extremely common. Or even:

```js
function foo (opts) {
  opts = Object.assign({
    default1: true,
    default2: 'cool string'
  }, opts)
}
```

Also, using `arguments` isn't really a good idea when we have `...args` now:

```js
function foo (...args) {
}
```

I'd prefer to pass on this rule, even though I agree at a high-level that it probably desirable. It's just not practical in the real-world.

**Comment by dcousens** [comment]
@feross I think if you could avoid `arguments` usage,  generally,  that would be good.
Its only useful in an `.apply` context no?

**Comment by yoshuawuyts** [comment]
@dcousens yeah I think so, although it's very common - just in the last week I've written 2 new modules built entirely around this. In the example below there's no escaping using `arguments`:

```js
// written just for show, idk there might be bugs but yeah.
Emitter.prototype.emit = function (eventName) {
  var event = null
  var args = []
  for (var i = arguments.length - 1; i >= 1; --i) args[i] = arguments[i]
  var events = this._events[eventName]
  if (!events) return
  for (var j = events.length - 1; i >= 0; --i) {
    event = events[j]
    event.apply(event, args)
  }
}
```

> Also, using `arguments` isn't really a good idea when we have `...args` now

Like with most things there's probably fancy ways to write this using new language additions, but I'd rather we allow people (like me :sparkles:) to use `standard` without forcing them to tail new specs. I mean: [rest params doesn't even have widespread support yet](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/rest_parameters).

**Comment by dcousens** [comment]
@yoshuawuyts why not `args = [].slice.call(arguments, 1)`

**Comment by feross** [comment]
> Like with most things there's probably fancy ways to write this using new language additions, but I'd rather we allow people (like me ✨) to use standard without forcing them to tail new specs

Sure thing. Wasn't trying to enforce that on folks. I was just saying that I'm not too worried about `arguments` implicitly getting modified when we have rest params as a great up-and-coming alternative.

Also, most functions that use `arguments` don't use named arguments. It's usually either-or.

**Comment by feross** [comment]
One last thing: rest params have more support than you think! Check it out!

<img width="1170" alt="screen shot 2017-03-13 at 1 08 26 pm" src="https://cloud.githubusercontent.com/assets/121766/23873122/2c5dd008-07ee-11e7-9f6e-942ccc3f432f.png">

We're rapidly approaching a world where you can use the new fanciness and forgo preprocessor complexity like babel. Can't wait.

**Comment by dcousens** [comment]
> Also, most functions that use arguments don't use named arguments. It's usually either-or.

Maybe that is something we could look into?
