### ISSUE TITLE
Allow, or ignore, @ decorators

### ISSUE THREAD

**Issue by owenayres** [feross/standard#819]
I have JS Standard running nicely on my project, with one annoying issue. My project is running in React and Webpack, with Babel, so I'm using shiny features such as decorators with frameworks like MobX (the framework I use to manage state).

The problem here is that JS Standard doesn't like, or shall we say recognise, what these decorators are. It will throw an error like: -

`src/components/Avatar/Avatar.js:6:1: Parsing error: Unexpected character '@'`

My React component might look something like this, as a really simple example: -

```
@CSSModules(styles, { allowMultiple: true })
class Avatar extends Component {
  render() {
    const { whatever } = this.props
    return <MyHtmlStuff whatever={whatever} styleName='example' />
  }
}

export default Avatar
```

It doesn't get the @CSSModules declaration in the above example. Is there something we can do to easily support this in a future release?

Cheers,
Owen

**Comment by timoxley** [comment]
@owenayres does this solve your problem? https://github.com/feross/standard#how-do-i-use-experimental-javascript-es-next-features

**Comment by owenayres** [comment]
@timoxley Yep, that fixed my issue. Thanks for linking me up, feel stupid for missing this...!

**Comment by progtarek** [comment]
HI @owenayres , @timoxley 
I am working on angular 5 application, I have a similar problem with decorator
```
import { Injectable } from '@angular/core'
@Injectable()
export class WindowService {
}
```
 'Injectable' is defined but never used.
