### ISSUE TITLE
How to run standard in JetBrains IDEs (intellij, webstorm)

### ISSUE THREAD

**Issue by rtorr** [feross/standard#82]
![screenshot 2015-03-24 19 18 23](https://cloud.githubusercontent.com/assets/297045/6817175/a6f43684-d25a-11e4-87ef-243cbf729e5b.png)

This might be better long term as a plug-in, but this could also be useful to those of us running Intellij.

**Comment by rtorr** [comment]
might add better documentation for this later
![screenshot 2015-03-24 19 23 12](https://cloud.githubusercontent.com/assets/297045/6817240/5f8dcdcc-d25b-11e4-9b54-a254a5d6944f.png)
![screenshot 2015-03-24 19 23 20](https://cloud.githubusercontent.com/assets/297045/6817239/5f8d93a2-d25b-11e4-8929-ac0b4848a437.png)
![screenshot 2015-03-24 19 23 31](https://cloud.githubusercontent.com/assets/297045/6817241/5f8eb958-d25b-11e4-9156-cd7989e995f9.png)

**Comment by maxogden** [comment]
@rtorr sorry, is this is a question or a statement?

**Comment by rtorr** [comment]
@maxogden It was a statement, and was planning on jotting notes for a pull request or some documentation. I will close this for now.
