### ISSUE TITLE
Lock down eslint plugin versions

### ISSUE THREAD

**Issue by feross** [feross/standard#825]
The latest v10 beta just started giving false positives related to JSX indentation. This is caused by a bug introduced in a patch version of `eslint-plugin-react` which we use to enforce JSX indentation.

Details here: https://github.com/yannickcr/eslint-plugin-react/issues/1117

Not a big deal since this is still a beta version, but let's lock down the plugin versions before the final v10 is released. Let's use exact versions instead of loose with `~`. I thought patch versions would be safe, but alas...

**Comment by yannickcr** [comment]
`v6.10.3` is now published and should fix the issue. Sorry for the inconvenience.

**Comment by feross** [comment]
@yannickcr No problem. Thanks for maintaining an excellent plugin!

I'm happy to close this, and revisit if it's actually an issue in the future. No harm done.
