### ISSUE TITLE
Add --watch option.

### ISSUE THREAD

**Issue by ravshansbox** [feross/standard#828]

**Comment by feross** [comment]
Without additional information, it's unclear what this is even asking for.

**Comment by ravshansbox** [comment]
It would be useful is we had a --watch option that prevents process from quitting and in case of change relinting changed files only.

**Comment by enjoylife** [comment]
Anyone come across plugins or forks which have a watch or continuous mode?

**Comment by yuvilio** [comment]
I've gotten it to work by having separate watch tools. In my case it was for my npm scripts setup with the nodemon powered  [npm-watch](https://github.com/M-Zuber/npm-watch) . 

```json
  "watch": {
    "standardlint": "assets/js/main.js"
  },
  "scripts": {
    "watch": "npm-watch",
    "standardlint" : "standard assets/js/main.js",
}
```

Then just run the watch task and to carry out the monitoring and running of the `standard`` lnter
```bash 
$ npm run watch
```

For more direct command line usage, you can probably use [nodemon](https://github.com/remy/nodemon#monitoring-multiple-directories) directly with something like  `nodemon --watch assets/js/main.js --exec "standard assets/js/main.js"`

I agree that a `--watch` flag would be a nice convenience addition. It's got plenty of conventional examples in similar tools (similar to eslint-watch postcss-watch, ...). It can also be handy in npm scripts,  for watch tasks to just pass `npm run lint:js -- --watch` to one time run tasks.

**Comment by ravshansbox** [comment]
Will it lint only changed files or all?

**Comment by axelpale** [comment]
+1

**Comment by mxdi9i7** [comment]
the no-unused-vars rule in standard js is going to be annoying during development when u have watch on, i think it makes more sense to run linting during pre-commit instead of during active development
