### ISSUE TITLE
Ban ES2018?

### ISSUE THREAD

**Issue by tunnckoCore** [feross/standard#831]
@feross what's your state about #ES2018? 

ref: https://youtu.be/s-G_RZ4RJLU, I think it is total crap and looks very bad. The only thing that I like is native Flow/TypeScript support.

Sorry, but that 

![2017-04-01-10 44 51_259x138_scrot](https://cloud.githubusercontent.com/assets/5038030/24576652/75ad1046-16c8-11e7-98c0-2cc7a3747665.png)

is worst thing ever seen.

**Comment by Guria** [comment]
@tunnckoCore close the browser and don't read/watch anything from the Internet at least 2days. :)

**Comment by tunnckoCore** [comment]
Haha, why? Is that more "readable" and user-friendly code? Everything is replaced with dots and this mess with your mind totally, at least from the psychological side of look - what is object, what is array, what is argument, what is native and what is from your codebase.

at least partial ban, for shortcuts for example

**Comment by yoshuawuyts** [comment]
You do realize this is an April's fools joke right?

**Comment by tunnckoCore** [comment]
haha, damn, didn't thought for that. i even didnt realize it is 1st april, haha
