### ISSUE TITLE
did not able to upgrade opencat 2.0.3.1 to latest version

### ISSUE THREAD

**Issue by smnayeem** [feross/standard#832]
i had tried to up-gradation 2.0.3.1 to 2.3 in several times, every times upgraded success but after next step when click the 'Continue' button then next step going to the main page as 'HTTP ERROR 500' 
What is the solution? please explain as easy, because i am not expert user.
![screenshot_2](https://cloud.githubusercontent.com/assets/26857833/24590537/919171dc-1810-11e7-89e7-18a296d854f9.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/26857833/24590538/9198ca2c-1810-11e7-97aa-d4c7d0b5c8d3.png)

**Comment by feross** [comment]
This issue has nothing to do with `standard`. I think you're looking for this issue tracker: https://github.com/opencart/opencart
