### ISSUE TITLE
strings and template string expressions

### ISSUE THREAD

**Issue by robertkowalski** [feross/standard#841]
hey folks,

standard 10.0.1 thinks that a string with a `${}` is a template literal and it feels like a bug to me:

this code:

```js
      const config = [
        '# Switch to false to enhance the performance of the javascript generation and similar',
        'magnolia.develop=false',
        'magnolia.resources.dir=${magnolia.home}/logs'
      ].join('\n')
```
(note the `${magnolia.home}/logs'`)

gets an error with:

 ```
  /Users/robert/magnolia/npm-cli/test/editMagnoliaPropertiesTest.js:20:9: 
Unexpected template string expression.
```

**Comment by feross** [comment]
This is an intentional rule – it's designed to catch accidental usage of `'` when `` ` `` was intended. If your usage is intentional, then you can simply disable the rule as [described in the readme](https://standardjs.com/#how-do-i-hide-a-certain-warning).
