### ISSUE TITLE
"Export from" Unexpected token

### ISSUE THREAD

**Issue by pinn3** [feross/standard#847]
Using babel [export extensions](https://babeljs.io/docs/plugins/transform-export-extensions/) you get "Parsing error: Unexpected token".

Example:

```js
// components/index.js
export Header from './header.js'
export Footer from './footer.js'

// produces "Parsing error: Unexpected token Header"
```

**Comment by falmar** [comment]
I may be wrong. But I think this is on the ESLint side capabilities to understand the feature

Take a look if this will be a workaround for you. https://github.com/feross/standard/issues/652

**Comment by feross** [comment]
This is a stage 1 proposal and not part of the spec yet. You need to tell standard to use `babel-eslint` as your parser. See https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features
