### ISSUE TITLE
Cannot find module 'babel-eslint' (eslint/undefined) 

### ISSUE THREAD

**Issue by mattdesl** [feross/standard#85]
Using this as a local dependency has the following error:

```
Error: Use JavaScript Standard Style (https://github.com/feross/standard)
  cmd.js:0:0: Cannot find module 'babel-eslint'
```

Installing it globally and running that works. 

Getting the same error in the SublimeLint plugin. 

Versions:
```
standard@3.2.1
└── eslint@0.17.1 
```

**Comment by mattdesl** [comment]
Doing `npm install babel-eslint --save-dev` seems to fix the issue as well.

**Comment by Flet** [comment]
Really strange, I don't believe `babel-eslint` is used anywhere in this repo or any branches.

**Comment by feross** [comment]
Weird. Can you try again with the latest version, 3.3.0?

**Comment by mattdesl** [comment]
works now :+1:

**Comment by baygeldin** [comment]
Hi! I've just faced with this problem and it turned out that `standard` was installed globally and `babel-eslint` was installed into `nvm` internal folder. Be careful when using `nvm` :)

**Comment by sethbergman** [comment]
Try this setting:

![](https://cloud.githubusercontent.com/assets/427137/14826214/b85fabf8-0b91-11e6-9786-8a6ea0d1affe.png)

You don't need to add `babel-eslint` as a dependency. Just check this setting in Atom.

**Comment by otajor** [comment]
Just had the same error.

I had:
- `standard` installed globally but not locally as a dependency in my project
- `babel-eslint` installed locally but not globally

Once I added standard as a local dependency as well, it was fine.

**Comment by chevdor** [comment]
FYI:
Added with `npm i -D babel-eslint` and it still failed.
Installed globally `npm i -g babel-eslint` and it worked.

**Comment by feross** [comment]
Yep, both `standard` and `babel-eslint` need to be installed at the same level, both local or both global.

**Comment by chevdor** [comment]
Even both local does not work.

**Comment by feross** [comment]
@chevdor Please open a new issue with all the details of your situation.
