### ISSUE TITLE
ReactJS Flow stateless component: "Parsing error: Unexpected token :"

### ISSUE THREAD

**Issue by will-stone** [feross/standard#850]
```
const Component = ({ something }: { something:string }) => {
```

Causes `Parsing error: Unexpected token :` on the colon. The latest update adds better support for Flow but looks like it's not quite there. Any chance this could be fixed?

**Comment by feross** [comment]
Are you using `eslint-plugin-flowtype` as recommended in the readme?
 https://standardjs.com/#can-i-use-a-javascript-language-variant-like-flow

**Comment by will-stone** [comment]
I installed the plugin but the error still appears on that colon. I'm using Create React App, an excerpt from my `package.json`:

```
"devDependencies": {
    "eslint-plugin-flowtype": "^2.30.4",
    "react-scripts": "0.9.5",
    "standard": "^10.0.1"
},
"standard": {
    "plugins": [ "flowtype" ]
},
```

Using VSCode and `vscode-standardjs` extension.

Running `./node_modules/standard/bin/cmd.js --plugin flowtype` gives the same error.

**Comment by feross** [comment]
Aha. This is happening because `babel-eslint` is not specified as the parser.

You also need to `npm install babel-eslint --save-dev` and set the "parser" option to "babel-eslint".

```js
"standard": {
    "plugins": [ "flowtype" ],
    "parser": "babel-eslint"
}
```

**Comment by will-stone** [comment]
Thanks. That fixed it.
