### ISSUE TITLE
JSON-formatted output via `-f json`

### ISSUE THREAD

**Issue by rstacruz** [feross/standard#852]
Eslint supports this `-f json` to output JSON-formatted output:

```sh
./node_modules/.bin/eslint '**/*.js*' -f json | jq .

[
  {
    "filePath": "/Users/rsc/Projects/lol/behaviors/role-select.js",
    "messages": [
      {
        "ruleId": "no-multiple-empty-lines",
        "severity": 2,
        "message": "Too many blank lines at the end of file. Max of 0 allowed.",
        "line": 94,
        "column": 1,
        "nodeType": "Program",
        "source": "",
        "endLine": 95,
        "endColumn": 1,
        "fix": {
          "range": [
            2301,
            2302
          ],
          "text": ""
          /* snip */
```

## Motivation

We can use tools that consume Eslint's JSON output, eg, https://github.com/rstacruz/stylelint-disable-all.

**Comment by dcousens** [comment]
To be clear,  @rstacruz is asking about optionally allowing the output of _the warnings_ emitted by `standard` (from `eslint`),  as JSON,  for consumption by other tools.

Not that `standard` could add a JSON formatting feature.

**Comment by rstacruz** [comment]
Happy to help adding this to standard-engine if you welcome it :)

**Comment by feross** [comment]
@rstacruz Have you tried using [`standard-json`](https://www.npmjs.com/package/standard-json)? It's a standalone tool that takes the output from `standard` and converts it to JSON.

```bash
standard --verbose | standard-json
```

**Comment by rstacruz** [comment]
ohh, i suppose thats what I'm looking for. It's not as verbose as eslint's `-f json` flag but it'll do for most cases.
