### ISSUE TITLE
Exclude semicolon is a bad practice or not

### ISSUE THREAD

**Issue by ufocoder** [feross/standard#856]
I use `standard` and I have the following code:
 
```
const a = 'methodA'
const b = 'methodB'

class MyClass {
  [a] = () => (5 * 7)
  [b] = () => (5 * 10)
}
```

Of course, it will be compiled not correct. [Try it online through REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=const%20a%20%3D%20'methodA'%0Aconst%20b%20%3D%20'methodB'%0A%0Aclass%20MyClass%20%7B%0A%20%20%5Ba%5D%20%3D%20()%20%3D%3E%20(5%20*%207)%0A%20%20%5Bb%5D%20%3D%20()%20%3D%3E%20(5%20*%2010)%0A%7D%0A%0Aclass%20MySecondClass%20%7B%0A%20%20methodA%20%3D%20()%20%3D%3E%20(5%20*%207)%0A%20%20methodB%20%3D%20()%20%3D%3E%20(5%20*%2010)%0A%7D)

There's the correct code:
```
const a = 'methodA'
const b = 'methodB'

class MyClass {
  [a] = () => (5 * 7);
  [b] = () => (5 * 10)
}
```

`Standard` allow us not to write semicolons, but sometimes it required. How I should resolve this situation more elegantly?

**Comment by rstacruz** [comment]
> Never start a line with (, [, or `. This is the only gotcha with omitting semicolons, and standard protects you from this potential issue.
> eslint: no-unexpected-multiline

See the [no-unexpected-multiline](http://eslint.org/docs/rules/no-unexpected-multiline) rule for a list of violations it'll catch.

**Comment by rstacruz** [comment]
Usually prefixing the line with `;` or `void` would fix it. In your case, it'll have to be `;`.

```js
// Bad
window.a = 2
(function () {})()

// OK
window.a = 2
;(function () {})()

// Also OK
window.a = 2
void (function () {})()
```

**Comment by feross** [comment]
When omitting semicolons, the only rule to remember is **never start a line with `(`, `[` or `` ` ``**. When you must, you can prefix that line with a semicolon.

```js
const a = 'methodA'
const b = 'methodB'

class MyClass {
  [a] = () => (5 * 7)
  ;[b] = () => (5 * 10)
}
```

It looks a bit silly at first, but you quickly get used to it.
