### ISSUE TITLE
Does it work with Angular 2

### ISSUE THREAD

**Issue by kina4smile** [feross/standard#862]
I have a project on Ionic 2 with Angular 2,  I'm trying to use Standard but I'm getting a lot of errors I can not fix, like white space on declarations or @ sign on @Injectable, or @Input or many others. I've added experimental features, but it didn't help. My packege.json looks like this
```
 {
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "test": "standard \"**/*.ts\" \"**/*.js\"",
    "fix": "standard \"**/*.ts\" \"**/*.js\" --fix"
  },
  "standard": {
    "parser": "babel-eslint",
    "ignore": [
      "/plugins/"
    ]
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "1.0.3",
    "hammerjs": "^2.0.8",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.36",
    "babel-eslint": "^7.2.2",
    "standard": "^10.0.2",
    "typescript": "^2.0.3"
  }
}
```

And here is some of errors I'm getting:
![screenshot_2](https://cloud.githubusercontent.com/assets/7254847/25129708/d1118372-2447-11e7-9b7c-0dd497666cf6.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/7254847/25129709/d51cd020-2447-11e7-9e3d-98bf47f1b19e.png)

**Comment by feross** [comment]
Since you're linting TypeScript files, you need to tell `standard` to use a plugin to convert your TypeScript to normal JavaScript.

You can see instructions for doing this for Flow in the readme: https://standardjs.com/#can-i-use-a-javascript-language-variant-like-flow Just follow those instructions, but instead of installing `eslint-plugin-flowtype`, you should install `eslint-plugin-typescript`.
