### ISSUE TITLE
No named exports found in module

### ISSUE THREAD

**Issue by matthieusieben** [feross/standard#863]
```js
// File a.js
export const A = 'a'

// File b.js
export * from './a.js'

// File c.js
export * from './b.js'
```

```sh
standard c.js
```

Will result in `No named exports found in module './b.js'  import/export`

**Comment by feross** [comment]
In a fresh folder, I cannot reproduce this issue. Is it possible that you're using webpack and this rule is using that configuration?

**Comment by rbecheras** [comment]
@matthieusieben I got the same issue. Could you explain the solution please ?

**Comment by rbecheras** [comment]
Ok I found the solution.

It seems it better to do:

```js
// File c.js
export * from './b.js'
```

**Comment by TriMoon** [comment]
@rbecheras, you DO understand that those two export styles do NOT function the same right?

**Comment by timoxley** [comment]
@TriMoon perhaps explain the difference

**Comment by TriMoon** [comment]
@timoxley [export@mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) does a much better job at that as i should :wink:
