### ISSUE TITLE
Shorthand async function interpreted as beginning of function paren.

### ISSUE THREAD

**Issue by lesander** [feross/standard#865]
Hi!

Not quite sure if the issue I've described below is a 'bug' in the `standard` parser, or if shorthand functions are not supported at all.

Let's have a look at the following code snippet.
```js
const bar = async () => { return true }
const foo = bar

(async () => {
  // do something async directly without creating a named function.
  await foo
})()
```
As you can see, `foo` is set to `bar` and after that, we invoke a directly executed async function. Now let's run `standard` on the snippet.

```
$ standard test.js
test.js:2:13: Unexpected space between function name and paren.
test.js:4:1: Unexpected newline between function and ( of function call.
```
We see that `standard` interprets the shorthand function and assignment of `foo = bar` as an invalid formatted function.

After running `standard --fix`, the shorthand function is pasted directly after the assignment of `foo`.
```js
const bar = async () => { return true }
const foo = bar(async () => {
  // do something async directly without creating a named function.
  await foo
})()
```  

My question is; is this wanted behaviour?

**Comment by LinusU** [comment]
The code that you get after running `standard --fix` is the same as will be run before. I think that you want to write:

```js
const bar = async () => { return true }
const foo = bar

;(async () => {
  // do something async directly without creating a named function.
  await foo
})()
```

**Comment by lesander** [comment]
Thanks @LinusU, I noticed that I was missing a semicolon in my shorthand function.

Is it possible for StandardJS to recognise and correctly fix this mistake?

**Comment by LinusU** [comment]
I think it's quite hard since the code you originally wrote still is valid javascript, and it would be weird if `standard --fix` impacted the output of the script...

**Comment by tunnckoCore** [comment]
Yea, it's sounds almost impossible.

But still

```
test.js:2:13: Unexpected space between function name and paren.
```

sounds strange for me and like a bug in ESLint parser. @lesander is it fixed when use semicolon?

But yea as @LinusU said, the `--fix` is totally correct, that's one of the "special" cases where you must add semi-colon.

**Comment by LinusU** [comment]
I think that "Unexpected space between function name and paren." is correct, since there are whitespace between `bar` and `(`. To be precise, there are two newlines between them...

**Comment by feross** [comment]
I believe this is working as intended.
