### ISSUE TITLE
[auto fix] Bug encountered while optimizing ternary operator

### ISSUE THREAD

**Issue by shiye515** [feross/standard#866]
before fix
```javascript
var value = 'a'
var canSet = true
var result = value ? value : canSet ? 'unset' : 'can not set'
```
The value of result is `'a'`

after fix

```javascript
var value = 'a'
var canSet = true
var result = value || canSet ? 'unset' : 'can not set'
```
The value of result is `'unset'`

**Comment by dcousens** [comment]
Brackets!

**Comment by feross** [comment]
Reported bug to eslint team: https://github.com/eslint/eslint/issues/8507

**Comment by feross** [comment]
Closing this issue. Further discussion should happen in the ESLint issue.

**Comment by saknarak** [comment]
I just found same case. That make me sick to find bug.

**Comment by cytGitHub** [comment]
hi brother . how do you do it ?


On 04/26/2017 15:39，saknarak<notifications@github.com> wrote：

I just found same case. That make me sick to find bug.
