### ISSUE TITLE
Question: how to handle camelCase for entity name in variable name

### ISSUE THREAD

**Issue by pthieu** [feross/standard#868]
`var fooSaaSBar = ...` or `var fooSaasBar`?

And while we're at it, how do we handle something like company names in full and acronym form? Specifically something like:

`fooIBMBar` vs `fooIbmBar`
`fooGitHubBar` vs `fooGithubBar`

**Comment by feross** [comment]
In camel case style, the capital letters indicate the start of a new word. I would personally do `fooSaasBar`, `fooIbmBar`, and `fooGithubBar` since you want to treat "SAAS", "IBM", and "GitHub" as a single word. For the same reason, I also do `peerId` instead of `peerID`, for example.
