### ISSUE TITLE
Use VariableDeclarator ?

### ISSUE THREAD

**Issue by muhajirframe** [feross/standard#869]
consider this 

![screenshot from 2017-04-26 14-32-23](https://cloud.githubusercontent.com/assets/12745166/25423097/85044702-2a8d-11e7-830c-b05b772b7de7.png)

wouldn't it be nice if we just write like this

![screenshot from 2017-04-26 14-30-39](https://cloud.githubusercontent.com/assets/12745166/25423075/78ce9a5a-2a8d-11e7-86b1-04bf8fefd1e9.png)

But i got error `no-multi-spaces` when i wrote code like that.
We can implement that with `no-multi-spaces`' exception `VariableDeclarator`.
http://eslint.org/docs/rules/no-multi-spaces#exceptions

**Comment by dcousens** [comment]
I love that the example you gave perfectly describes [in my browser atleast] why this is such a terrible idea:

![image](https://cloud.githubusercontent.com/assets/413395/25422588/b41d87ee-2aa4-11e7-811e-356fc5e9990f.png)

**Comment by LinusU** [comment]
I think that the problem with this is the horrible `git diff`s that you get when adding one slightly longer variable. Then you have to go back and change all the previous lines to match.

Also, I personally don't think that standard should allow both, either this should be required or not allowed...

**Comment by feross** [comment]
Sorry, this kind of manual variable alignment is not really the best use of limited programmer time, even though I agree that it looks "pretty". Better to have a consistent rule: always type one space.

**Comment by Flet** [comment]
fixed?
![image](https://cloud.githubusercontent.com/assets/360233/25498347/4669f332-2b4d-11e7-9956-7362e2be4e6e.png)
