### ISSUE TITLE
Allow shebangs (#!/usr/bin/env node)

### ISSUE THREAD

**Issue by yamboy1** [feross/standard#871]
When I put in my shebang for node (#!/usr/bin/env node) standard gave me this warning 'Expected space or tab after '///' in comment. Could you allow shebangs on the first line. I will have to use `// eslint-disable-line` to fix this temporarily. 

EDIT: I can't find any way of disabling this warning, could someone explain how

**Comment by yamboy1** [comment]
Tried again and worked perfectly, so I'm closing this issue

**Comment by chinedufn** [comment]
In case someone else runs into this:

This linting error happens if your file only contains the following

```
#!/usr/bin/env node
```

Once you add code the errors goes away
