### ISSUE TITLE
bug: return.5

### ISSUE THREAD

**Issue by Eljay-Adobe** [feross/standard#873]
// standard 10.0.2
standard --fix --stdin <goof.js

// contents of goof.js
function goof() {
  return.5
}

...becomes...

function goof() {
  return0.5
}

**Comment by LinusU** [comment]
It seems like you have written `return.5` (notice the dot), this does indeed return `0.5` when being run.

![screen shot 2017-05-02 at 23 23 16](https://cloud.githubusercontent.com/assets/189580/25640032/5753c5d4-2f8e-11e7-843e-643dbc5b87c7.png)

Did you mean to write:

```js
function goof () {
  return 5
}
```

**Comment by Eljay-Adobe** [comment]
No, the example is return.5 which does indeed return 0.5.

But standard reforms the statement to return0.5 which is a bug, since return0 is undefined and u.5 (for undefined u) is a syntax error.

**Comment by dcousens** [comment]
This should be filed upstream to ESLint... but, `return.5`... JS,  honestly.

**Comment by LinusU** [comment]
Ah, my bad, sorry about that :)

**Comment by not-an-aardvark** [comment]
This was fixed in https://github.com/eslint/eslint/commit/275414198a41368438478b3c046e4bc762e2614b.

**Comment by Eljay-Adobe** [comment]
In my defense, it wasn't my JS code.  I was using standard to make the horribly formatted code legible.  Because... standard rocks!

Thanks for fixing the bug.  /hugs
