### ISSUE TITLE
Cuddled "else" ? 

### ISSUE THREAD

**Issue by Kyokou** [feross/standard#88]
Standard currently doesn't hold an opinion on: 

```
if (foo) {
  bar()
} else {
  qux()
}
```

vs

```
if (foo) {
  bar()
}
else {
  qux()
}

```

The [Mozilla Style Guide](https://github.com/mozilla/addon-sdk/wiki/Coding-style-guide) suggests not to cuddle. Examples given by `standard` use cuddled else. 

_Personally_ I prefer a cuddled else as I find it far more readable. However, I'm raising this issue as the goal of `standard` is to be highly opinionated on stylistic matters. 

Edit:
Same thing for Try/Catch

**Comment by dcposch** [comment]
We could enable "1tbs" (one true brace style) in eslint to enforce `} else {`

http://eslint.org/docs/rules/brace-style.html

**Comment by jprichardson** [comment]
While I prefer the 2nd over the 1st, I'm pretty sure that `standard` has complained in the past and so I have to correct to the 1st. So, I'm 99% sure `standard` prefers the 1st.

**Comment by Kyokou** [comment]
@jprichardson
Well well well... I should have tested before posting this! However it isn't mentioned in the readme, so should be. :) 

You are correct that it prefers the first.

**Comment by yoshuawuyts** [comment]
Fun fact: the standard uses standard to lint standard. If you're curious how some rule is used, there's a chance there's an example in source.

**Comment by Kyokou** [comment]
@yoshuawuyts 
The opinion is included, but not mentioned explicitly. 

Without testing it myself I would have no way to know if `standard` raised an error on cuddled else or not. I would just know, as I mentioned, that `standard` example files use a cuddled else.

I'm now confused though. The formatter I use implements rules to fix uncuddled else, but it doesn't seem to be within `standard` itself, which leads me to believe they differ and that I'm correct that `standard` does not care (as seen by the lack of `1tbs` in the eslint rules) but my Sublime Text plugin _does_ care. 

@jprichardson 
Are you sure `standard` threw a fit? Or are you using an editor plugin?

**Comment by dcousens** [comment]
@Kyokou 

The error given by `standard`:
> Closing curly brace does not appear on the same line as the subsequent block.

@maxogden maybe just add something to the README, otherwise, I think this is good to close.

**Comment by Kyokou** [comment]
Thank you @dcousens for giving the error. 

That rule is unmentioned, and I agree once something is added to the readme (or the " and other goodness"  is expanded upon elsewhere) this is good to close.

**Comment by feross** [comment]
Right now, only a few rules are actually mentioned in the readme. Most aren't listed explicitly because there are just too many. The `.eslintrc` file is already approaching 200 lines!

Let's try to enumerate all the rules over on the wiki: https://github.com/feross/standard/wiki for those who learn better that way. Please help out as you discover rules that aren't mentioned!
