### ISSUE TITLE
babel-eslint custom parser and polyfill

### ISSUE THREAD

**Issue by jayce-leathers** [feross/standard#881]
I'm trying to get Standard to ignore warnings for undefined variables due to using a babel polyfill (isomorphic-fetch specifically). I understand that you can use a custom parser to use experimental language features. I'm just not sure how to configure this. Can anyone give me an example of how to setup babel-eslint and standard to do this? I've searched but haven't been able to find good info. Thanks for any help.

**Comment by Flet** [comment]
Sorry for the late reply!

There is a bit of documentation on using `babel-eslint`:
https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features

Its also possible to avoid "varaible not defined" errors in a couple ways:
https://standardjs.com/#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors

I'm going to close this issue but please feel free to respond!

**Comment by feross** [comment]
For that library in particular (`isomorphic-fetch`) I recommend importing `fetch` explicitly and not relying on it's polyfill behavior. You want to be explicit about where `fetch` is coming from to satisfy `standard`. To do that, you have two options:

1. Use it directly *(best)*

```js
const fetch = require('isomorphic-fetch')
fetch('http://example.com')
```

2. Use the global

```js
require('isomorphic-fetch') /* global fetch */
fetch('http://example.com')
```

**Comment by karnavkumar** [comment]
use this global.fetch = require('node-fetch')
