### ISSUE TITLE
I got an reserved word error for await statements

### ISSUE THREAD

**Issue by rbecheras** [feross/standard#884]
I posted an issue on atom `linter-js-standard` plugin, but I guess it is most likely an issue with `standard` itself:

https://github.com/ricardofbarros/linter-js-standard/issues/185

![capture d ecran de 2017-05-11 22-18-44](https://cloud.githubusercontent.com/assets/6469390/25970127/d6f9067c-3697-11e7-998a-cb6a005a1dc2.png)

But I use `linter-js-standard v3.9.1`:

![capture d ecran de 2017-05-11 22-19-36](https://cloud.githubusercontent.com/assets/6469390/25970197/0175956e-3698-11e7-9857-382acf736f78.png)
 
Which use `standard v8.6.0` as dependency

> https://github.com/ricardofbarros/linter-js-standard/blob/master/package.json

And `standard` seems support `async/await` since `standard v8.3.0` (`> v8.6.0`)

> https://github.com/feross/standard/issues/645#issuecomment-250550504

![capture d ecran de 2017-05-11 22-22-38](https://cloud.githubusercontent.com/assets/6469390/25970298/63e6dbe0-3698-11e7-9dfe-66358c96cf19.png)

What's wrong ?

**Comment by Flet** [comment]
Hello!

I think this is working normally. The error isn't very informative, but the `await` keyword can only be used inside of a function marked `async`. So the sample above is correctly marked as an error.
https://ponyfoo.com/articles/understanding-javascript-async-await#using-async-await

Just for kicks, I checked out the v8.6.0 tag and tried another sample file with different syntax, and it worked! :)

```bash
~/code/standard v8.6.0*
🕦 ❯ cat test.js
```
```js
/* global foo */

async function yo () {
  let x = await foo()
  return x
}

module.exports = yo
```
```bash
~/code/standard v8.6.0*
🕦 ❯ node bin/cmd.js test.js
🕦 ❯ # no error returned!
```


I'm going to close this issue, but please feel free to continue the conversation.

**Comment by brianmhunt** [comment]
I think the issue here is that the message is misleading.

It would be better (and properly informative) if it said "The 'await' keyword can only be used inside functions marked 'async'."

**Comment by Flet** [comment]
I agree @brianmhunt, however the error originates from deep inside `eslint`s parser.
