### ISSUE TITLE
Space after function name? Why?

### ISSUE THREAD

**Issue by nikolay** [feross/standard#89]

**Comment by feross** [comment]
No reason.

https://www.youtube.com/watch?v=ajLKtjozKNw

**Comment by bmeck** [comment]
I can grep for function name via `/\S+\s\(/` which will catch both `function*` and `function`; this also makes function declaration and invocation (  `/\S+\(/` ) different while I grep through code which is kinda nice.

**Comment by feross** [comment]
@bmeck Nice, I've actually been relying on that too, without realizing it!
