### ISSUE TITLE
Unexpected trailing comma

### ISSUE THREAD

**Issue by jcalfee** [feross/standard#890]
Would you consider turning off the warning for "Unexpected trailing comma" ?? 

I save time and mental load when reordering lists by not having to track that last comma.  I'm not aware of any issues that could be caused by allowing this extra comma.

```javascript
module.exports = {
  languages: [
    'chinese_simplified',
    'chinese_traditional',
    'japanese',
    'english',
    'italian',
    'french',
    'spanish', // <= This is good
  ], // <= This is good
}
```

**Comment by Flet** [comment]
Hi @jcalfee! Thanks for the thoughtful feedback!

This rule change has been discussed previously, and here was the decision we came to at that time:
>If there's two ways to do something and there's no difference in correctness or chance of introducing a bug, then standard tends to 'just pick something'. So, relaxing the rule to allow either style isn't really a viable option.
>
>Given that it's gotta be either 'disallow' or 'enforce', I think disallow is the least controversial option. Enforcing trailing commas would confuse a lot of beginners to programming or JS, IMO.

With the above in mind I'm going to close this issue now, but please feel free to continue the conversation!

**Comment by AJamesPhillips** [comment]
I agree that with only disallow and enforce, it should be disallow.  But I'd rather have it be optional.  I’m not opinionated enough to say we should have them, but I am opinionated enough to say we should not force people to have/not have them.

Also reordering a list is a common activity and not having a trailing comma would increase chances of introducing a bug as well as increasing the commit diff noise.

**Comment by LinusU** [comment]
I personally would love to have trailing comma enforced, but I don't think that making this optional is the way to go.

> [...] but I am opinionated enough to say we should not force people to have/not have them.

The whole point of standard is to be opinionated and to pick one way. Otherwise, that same argument could be made about semicolons, space vs. tabs, and basically every other rule. I think it's important that standard enforces one of them.
