### ISSUE TITLE
Use different standard configs for different subfolders

### ISSUE THREAD

**Issue by lohfu** [feross/standard#896]
Hi,

I am using the regular standard tool to lint both my front end code and back end code. However, I don't understand how to use more configs than the standard?

For example I have 3 different folders requiring different configs:

- **/client/admin** - uses [ "standard, "standard-react" ]
- **/client/public** - uses [ "standard, "standard-preact" ]
- **/server** - uses [ "standard" ]

Currently i have just gone with using the regular eslint CLI and setting up different `.eslintrc` files in the respective folders... but i would like to solve this with just the standard CLI and configuration if possible.

**Comment by ifraixedes** [comment]
What's the problem having an `.eslintrc` file inside of each folder?

**Comment by batiste** [comment]
I have the same request. I do have an .eslintrc in a subfolder (compat plugin form browser JS) but standard seems to ignore it. Is there anyway to make standard use this file under this directory?

**Comment by Flet** [comment]
The only way to accomplish this would be separate `.eslintrc` files (and using `eslint-config-standard` with `eslint` directly instead of using the `standard` CLI).

**Comment by lohfu** [comment]
@ifraixedes no real problems, i was just curious to see if there was a way to do using the `standard` CLI

@Flet yup that's what i'm doing. i will just continue doing that and close this issue.
