### ISSUE TITLE
Running npm script `    "lint": "standard"` from `linting` folder doesn't find standard in ../node_modules/bin 

### ISSUE THREAD

**Issue by QuantumInformation** [feross/standard#901]
Just gives me:

```
➜  linting git:(master) ✗ npm run standard
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/nikos/.nvm/versions/node/v7.8.0/bin/node" "/Users/nikos/.nvm/versions/node/v7.8.0/bin/npm" "run" "standard"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0

npm ERR! missing script: standard
```

![image](https://cloud.githubusercontent.com/assets/216566/26584163/ccf345b4-453f-11e7-8cd2-83f3fb344140.png)

**Comment by Flet** [comment]
`missing script: standard` is an error from npm.
It means the script named `standard` has not been defined in `package.json`. 

Can you check `package.json` to see if its defined?

**Comment by QuantumInformation** [comment]
`standard` is defined in the parent package.json. I am wanting to avoid running `npm i` in the current dir.

**Comment by QuantumInformation** [comment]
Adding standard as a dep also doesn't work

**Comment by QuantumInformation** [comment]
![image](https://cloud.githubusercontent.com/assets/216566/26625238/6bb3b0d4-45eb-11e7-8964-5432ad418cdf.png)

**Comment by LinusU** [comment]
You have defined a script called `lint`, if you run `npm run lint` instead of `npm run standard` it should work

**Comment by QuantumInformation** [comment]
npm run lint
> standard

sh: standard: command not found

**Comment by LinusU** [comment]
Have you run `npm install`?

**Comment by QuantumInformation** [comment]
Only in the parent dir

**Comment by LinusU** [comment]
Aha, `npm` only appends `./node_modules/.bin/` to the `PATH` but since your binaries are placed at a directory higher that wont work... I think that you'll have to hardcode the path in the script, `"lint": "../node_modules/.bin/standard"` or install standard globally (`npm install -g standard`)

**Comment by feross** [comment]
Yep, @LinusU is correct! I'll close this now, as it's not an issue with `standard`.
