### ISSUE TITLE
lintText and lintTextSync forcefully interact with the file system API

### ISSUE THREAD

**Issue by sadasant** [feross/standard#904]
Hi team!

We're planning to use standard as a formatting API tool, since we know this repo offers functions such as `lintText` and `lintTextSync`. However, our target software does heavy interactions with the file system, and we do heavily mock the file system in our unit tests. I wonder if we could optionally disallow standard to use the file system API for lintText and lintTextSync. What do you people think? 🤔❔

**Comment by Flet** [comment]
- `lintText` calls the internal [parseOpts](https://github.com/Flet/standard-engine/blob/master/index.js#L122) function
- this function uses [pkgConf](https://github.com/sindresorhus/pkg-conf) to scan the filesystem for a `package.json` to look for additional options. This may be the filesystem calls that are happening.
- there may also be additional calls inside [executeOnText](https://github.com/eslint/eslint/blob/c702858a0ba51c294a1e431ec2a1f92a6c872f6e/lib/cli-engine.js#L721) function in `eslint` itself (I didn't get a chance to check it thoroughly)


It may be worth using [standard-engine](https://github.com/Flet/standard-engine) directly (with `eslint-config-standard` and passing the `customParseOpts` option to send a modified `parseOpts` function. This would be a way to avoid the file system call to read `package.json`. Another option is to just use `eslint` directly :).

Part of the philosophy of the `standard` tool is to avoid having lots of configuration. Dropping down to using `standard-engine` directly may be the fastest way to accomplish your goal.

**Comment by feross** [comment]
@Flet Maybe we should change `standard-engine` so that `lintText` doesn't take into account the `package.json` settings? It seems pretty random that `lintText` would behave differently depending on the current working directory.

**Comment by Flet** [comment]
@feross yeah that makes sense!

**Comment by feross** [comment]
PR sent: https://github.com/Flet/standard-engine/pull/166

@sadasant Can you check if using `standard` with that PR applied to `standard-engine` solves your issue?
