### ISSUE TITLE
[Question] How to use with jest?

### ISSUE THREAD

**Issue by katopz** [feross/standard#905]
![image](https://cloud.githubusercontent.com/assets/97060/26666693/81066270-46cb-11e7-8b92-aa9bd9c8bc9e.png)

Usually I use `/* eslint-env jest */` for `eslint` how can I do this with `standard`?

Thanks

**Comment by dcousens** [comment]
`/* eslint-env jest */` will probably work

**Comment by katopz** [comment]
@dcousens  Hm, I still see error there? Do I miss something?

![image](https://cloud.githubusercontent.com/assets/97060/26667111/ad78ec68-46cd-11e7-96bb-2da6098d3a86.png)

**Comment by dcousens** [comment]
Not sure, boo globals anyway.

**Comment by blgm** [comment]
Does the `standard` command report problems?  If you are only seeing issues in the editor, then the issue is likely to be with the editor's standard plugin.  Which editor are you using?

I've been using standard, jest and Atom; and `/* eslint-env jest */` is working for me.

**Comment by katopz** [comment]
@blgm `standard` command did report usual format problems. I use `VSCode` and `/* eslint-env jest */` work fine without `standard` plugin (working with `ESLint` extension I mean).

Thanks

**Comment by dcousens** [comment]
@katopz try a different editor,  and if the problem persists with repro,  we'll re-open the issue

**Comment by bcomnes** [comment]
Declaring eslint environments at the top of the file helps provide context to the globals that are used as well.  👍 to that
