### ISSUE TITLE
[Question] How to use with flow?

### ISSUE THREAD

**Issue by capaj** [feross/standard#906]
I'd love to use standard on a project where I use flow. Problem is whenever I try to use flow declarations-those are basically flow globals which are declared in my `flow-typed` directory.
Now the problem is these globals are obviously marked as `not defined` by standard.

Is there any way to tell standard that he should not flag a declared type as a `not defined`?

```
/home/capaj/git_projects/looop/project-alpha/back-end/src/route/handlers/login-post.js
  52:28  error  '$Request' is not defined
  52:43  error  '$Response' is not defined
```

Only solution I can think of is to write 

```
/* global $Request, $Response */
```

but that's just plain dumb.

**Comment by Flet** [comment]
Check out the documentation here:
https://standardjs.com/#can-i-use-a-javascript-language-variant-like-flow

👍

**Comment by Flet** [comment]
Ah, also if you want to have `standard` avoid some globals:
https://standardjs.com/#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors
