### ISSUE TITLE
Support for dynamic import()

### ISSUE THREAD

**Issue by ejfrancis** [feross/standard#909]
With the [dynamic import() spec](https://github.com/tc39/proposal-dynamic-import) at stage 3, it would be nice to allow `import()` statements.

Currently using an `import()` within a function gives this error:

```
Parsing error: 'import' and 'export' may only appear at the top level 
```

**Comment by ematipico** [comment]
Duplicate of https://github.com/feross/standard/issues/751

**Comment by ejfrancis** [comment]
:+1: sorry for the dupe, couldn't find it when searching
