### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by rochapablo** [feross/standard#910]
When I run ```$ standard``` no message output is retuned;

```
pablo:hello-project pablo$ standard
pablo:hello-project pablo$
```

This is my config inside package.json:

```
"standard": {
  "ignore": [
    "/src/assets/",
    "karma.conf.js",
    "protractor.conf.js"
  ],
  "parser": "babel-eslint",
  "plugins": [
    "eslint-plugin-typescript"
  ],
  "rules": {
    "typescript/type-annotation-spacing": "error"
  }
}
```

If I remove the *ignore*, still got nothing; but removing all config only my *.js* files it's validate. But what I need it's validate my *.ts* files.

I'm working with

- Angular JS 2 (4.2.0)
- Angular CLI (1.0.6)
- "babel-eslint": "^7.2.3"
- "eslint-plugin-typescript": "^0.1.0"
- "standard": "^10.0.2"
- "typescript-eslint-parser": "^3.0.0"

Is there anyone who could guide me here?

**Comment by Flet** [comment]
Currently, `standard` only scans *.js and *.jsx files:
https://github.com/Flet/standard-engine/blob/master/index.js#L12

Unfortunately I don't think it will be possible to support typescript files until they are well supported in `eslint`. Some related efforts:
https://github.com/eslint/typescript-eslint-parser
https://github.com/krzkaczor/standardts

I'm going to close this issue, but please feel free to continue the conversation!

**Comment by feross** [comment]
Actually, it's possible to use `standard` with Typescript.

Install these two packages:

```bash
npm install typescript-eslint-parser eslint-plugin-typescript
```

Then tell standard to check all `*.ts` files, and to use the two packages we just installed:

```
standard --plugin typescript --parser typescript-eslint-parser *.ts
```

If you want, you can put some of that config into `package.json`:

```json
{
  "standard": {
    "parser": "typescript-eslint-parser",
    "plugins": [
      "typescript"
    ]
  }
}
```

With that config in place, you can run `standard *.ts` and you're good to go!

**Comment by feross** [comment]
I just sent a PR to add these instructions to the readme: https://github.com/feross/standard/pull/928
