### ISSUE TITLE
Way to prevent warnings from an external library wither lower case constructor names

### ISSUE THREAD

**Issue by computersarecool** [feross/standard#916]
I am using a library that uses lower case names for all constructors (in this case [Ammo.js](https://github.com/kripken/ammo.js/). This creates warnings all my code.  Is there a way to disable this warning.

I am using Flycheck and Emacs so these warnings show up as I am coding.

**Comment by feross** [comment]
You can try using the functions without `new`. Sometimes libraries support with and without `new`.

If that doesn't work, add `/* eslint-disable new-cap */` to the top of your file to disable the rule.
