### ISSUE TITLE
Leverage Standards initiative 

### ISSUE THREAD

**Issue by leog** [feross/standard#919]
I was wondering if it made sense I work on a PR to apply @Standards process to feature StandardJS in that initiative.

StandardJS can really help shape other standards among the open-source community sharing a common way to create, improve and evolve open-source standards.

BTW the processes and inner workings of the @Standards initiative are also open to be improved.

**Comment by feross** [comment]
I'm not sure I understand the goal of your initiative. StandardJS is already a successful project with community support from lots of folks in the community. I don't think we really have anything to gain by changing our processes at this point, though I do see how new initiatives could benefit from your guidance and structure.

If you want to feature us as an example or recommendation, feel free to do that :) But I don't think we should add more process. What we have now is quite lightweight and simple: lots of community input (weighted toward collaborators / people who have contributed to `standard` in the past), but with final curation decisions made by me. This has worked really well so far :)
