### ISSUE TITLE
SVG badge?

### ISSUE THREAD

**Issue by tomekwi** [feross/standard#93]
Hey, the badge is really handsome! A pleasure to look at, isn't it?

[![js-standard-style](https://raw.githubusercontent.com/feross/standard/master/badge.png)](https://github.com/feross/standard)

How about releasing an SVG version? So that it's equally amazing on a retina, or after zooming in.

**Comment by maxogden** [comment]
I made it in photoshop. If you wanna make a SVG version we'd happily accept a PR :)

**Comment by yoshuawuyts** [comment]
Which fonts were used? [What the font](https://www.myfonts.com/WhatTheFont/) can't make them out, hah.

**Comment by tomekwi** [comment]
Isn't that [Source Sans Pro](https://store1.adobe.com/cfusion/store/html/index.cfm?event=displayFontPackage&code=1959)? Fits in well for a high-quality open-source project :)

**Comment by feross** [comment]
Yeah, +1 for an SVG logo :+1:

**Comment by ngoldman** [comment]
![](http://f.cl.ly/items/2l1N0j0m3g1g1T3N2h1Y/js-standard.svg)

Gave an SVG logo a shot with Source Sans Pro, don't think it's quite that unless I'm doing it wrong.

**Comment by Flet** [comment]
Ooooh crisp! Looks pretty close to me :+1:

**Comment by feross** [comment]
Thanks, added this to the readme!

**Comment by ngoldman** [comment]
yay
