### ISSUE TITLE
Comparison to AirBnb Style Guide

### ISSUE THREAD

**Issue by justin808** [feross/standard#94]
@feross Any comparison to the AirBnb style guide?

It would be awesome to see your version of a fork of that which meets your idea of a JavaScript coding standard. I'm setting up a project for a new startup, so I'm hoping to get this as right as possible from the get-go.

AirBnb has this comment about semicolons: https://github.com/airbnb/javascript#semicolons
```javascript
// bad
(function() {
  var name = 'Skywalker'
  return name
})()

// good
(function() {
  var name = 'Skywalker';
  return name;
})();

// good (guards against the function becoming an argument when two files with IIFEs are concatenated)
;(function() {
  var name = 'Skywalker';
  return name;
})();
```

**Comment by rlidwka** [comment]
I assume the "good one" would be this:

```js
;(function() {
  var name = 'Skywalker'
  return name
})()
```

**Comment by feross** [comment]
The main difference is that `standard` is a tool, not just a style guide. `standard` can automatically check, and even format, your code.

Maybe eventually someone will write up a more verbose style guide for `standard`, but for now the best way to learn about it is to install it and run it against your code :)
