### ISSUE TITLE
ignore files in .gitignore

### ISSUE THREAD

**Issue by mafintosh** [feross/standard#95]
i sometimes have an *experimental* folder in a project where i try out different things. i usually add that to .gitignore. standard however still checks javascript files inside but since that folder sometimes contains some crazy bad code it usually fails. this makes my tests not run locally because of `standard && tape test/*.js`.

it would be great it standard just ignored files ignored by .gitignore (similar to how npm works).

**Comment by feross** [comment]
This is a great idea. I'll implement it when I get the time, or accept a PR for it, of course.

**Comment by jprichardson** [comment]
This feels like scope creep. Unless I'm missing something, why not just put the ignore definition in `package.json`? I guess if `npm` does it, there's a set precedent, but it doesn't seem right. (I think I understand the case for it though)

**Comment by feross** [comment]
I think it actually makes sense to ignore the files in `.gitignore` by default.

Anything that's not checked into git (generated files, `node_modules`, temporary files, etc.) shouldn't be getting linted. I don't see a downside to ignoring them by default. This should hopefully decrease the need for people to use the `"standard"` property of `package.json`.

**Comment by feross** [comment]
Another plus is that it would solve #61. See #66 for more discussion.

**Comment by feross** [comment]
PR out: https://github.com/feross/standard/pull/107

**Comment by feross** [comment]
Released as 3.4.0.

**Comment by karissa** [comment]
yay

**Comment by mvayngrib** [comment]
instead of this, I think it should defer to git, and ignore everything not being tracked

**Comment by feross** [comment]
@mvayngrib That's what this change does

**Comment by mvayngrib** [comment]
as far as i understand deglob uses the .gitignore *file*. There may also be plenty of files in the directory that are not in .gitignore and that are untracked, for example all files covered in .git/info/exclude, and all files you didn't add to git yet, and may never do. I mean something like the list [git-untracked](https://github.com/mvayngrib/git-untracked) would give you

the command line equivalent is: 

```
git ls-files --others --exclude-standard
```

**Comment by feross** [comment]
Hm, my first thought is that this will make it really hard to debug why `standard` is not checking certain files.

What does npm do? My understanding is that npm only looks for `.gitignore` when doing `npm publish`.

**Comment by mvayngrib** [comment]
good point, that is what npm does. But that just makes me think they have it wrong too!

**Comment by feross** [comment]
I wonder if someone's brought this up with npm? It seems likely to have come up for them if we're discussing it here (on a much smaller project). If we find a bug on their tracker about this, it would help illuminate the tradeoffs involved.

**Comment by mvayngrib** [comment]
no luck so far, but judging by the sheer number of issues, they must have it. Anyone else find it?

**Comment by Flet** [comment]
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

From what I can tell, npm will publish everything in the folder. It will also look for `.npmignore` and fall back to using `.gitignore` as a convenience.

Perhaps npm is purposely not tied to a specific version control system? It would make sense as it ensures broader support.

I can't think of any CLI tools that I use that take untracked git files into account (other than git itself).

**Comment by mvayngrib** [comment]
@Flet that makes sense, but also throws into doubt the use of .gitignore. I guess it depends on what standard is doing style-enforcement for: modules to be published in npm (a fraction of javascript projects), or all javascript projects. If it's the first, it would be best to defer to the npm module to see what files it plans to publish (if this is possible). If it's the second, then maybe standard can have options like "standard --git" or "standard --npm". Just an idea.

**Comment by karissa** [comment]
How about keeping it the way it is, but letting you change that default
with

standard --ignore=/path/to/.ignore
Or with an env var.

Would that be a nice compromise?

On Tuesday, July 21, 2015, Mark Vayngrib <notifications@github.com> wrote:

> @Flet <https://github.com/Flet> that makes sense, but also throws into
> doubt the use of .gitignore. I guess it depends on what standard is doing
> style-enforcement for: modules to be published in npm (a fraction of
> javascript projects), or all javascript projects. If it's the first, it
> would be best to defer to the npm module to see what files it plans to
> publish (if this is possible). If it's the second, then maybe standard can
> have options like "standard --git" or "standard --npm". Just an idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feross/standard/issues/95#issuecomment-123447239>.
>


-- 
Karissa McKelvey
http://karissa.github.io/ <http://karissamck.com>

Send me an encrypted message:
https://keybase.io/karissa <https://keybase.io/karissa/key.asc>

**Comment by feross** [comment]
@mvayngrib Can't you just add your untracked files to the "standard.ignore" property in `package.json`?

**Comment by mvayngrib** [comment]
@feross it's not a problem for me to just have

```json
"scripts": {
  "style": "standard $(git ls-files '**.js')"
}
```

this works just fine and does what I want it to. I was just curious what other people thought.
