### ISSUE TITLE
'javascript:' in string bug

### ISSUE THREAD

**Issue by jprichardson** [feross/standard#97]
Consider this simple app:

```js
var s = 'javascript: is so cool!'
console.log(s)
```

Causes `standard` to report:

```
Error: Use JavaScript Standard Style (https://github.com/feross/standard)
  app.js:1:8: Script URL is a form of eval.
```

**Comment by Flet** [comment]
Looks like this came up as an issue on the eslint side too:
https://github.com/eslint/eslint/issues/1448

Suggested fix was:
>To close the loop on this, I'd say your best bet is to disable the rule around the area in question via /*eslint-disable no-script-url*/

**Comment by feross** [comment]
@jprichardson Out of curiosity, what were you trying to do where this rule was an issue?

**Comment by jprichardson** [comment]
@feross Sure, cleaning up this old project: https://github.com/jprichardson/node-linkscrape Specifically, this file https://github.com/jprichardson/node-linkscrape/blob/master/lib/linkscrape.js

It seems to me that this behavior is pretty odd and unexpected, specifically in the context of Node.js (albeit rare). Would it make sense for `standard` to disable `no-script-url`?

**Comment by Flet** [comment]
Heh its the exact same use case in that eslint issue... Interrogating a string.

**Comment by feross** [comment]
Agreed. This is a bit odd.
