### ISSUE TITLE
Obnoxious naming

### ISSUE THREAD

**Issue by TazeTSchnitzel** [feross/standard#99]
"JS Standard" would imply that it's actually *standardised*. It isn't, it's an arbitrary coding style guide with no official endorsement.

**Comment by feross** [comment]
Thanks for sharing your opinion :)

Those of us who use `standard` find it helps hold our code to a high *standard of quality* and ensures that new contributors follow our module's *style standards*.

**Comment by maxogden** [comment]
@feross im gonna put that in the readme :)

**Comment by maxogden** [comment]
@TazeTSchnitzel Thanks for the feedback. You can find our clarified intent of use of the word 'standard' here: https://github.com/feross/standard/blob/master/README.md#one-style-to-rule-them-all
